import { GearBaseItemDefinition, lightSalvage, mediumSalvage, heavySalvage } from "./types";

export const baseItemGroup1 = {
  "double-axe": {
    id: "double-axe",
    displayName: "Double Axe",
    compatibleSlots: ["main-hand"],
    requiresTwoHands: true,
    affinityKeywords: ["physical", "stun", "bleed"],
    availableRarities: ["basic", "astral"],
    salvageByRarity: heavySalvage,
    rangedWeapon: false,
  },
  maul: {
    id: "maul",
    displayName: "Maul",
    compatibleSlots: ["main-hand"],
    requiresTwoHands: true,
    affinityKeywords: ["physical", "stun", "holy"],
    availableRarities: ["basic", "astral"],
    salvageByRarity: heavySalvage,
    rangedWeapon: false,
  },
  greatsword: {
    id: "greatsword",
    displayName: "Greatsword",
    compatibleSlots: ["main-hand"],
    requiresTwoHands: true,
    affinityKeywords: ["physical", "stun", "forge"],
    availableRarities: ["basic", "astral"],
    salvageByRarity: heavySalvage,
    rangedWeapon: false,
  },
  hatchet: {
    id: "hatchet",
    displayName: "Hatchet",
    compatibleSlots: ["main-hand"],
    requiresTwoHands: false,
    affinityKeywords: ["physical", "bleed"],
    availableRarities: ["basic", "astral"],
    salvageByRarity: mediumSalvage,
    rangedWeapon: false,
  },
  longsword: {
    id: "longsword",
    displayName: "Longsword",
    compatibleSlots: ["main-hand"],
    requiresTwoHands: false,
    affinityKeywords: ["physical", "forge", "holy"],
    availableRarities: ["basic", "astral"],
    salvageByRarity: mediumSalvage,
    rangedWeapon: false,
  },
  shortsword: {
    id: "shortsword",
    displayName: "Shortsword",
    compatibleSlots: ["main-hand"],
    requiresTwoHands: false,
    affinityKeywords: ["physical", "forge", "bleed"],
    availableRarities: ["basic", "astral"],
    salvageByRarity: lightSalvage,
    rangedWeapon: false,
  },
  dagger: {
    id: "dagger",
    displayName: "Dagger",
    compatibleSlots: ["main-hand"],
    requiresTwoHands: false,
    affinityKeywords: ["physical", "bleed", "poison"],
    availableRarities: ["basic", "astral"],
    salvageByRarity: lightSalvage,
    rangedWeapon: false,
  },
  mace: {
    id: "mace",
    displayName: "Mace",
    compatibleSlots: ["main-hand"],
    requiresTwoHands: false,
    affinityKeywords: ["physical", "stun", "holy"],
    availableRarities: ["basic", "astral"],
    salvageByRarity: mediumSalvage,
    rangedWeapon: false,
  },
  flail: {
    id: "flail",
    displayName: "Flail",
    compatibleSlots: ["main-hand"],
    requiresTwoHands: false,
    affinityKeywords: ["physical", "stun"],
    availableRarities: ["basic", "astral"],
    salvageByRarity: mediumSalvage,
    rangedWeapon: false,
  },
  longbow: {
    id: "longbow",
    displayName: "Longbow",
    compatibleSlots: ["main-hand"],
    requiresTwoHands: false,
    affinityKeywords: ["archery", "physical", "nature", "companion"],
    availableRarities: ["basic", "astral"],
    salvageByRarity: mediumSalvage,
    rangedWeapon: true,
  },
  shortbow: {
    id: "shortbow",
    displayName: "Shortbow",
    compatibleSlots: ["main-hand"],
    requiresTwoHands: false,
    affinityKeywords: ["archery", "physical", "nature", "companion"],
    availableRarities: ["basic", "astral"],
    salvageByRarity: lightSalvage,
    rangedWeapon: true,
  },
  "recurve-bow": {
    id: "recurve-bow",
    displayName: "Recurve Bow",
    compatibleSlots: ["main-hand"],
    requiresTwoHands: false,
    affinityKeywords: ["archery", "nature", "physical", "companion"],
    availableRarities: ["basic", "astral"],
    salvageByRarity: mediumSalvage,
    rangedWeapon: true,
  },
} satisfies Record<string, GearBaseItemDefinition>;
