import { GearBaseItemDefinition, lightSalvage, mediumSalvage, heavySalvage } from "./types";

export const baseItemGroup2 = {
  crossbow: {
    id: "crossbow",
    displayName: "Crossbow",
    compatibleSlots: ["main-hand"],
    requiresTwoHands: false,
    affinityKeywords: ["archery", "physical"],
    availableRarities: ["basic", "astral"],
    salvageByRarity: heavySalvage,
    rangedWeapon: true,
  },
  staff: {
    id: "staff",
    displayName: "Staff",
    compatibleSlots: ["main-hand"],
    requiresTwoHands: true,
    affinityKeywords: ["burn", "freeze", "mana"],
    availableRarities: ["basic", "astral"],
    salvageByRarity: mediumSalvage,
    rangedWeapon: false,
  },
  wand: {
    id: "wand",
    displayName: "Wand",
    compatibleSlots: ["main-hand"],
    requiresTwoHands: false,
    affinityKeywords: ["burn", "freeze", "mana"],
    availableRarities: ["basic", "astral"],
    salvageByRarity: lightSalvage,
    rangedWeapon: false,
  },
  "leather-buckler": {
    id: "leather-buckler",
    displayName: "Leather Buckler",
    compatibleSlots: ["off-hand"],
    requiresTwoHands: false,
    affinityKeywords: ["block", "armor", "physical"],
    availableRarities: ["basic", "astral"],
    salvageByRarity: lightSalvage,
  },
  "kite-shield": {
    id: "kite-shield",
    displayName: "Kite Shield",
    compatibleSlots: ["off-hand"],
    requiresTwoHands: false,
    affinityKeywords: ["block", "armor", "stun", "physical"],
    availableRarities: ["basic", "astral"],
    salvageByRarity: heavySalvage,
  },
  quiver: {
    id: "quiver",
    displayName: "Quiver",
    compatibleSlots: ["off-hand"],
    requiresTwoHands: false,
    affinityKeywords: ["archery", "physical"],
    availableRarities: ["basic", "astral"],
    salvageByRarity: lightSalvage,
    quiver: true,
  },
  spellbook: {
    id: "spellbook",
    displayName: "Spellbook",
    compatibleSlots: ["off-hand"],
    requiresTwoHands: false,
    affinityKeywords: ["burn", "freeze", "holy"],
    availableRarities: ["basic", "astral"],
    salvageByRarity: mediumSalvage,
  },
  "leather-armor": {
    id: "leather-armor",
    displayName: "Leather Armor",
    compatibleSlots: ["body"],
    requiresTwoHands: false,
    affinityKeywords: ["physical", "health", "armor"],
    availableRarities: ["basic", "astral"],
    salvageByRarity: mediumSalvage,
  },
  "plate-armor": {
    id: "plate-armor",
    displayName: "Plate Armor",
    compatibleSlots: ["body"],
    requiresTwoHands: false,
    affinityKeywords: ["armor", "block", "stun", "physical"],
    availableRarities: ["basic", "astral"],
    salvageByRarity: heavySalvage,
  },
  "leather-helm": {
    id: "leather-helm",
    displayName: "Leather Helm",
    compatibleSlots: ["helm"],
    requiresTwoHands: false,
    affinityKeywords: ["physical", "armor", "health"],
    availableRarities: ["basic", "astral"],
    salvageByRarity: mediumSalvage,
  },
  "plate-helm": {
    id: "plate-helm",
    displayName: "Plate Helm",
    compatibleSlots: ["helm"],
    requiresTwoHands: false,
    affinityKeywords: ["armor", "stun", "block"],
    availableRarities: ["basic", "astral"],
    salvageByRarity: heavySalvage,
  },
  "leather-boots": {
    id: "leather-boots",
    displayName: "Leather Boots",
    compatibleSlots: ["boots"],
    requiresTwoHands: false,
    affinityKeywords: ["physical", "armor", "health"],
    availableRarities: ["basic", "astral"],
    salvageByRarity: lightSalvage,
  },
} satisfies Record<string, GearBaseItemDefinition>;
