import { GearBaseItemDefinition, lightSalvage, heavySalvage } from "./types";

export const baseItemGroup3 = {
  "plate-boots": {
    id: "plate-boots",
    displayName: "Plate Boots",
    compatibleSlots: ["boots"],
    requiresTwoHands: false,
    affinityKeywords: ["armor", "stun", "physical", "health"],
    availableRarities: ["basic", "astral"],
    salvageByRarity: heavySalvage,
  },
  "leather-gloves": {
    id: "leather-gloves",
    displayName: "Leather Gloves",
    compatibleSlots: ["gloves"],
    requiresTwoHands: false,
    affinityKeywords: ["physical", "armor", "health", "gold"],
    availableRarities: ["basic", "astral"],
    salvageByRarity: lightSalvage,
  },
  "leather-belt": {
    id: "leather-belt",
    displayName: "Leather Belt",
    compatibleSlots: ["belt"],
    requiresTwoHands: false,
    affinityKeywords: ["physical", "gold", "armor", "health", "consume"],
    availableRarities: ["basic", "astral"],
    salvageByRarity: lightSalvage,
  },
  "ruby-ring": {
    id: "ruby-ring",
    displayName: "Ruby Ring",
    compatibleSlots: ["left-ring", "right-ring"],
    requiresTwoHands: false,
    affinityKeywords: ["burn", "bleed", "leech"],
    availableRarities: ["basic", "astral"],
    salvageByRarity: lightSalvage,
  },
  "sapphire-ring": {
    id: "sapphire-ring",
    displayName: "Sapphire Ring",
    compatibleSlots: ["left-ring", "right-ring"],
    requiresTwoHands: false,
    affinityKeywords: ["freeze", "mana", "block"],
    availableRarities: ["basic", "astral"],
    salvageByRarity: lightSalvage,
  },
  "emerald-ring": {
    id: "emerald-ring",
    displayName: "Emerald Ring",
    compatibleSlots: ["left-ring", "right-ring"],
    requiresTwoHands: false,
    affinityKeywords: ["nature", "poison", "archery"],
    availableRarities: ["basic", "astral"],
    salvageByRarity: lightSalvage,
  },
  "topaz-ring": {
    id: "topaz-ring",
    displayName: "Topaz Ring",
    compatibleSlots: ["left-ring", "right-ring"],
    requiresTwoHands: false,
    affinityKeywords: ["holy", "gold", "forge", "stun"],
    availableRarities: ["basic", "astral"],
    salvageByRarity: lightSalvage,
  },
  "ruby-amulet": {
    id: "ruby-amulet",
    displayName: "Ruby Amulet",
    compatibleSlots: ["amulet"],
    requiresTwoHands: false,
    affinityKeywords: ["burn", "bleed", "leech"],
    availableRarities: ["basic", "astral"],
    salvageByRarity: lightSalvage,
  },
  "sapphire-amulet": {
    id: "sapphire-amulet",
    displayName: "Sapphire Amulet",
    compatibleSlots: ["amulet"],
    requiresTwoHands: false,
    affinityKeywords: ["freeze", "mana", "block"],
    availableRarities: ["basic", "astral"],
    salvageByRarity: lightSalvage,
  },
  "emerald-amulet": {
    id: "emerald-amulet",
    displayName: "Emerald Amulet",
    compatibleSlots: ["amulet"],
    requiresTwoHands: false,
    affinityKeywords: ["nature", "poison", "archery"],
    availableRarities: ["basic", "astral"],
    salvageByRarity: lightSalvage,
  },
  "topaz-amulet": {
    id: "topaz-amulet",
    displayName: "Topaz Amulet",
    compatibleSlots: ["amulet"],
    requiresTwoHands: false,
    affinityKeywords: ["holy", "gold", "forge", "stun"],
    availableRarities: ["basic", "astral"],
    salvageByRarity: lightSalvage,
  },
} satisfies Record<string, GearBaseItemDefinition>;
