// Sound URL resolution and HTMLAudio warmup for SFX. Playback itself lives in audio-sfx.ts.
// Web Audio context helpers remain for unlock/resume; SFX no longer decode AudioBuffers.
import { allRegisteredSoundFiles, battleEventSounds, cardSounds, enemyAttackSounds, uiSounds } from "./sound-registry";
import { audioState, syncMasterGain } from "./audio-state";

const SOUND_PRELOAD_CONFIG = {
  SOUNDS_BASE_PATH: "sounds/",
  IDLE_CALLBACK_TIMEOUT_MS: 5000,
  PRELOAD_BATCH_SIZE: 4,
} as const;

const htmlPreloadStarted = new Set<string>();

// Lazily creates the AudioContext because browsers require user interaction before playback.
// Creates a master GainNode to clamp total audio amplitude under comfortable limits.
export function getAudioContext(): AudioContext {
  if (!audioState.context) {
    audioState.context = new AudioContext();
    audioState.masterGain = audioState.context.createGain();
    audioState.masterGain.connect(audioState.context.destination);

    syncMasterGain();
  }
  return audioState.context;
}

function markAudioUnlockedIfRunning(): boolean {
  const running = audioState.context?.state === "running";
  if (running) audioState.audioUnlocked = true;
  return running;
}

// Resumes suspended audio after a gesture so queued play calls can become audible.
// Creates the context on first unlock so it is constructed inside a user-activation stack.
export function resumeAudioContext(): Promise<boolean> {
  const ctx = getAudioContext();
  if (markAudioUnlockedIfRunning()) {
    return Promise.resolve(true);
  }

  const state = ctx.state;
  if (state !== "suspended" && state !== "interrupted") {
    return Promise.resolve(false);
  }

  return ctx
    .resume()
    .then(() => {
      if (ctx.state === "suspended") return false;
      audioState.audioUnlocked = true;
      return true;
    })
    .catch(() => false);
}

/** Prime Web Audio inside a click/keypress so later combat SFX can play without a gesture. */
export function unlockAudioFromUserGesture(): Promise<boolean> {
  const ctx = getAudioContext();
  try {
    const buffer = ctx.createBuffer(1, 1, ctx.sampleRate || 22050);
    const source = ctx.createBufferSource();
    source.buffer = buffer;
    source.connect(ctx.destination);
    source.start(0);
  } catch {
    // Some test doubles omit buffer APIs; resume() is still enough in real browsers.
  }
  return resumeAudioContext();
}

// Builds sound URLs through Vite's base path so GitHub Pages deployments resolve assets correctly.
// Safari cannot play Ogg Vorbis; MP3 siblings are generated by optimize-sounds.mjs.
function playableSoundFileName(name: string): string {
  if (!name.endsWith(".ogg") || browserCanPlayOggVorbis()) return name;
  return `${name.slice(0, -4)}.mp3`;
}

function browserCanPlayOggVorbis(): boolean {
  if (typeof Audio === "undefined") return true;
  try {
    return new Audio().canPlayType('audio/ogg; codecs="vorbis"') !== "";
  } catch {
    return true;
  }
}

export function getSoundUrl(name: string): string {
  const baseUrl = import.meta.env.BASE_URL ?? "/";
  const prefix = baseUrl.endsWith("/") ? baseUrl : `${baseUrl}/`;
  return `${prefix}${SOUND_PRELOAD_CONFIG.SOUNDS_BASE_PATH}${playableSoundFileName(name)}`;
}

/** Test-only: allow preload assertions to start from a cold cache. */
export function resetSoundPreloadCache() {
  htmlPreloadStarted.clear();
}

// Warms HTMLAudio so the first play() hits the browser cache instead of a cold fetch.
export function preloadSounds(names: string[]) {
  if (typeof Audio === "undefined") return;
  for (const name of names) {
    if (htmlPreloadStarted.has(name)) continue;
    htmlPreloadStarted.add(name);
    const el = new Audio();
    el.preload = "auto";
    el.src = getSoundUrl(name);
  }
}

/** Warm the sounds a battle can use before its first interactive frame. */
export function preloadBattleSounds(cardIds: readonly string[], enemyId: string) {
  const names = new Set<string>([
    battleEventSounds.drawTransfer,
    battleEventSounds.enemyHit,
    battleEventSounds.playerHit,
    battleEventSounds.blockAbsorb,
    battleEventSounds.critHit,
    battleEventSounds.endTurn,
  ]);
  for (const cardId of cardIds) {
    for (const name of cardSounds[cardId] ?? []) names.add(name);
  }
  for (const name of enemyAttackSounds[enemyId] ?? []) names.add(name);
  preloadSounds([...names]);
}

// Collects every registered sound and warms HTMLAudio gradually after startup.
export function preloadAllSounds() {
  const names = allRegisteredSoundFiles();

  // Eagerly preload latency-critical sounds so first interactions and first card transfers are instant.
  preloadSounds([...Object.values(uiSounds), battleEventSounds.drawTransfer]);

  // Defer the rest to idle time so they don't block the initial render.
  preloadSoundsWhenIdle(names);
}

function preloadSoundsWhenIdle(names: string[]) {
  let index = 0;

  function preloadNextBatch() {
    if (index >= names.length) return;
    preloadSounds(names.slice(index, index + SOUND_PRELOAD_CONFIG.PRELOAD_BATCH_SIZE));
    index += SOUND_PRELOAD_CONFIG.PRELOAD_BATCH_SIZE;

    if (index < names.length) {
      schedulePreloadBatch(preloadNextBatch);
    }
  }

  schedulePreloadBatch(preloadNextBatch);
}

function schedulePreloadBatch(callback: () => void, retries = 0) {
  if ("requestIdleCallback" in window) {
    window.requestIdleCallback(
      () => {
        const scheduling = navigator as Navigator & { scheduling?: { isInputPending?: () => boolean } };
        if (retries < 3 && scheduling.scheduling?.isInputPending?.()) {
          schedulePreloadBatch(callback, retries + 1);
          return;
        }
        callback();
      },
      {
        timeout: SOUND_PRELOAD_CONFIG.IDLE_CALLBACK_TIMEOUT_MS,
      },
    );
    return;
  }

  globalThis.setTimeout(() => callback(), 0);
}
