// Isolated React state for merchant and alchemist offers.
// Depends on game-data card pools, shop constants, and sampling utilities.
// Used by shop controller so offer lifecycle stays separate from purchase/mixing rules.
import { useState } from "react";
import { cardLibrary, type BattleCard } from "@/lib/game-data";
import { ALCHEMIST_POTIONS_OFFERED, ALCHEMIST_REFRESHES, MIXED_POTION_CARD_ID, POTION_CARD_ID_FRAGMENT, SHOP_CARDS_OFFERED, SHOP_REFRESHES } from "@/lib/game-constants";
import { sampleItems } from "./utils";

export interface ShopState {
  cards: BattleCard[];
  refreshesLeft: number;
  removeUsed: boolean;
  firstPurchaseUsed: boolean;
}

export interface AlchemistState {
  potions: BattleCard[];
  refreshesLeft: number;
  mixUsed: boolean;
  firstPurchaseUsed: boolean;
}

type ShopStore = {
  shop: ShopState;
  alchemist: AlchemistState;
};

const emptyShop: ShopState = { cards: [], refreshesLeft: SHOP_REFRESHES, removeUsed: false, firstPurchaseUsed: false };
const emptyAlchemist: AlchemistState = { potions: [], refreshesLeft: ALCHEMIST_REFRESHES, mixUsed: false, firstPurchaseUsed: false };

export function useShopState() {
  // Shop visit data lives in one store so merchant and alchemist offers share one owner.
  const [store, setStore] = useState<ShopStore>({ shop: emptyShop, alchemist: emptyAlchemist });

  const setShopState: React.Dispatch<React.SetStateAction<ShopState>> = (action) => setStore((prev) => ({ ...prev, shop: typeof action === "function" ? action(prev.shop) : action }));
  const setAlchemistState: React.Dispatch<React.SetStateAction<AlchemistState>> = (action) => setStore((prev) => ({ ...prev, alchemist: typeof action === "function" ? action(prev.alchemist) : action }));

  function initShop() {
    setShopState({ cards: sampleItems(cardLibrary, SHOP_CARDS_OFFERED), refreshesLeft: SHOP_REFRESHES, removeUsed: false, firstPurchaseUsed: false });
  }

  function initAlchemist() {
    // The alchemist sells only base potions; Mixed Potion is generated by the mixer and
    // should not appear as a normal offer.
    const potions = sampleItems(cardLibrary.filter((c) => c.id.includes(POTION_CARD_ID_FRAGMENT) && c.id !== MIXED_POTION_CARD_ID), ALCHEMIST_POTIONS_OFFERED);
    setAlchemistState({ potions, refreshesLeft: ALCHEMIST_REFRESHES, mixUsed: false, firstPurchaseUsed: false });
  }

  function resetShop() { setShopState(emptyShop); }
  function resetAlchemist() { setAlchemistState(emptyAlchemist); }

  return { shopState: store.shop, setShopState, alchemistState: store.alchemist, setAlchemistState, initShop, initAlchemist, resetShop, resetAlchemist };
}
