// Thin React wiring around createRunFlowHandlers.
import { useMemo } from "react";
import { createRunFlowHandlers } from "@/features/alchemy/run-loop/run/run-flow-handlers";
import type { RunFlowHandlerDeps } from "@/features/alchemy/run-loop/run/run-flow-handler-deps";

export function useRunFlowHandlers({
  run,
  talents,
  navigateTo,
  transition,
  onLabyrinthFailNode,
  onLabyrinthClearNode,
  onInitShop,
  onInitAlchemist,
  onInitTrinketShop,
  onInitEquipmentShop,
  onStartBattle,
  onStartBossBattle,
  onStartBossById,
  onMarkDifficultyCompleted,
  onCommitWildwoodVictory,
  contentNav,
  getAvailableDestinations,
  beginMysteryEvent,
  clearMysteryCardChoices,
  onWildwoodRewardComplete,
  onSelectRewardChoice,
  rewardRng,
  destinationRng,
  worldRng,
}: RunFlowHandlerDeps) {
  return useMemo(
    () =>
      createRunFlowHandlers({
        run,
        talents,
        navigateTo,
        transition,
        onLabyrinthFailNode,
        onLabyrinthClearNode,
        onInitShop,
        onInitAlchemist,
        onInitTrinketShop,
        onInitEquipmentShop,
        onStartBattle,
        onStartBossBattle,
        onStartBossById,
        onMarkDifficultyCompleted,
        onCommitWildwoodVictory,
        contentNav,
        getAvailableDestinations,
        beginMysteryEvent,
        clearMysteryCardChoices,
        onWildwoodRewardComplete,
        ...(onSelectRewardChoice ? { onSelectRewardChoice } : {}),
        rewardRng,
        destinationRng,
        worldRng,
      }),
    [
      run,
      talents,
      navigateTo,
      transition,
      onLabyrinthFailNode,
      onLabyrinthClearNode,
      onInitShop,
      onInitAlchemist,
      onInitTrinketShop,
      onInitEquipmentShop,
      onStartBattle,
      onStartBossBattle,
      onStartBossById,
      onMarkDifficultyCompleted,
      onCommitWildwoodVictory,
      contentNav,
      getAvailableDestinations,
      beginMysteryEvent,
      clearMysteryCardChoices,
      onWildwoodRewardComplete,
      onSelectRewardChoice,
      rewardRng,
      destinationRng,
      worldRng,
    ],
  );
}
