export const DEFAULT_MUSIC_VOLUME_PCT = 50;
export const DEFAULT_SFX_VOLUME_PCT = 50;
export const DEFAULT_MASTER_VOLUME_PCT = 50;
export const DEFAULT_BRIGHTNESS_PCT = 100;
export const DEFAULT_BACKGROUND_PARTICLES_PCT = 100;
export const DEFAULT_BACKGROUND_GLOW_PCT = 100;
