import {
  Anvil,
  Bone,
  Bug,
  Coins,
  Droplet,
  Droplets,
  Flame,
  Heart,
  HeartCrack,
  Mountain,
  PawPrint,
  Scale,
  Shield,
  Snowflake,
  Sprout,
  Stars,
  Sun,
  Swords,
  Volume2,
  type LucideIcon,
} from "lucide-react";
import type { EnemyTrait } from "./game-data-catalog";
import { extractKeywordIds } from "./keywords";
import { keywordIcons } from "./metadata";

const traitIcons: Record<string, LucideIcon> = {
  banshee: Volume2,
  pyromancer: Flame,
  ogre: Swords,
  "giant-snake": Droplets,
  "living-armor": Shield,
  "will-o-wisp": Stars,
  yeti: Shield,
  "earth-elemental": Mountain,
  "glacial-body": Snowflake,
  "minor-freeze-vulnerability": Snowflake,
  "cold-blooded": Snowflake,
  "minor-holy-vulnerability": Sun,
  "holy-vulnerability": Sun,
  "tough-hide": Shield,
  "vampiric-curse": HeartCrack,
  "frozen-apparition": Snowflake,
  "winter-hide": Snowflake,
  "earthen-body": Mountain,
  bandit: Swords,
  "blood-cultist": Droplet,
  brawler: Stars,
  vampire: Droplets,
  "zealot-enemy": Flame,
  inquisitor: Scale,
  cleric: Heart,
  paladin: Shield,
  "fire-imp": Flame,
  "giant-spider": Bug,
  "winter-wolf": Snowflake,
  "dire-wolf": PawPrint,
  hellhound: Flame,
  "stone-golem": Shield,
  "ice-wraith": Snowflake,
  "frost-elemental": Snowflake,
  "rusting-carapace": Anvil,
  "starting-block": Shield,
  "glacial-shell": Snowflake,
  "iron-hide": Shield,
  seraph: Sun,
  "stone-titan": Mountain,
  "blood-countess": HeartCrack,
  regeneration: Sprout,
  "brittle-bones": Bone,
  "gold-trove": Coins,
  amorphous: Droplet,
  "cinder-skin": Flame,
};

export function getEnemyTraitIcon(trait: EnemyTrait): LucideIcon {
  const icon = Object.hasOwn(traitIcons, trait.id) ? traitIcons[trait.id] : undefined;
  if (icon) return icon;
  const keyword = extractKeywordIds(trait.description)[0];
  return keyword ? keywordIcons[keyword] : Shield;
}
