// Feature-facing catalog seam for screen/runtime reads of static game data.
// Keeps UI modules from importing broad game-data registries directly.
export {
  alchemistShopBg,
  campfire,
  cardLibrary,
  characterArt,
  characters,
  corruptionAltar,
  eliteEnemyBg,
  enemyBestiary,
  getCardKeywords,
  getCharacterUnlockMessage,
  getGameModeUnlockMessage,
  getRequiredPreviousCharacter,
  KNIGHT_UNLOCK_MESSAGE,
  getTalentKeywordProgress,
  isCharacterUnlocked,
  isGameModeUnlocked,
  isProgressionFeatureUnlocked,
  keywordDefinitions,
  merchantShopBg,
  mysteryBg,
  normalEnemyBg,
  pileDiscardArt,
  pileDrawArt,
  theCampaign,
  theLabyrinth,
  wildwoodDraft,
  trinketLibrary,
  talentArt,
} from "@/lib/game-data";

export type {
  BattleCard,
  BestiaryEntry,
  CharacterId,
  CompanionId,
  EnemyType,
  GameModeId,
  KeywordId,
  TrinketEntry,
} from "@/lib/game-data";
