import type { BattleCard } from "../types";
import {
  anvil,
  apple,
  bash,
  blessedAegis,
  block,
  bread,
  fireArrow,
  iceShot,
  impCompanion,
  lizardScoutCompanion,
  luckPotion,
  meteor,
  mixedPotion,
  wish,
  wishingPotion,
  wolfCompanion,
} from "../assets";
import {
  archeryDamageCard,
  consumableCard,
  damageCard,
  playerStatThenScaledDamageCard,
  playerStatusCard,
  singleEffectCard,
  summonCompanionCard,
} from "./card-builders";

export const cardLibraryPart2: BattleCard[] = [
  playerStatusCard({ id: "anvil", art: anvil, status: "forge", amount: 1 }),
  consumableCard({ id: "apple", art: apple, effect: { kind: "heal", amount: 5 } }),
  damageCard({ id: "bash", art: bash, damageType: "stun", amount: 3 }),
  playerStatusCard({ id: "block", art: block, status: "block", amount: 5 }),
  consumableCard({ id: "bread", art: bread, effect: { kind: "heal", amount: 5 } }),
  playerStatThenScaledDamageCard({
    id: "blessed-aegis",
    art: blessedAegis,
    damageType: "holy",
    scaleFrom: "block",
  }),
  consumableCard({
    id: "luck-potion",
    art: luckPotion,
    effect: { kind: "gain-gold", amount: 7 },
  }),
  singleEffectCard({ id: "wish", art: wish, effect: { kind: "wish", amount: 1 } }),
  consumableCard({
    id: "wishing-potion",
    art: wishingPotion,
    effect: { kind: "wish", amount: 1 },
  }),
  {
    id: "meteor",
    title: "Meteor",
    descriptionLines: ["Deal 7 Burn damage", "Lose 1 Mana Crystal", "Consume"],
    art: meteor,
    cost: 1,
    consume: true,
    effects: [
      { kind: "damage", damageType: "burn", amount: 7 },
      { kind: "lose-max-mana", amount: 1 },
    ],
  },
  {
    id: "mixed-potion",
    title: "Mixed Potion",
    descriptionLines: ["Mixed at an Alchemist's Shop", "Consume"],
    art: mixedPotion,
    cost: 1,
    consume: true,
    effects: [],
    excludeFromOfferPool: true,
  },
  summonCompanionCard({ id: "wolf-companion", art: wolfCompanion, companionId: "wolf" }),
  summonCompanionCard({
    id: "lizard-scout-companion",
    art: lizardScoutCompanion,
    companionId: "lizard-scout",
  }),
  summonCompanionCard({ id: "imp-companion", art: impCompanion, companionId: "imp" }),
  archeryDamageCard({
    id: "fire-arrow",
    art: fireArrow,
    damageType: "burn",
    amount: 2,
  }),
  archeryDamageCard({
    id: "ice-shot",
    art: iceShot,
    damageType: "freeze",
    amount: 2,
  }),
];
