import type { BattleCard } from "../types";
import {
  bountyShot,
  concussiveShot,
  exorcism,
  frostWhelpCompanion,
  gamblersShot,
  hemorrhage,
  kindling,
  lightningArrow,
  lightningBolt,
  phoenixFeather,
  roulette,
  sapArrow,
  serratedArrowhead,
  tithe,
  venomArrow,
  wishingWell,
} from "../assets";
import {
  archeryDamageCard,
  damageCard,
  damageThenMultiplyEnemyStatusCard,
  dualDamageCard,
  summonCompanionCard,
} from "./card-builders";

export const cardLibraryPart3: BattleCard[] = [
  archeryDamageCard({
    id: "venom-arrow",
    art: venomArrow,
    damageType: "poison",
    amount: 2,
  }),
  archeryDamageCard({
    id: "serrated-arrowhead",
    art: serratedArrowhead,
    damageType: "bleed",
    amount: 2,
  }),
  archeryDamageCard({
    id: "concussive-shot",
    art: concussiveShot,
    damageType: "stun",
    amount: 3,
  }),
  archeryDamageCard({
    id: "lightning-arrow",
    art: lightningArrow,
    damageType: "nature",
    amount: 2,
  }),
  {
    id: "tithe",
    title: "Tithe",
    descriptionLines: ["Deal Holy damage equal to 10% of your Gold"],
    art: tithe,
    cost: 1,
    effects: [{ kind: "damage", damageType: "holy", amount: 0, equalToGoldPercent: 10 }],
  },
  {
    id: "exorcism",
    title: "Exorcism",
    descriptionLines: ["Cleanse all Burn on yourself", "Deal Holy damage equal to Burn removed"],
    art: exorcism,
    cost: 1,
    effects: [{ kind: "cleanse-player-status-to-damage", status: "burn", damageType: "holy", removeAll: true }],
  },
  damageThenMultiplyEnemyStatusCard({
    id: "kindling",
    art: kindling,
    damageType: "burn",
    damageAmount: 1,
    status: "burn",
    factor: 2,
    multiplyLine: "Double enemy Burn stacks",
    consume: true,
  }),
  {
    id: "roulette",
    title: "Roulette",
    descriptionLines: ["Deal 3 Random damage or Gain 3 Gold"],
    art: roulette,
    cost: 1,
    effects: [
      {
        kind: "chance",
        probability: 0.5,
        successEffects: [{ kind: "random-damage", minAmount: 3, maxAmount: 3 }],
        failureEffects: [{ kind: "gain-gold", amount: 3 }],
      },
    ],
  },
  damageCard({ id: "lightning-bolt", art: lightningBolt, damageType: "nature", amount: 4 }),
  {
    id: "wishing-well",
    title: "Wishing Well",
    descriptionLines: ["Wish 1", "Gain 1 Gold"],
    art: wishingWell,
    cost: 1,
    effects: [
      { kind: "wish", amount: 1 },
      { kind: "gain-gold", amount: 1 },
    ],
  },
  dualDamageCard({
    id: "hemorrhage",
    art: hemorrhage,
    hits: [
      { damageType: "physical", amount: 2 },
      { damageType: "bleed", amount: 1 },
    ],
  }),
  {
    id: "bounty-shot",
    title: "Bounty Shot",
    descriptionLines: ["Deal 2 Physical damage", "Gain 2 Gold", "Archery"],
    art: bountyShot,
    cost: 1,
    tags: ["archery"],
    effects: [
      { kind: "damage", damageType: "physical", amount: 2 },
      { kind: "gain-gold", amount: 2 },
    ],
  },
  {
    id: "sap-arrow",
    title: "Sap Arrow",
    descriptionLines: ["Deal 2 Nature damage", "Leech", "Archery"],
    art: sapArrow,
    cost: 1,
    tags: ["archery"],
    effects: [{ kind: "damage", damageType: "nature", amount: 2, lifesteal: true }],
  },
  {
    id: "gamblers-shot",
    title: "Gambler's Shot",
    descriptionLines: ["Deal 1–6 Random damage", "Archery"],
    art: gamblersShot,
    cost: 1,
    tags: ["archery"],
    effects: [{ kind: "random-damage", minAmount: 1, maxAmount: 6 }],
  },
  {
    id: "phoenix-feather",
    title: "Phoenix Feather",
    descriptionLines: ["Lose 1 Mana Crystal", "If you would die, instead restore 30% Health"],
    art: phoenixFeather,
    cost: 1,
    effects: [
      { kind: "lose-max-mana", amount: 1 },
      { kind: "player-status", status: "phoenixFeather", amount: 1 },
    ],
  },
  summonCompanionCard({
    id: "frost-whelp-companion",
    art: frostWhelpCompanion,
    companionId: "frost-whelp",
  }),
];
