// Card library — every playable BattleCard in the game, authored as data.
// Depends on art assets and card type shapes. Each card is an effect pipeline; no logic.
import {
  acidPotion,
  anvil,
  apple,
  bash,
  blessedAegis,
  block,
  bread,
  cleanse,
  fangs,
  concussiveShot,
  fireArrow,
  fireball,
  frostbolt,
  iceShot,
  exorcism,
  kindling,
  lightningArrow,
  lightningBolt,
  roulette,
  serratedArrowhead,
  tithe,
  venomArrow,
  haste,
  heal,
  healthPotion,
  impCompanion,
  lizardScoutCompanion,
  luckPotion,
  manaBerries,
  manaCrystal,
  manaPotion,
  meteor,
  mixedPotion,
  panaceaPotion,
  poisonDagger,
  slash,
  stab,
  stoneskinPotion,
  wish,
  wishingPotion,
  wolfCompanion,
} from "../assets";
import type { BattleCard } from "../types";

export const combatCards: BattleCard[] = [
  {
    id: "slash",
    title: "Slash",
    descriptionLines: ["Deal 6 Physical damage"],
    art: slash,
    cost: 1,
    effects: [{ kind: "damage", damageType: "physical", amount: 6 }],
  },
  {
    id: "stab",
    title: "Stab",
    descriptionLines: ["Deal 2 Bleed damage"],
    art: stab,
    cost: 1,
    effects: [{ kind: "damage", damageType: "bleed", amount: 2 }],
  },
  {
    id: "cleanse",
    title: "Cleanse",
    descriptionLines: ["Cleanse 1 harmful status effect"],
    art: cleanse,
    cost: 1,
    effects: [{ kind: "remove-harmful-status", amount: 1 }],
  },
  {
    id: "heal",
    title: "Heal",
    descriptionLines: ["Restore 4 Health"],
    art: heal,
    cost: 1,
    effects: [{ kind: "heal", amount: 4 }],
  },
  {
    id: "haste",
    title: "Haste",
    descriptionLines: ["Take an extra turn after this one", "Consume"],
    art: haste,
    cost: 1,
    consume: true,
    effects: [{ kind: "player-status", status: "haste", amount: 1 }],
  },
  {
    id: "poison-dagger",
    title: "Poison Dagger",
    descriptionLines: ["Deal 2 Poison damage"],
    art: poisonDagger,
    cost: 1,
    effects: [{ kind: "damage", damageType: "poison", amount: 2 }],
  },
  {
    id: "fireball",
    title: "Fireball",
    descriptionLines: ["Deal 3 Burn damage"],
    art: fireball,
    cost: 1,
    effects: [{ kind: "damage", damageType: "burn", amount: 3 }],
  },
  {
    id: "fangs",
    title: "Fangs",
    descriptionLines: ["Deal 3 Physical damage", "Leech"],
    art: fangs,
    cost: 1,
    effects: [{ kind: "damage", damageType: "physical", amount: 3, lifesteal: true }],
  },
  {
    id: "frostbolt",
    title: "Frostbolt",
    descriptionLines: ["Deal 3 Freeze damage"],
    art: frostbolt,
    cost: 1,
    effects: [{ kind: "damage", damageType: "freeze", amount: 3 }],
  },
  {
    id: "health-potion",
    title: "Health Potion",
    descriptionLines: ["Restore 8 Health", "Consume"],
    art: healthPotion,
    cost: 1,
    consume: true,
    effects: [{ kind: "heal", amount: 8 }],
  },
  {
    id: "mana-berries",
    title: "Mana Berries",
    descriptionLines: ["Restore 2 Mana", "Consume"],
    art: manaBerries,
    cost: 1,
    consume: true,
    effects: [{ kind: "restore-mana", amount: 2 }],
  },
  {
    id: "mana-crystals",
    title: "Mana Crystals",
    descriptionLines: ["Gain 1 Maximum Mana", "Consume"],
    art: manaCrystal,
    cost: 1,
    consume: true,
    effects: [{ kind: "gain-max-mana", amount: 1 }],
  },
  {
    id: "mana-potion",
    title: "Mana Potion",
    descriptionLines: ["Restore 2 Mana", "Consume"],
    art: manaPotion,
    cost: 1,
    consume: true,
    effects: [{ kind: "restore-mana", amount: 2 }],
  },
  {
    id: "panacea-potion",
    title: "Panacea Potion",
    descriptionLines: ["Remove 1 harmful status effect", "Consume"],
    art: panaceaPotion,
    cost: 1,
    consume: true,
    effects: [{ kind: "remove-harmful-status", amount: 1 }],
  },
  {
    id: "stoneskin-potion",
    title: "Stoneskin Potion",
    descriptionLines: ["Gain 2 Armor", "Consume"],
    art: stoneskinPotion,
    cost: 1,
    consume: true,
    effects: [{ kind: "player-status", status: "armor", amount: 2 }],
  },
  {
    id: "acid-potion",
    title: "Acid Potion",
    descriptionLines: ["Deal 3 Poison damage", "Consume"],
    art: acidPotion,
    cost: 1,
    consume: true,
    effects: [{ kind: "damage", damageType: "poison", amount: 3 }],
  },
  {
    id: "anvil",
    title: "Anvil",
    descriptionLines: ["Gain 1 Forge"],
    art: anvil,
    cost: 1,
    effects: [{ kind: "player-status", status: "forge", amount: 1 }],
  },
  {
    id: "apple",
    title: "Apple",
    descriptionLines: ["Restore 5 Health", "Consume"],
    art: apple,
    cost: 1,
    consume: true,
    effects: [{ kind: "heal", amount: 5 }],
  },
  {
    id: "bash",
    title: "Bash",
    descriptionLines: ["Deal 3 Stun damage"],
    art: bash,
    cost: 1,
    effects: [{ kind: "damage", damageType: "stun", amount: 3 }],
  },
  {
    id: "block",
    title: "Block",
    descriptionLines: ["Gain 5 Block"],
    art: block,
    cost: 1,
    effects: [{ kind: "player-status", status: "block", amount: 5 }],
  },
  {
    id: "bread",
    title: "Bread",
    descriptionLines: ["Restore 5 Health", "Consume"],
    art: bread,
    cost: 1,
    consume: true,
    effects: [{ kind: "heal", amount: 5 }],
  },
  {
    id: "blessed-aegis",
    title: "Blessed Aegis",
    descriptionLines: ["Deal Holy damage equal to your Block"],
    art: blessedAegis,
    cost: 1,
    effects: [{ kind: "damage", damageType: "holy", amount: 0, equalToBlock: true }],
  },
  {
    id: "luck-potion",
    title: "Luck Potion",
    descriptionLines: ["Gain 7 Gold", "Consume"],
    art: luckPotion,
    cost: 1,
    consume: true,
    effects: [{ kind: "gain-gold", amount: 7 }],
  },
  {
    id: "wish",
    title: "Wish",
    descriptionLines: ["Wish 1"],
    art: wish,
    cost: 1,
    effects: [{ kind: "wish", amount: 1 }],
  },
  {
    id: "wishing-potion",
    title: "Wishing Potion",
    descriptionLines: ["Wish 1", "Consume"],
    art: wishingPotion,
    cost: 1,
    consume: true,
    effects: [{ kind: "wish", amount: 1 }],
  },
  {
    id: "meteor",
    title: "Meteor",
    descriptionLines: ["Deal 7 Burn damage", "Lose 1 Mana Crystal", "Consume"],
    art: meteor,
    cost: 1,
    consume: true,
    effects: [
      { kind: "damage", damageType: "burn", amount: 7 },
      { kind: "lose-max-mana", amount: 1 },
    ],
  },
  {
    id: "mixed-potion",
    title: "Mixed Potion",
    descriptionLines: ["Mixed at an Alchemist's Shop", "Consume"],
    art: mixedPotion,
    cost: 1,
    consume: true,
    effects: [],
  },
  {
    id: "wolf-companion",
    title: "Wolf",
    descriptionLines: ["Deals 1 Bleed damage each turn", "Companion"],
    art: wolfCompanion,
    cost: 1,
    consume: true,
    effects: [{ kind: "summon-companion", companionId: "wolf" }],
  },
  {
    id: "lizard-scout-companion",
    title: "Lizard Scout",
    descriptionLines: ["Deals 1 Poison damage each turn", "Companion"],
    art: lizardScoutCompanion,
    cost: 1,
    consume: true,
    effects: [{ kind: "summon-companion", companionId: "lizard-scout" }],
  },
  {
    id: "imp-companion",
    title: "Imp",
    descriptionLines: ["Deals 1 Burn damage each turn", "Companion"],
    art: impCompanion,
    cost: 1,
    consume: true,
    effects: [{ kind: "summon-companion", companionId: "imp" }],
  },
  {
    id: "fire-arrow",
    title: "Fire Arrow",
    descriptionLines: ["Deal 2 Burn damage", "Archery"],
    art: fireArrow,
    cost: 1,
    tags: ["archery"],
    effects: [{ kind: "damage", damageType: "burn", amount: 2 }],
  },
  {
    id: "ice-shot",
    title: "Ice Shot",
    descriptionLines: ["Deal 2 Freeze damage", "Archery"],
    art: iceShot,
    cost: 1,
    tags: ["archery"],
    effects: [{ kind: "damage", damageType: "freeze", amount: 2 }],
  },
  {
    id: "venom-arrow",
    title: "Venom Arrow",
    descriptionLines: ["Deal 2 Poison damage", "Archery"],
    art: venomArrow,
    cost: 1,
    tags: ["archery"],
    effects: [{ kind: "damage", damageType: "poison", amount: 2 }],
  },
  {
    id: "serrated-arrowhead",
    title: "Serrated Arrowhead",
    descriptionLines: ["Deal 2 Bleed damage", "Archery"],
    art: serratedArrowhead,
    cost: 1,
    tags: ["archery"],
    effects: [{ kind: "damage", damageType: "bleed", amount: 2 }],
  },
  {
    id: "concussive-shot",
    title: "Concussive Shot",
    descriptionLines: ["Deal 3 Stun damage", "Archery"],
    art: concussiveShot,
    cost: 1,
    tags: ["archery"],
    effects: [{ kind: "damage", damageType: "stun", amount: 3 }],
  },
  {
    id: "lightning-arrow",
    title: "Lightning Arrow",
    descriptionLines: ["Deal 2 Nature damage", "Archery"],
    art: lightningArrow,
    cost: 1,
    tags: ["archery"],
    effects: [{ kind: "damage", damageType: "nature", amount: 2 }],
  },
  {
    id: "tithe",
    title: "Tithe",
    descriptionLines: ["Deal Holy damage equal to 10% of your Gold"],
    art: tithe,
    cost: 1,
    effects: [{ kind: "damage", damageType: "holy", amount: 0, equalToGoldPercent: 10 }],
  },
  {
    id: "exorcism",
    title: "Exorcism",
    descriptionLines: ["Cleanse all Burn on yourself", "Deal Holy damage equal to Burn removed"],
    art: exorcism,
    cost: 1,
    effects: [{ kind: "cleanse-player-status-to-damage", status: "burn", damageType: "holy", removeAll: true }],
  },
  {
    id: "kindling",
    title: "Kindling",
    descriptionLines: ["Deal 1 Burn damage", "Double enemy Burn stacks", "Consume"],
    art: kindling,
    cost: 1,
    consume: true,
    effects: [
      { kind: "damage", damageType: "burn", amount: 1 },
      { kind: "multiply-enemy-status", status: "burn", factor: 2 },
    ],
  },
  {
    id: "roulette",
    title: "Roulette",
    descriptionLines: ["Deal 1–7 damage of a random type"],
    art: roulette,
    cost: 1,
    effects: [{ kind: "random-damage", minAmount: 1, maxAmount: 7 }],
  },
  {
    id: "lightning-bolt",
    title: "Lightning Bolt",
    descriptionLines: ["Deal 4 Nature damage"],
    art: lightningBolt,
    cost: 1,
    effects: [{ kind: "damage", damageType: "nature", amount: 4 }],
  },
];
