// Card library — every playable BattleCard in the game, authored as data.
// Depends on art assets and card type shapes. Each card is an effect pipeline; no logic.
import {
  acidPotion,
  anvil,
  apple,
  bash,
  blessedAegis,
  block,
  bread,
  cleanse,
  fangs,
  concussiveShot,
  fireArrow,
  fireball,
  frostbolt,
  iceShot,
  exorcism,
  kindling,
  lightningArrow,
  lightningBolt,
  placeholderCard,
  roulette,
  serratedArrowhead,
  tithe,
  venomArrow,
  haste,
  heal,
  healthPotion,
  impCompanion,
  lizardScoutCompanion,
  luckPotion,
  manaBerries,
  manaCrystal,
  manaPotion,
  meteor,
  mixedPotion,
  panaceaPotion,
  poisonDagger,
  slash,
  stab,
  stoneskinPotion,
  wish,
  wishingPotion,
  wolfCompanion,
} from "../assets";
import type { BattleCard } from "../types";
import {
  archeryDamageCard,
  consumableCard,
  damageCard,
  damageThenMultiplyEnemyStatusCard,
  playerStatThenScaledDamageCard,
  playerStatusCard,
  singleEffectCard,
  summonCompanionCard,
} from "./card-builders";

export const combatCards: BattleCard[] = [
  damageCard({ id: "slash", title: "Slash", art: slash, damageType: "physical", amount: 6 }),
  damageCard({ id: "stab", title: "Stab", art: stab, damageType: "bleed", amount: 2 }),
  singleEffectCard({
    id: "cleanse",
    title: "Cleanse",
    art: cleanse,
    effect: { kind: "remove-harmful-status", amount: 1 },
    descriptionLine: "Cleanse 1 harmful status effect",
  }),
  singleEffectCard({ id: "heal", title: "Heal", art: heal, effect: { kind: "heal", amount: 4 } }),
  {
    id: "haste",
    title: "Haste",
    descriptionLines: ["Take an extra turn after this one", "Consume"],
    art: haste,
    cost: 1,
    consume: true,
    effects: [{ kind: "player-status", status: "haste", amount: 1 }],
  },
  damageCard({ id: "poison-dagger", title: "Poison Dagger", art: poisonDagger, damageType: "poison", amount: 2 }),
  damageCard({ id: "fireball", title: "Fireball", art: fireball, damageType: "burn", amount: 3 }),
  damageCard({ id: "fangs", title: "Fangs", art: fangs, damageType: "physical", amount: 3, lifesteal: true }),
  damageCard({ id: "frostbolt", title: "Frostbolt", art: frostbolt, damageType: "freeze", amount: 3 }),
  consumableCard({
    id: "health-potion",
    title: "Health Potion",
    art: healthPotion,
    effect: { kind: "heal", amount: 8 },
  }),
  consumableCard({
    id: "mana-berries",
    title: "Mana Berries",
    art: manaBerries,
    effect: { kind: "restore-mana", amount: 2 },
  }),
  consumableCard({
    id: "mana-crystals",
    title: "Mana Crystals",
    art: manaCrystal,
    effect: { kind: "gain-max-mana", amount: 1 },
  }),
  consumableCard({
    id: "mana-potion",
    title: "Mana Potion",
    art: manaPotion,
    effect: { kind: "restore-mana", amount: 2 },
  }),
  consumableCard({
    id: "panacea-potion",
    title: "Panacea Potion",
    art: panaceaPotion,
    effect: { kind: "remove-harmful-status", amount: 1 },
  }),
  consumableCard({
    id: "stoneskin-potion",
    title: "Stoneskin Potion",
    art: stoneskinPotion,
    effect: { kind: "player-status", status: "armor", amount: 2 },
  }),
  consumableCard({
    id: "acid-potion",
    title: "Acid Potion",
    art: acidPotion,
    effect: { kind: "damage", damageType: "poison", amount: 3 },
  }),
  playerStatusCard({ id: "anvil", title: "Anvil", art: anvil, status: "forge", amount: 1 }),
  consumableCard({ id: "apple", title: "Apple", art: apple, effect: { kind: "heal", amount: 5 } }),
  damageCard({ id: "bash", title: "Bash", art: bash, damageType: "stun", amount: 3 }),
  playerStatusCard({ id: "block", title: "Block", art: block, status: "block", amount: 5 }),
  consumableCard({ id: "bread", title: "Bread", art: bread, effect: { kind: "heal", amount: 5 } }),
  playerStatThenScaledDamageCard({
    id: "blessed-aegis",
    title: "Blessed Aegis",
    art: blessedAegis,
    damageType: "holy",
    scaleFrom: "block",
  }),
  consumableCard({
    id: "luck-potion",
    title: "Luck Potion",
    art: luckPotion,
    effect: { kind: "gain-gold", amount: 7 },
  }),
  singleEffectCard({ id: "wish", title: "Wish", art: wish, effect: { kind: "wish", amount: 1 } }),
  consumableCard({
    id: "wishing-potion",
    title: "Wishing Potion",
    art: wishingPotion,
    effect: { kind: "wish", amount: 1 },
  }),
  {
    id: "meteor",
    title: "Meteor",
    descriptionLines: ["Deal 7 Burn damage", "Lose 1 Mana Crystal", "Consume"],
    art: meteor,
    cost: 1,
    consume: true,
    effects: [
      { kind: "damage", damageType: "burn", amount: 7 },
      { kind: "lose-max-mana", amount: 1 },
    ],
  },
  {
    id: "mixed-potion",
    title: "Mixed Potion",
    descriptionLines: ["Mixed at an Alchemist's Shop", "Consume"],
    art: mixedPotion,
    cost: 1,
    consume: true,
    effects: [],
  },
  summonCompanionCard({ id: "wolf-companion", title: "Wolf", art: wolfCompanion, companionId: "wolf" }),
  summonCompanionCard({
    id: "lizard-scout-companion",
    title: "Lizard Scout",
    art: lizardScoutCompanion,
    companionId: "lizard-scout",
  }),
  summonCompanionCard({ id: "imp-companion", title: "Imp", art: impCompanion, companionId: "imp" }),
  archeryDamageCard({
    id: "fire-arrow",
    title: "Fire Arrow",
    art: fireArrow,
    damageType: "burn",
    amount: 2,
  }),
  archeryDamageCard({
    id: "ice-shot",
    title: "Ice Shot",
    art: iceShot,
    damageType: "freeze",
    amount: 2,
  }),
  archeryDamageCard({
    id: "venom-arrow",
    title: "Venom Arrow",
    art: venomArrow,
    damageType: "poison",
    amount: 2,
  }),
  archeryDamageCard({
    id: "serrated-arrowhead",
    title: "Serrated Arrowhead",
    art: serratedArrowhead,
    damageType: "bleed",
    amount: 2,
  }),
  archeryDamageCard({
    id: "concussive-shot",
    title: "Concussive Shot",
    art: concussiveShot,
    damageType: "stun",
    amount: 3,
  }),
  archeryDamageCard({
    id: "lightning-arrow",
    title: "Lightning Arrow",
    art: lightningArrow,
    damageType: "nature",
    amount: 2,
  }),
  {
    id: "tithe",
    title: "Tithe",
    descriptionLines: ["Deal Holy damage equal to 10% of your Gold"],
    art: tithe,
    cost: 1,
    effects: [{ kind: "damage", damageType: "holy", amount: 0, equalToGoldPercent: 10 }],
  },
  {
    id: "exorcism",
    title: "Exorcism",
    descriptionLines: ["Cleanse all Burn on yourself", "Deal Holy damage equal to Burn removed"],
    art: exorcism,
    cost: 1,
    effects: [{ kind: "cleanse-player-status-to-damage", status: "burn", damageType: "holy", removeAll: true }],
  },
  damageThenMultiplyEnemyStatusCard({
    id: "kindling",
    title: "Kindling",
    art: kindling,
    damageType: "burn",
    damageAmount: 1,
    status: "burn",
    factor: 2,
    multiplyLine: "Double enemy Burn stacks",
    consume: true,
  }),
  {
    id: "roulette",
    title: "Roulette",
    descriptionLines: ["Deal 3 Random damage or Gain 3 Gold"],
    art: roulette,
    cost: 1,
    effects: [
      {
        kind: "chance",
        probability: 0.5,
        successEffects: [{ kind: "random-damage", minAmount: 3, maxAmount: 3 }],
        failureEffects: [{ kind: "gain-gold", amount: 3 }],
      },
    ],
  },
  damageCard({ id: "lightning-bolt", title: "Lightning Bolt", art: lightningBolt, damageType: "nature", amount: 4 }),
  {
    id: "wishing-well",
    title: "Wishing Well",
    descriptionLines: ["Wish 1", "Gain 1 Gold"],
    art: placeholderCard,
    cost: 1,
    effects: [
      { kind: "wish", amount: 1 },
      { kind: "gain-gold", amount: 1 },
    ],
  },
  damageThenMultiplyEnemyStatusCard({
    id: "hemorrhage",
    title: "Hemorrhage",
    art: placeholderCard,
    damageType: "physical",
    damageAmount: 2,
    status: "bleed",
    factor: 2,
    multiplyLine: "Double enemy Bleed stacks",
  }),
  {
    id: "bounty-shot",
    title: "Bounty Shot",
    descriptionLines: ["Deal 2 Physical damage", "Gain 2 Gold", "Archery"],
    art: placeholderCard,
    cost: 1,
    tags: ["archery"],
    effects: [
      { kind: "damage", damageType: "physical", amount: 2 },
      { kind: "gain-gold", amount: 2 },
    ],
  },
  {
    id: "sap-arrow",
    title: "Sap Arrow",
    descriptionLines: ["Deal 2 Nature damage", "Leech", "Archery"],
    art: placeholderCard,
    cost: 1,
    tags: ["archery"],
    effects: [{ kind: "damage", damageType: "nature", amount: 2, lifesteal: true }],
  },
  {
    id: "gamblers-shot",
    title: "Gambler's Shot",
    descriptionLines: ["Deal 1–6 Random damage", "Archery"],
    art: placeholderCard,
    cost: 1,
    tags: ["archery"],
    effects: [{ kind: "random-damage", minAmount: 1, maxAmount: 6 }],
  },
  {
    id: "phoenix-feather",
    title: "Phoenix Feather",
    descriptionLines: ["Lose 1 Mana Crystal", "If you would die, instead restore 30% Health"],
    art: placeholderCard,
    cost: 1,
    effects: [
      { kind: "lose-max-mana", amount: 1 },
      { kind: "player-status", status: "phoenixFeather", amount: 1 },
    ],
  },
];
