// Card library — every playable BattleCard in the game, authored as data.
// Depends on art assets and card type shapes. Each card is an effect pipeline; no logic.
import {
  antivenomPotion,
  bearCompanion,
  darkPact,
  goldenRetrieverCompanion,
  libraryOwlCompanion,
  manaMothCompanion,
  pixieCompanion,
  raiseSkeletonCompanion,
  shieldScarabCompanion,
  willOWispCompanion,
  blackjack,
  bloodOffering,
  bloodthorn,
  briarShield,
  burningBlade,
  cauterize,
  cinderbloom,
  coldSnap,
  faustianBargain,
  frostWhelpCompanion,
  graspingVines,
  holyRadiance,
  judgment,
  manaShield,
  packTactics,
  pantherCompanion,
  phoenixCompanion,
  plateMail,
  prayer,
  sanctifiedPlate,
  serratedEdge,
  shieldBash,
  smellingSalts,
  smite,
  steal,
  sunburst,
  sunderArmor,
  thornMail,
  venomFangs,
} from "../assets";
import type { BattleCard } from "../types";
import {
  cleansePlayerStatusCard,
  damageCard,
  damageThenMultiplyEnemyStatusCard,
  dualDamageCard,
  healThenDamageCard,
  loseHealthBenefitCard,
  playerStatThenScaledDamageCard,
  playerStatusCard,
  summonCompanionCard,
} from "./card-builders";

export const supportCards: BattleCard[] = [
  summonCompanionCard({
    id: "frost-whelp-companion",
    title: "Frost Whelp",
    art: frostWhelpCompanion,
    companionId: "frost-whelp",
  }),
  summonCompanionCard({ id: "bear-companion", title: "Bear", art: bearCompanion, companionId: "bear" }),
  summonCompanionCard({
    id: "panther-companion",
    title: "Panther",
    art: pantherCompanion,
    companionId: "panther",
  }),
  summonCompanionCard({
    id: "phoenix-companion",
    title: "Phoenix",
    art: phoenixCompanion,
    companionId: "phoenix",
  }),
  playerStatusCard({ id: "plate-mail", title: "Plate Mail", art: plateMail, status: "armor", amount: 2 }),
  playerStatThenScaledDamageCard({
    id: "sanctified-plate",
    title: "Sanctified Plate",
    art: sanctifiedPlate,
    damageType: "holy",
    scaleFrom: "armor",
    playerStat: { status: "armor", amount: 1 },
  }),
  {
    id: "shield-bash",
    title: "Shield Bash",
    descriptionLines: ["Deal 2 Stun damage", "Gain 2 Block"],
    art: shieldBash,
    cost: 1,
    effects: [
      { kind: "damage", damageType: "stun", amount: 2 },
      { kind: "player-status", status: "block", amount: 2 },
    ],
  },
  {
    id: "steal",
    title: "Steal",
    descriptionLines: ["Steal 4 Gold"],
    art: steal,
    cost: 1,
    effects: [{ kind: "gain-gold", amount: 4 }],
  },
  dualDamageCard({
    id: "burning-blade",
    title: "Burning Blade",
    art: burningBlade,
    hits: [
      { damageType: "physical", amount: 2 },
      { damageType: "burn", amount: 2 },
    ],
  }),
  // remove-harmful-status must come before self-damage so the burn cost is not instantly cleansed,
  {
    id: "cauterize",
    title: "Cauterize",
    descriptionLines: ["Remove 2 harmful status effects", "Receive 1 Burn damage"],
    art: cauterize,
    cost: 1,
    effects: [
      { kind: "remove-harmful-status", amount: 2 },
      { kind: "self-damage", damageType: "burn", amount: 1 },
    ],
  },
  {
    id: "blackjack",
    title: "Blackjack",
    descriptionLines: ["Deal 2 Stun damage", "Steal 2 Gold"],
    art: blackjack,
    cost: 1,
    effects: [
      { kind: "damage", damageType: "stun", amount: 2 },
      { kind: "gain-gold", amount: 2 },
    ],
  },
  healThenDamageCard({
    id: "sunburst",
    title: "Sunburst",
    art: sunburst,
    heal: 2,
    damageType: "burn",
    damage: 2,
  }),
  healThenDamageCard({
    id: "holy-radiance",
    title: "Holy Radiance",
    art: holyRadiance,
    heal: 2,
    damageType: "holy",
    damage: 2,
  }),
  damageCard({
    id: "venom-fangs",
    title: "Venom Fangs",
    art: venomFangs,
    damageType: "poison",
    amount: 2,
    lifesteal: true,
  }),
  damageCard({
    id: "bloodthorn",
    title: "Bloodthorn",
    art: bloodthorn,
    damageType: "nature",
    amount: 4,
    lifesteal: true,
  }),
  dualDamageCard({
    id: "cinderbloom",
    title: "Cinderbloom",
    art: cinderbloom,
    hits: [
      { damageType: "nature", amount: 2 },
      { damageType: "burn", amount: 2 },
    ],
  }),
  dualDamageCard({
    id: "grasping-vines",
    title: "Grasping Vines",
    art: graspingVines,
    hits: [
      { damageType: "nature", amount: 2 },
      { damageType: "stun", amount: 2 },
    ],
  }),
  playerStatThenScaledDamageCard({
    id: "briar-shield",
    title: "Briar Shield",
    art: briarShield,
    damageType: "nature",
    scaleFrom: "block",
    playerStat: { status: "block", amount: 3 },
  }),
  playerStatThenScaledDamageCard({
    id: "thorn-mail",
    title: "Thorn Mail",
    art: thornMail,
    damageType: "nature",
    scaleFrom: "armor",
    playerStat: { status: "armor", amount: 2 },
  }),
  {
    id: "pack-tactics",
    title: "Pack Tactics",
    descriptionLines: ["Increase Companion damage by 1", "Deal 3 Nature damage"],
    art: packTactics,
    cost: 1,
    effects: [
      { kind: "buff-companion", amount: 1 },
      { kind: "damage", damageType: "nature", amount: 3 },
    ],
  },
  dualDamageCard({
    id: "serrated-edge",
    title: "Serrated Edge",
    art: serratedEdge,
    hits: [
      { damageType: "bleed", amount: 1 },
      { damageType: "physical", amount: 3 },
    ],
  }),
  dualDamageCard({
    id: "smite",
    title: "Smite",
    art: smite,
    hits: [
      { damageType: "holy", amount: 2 },
      { damageType: "burn", amount: 2 },
    ],
  }),
  cleansePlayerStatusCard({
    id: "antivenom-potion",
    title: "Antivenom Potion",
    art: antivenomPotion,
    status: "poison",
    cleanseLine: "Cleanse all Poison",
    consume: true,
  }),
  damageThenMultiplyEnemyStatusCard({
    id: "cold-snap",
    title: "Cold Snap",
    art: coldSnap,
    damageType: "freeze",
    damageAmount: 1,
    status: "freeze",
    factor: 2,
    multiplyLine: "Double enemy's Freeze build-up",
  }),
  loseHealthBenefitCard({ id: "blood-offering", title: "Blood Offering", art: bloodOffering, healthLoss: 1, draw: 2 }),
  {
    id: "sunder-armor",
    title: "Sunder Armor",
    descriptionLines: ["Deal 4 Physical damage", "Strip 2 enemy Armor"],
    art: sunderArmor,
    cost: 1,
    effects: [
      { kind: "damage", damageType: "physical", amount: 4 },
      { kind: "remove-enemy-armor", amount: 2 },
    ],
  },
  {
    id: "mana-shield",
    title: "Mana Shield",
    descriptionLines: ["Gain 2 Block per Mana Crystal"],
    art: manaShield,
    cost: 1,
    effects: [{ kind: "player-status", status: "block", amount: 0, perManaCrystal: 2 }],
  },
  {
    id: "prayer",
    title: "Prayer",
    descriptionLines: ["Wish 1", "Restore 3 Health"],
    art: prayer,
    cost: 1,
    effects: [
      { kind: "wish", amount: 1 },
      { kind: "heal", amount: 3 },
    ],
  },
  loseHealthBenefitCard({
    id: "faustian-bargain",
    title: "Faustian Bargain",
    art: faustianBargain,
    healthLoss: 2,
    wish: 2,
    consume: true,
  }),
  dualDamageCard({
    id: "judgment",
    title: "Judgment",
    art: judgment,
    hits: [
      { damageType: "holy", amount: 3 },
      { damageType: "stun", amount: 1 },
    ],
  }),
  cleansePlayerStatusCard({
    id: "smelling-salts",
    title: "Smelling Salts",
    art: smellingSalts,
    status: "stun",
    cleanseLine: "Cleanse Stun build-up",
  }),
  loseHealthBenefitCard({
    id: "dark-pact",
    title: "Dark Pact",
    art: darkPact,
    healthLoss: 2,
    wish: 1,
    draw: 1,
  }),
  summonCompanionCard({
    id: "skeleton-companion",
    title: "Raise Skeleton",
    art: raiseSkeletonCompanion,
    companionId: "skeleton",
  }),
  summonCompanionCard({ id: "pixie-companion", title: "Pixie", art: pixieCompanion, companionId: "pixie" }),
  summonCompanionCard({
    id: "mana-moth-companion",
    title: "Mana Moth",
    art: manaMothCompanion,
    companionId: "mana-moth",
  }),
  summonCompanionCard({
    id: "will-o-wisp-companion",
    title: "Will-o'-Wisp",
    art: willOWispCompanion,
    companionId: "will-o-wisp",
  }),
  summonCompanionCard({
    id: "golden-retriever-companion",
    title: "Golden Retriever",
    art: goldenRetrieverCompanion,
    companionId: "golden-retriever",
  }),
  summonCompanionCard({
    id: "shield-scarab-companion",
    title: "Shield Scarab",
    art: shieldScarabCompanion,
    companionId: "shield-scarab",
  }),
  summonCompanionCard({
    id: "library-owl-companion",
    title: "Library Owl",
    art: libraryOwlCompanion,
    companionId: "library-owl",
  }),
];
