// Card library — every playable BattleCard in the game, authored as data.
// Depends on art assets and card type shapes. Each card is an effect pipeline; no logic.
import {
  antivenomPotion,
  bearCompanion,
  darkPact,
  goldenRetrieverCompanion,
  libraryOwlCompanion,
  manaMothCompanion,
  pixieCompanion,
  raiseSkeletonCompanion,
  shieldScarabCompanion,
  willOWispCompanion,
  blackjack,
  bloodOffering,
  bloodthorn,
  briarShield,
  burningBlade,
  cauterize,
  cinderbloom,
  coldSnap,
  faustianBargain,
  frostWhelpCompanion,
  graspingVines,
  holyRadiance,
  judgment,
  manaShield,
  packTactics,
  pantherCompanion,
  phoenixCompanion,
  plateMail,
  prayer,
  sanctifiedPlate,
  serratedEdge,
  shieldBash,
  smellingSalts,
  smite,
  steal,
  sunburst,
  sunderArmor,
  thornMail,
  venomFangs,
} from "../assets";
import type { BattleCard } from "../types";

export const supportCards: BattleCard[] = [
  {
    id: "frost-whelp-companion",
    title: "Frost Whelp",
    descriptionLines: ["Deals 1 Freeze damage each turn", "Companion"],
    art: frostWhelpCompanion,
    cost: 1,
    consume: true,
    effects: [{ kind: "summon-companion", companionId: "frost-whelp" }],
  },
  {
    id: "bear-companion",
    title: "Bear",
    descriptionLines: ["Deals 1 Stun damage each turn", "Companion"],
    art: bearCompanion,
    cost: 1,
    consume: true,
    effects: [{ kind: "summon-companion", companionId: "bear" }],
  },
  {
    id: "panther-companion",
    title: "Panther",
    descriptionLines: ["Deals 1 Bleed damage each turn", "Companion"],
    art: pantherCompanion,
    cost: 1,
    consume: true,
    effects: [{ kind: "summon-companion", companionId: "panther" }],
  },
  {
    id: "phoenix-companion",
    title: "Phoenix",
    descriptionLines: ["Deals 1 Burn damage each turn", "Companion"],
    art: phoenixCompanion,
    cost: 1,
    consume: true,
    effects: [{ kind: "summon-companion", companionId: "phoenix" }],
  },
  {
    id: "plate-mail",
    title: "Plate Mail",
    descriptionLines: ["Gain 2 Armor"],
    art: plateMail,
    cost: 1,
    effects: [{ kind: "player-status", status: "armor", amount: 2 }],
  },
  {
    id: "sanctified-plate",
    title: "Sanctified Plate",
    descriptionLines: ["Gain 1 Armor", "Deal Holy damage equal to your Armor"],
    art: sanctifiedPlate,
    cost: 1,
    effects: [
      { kind: "player-status", status: "armor", amount: 1 },
      { kind: "damage", damageType: "holy", amount: 0, equalToArmor: true },
    ],
  },
  {
    id: "shield-bash",
    title: "Shield Bash",
    descriptionLines: ["Deal 2 Stun damage", "Gain 2 Block"],
    art: shieldBash,
    cost: 1,
    effects: [
      { kind: "damage", damageType: "stun", amount: 2 },
      { kind: "player-status", status: "block", amount: 2 },
    ],
  },
  {
    id: "steal",
    title: "Steal",
    descriptionLines: ["Steal 4 Gold"],
    art: steal,
    cost: 1,
    effects: [{ kind: "gain-gold", amount: 4 }],
  },
  {
    id: "burning-blade",
    title: "Burning Blade",
    descriptionLines: ["Deal 2 Physical damage", "Deal 2 Burn damage"],
    art: burningBlade,
    cost: 1,
    effects: [
      { kind: "damage", damageType: "physical", amount: 2 },
      { kind: "damage", damageType: "burn", amount: 2 },
    ],
  },
  // remove-harmful-status must come before self-damage so the burn cost is not instantly cleansed,
  {
    id: "cauterize",
    title: "Cauterize",
    descriptionLines: ["Remove 2 harmful status effects", "Receive 1 Burn damage"],
    art: cauterize,
    cost: 1,
    effects: [
      { kind: "remove-harmful-status", amount: 2 },
      { kind: "self-damage", damageType: "burn", amount: 1 },
    ],
  },
  {
    id: "blackjack",
    title: "Blackjack",
    descriptionLines: ["Deal 2 Stun damage", "Steal 2 Gold"],
    art: blackjack,
    cost: 1,
    effects: [
      { kind: "damage", damageType: "stun", amount: 2 },
      { kind: "gain-gold", amount: 2 },
    ],
  },
  {
    id: "sunburst",
    title: "Sunburst",
    descriptionLines: ["Restore 2 Health", "Deal 2 Burn damage"],
    art: sunburst,
    cost: 1,
    effects: [
      { kind: "heal", amount: 2 },
      { kind: "damage", damageType: "burn", amount: 2 },
    ],
  },
  {
    id: "holy-radiance",
    title: "Holy Radiance",
    descriptionLines: ["Restore 2 Health", "Deal 2 Holy damage"],
    art: holyRadiance,
    cost: 1,
    effects: [
      { kind: "heal", amount: 2 },
      { kind: "damage", damageType: "holy", amount: 2 },
    ],
  },
  {
    id: "venom-fangs",
    title: "Venom Fangs",
    descriptionLines: ["Deal 2 Poison damage", "Leech"],
    art: venomFangs,
    cost: 1,
    effects: [{ kind: "damage", damageType: "poison", amount: 2, lifesteal: true }],
  },
  {
    id: "bloodthorn",
    title: "Bloodthorn",
    descriptionLines: ["Deal 4 Nature damage", "Leech"],
    art: bloodthorn,
    cost: 1,
    effects: [{ kind: "damage", damageType: "nature", amount: 4, lifesteal: true }],
  },
  {
    id: "cinderbloom",
    title: "Cinderbloom",
    descriptionLines: ["Deal 2 Nature damage", "Deal 2 Burn damage"],
    art: cinderbloom,
    cost: 1,
    effects: [
      { kind: "damage", damageType: "nature", amount: 2 },
      { kind: "damage", damageType: "burn", amount: 2 },
    ],
  },
  {
    id: "grasping-vines",
    title: "Grasping Vines",
    descriptionLines: ["Deal 2 Nature damage", "Deal 2 Stun damage"],
    art: graspingVines,
    cost: 1,
    effects: [
      { kind: "damage", damageType: "nature", amount: 2 },
      { kind: "damage", damageType: "stun", amount: 2 },
    ],
  },
  {
    id: "briar-shield",
    title: "Briar Shield",
    descriptionLines: ["Gain 3 Block", "Deal Nature damage equal to your Block"],
    art: briarShield,
    cost: 1,
    effects: [
      { kind: "player-status", status: "block", amount: 3 },
      { kind: "damage", damageType: "nature", amount: 0, equalToBlock: true },
    ],
  },
  {
    id: "thorn-mail",
    title: "Thorn Mail",
    descriptionLines: ["Gain 2 Armor", "Deal Nature damage equal to your Armor"],
    art: thornMail,
    cost: 1,
    effects: [
      { kind: "player-status", status: "armor", amount: 2 },
      { kind: "damage", damageType: "nature", amount: 0, equalToArmor: true },
    ],
  },
  {
    id: "pack-tactics",
    title: "Pack Tactics",
    descriptionLines: ["Increase Companion damage by 1", "Deal 3 Nature damage"],
    art: packTactics,
    cost: 1,
    effects: [
      { kind: "buff-companion", amount: 1 },
      { kind: "damage", damageType: "nature", amount: 3 },
    ],
  },
  {
    id: "serrated-edge",
    title: "Serrated Edge",
    descriptionLines: ["Deal 1 Bleed damage", "Deal 3 Physical damage"],
    art: serratedEdge,
    cost: 1,
    effects: [
      { kind: "damage", damageType: "bleed", amount: 1 },
      { kind: "damage", damageType: "physical", amount: 3 },
    ],
  },
  {
    id: "smite",
    title: "Smite",
    descriptionLines: ["Deal 2 Holy damage", "Deal 2 Burn damage"],
    art: smite,
    cost: 1,
    effects: [
      { kind: "damage", damageType: "holy", amount: 2 },
      { kind: "damage", damageType: "burn", amount: 2 },
    ],
  },
  {
    id: "antivenom-potion",
    title: "Antivenom Potion",
    descriptionLines: ["Cleanse all Poison", "Consume"],
    art: antivenomPotion,
    cost: 1,
    consume: true,
    effects: [{ kind: "remove-player-status", status: "poison" }],
  },
  {
    id: "cold-snap",
    title: "Cold Snap",
    descriptionLines: ["Deal 1 Freeze damage", "Double enemy's Freeze build-up"],
    art: coldSnap,
    cost: 1,
    effects: [
      { kind: "damage", damageType: "freeze", amount: 1 },
      { kind: "multiply-enemy-status", status: "freeze", factor: 2 },
    ],
  },
  {
    id: "blood-offering",
    title: "Blood Offering",
    descriptionLines: ["Lose 1 Health", "Draw 2 Cards"],
    art: bloodOffering,
    cost: 1,
    effects: [
      { kind: "lose-health", amount: 1 },
      { kind: "draw-cards", amount: 2 },
    ],
  },
  {
    id: "sunder-armor",
    title: "Sunder Armor",
    descriptionLines: ["Deal 4 Physical damage", "Strip 2 enemy Armor"],
    art: sunderArmor,
    cost: 1,
    effects: [
      { kind: "damage", damageType: "physical", amount: 4 },
      { kind: "remove-enemy-armor", amount: 2 },
    ],
  },
  {
    id: "mana-shield",
    title: "Mana Shield",
    descriptionLines: ["Gain 2 Block per Mana Crystal"],
    art: manaShield,
    cost: 1,
    effects: [{ kind: "player-status", status: "block", amount: 0, perManaCrystal: 2 }],
  },
  {
    id: "prayer",
    title: "Prayer",
    descriptionLines: ["Wish 1", "Restore 3 Health"],
    art: prayer,
    cost: 1,
    effects: [
      { kind: "wish", amount: 1 },
      { kind: "heal", amount: 3 },
    ],
  },
  {
    id: "faustian-bargain",
    title: "Faustian Bargain",
    descriptionLines: ["Lose 2 Health", "Wish 2", "Consume"],
    art: faustianBargain,
    cost: 1,
    consume: true,
    effects: [
      { kind: "lose-health", amount: 2 },
      { kind: "wish", amount: 2 },
    ],
  },
  {
    id: "judgment",
    title: "Judgment",
    descriptionLines: ["Deal 3 Holy damage", "Deal 1 Stun damage"],
    art: judgment,
    cost: 1,
    effects: [
      { kind: "damage", damageType: "holy", amount: 3 },
      { kind: "damage", damageType: "stun", amount: 1 },
    ],
  },
  {
    id: "smelling-salts",
    title: "Smelling Salts",
    descriptionLines: ["Cleanse Stun build-up"],
    art: smellingSalts,
    cost: 1,
    effects: [{ kind: "remove-player-status", status: "stun" }],
  },
  {
    id: "dark-pact",
    title: "Dark Pact",
    descriptionLines: ["Lose 2 Health", "Wish 1", "Draw 1 Card"],
    art: darkPact,
    cost: 1,
    effects: [
      { kind: "lose-health", amount: 2 },
      { kind: "wish", amount: 1 },
      { kind: "draw-cards", amount: 1 },
    ],
  },
  {
    id: "skeleton-companion",
    title: "Raise Skeleton",
    descriptionLines: ["Deals 1 Physical damage each turn", "Companion"],
    art: raiseSkeletonCompanion,
    cost: 1,
    consume: true,
    effects: [{ kind: "summon-companion", companionId: "skeleton" }],
  },
  {
    id: "pixie-companion",
    title: "Pixie",
    descriptionLines: ["Restores 1 Health each turn", "Companion"],
    art: pixieCompanion,
    cost: 1,
    consume: true,
    effects: [{ kind: "summon-companion", companionId: "pixie" }],
  },
  {
    id: "mana-moth-companion",
    title: "Mana Moth",
    descriptionLines: ["Restores 1 Mana each turn", "Companion"],
    art: manaMothCompanion,
    cost: 1,
    consume: true,
    effects: [{ kind: "summon-companion", companionId: "mana-moth" }],
  },
  {
    id: "will-o-wisp-companion",
    title: "Will-o'-Wisp",
    descriptionLines: ["Cleanses 1 harmful status each turn", "Companion"],
    art: willOWispCompanion,
    cost: 1,
    consume: true,
    effects: [{ kind: "summon-companion", companionId: "will-o-wisp" }],
  },
  {
    id: "golden-retriever-companion",
    title: "Golden Retriever",
    descriptionLines: ["Steals 1 Gold each turn", "Companion"],
    art: goldenRetrieverCompanion,
    cost: 1,
    consume: true,
    effects: [{ kind: "summon-companion", companionId: "golden-retriever" }],
  },
  {
    id: "shield-scarab-companion",
    title: "Shield Scarab",
    descriptionLines: ["Gain 2 Block each turn", "Companion"],
    art: shieldScarabCompanion,
    cost: 1,
    consume: true,
    effects: [{ kind: "summon-companion", companionId: "shield-scarab" }],
  },
  {
    id: "library-owl-companion",
    title: "Library Owl",
    descriptionLines: ["Draws 1 Card each turn", "Companion"],
    art: libraryOwlCompanion,
    cost: 1,
    consume: true,
    effects: [{ kind: "summon-companion", companionId: "library-owl" }],
  },
];
