import type { CardDefinition } from '@/entities/cards/types';
import type { CharacterId } from '@/shared/content/characters';

export const cards: CardDefinition[] = [
  {
    id: 'slash',
    title: 'Slash',
    description: 'Deal 4 Physical',
    artKey: 'slash',
    category: 'attack',
    keywords: ['physical'],
    templateId: 'fire',
  },
  {
    id: 'bash',
    title: 'Bash',
    description: 'Deal 3 Stun',
    artKey: 'bash',
    category: 'attack',
    keywords: ['stun'],
    templateId: 'fire',
  },
  {
    id: 'block',
    title: 'Block',
    description: 'Gain 6 Block',
    artKey: 'block',
    category: 'skill',
    keywords: ['block'],
    templateId: 'fire',
  },
  {
    id: 'anvil',
    title: 'Anvil',
    description: 'Gain 1 Forge',
    artKey: 'anvil',
    category: 'skill',
    keywords: ['forge'],
    templateId: 'fire',
  },
  {
    id: 'plate-mail',
    title: 'Plate Mail',
    description: 'Gain 1 Armor',
    artKey: 'plate-mail',
    category: 'skill',
    keywords: ['armor'],
    templateId: 'fire',
  },
  {
    id: 'apple',
    title: 'Apple',
    description: 'Gain 4 Health',
    artKey: 'apple',
    category: 'item',
    keywords: ['health'],
    templateId: 'nature',
  },
  {
    id: 'bread',
    title: 'Bread',
    description: 'Gain 6 Health',
    artKey: 'bread',
    category: 'item',
    keywords: ['health'],
    templateId: 'nature',
  },
  {
    id: 'stab',
    title: 'Stab',
    description: 'Deal 2 Damage\nTwice',
    artKey: 'stab',
    category: 'attack',
    keywords: ['twice'],
    templateId: 'mechanical',
  },
  {
    id: 'meteor',
    title: 'Meteor',
    description: 'Deal 15 Burn\nLose a Mana Crystal',
    artKey: 'meteor',
    category: 'attack',
    keywords: ['burn', 'mana'],
    templateId: 'fire',
  },
  {
    id: 'steal',
    title: 'Steal',
    description: 'Steal 4 Gold',
    artKey: 'steal',
    category: 'skill',
    keywords: ['gold'],
    templateId: 'death',
  },
  {
    id: 'blessed-aegis',
    title: 'Blessed Aegis',
    description: 'Deal Holy equal to your Block',
    artKey: 'blessed-aegis',
    category: 'attack',
    keywords: ['block'],
    templateId: 'holy',
  },
  {
    id: 'wish',
    title: 'Wish',
    description: 'Wish 1',
    artKey: 'wish',
    category: 'skill',
    keywords: ['wish'],
    templateId: 'arcane',
  },
  {
    id: 'cleanse',
    title: 'Cleanse',
    description: 'Remove an Ailment',
    artKey: 'cleanse',
    category: 'skill',
    keywords: ['ailment'],
    templateId: 'holy',
  },
  {
    id: 'heal',
    title: 'Heal',
    description: 'Restore 6 Health',
    artKey: 'heal',
    category: 'skill',
    keywords: ['health'],
    templateId: 'holy',
  },
  {
    id: 'haste',
    title: 'Haste',
    description: 'Take an extra turn after this one\nConsume',
    artKey: 'haste',
    category: 'skill',
    keywords: ['consume'],
    templateId: 'arcane',
  },
  {
    id: 'poison-dagger',
    title: 'Poison Dagger',
    description: 'Poison 2',
    artKey: 'poison-dagger',
    category: 'attack',
    keywords: ['poison'],
    templateId: 'death',
  },
  {
    id: 'fireball',
    title: 'Fireball',
    description: 'Deal 3 Burn',
    artKey: 'fireball',
    category: 'attack',
    keywords: ['burn'],
    templateId: 'fire',
  },
  {
    id: 'fangs',
    title: 'Fangs',
    description: 'Deal 2 Bleed\nLeech',
    artKey: 'fangs',
    category: 'attack',
    keywords: ['bleed', 'leech'],
    templateId: 'death',
  },
  {
    id: 'frostbolt',
    title: 'Frostbolt',
    description: 'Deal 3 Freeze',
    artKey: 'frostbolt',
    category: 'attack',
    keywords: ['freeze'],
    templateId: 'frost',
  },
  {
    id: 'health-potion',
    title: 'Health Potion',
    description: 'Restore 8 Health\nConsume',
    artKey: 'health-potion',
    category: 'item',
    keywords: ['health', 'consume'],
    templateId: 'nature',
  },
  {
    id: 'mana-berries',
    title: 'Mana Berries',
    description: 'Restore 2 Mana\nConsume',
    artKey: 'mana-berries',
    category: 'item',
    keywords: ['mana', 'consume'],
    templateId: 'arcane',
  },
  {
    id: 'mana-crystals',
    title: 'Mana Crystals',
    description: 'Gain 1 Mana Crystal',
    artKey: 'mana-crystals',
    category: 'skill',
    keywords: ['mana'],
    templateId: 'arcane',
  },
  {
    id: 'mana-potion',
    title: 'Mana Potion',
    description: 'Restore 2 Mana\nConsume',
    artKey: 'mana-potion',
    category: 'item',
    keywords: ['mana', 'consume'],
    templateId: 'arcane',
  },
  {
    id: 'panacea-potion',
    title: 'Panacea Potion',
    description: 'Remove all Ailments\nConsume',
    artKey: 'panacea-potion',
    category: 'item',
    keywords: ['ailment', 'consume'],
    templateId: 'nature',
  },
];

export const cardsById = Object.fromEntries(cards.map((card) => [card.id, card])) as Record<
  string,
  CardDefinition
>;

export const characterStarterDeckIds: Record<CharacterId, CardDefinition['id'][]> = {
  knight: ['slash', 'bash', 'block', 'anvil', 'plate-mail'],
  rogue: ['slash', 'stab', 'block', 'apple', 'bread'],
  wizard: ['bash', 'block', 'apple', 'bread', 'stab'],
};

export const starterDeckIds = characterStarterDeckIds.knight;
