import {
  defineResearch,
  foodSingleCosts,
  gemsSingleCosts,
  herbsSingleCosts,
  materialCost,
  stackingBuilding,
  stackingFarm,
  stackingResearch,
  stackingTiers,
  woodFoodCosts,
  woodHideCosts,
  woodStoneCosts,
} from "./data-builders";

export const buildings = [
  stackingBuilding(
    "blacksmiths-forge",
    "Blacksmith",
    [
      materialCost({ stone: 8, iron: 22 }),
      materialCost({ stone: 12, iron: 33 }),
      materialCost({ stone: 16, iron: 44 }),
      materialCost({ stone: 20, iron: 55 }),
    ],
    { flatPhysicalDamage: 1, homesteadForgeBurnPercent: 25, endRunIronPerRoom: 1 },
    (t) => `Physical damage +${t}\nBurn damage gains ${25 * t}% of Forge.`,
    (t) => `+${t} Iron per Room`,
  ),
  stackingBuilding(
    "hunters-lodge",
    "Hunter's Lodge",
    woodHideCosts(),
    { flatNatureDamage: 1, endRunFoodPerRoom: 1, endRunHidePerRoom: 1 },
    (t) => `Nature damage +${t}`,
    (t) => `+${t} Food and +${t} Hide per Room`,
  ),
  stackingBuilding(
    "alchemy-lab",
    "Alchemy Lab",
    [
      materialCost({ herbs: 22 }),
      materialCost({ stone: 12, herbs: 33 }),
      materialCost({ stone: 16, herbs: 44 }),
      materialCost({ stone: 20, herbs: 55 }),
    ],
    { homesteadPotionBonus: 1, endRunHerbsPerRoom: 1 },
    (t) => `Potion damage and healing +${t}`,
    (t) => `+${t} Herbs per Room`,
  ),
  stackingBuilding(
    "runesmiths-workshop",
    "Runesmith",
    [
      materialCost({ iron: 11, gems: 11 }),
      materialCost({ iron: 17, gems: 16 }),
      materialCost({ iron: 22, gems: 21 }),
      materialCost({ iron: 28, gems: 26 }),
    ],
    { flatFreezeDamage: 1, flatHolyDamage: 1, endRunGemsPerRoom: 1 },
    (t) => `Freeze and Holy damage +${t}`,
    (t) => `+${t} Gems per Room`,
  ),
  stackingBuilding(
    "companion-sanctuary",
    "Sanctuary",
    woodFoodCosts(),
    { companionDamage: 1 },
    (t) => `Companion damage +${t}`,
  ),
  stackingBuilding(
    "wishing-well",
    "Wishing Well",
    woodStoneCosts(),
    { wishExtraChoiceChance: 10, endRunWishPerRoom: 1 },
    (t) => `${10 * t}% chance for an extra Wish choice`,
    (t) => `+${t} Gems or Gold per Room`,
  ),
  stackingBuilding(
    "transmutation-crucible",
    "Transmutation Crucible",
    [
      materialCost({ stone: 8, iron: 11 }),
      materialCost({ stone: 12, iron: 17 }),
      materialCost({ stone: 16, iron: 22 }),
      materialCost({ stone: 20, iron: 28 }),
    ],
    { flatBurnDamage: 1, endRunIronPerRoom: 1 },
    (t) => `Burn damage +${t}`,
    (t) => `+${t} Iron per Room`,
  ),
  stackingBuilding(
    "mycology-cellar",
    "Mycology Cellar",
    [
      materialCost({ stone: 8, herbs: 11 }),
      materialCost({ stone: 12, herbs: 17 }),
      materialCost({ stone: 16, herbs: 22 }),
      materialCost({ stone: 20, herbs: 28 }),
    ],
    { homesteadLeechHealing: 1, endRunHerbsPerRoom: 1 },
    (t) => `Leech healing +${t}`,
    (t) => `+${t} Herbs per Room`,
  ),
  stackingBuilding(
    "sparring-grounds",
    "Sparring Grounds",
    woodStoneCosts(),
    { startBlock: 2, endRunIronPerRoom: 1 },
    (t) => `Starting Block +${2 * t}`,
    (t) => `+${t} Iron per Room`,
  ),
  stackingBuilding(
    "archery-range",
    "Archery Range",
    woodHideCosts(),
    { flatArrowDamage: 1, endRunWoodPerRoom: 1 },
    (t) => `Archery damage +${t}`,
    (t) => `+${t} Wood per Room`,
  ),
  stackingBuilding(
    "library",
    "Library",
    [
      materialCost({ wood: 8, gems: 11 }),
      materialCost({ wood: 12, gems: 16 }),
      materialCost({ wood: 16, gems: 21 }),
      materialCost({ wood: 20, gems: 26 }),
    ],
    { removeCardDiscount: 2 },
    (t) => `Removal cost −${2 * t} Gold`,
  ),
];

export const farmPlots = [
  stackingFarm(
    "wheat-field",
    "Wheat Field",
    foodSingleCosts(),
    { cardHealBonus: { bread: 2 }, endRunFoodPerRoom: 2 },
    (t) => `Bread healing +${2 * t}`,
    (t) => `+${2 * t} Food per Room`,
  ),
  stackingFarm(
    "herb-garden",
    "Herb Garden",
    herbsSingleCosts(),
    { poisonDamageReduction: 1, endRunHerbsPerRoom: 1 },
    (t) => `Poison damage taken −${t}`,
    (t) => `+${t} Herbs per Room`,
  ),
  stackingFarm(
    "chicken-coop",
    "Chicken Coop",
    woodFoodCosts(),
    { runMaxHealthBonus: 5, endRunFoodPerRoom: 2 },
    (t) => `Health +${5 * t}`,
    (t) => `+${2 * t} Food per Room`,
  ),
  stackingFarm(
    "pasture",
    "Pasture",
    woodFoodCosts(),
    { physicalDamageReduction: 1, endRunHidePerRoom: 1 },
    (t) => `Physical damage taken −${t}`,
    (t) => `+${t} Hide per Room`,
  ),
  stackingFarm(
    "orchard",
    "Orchard",
    woodFoodCosts(),
    { cardHealBonus: { apple: 2 }, endRunFoodPerRoom: 2 },
    (t) => `Apple healing +${2 * t}`,
    (t) => `+${2 * t} Food per Room`,
  ),
  stackingFarm(
    "crystal-garden",
    "Crystal Garden",
    [
      materialCost({ stone: 8, gems: 21 }),
      materialCost({ stone: 12, gems: 32 }),
      materialCost({ stone: 16, gems: 42 }),
      materialCost({ stone: 20, gems: 53 }),
    ],
    { homesteadCriticalDamage: 1, endRunGemsPerRoom: 2, endRunStonePerRoom: 1 },
    (t) => `Critical damage +${t}`,
    (t) => `+${2 * t} Gems and +${t} Stone per Room`,
  ),
];

export const researchUpgrades = [
  stackingResearch(
    "leyline-energy",
    "Leyline Energy",
    gemsSingleCosts(),
    { homesteadFreeManaChance: 5, endRunGemsPerRoom: 1 },
    (t) => `${5 * t}% chance to spend no Mana`,
    (t) => `+${t} Gems per Room`,
  ),
  defineResearch(
    "detect-magic",
    "Detect Magic",
    stackingTiers(
      gemsSingleCosts(),
      { gearAstralChanceBonus: 0.03, endRunGemsPerRoom: 1 },
      (t) => `Basic → Astral chance +${[3, 6, 10, 15][t - 1]}%`,
      (t) => `+${t} Gems per Room`,
    ).map((tier, index) => ({
      ...tier,
      effects: { ...tier.effects, gearAstralChanceBonus: index < 2 ? 0.03 : index === 2 ? 0.04 : 0.05 },
    })),
  ),
  stackingResearch(
    "botanical-distillation",
    "Botanical Distillation",
    herbsSingleCosts(),
    { mixPotionDiscount: 2, endRunHerbsPerRoom: 1 },
    (t) => `Potion mixing cost −${2 * t} Gold`,
    (t) => `+${t} Herbs per Room`,
  ),
  stackingResearch(
    "culinary-arts",
    "Culinary Arts",
    foodSingleCosts(),
    { homesteadHealing: 1, endRunFoodPerRoom: 1 },
    (t) => `Health restored +${t}`,
    (t) => `+${t} Food per Room`,
  ),
  stackingResearch(
    "wool-tailoring",
    "Wool Tailoring",
    woodHideCosts(),
    { freezeDamageReduction: 1, burnDamageReduction: 1, endRunGoldPerRoom: 1 },
    (t) => `Freeze and Burn damage taken −${t}`,
    (t) => `+${t} Gold per Room`,
  ),
  stackingResearch(
    "agility-training",
    "Agility Training",
    [
      materialCost({ food: 12, hide: 10 }),
      materialCost({ food: 17, hide: 15 }),
      materialCost({ food: 23, hide: 20 }),
      materialCost({ food: 29, hide: 25 }),
    ],
    { dodgeChance: 2 },
    (t) => `Dodge +${2 * t}%`,
  ),
];
