import { defaultCompanionBondLevels } from "@/lib/game-data";
import type { HomesteadEffectManifest } from "./types";

export const defaultHomesteadEffects: HomesteadEffectManifest = {
  flatPhysicalDamage: 0,
  flatHolyDamage: 0,
  physicalDamageReduction: 0,
  homesteadCriticalDamage: 0,
  homesteadHealing: 0,
  homesteadLeechHealing: 0,
  homesteadPotionBonus: 0,
  homesteadFreeManaChance: 0,
  homesteadForgeBurnPercent: 0,
  dodgeChance: 0,
  wishExtraChoiceChance: 0,
  companionDamage: 0,
  flatBurnDamage: 0,
  flatArrowDamage: 0,
  flatFreezeDamage: 0,
  flatNatureDamage: 0,
  startBlock: 0,
  burnDamageReduction: 0,
  freezeDamageReduction: 0,
  poisonDamageReduction: 0,
  runMaxHealthBonus: 0,
  companionBondLevels: { ...defaultCompanionBondLevels },
  cardHealBonus: {},
  herbFindBonus: 0,
  endRunStonePerRoom: 0,
  endRunFoodPerRoom: 0,
  endRunHerbsPerRoom: 0,
  endRunHidePerRoom: 0,
  endRunGemsPerRoom: 0,
  endRunIronPerRoom: 0,
  endRunWoodPerRoom: 0,
  endRunGoldPerRoom: 0,
  endRunWishPerRoom: 0,
  removeCardDiscount: 0,
  mixPotionDiscount: 0,
  gearAstralChanceBonus: 0,
};
