import { defaultCompanionBondLevels } from "@/lib/game-data";
import type { HomesteadEffectManifest } from "./types";

export const defaultHomesteadEffects: HomesteadEffectManifest = {
  flatPhysicalDamage: 0,
  companionDamage: 0,
  potionPotency: 0,
  flatBurnDamage: 0,
  flatArrowDamage: 0,
  flatFreezeDamage: 0,
  flatNatureDamage: 0,
  wishCrystalGold: 0,
  startMana: 0,
  consumeHealMultiplier: 0,
  potionMixPotency: 0,
  burnDamageReduction: 0,
  freezeDamageReduction: 0,
  natureDamageReduction: 0,
  poisonDamageReduction: 0,
  runMaxHealthBonus: 0,
  runMaxManaBonus: 0,
  forgeToBurn: false,
  companionBondLevels: { ...defaultCompanionBondLevels },
  cardHealBonus: {},
  herbFindBonus: 0,
  endRunFoodPerRoom: 0,
  endRunHerbsPerRoom: 0,
  endRunCrystalPerRoom: 0,
  gearAstralChanceBonus: 0,
};
