import { fileURLToPath } from "node:url";
import { defineConfig } from "oxlint";
import { BOUNDARY_CONFIGS } from "./lint/boundaries.js";
import { SYNTAX_CONFIGS } from "./lint/syntax.js";

// Explicit migrated policies keep unrelated Oxlint defaults out of this upgrade.
export default defineConfig({
  categories: { correctness: "off" },
  plugins: ["typescript", "react", "jsx-a11y", "vitest"],
  jsPlugins: [
    { name: "alchemy", specifier: fileURLToPath(new URL("./lint/plugin.js", import.meta.url)) },
    "eslint-plugin-playwright",
    { name: "react-hooks-js", specifier: "eslint-plugin-react-hooks" },
  ],
  options: { typeAware: true, reportUnusedDisableDirectives: "error" },
  ignorePatterns: [
    "dist",
    "dist-demo",
    "node_modules",
    ".vite",
    ".worktrees",
    "Raw Assets",
    "scratch",
    "playwright-report",
    "test-results",
    "coverage",
    "release-desktop",
    "release-desktop-demo",
    "reports",
    "blob-report",
    ".knip-output.json",
    ".eslintcache",
    "src/**/*.generated.ts",
    "src/lib/game-data/gear-art.generated.ts",
  ],
  rules: {
    "constructor-super": "error",
    "for-direction": "error",
    "getter-return": "error",
    "no-async-promise-executor": "error",
    "no-case-declarations": "error",
    "no-class-assign": "error",
    "no-compare-neg-zero": "error",
    "no-cond-assign": "error",
    "no-const-assign": "error",
    "no-constant-binary-expression": "error",
    "no-constant-condition": "error",
    "no-control-regex": "error",
    "no-debugger": "error",
    "no-delete-var": "error",
    "no-dupe-class-members": "error",
    "no-dupe-else-if": "error",
    "no-dupe-keys": "error",
    "no-duplicate-case": "error",
    "no-empty": [
      "error",
      {
        allowEmptyCatch: true,
      },
    ],
    "no-empty-character-class": "error",
    "no-empty-pattern": "error",
    "no-empty-static-block": "error",
    "no-ex-assign": "error",
    "no-extra-boolean-cast": "error",
    "no-fallthrough": "error",
    "no-func-assign": "error",
    "no-global-assign": "error",
    "no-import-assign": "error",
    "no-invalid-regexp": "error",
    "no-irregular-whitespace": "error",
    "no-loss-of-precision": "error",
    "no-misleading-character-class": "error",
    "no-new-native-nonconstructor": "error",
    "no-nonoctal-decimal-escape": "error",
    "no-obj-calls": "error",
    "no-prototype-builtins": "error",
    "no-redeclare": "error",
    "no-regex-spaces": "error",
    "no-self-assign": "error",
    "no-setter-return": "error",
    "no-shadow-restricted-names": "error",
    "no-sparse-arrays": "error",
    "no-this-before-super": "error",
    "no-unassigned-vars": "error",
    "no-undef": "error",
    "no-unreachable": "error",
    "no-unsafe-finally": "error",
    "no-unsafe-negation": "error",
    "no-unsafe-optional-chaining": "error",
    "no-unused-labels": "error",
    "no-unused-private-class-members": "error",
    "no-unused-vars": [
      "error",
      {
        argsIgnorePattern: "^_",
        varsIgnorePattern: "^_",
        caughtErrorsIgnorePattern: "^_",
        destructuredArrayIgnorePattern: "^_",
      },
    ],
    "no-useless-assignment": "error",
    "no-useless-backreference": "error",
    "no-useless-catch": "error",
    "no-useless-escape": "error",
    "no-with": "error",
    "preserve-caught-error": "error",
    "require-yield": "error",
    "use-isnan": "error",
    "valid-typeof": "error",
    "typescript/ban-ts-comment": "error",
    "no-array-constructor": "error",
    "typescript/no-duplicate-enum-values": "error",
    "typescript/no-empty-object-type": "error",
    "typescript/no-explicit-any": "error",
    "typescript/no-extra-non-null-assertion": "error",
    "typescript/no-misused-new": "error",
    "typescript/no-namespace": "error",
    "typescript/no-non-null-asserted-optional-chain": "error",
    "typescript/no-require-imports": "error",
    "typescript/no-this-alias": "error",
    "typescript/no-unnecessary-type-constraint": "error",
    "typescript/no-unsafe-declaration-merging": "error",
    "typescript/no-unsafe-function-type": "error",
    "no-unused-expressions": "error",
    "typescript/no-wrapper-object-types": "error",
    "typescript/prefer-as-const": "error",
    "typescript/prefer-namespace-keyword": "error",
    "typescript/triple-slash-reference": "error",
    eqeqeq: [
      "error",
      "always",
      {
        null: "ignore",
      },
    ],
    "no-promise-executor-return": "error",
    "typescript/consistent-type-imports": [
      "error",
      {
        prefer: "type-imports",
        fixStyle: "inline-type-imports",
        disallowTypeAnnotations: false,
      },
    ],
    "typescript/consistent-type-definitions": ["error", "interface"],
    "typescript/array-type": [
      "error",
      {
        default: "array-simple",
      },
    ],
    "alchemy/require-disable-reason": "error",
    "typescript/no-restricted-types": [
      "error",
      {
        types: {
          "React.FC": {
            message: "Use plain function components with explicit Props instead of React.FC.",
          },
          "React.FunctionComponent": {
            message: "Use plain function components with explicit Props instead of React.FunctionComponent.",
          },
        },
      },
    ],
  },
  overrides: [
    { files: ["desktop/preload.cjs"], globals: { document: "readonly" } },
    {
      files: ["**/*.ts", "**/*.tsx", "**/*.mts", "**/*.cts"],
      rules: {
        "constructor-super": "off",
        "getter-return": "off",
        "no-class-assign": "off",
        "no-const-assign": "off",
        "no-dupe-class-members": "off",
        "no-dupe-keys": "off",
        "no-func-assign": "off",
        "no-import-assign": "off",
        "no-new-native-nonconstructor": "off",
        "no-obj-calls": "off",
        "no-redeclare": "off",
        "no-setter-return": "off",
        "no-this-before-super": "off",
        "no-undef": "off",
        "no-unreachable": "off",
        "no-unsafe-negation": "off",
        "no-var": "error",
        "no-with": "off",
        "prefer-const": "error",
        "prefer-rest-params": "error",
        "prefer-spread": "error",
      },
    },
    {
      files: ["src/**"],
      rules: {
        "constructor-super": "off",
        "getter-return": "off",
        "no-class-assign": "off",
        "no-const-assign": "off",
        "no-dupe-class-members": "off",
        "no-dupe-keys": "off",
        "no-func-assign": "off",
        "no-import-assign": "off",
        "no-new-native-nonconstructor": "off",
        "no-obj-calls": "off",
        "no-redeclare": "off",
        "no-setter-return": "off",
        "no-this-before-super": "off",
        "no-undef": "off",
        "no-unreachable": "off",
        "no-unsafe-negation": "off",
        "no-var": "error",
        "no-with": "off",
        "prefer-const": "error",
        "prefer-rest-params": "error",
        "prefer-spread": "error",
      },
    },
    {
      files: ["src/**"],
      rules: {
        "typescript/await-thenable": "error",
        "typescript/ban-ts-comment": [
          "error",
          {
            minimumDescriptionLength: 10,
          },
        ],
        "no-array-constructor": "error",
        "typescript/no-array-delete": "error",
        "typescript/no-base-to-string": "error",
        "typescript/no-confusing-void-expression": "error",
        "typescript/no-deprecated": "error",
        "typescript/no-duplicate-enum-values": "error",
        "typescript/no-duplicate-type-constituents": "error",
        "typescript/no-dynamic-delete": "error",
        "typescript/no-empty-object-type": "error",
        "typescript/no-explicit-any": "error",
        "typescript/no-extra-non-null-assertion": "error",
        "typescript/no-extraneous-class": "error",
        "typescript/no-floating-promises": "error",
        "typescript/no-for-in-array": "error",
        "no-implied-eval": "off",
        "typescript/no-implied-eval": "error",
        "typescript/no-invalid-void-type": "error",
        "typescript/no-meaningless-void-operator": "error",
        "typescript/no-misused-new": "error",
        "typescript/no-misused-promises": "error",
        "typescript/no-misused-spread": "error",
        "typescript/no-mixed-enums": "error",
        "typescript/no-namespace": "error",
        "typescript/no-non-null-asserted-nullish-coalescing": "error",
        "typescript/no-non-null-asserted-optional-chain": "error",
        "typescript/no-non-null-assertion": "error",
        "typescript/no-redundant-type-constituents": "error",
        "typescript/no-require-imports": "error",
        "typescript/no-this-alias": "error",
        "typescript/no-unnecessary-boolean-literal-compare": "error",
        "typescript/no-unnecessary-condition": "error",
        "typescript/no-unnecessary-template-expression": "error",
        "typescript/no-unnecessary-type-arguments": "error",
        "typescript/no-unnecessary-type-assertion": "error",
        "typescript/no-unnecessary-type-constraint": "error",
        "typescript/no-unnecessary-type-conversion": "error",
        "typescript/no-unnecessary-type-parameters": "error",
        "typescript/no-unsafe-argument": "error",
        "typescript/no-unsafe-assignment": "error",
        "typescript/no-unsafe-call": "error",
        "typescript/no-unsafe-declaration-merging": "error",
        "typescript/no-unsafe-enum-comparison": "error",
        "typescript/no-unsafe-function-type": "error",
        "typescript/no-unsafe-member-access": "error",
        "typescript/no-unsafe-return": "error",
        "typescript/no-unsafe-unary-minus": "error",
        "no-unused-expressions": "error",
        "no-unused-vars": "error",
        "no-useless-constructor": "error",
        "typescript/no-useless-default-assignment": "error",
        "typescript/no-wrapper-object-types": "error",
        "typescript/only-throw-error": "error",
        "typescript/prefer-as-const": "error",
        "typescript/prefer-literal-enum-member": "error",
        "typescript/prefer-namespace-keyword": "error",
        "prefer-promise-reject-errors": "off",
        "typescript/prefer-promise-reject-errors": "error",
        "typescript/prefer-reduce-type-parameter": "error",
        "typescript/prefer-return-this-type": "error",
        "typescript/related-getter-setter-pairs": "error",
        "require-await": "off",
        "typescript/require-await": "error",
        "typescript/restrict-plus-operands": [
          "error",
          {
            allowAny: false,
            allowBoolean: false,
            allowNullish: false,
            allowNumberAndString: false,
            allowRegExp: false,
          },
        ],
        "typescript/restrict-template-expressions": [
          "error",
          {
            allowAny: false,
            allowBoolean: false,
            allowNever: false,
            allowNullish: false,
            allowNumber: false,
            allowRegExp: false,
          },
        ],
        "typescript/return-await": ["error", "error-handling-correctness-only"],
        "typescript/triple-slash-reference": "error",
        "typescript/unbound-method": "error",
        "typescript/unified-signatures": "error",
        "typescript/use-unknown-in-catch-callback-variable": "error",
      },
    },
    {
      files: ["src/**"],
      rules: {
        "typescript/no-non-null-assertion": "off",
        "typescript/no-confusing-void-expression": "off",
        "typescript/restrict-template-expressions": [
          "error",
          {
            allowNumber: true,
            allowBoolean: true,
            allowNever: true,
            allowAny: false,
            allowNullish: true,
          },
        ],
        "typescript/no-unnecessary-condition": "off",
        "typescript/no-invalid-void-type": "off",
        "typescript/consistent-type-exports": [
          "error",
          {
            fixMixedExportsWithInlineTypeSpecifier: true,
          },
        ],
        "typescript/no-deprecated": "error",
        "typescript/switch-exhaustiveness-check": "error",
        "typescript/prefer-nullish-coalescing": "error",
        "no-console": [
          "error",
          {
            allow: ["warn", "error"],
          },
        ],
        "typescript/ban-ts-comment": [
          "error",
          {
            "ts-expect-error": "allow-with-description",
            "ts-ignore": true,
            "ts-nocheck": true,
            "ts-check": false,
            minimumDescriptionLength: 3,
          },
        ],
      },
    },
    {
      files: ["src/**/*.{ts,tsx}", "tests/**/*.test.tsx", "tests/**/*.dom.test.ts"],
      rules: {
        "react/rules-of-hooks": "error",
        "react/exhaustive-deps": "warn",
        "react/static-components": "error",
        "react/use-memo": "error",
        "react/void-use-memo": "error",
        "react/preserve-manual-memoization": "error",
        "react/incompatible-library": "warn",
        "react/immutability": "error",
        "react/globals": "error",
        "react/refs": "error",
        "react/set-state-in-effect": "error",
        "react/error-boundaries": "error",
        "react/purity": "error",
        "react/set-state-in-render": "error",
        "react/unsupported-syntax": "warn",
        "react-hooks-js/config": "error",
        "react-hooks-js/gating": "error",
        "react/only-export-components": [
          "error",
          {
            allowConstantExport: true,
          },
        ],
      },
    },
    {
      files: ["src/**/*.{ts,tsx}"],
      rules: {
        "alchemy/no-run-earned-add-materials": "error",
        "alchemy/session-ownership": "error",
        "alchemy/no-unowned-web-storage": "error",
      },
    },
    {
      files: ["src/lib/**/*.{ts,tsx}"],
      rules: {
        "alchemy/no-lib-fetch": "error",
      },
    },
    {
      files: [
        "src/lib/mystery/**/*.{ts,tsx}",
        "src/lib/game-data/**/*.{ts,tsx}",
        "src/lib/gear/**/*.{ts,tsx}",
        "src/lib/content-systems/**/*.{ts,tsx}",
        "src/features/alchemy/run-loop/screens/**/*.{ts,tsx}",
        "src/features/alchemy/run-setup/screens/**/*.{ts,tsx}",
        "src/features/alchemy/meta/screens/**/*.{ts,tsx}",
      ],
      rules: {
        "alchemy/no-em-dash": "error",
      },
    },
    ...BOUNDARY_CONFIGS,
    {
      files: [
        "src/app/screen-routes/*-routes.tsx",
        "src/app/screen-routes/*-route.tsx",
        "src/app/app-screen-chrome-context.tsx",
        "src/features/alchemy/shared/context/card-description-context.tsx",
        "src/features/alchemy/shared/ui/use-fade.tsx",
        "src/features/alchemy/shared/ui/cards/card-description-ui.tsx",
        "src/features/alchemy/shared/ui/material-icons.tsx",
        "src/features/alchemy/shared/ui/collection-ui.tsx",
        "src/features/alchemy/meta/screens/homestead/helpers.tsx",
        "src/features/alchemy/meta/screens/armory/paged-picker-grid.tsx",
        "src/features/alchemy/meta/screens/armory/armory-character-tabs.tsx",
      ],
      rules: {
        "react/only-export-components": "off",
      },
    },
    {
      files: ["src/**/*.{ts,tsx}"],
      rules: {
        "typescript/no-explicit-any": "error",
        "no-template-curly-in-string": "error",
      },
    },
    {
      files: ["tests/**/*.ts", "tests/**/*.tsx", "performance/**/*.ts"],
      rules: {
        "no-unused-vars": [
          "error",
          {
            argsIgnorePattern: "^_",
            varsIgnorePattern: "^_",
            caughtErrorsIgnorePattern: "^_",
            destructuredArrayIgnorePattern: "^_",
          },
        ],
        "typescript/no-explicit-any": "off",
      },
    },
    {
      files: ["tests/**/*.test.ts", "tests/**/*.test.tsx", "tests/**/*.dom.test.ts"],
      rules: {
        "vitest/expect-expect": "off",
        "vitest/no-commented-out-tests": "error",
        "vitest/no-conditional-expect": "off",
        "vitest/no-disabled-tests": "warn",
        "vitest/no-focused-tests": "error",
        "vitest/no-identical-title": "error",
        "vitest/no-import-node-test": "error",
        "vitest/no-interpolation-in-snapshots": "off",
        "vitest/no-mocks-import": "error",
        "vitest/no-standalone-expect": "error",
        "vitest/no-unneeded-async-expect-function": "error",
        "vitest/prefer-called-exactly-once-with": "error",
        "vitest/require-local-test-context-for-concurrent-snapshots": "error",
        "vitest/valid-describe-callback": "error",
        "vitest/valid-expect": [
          "error",
          {
            maxArgs: 2,
          },
        ],
        "vitest/valid-expect-in-promise": "error",
        "vitest/valid-title": "error",
      },
    },
    {
      files: ["tests/e2e/**/*.ts", "tests/helpers/diagnostics/**/*.{ts,tsx}"],
      excludeFiles: ["tests/**/*.spec.ts"],
      rules: {
        "vitest/no-disabled-tests": "off",
      },
    },
    {
      files: ["tests/**/*.spec.ts", "tests/pages/**/*.ts", "tests/fixtures/**/*.ts"],
      rules: {
        "react/rules-of-hooks": "off",
        "react/exhaustive-deps": "off",
      },
    },
    {
      files: ["src/**/*.tsx", "src/**/*.jsx"],
      rules: {
        "jsx-a11y/alt-text": "error",
        "jsx-a11y/aria-props": "error",
        "jsx-a11y/aria-role": [
          "error",
          {
            ignoreNonDOM: true,
          },
        ],
        "jsx-a11y/aria-unsupported-elements": "error",
        "jsx-a11y/role-has-required-aria-props": "error",
        "jsx-a11y/no-noninteractive-element-interactions": "error",
        "jsx-a11y/interactive-supports-focus": "error",
        "jsx-a11y/click-events-have-key-events": "error",
        "jsx-a11y/no-aria-hidden-on-focusable": "error",
        "jsx-a11y/anchor-is-valid": "error",
        "jsx-a11y/label-has-associated-control": "error",
        "jsx-a11y/no-noninteractive-tabindex": "error",
        "jsx-a11y/tabindex-no-positive": "error",
      },
    },
    {
      files: [
        "tests/**/*.spec.ts",
        "tests/pages/**/*.ts",
        "tests/fixtures/**/*.ts",
        "performance/scenarios/**/*.perf.ts",
      ],
      globals: {
        AbortController: "readonly",
        AbortSignal: "readonly",
        atob: "readonly",
        Blob: "readonly",
        BroadcastChannel: "readonly",
        btoa: "readonly",
        ByteLengthQueuingStrategy: "readonly",
        clearInterval: "readonly",
        clearTimeout: "readonly",
        CloseEvent: "readonly",
        CompressionStream: "readonly",
        console: "readonly",
        CountQueuingStrategy: "readonly",
        crypto: "readonly",
        Crypto: "readonly",
        CryptoKey: "readonly",
        CustomEvent: "readonly",
        DecompressionStream: "readonly",
        DOMException: "readonly",
        ErrorEvent: "readonly",
        Event: "readonly",
        EventTarget: "readonly",
        fetch: "readonly",
        File: "readonly",
        FormData: "readonly",
        Headers: "readonly",
        localStorage: "readonly",
        MessageChannel: "readonly",
        MessageEvent: "readonly",
        MessagePort: "readonly",
        navigator: "readonly",
        Navigator: "readonly",
        performance: "readonly",
        Performance: "readonly",
        PerformanceEntry: "readonly",
        PerformanceMark: "readonly",
        PerformanceMeasure: "readonly",
        PerformanceObserver: "readonly",
        PerformanceObserverEntryList: "readonly",
        PerformanceResourceTiming: "readonly",
        queueMicrotask: "readonly",
        QuotaExceededError: "readonly",
        ReadableByteStreamController: "readonly",
        ReadableStream: "readonly",
        ReadableStreamBYOBReader: "readonly",
        ReadableStreamBYOBRequest: "readonly",
        ReadableStreamDefaultController: "readonly",
        ReadableStreamDefaultReader: "readonly",
        Request: "readonly",
        Response: "readonly",
        sessionStorage: "readonly",
        setInterval: "readonly",
        setTimeout: "readonly",
        Storage: "readonly",
        structuredClone: "readonly",
        SubtleCrypto: "readonly",
        Temporal: "readonly",
        TextDecoder: "readonly",
        TextDecoderStream: "readonly",
        TextEncoder: "readonly",
        TextEncoderStream: "readonly",
        TransformStream: "readonly",
        TransformStreamDefaultController: "readonly",
        URL: "readonly",
        URLPattern: "readonly",
        URLSearchParams: "readonly",
        WebAssembly: "readonly",
        WebSocket: "readonly",
        WritableStream: "readonly",
        WritableStreamDefaultController: "readonly",
        WritableStreamDefaultWriter: "readonly",
      },
      rules: {
        "no-empty-pattern": "off",
        "playwright/consistent-spacing-between-blocks": "warn",
        "playwright/expect-expect": "off",
        "playwright/max-nested-describe": "warn",
        "playwright/missing-playwright-await": "error",
        "playwright/no-conditional-expect": "off",
        "playwright/no-conditional-in-test": "off",
        "playwright/no-duplicate-hooks": "warn",
        "playwright/no-duplicate-slow": "warn",
        "playwright/no-element-handle": "warn",
        "playwright/no-eval": "warn",
        "playwright/no-focused-test": "error",
        "playwright/no-force-option": "off",
        "playwright/no-nested-step": "warn",
        "playwright/no-networkidle": "error",
        "playwright/no-page-pause": "warn",
        "playwright/no-skipped-test": "warn",
        "playwright/no-standalone-expect": "error",
        "playwright/no-unnecessary-assertions": "error",
        "playwright/no-unsafe-references": "error",
        "playwright/no-unused-locators": "error",
        "playwright/no-useless-await": "warn",
        "playwright/no-useless-not": "warn",
        "playwright/no-wait-for-navigation": "error",
        "playwright/no-wait-for-selector": "warn",
        "playwright/no-wait-for-timeout": "warn",
        "playwright/prefer-hooks-in-order": "warn",
        "playwright/prefer-hooks-on-top": "warn",
        "playwright/prefer-locator": "warn",
        "playwright/prefer-to-have-count": "warn",
        "playwright/prefer-to-have-length": "warn",
        "playwright/prefer-web-first-assertions": "error",
        "playwright/valid-describe-callback": "error",
        "playwright/valid-expect": "error",
        "playwright/valid-expect-in-promise": "error",
        "playwright/valid-test-tags": "error",
        "playwright/valid-title": "error",
      },
    },
    {
      files: ["scripts/**/*.mjs", "lint/**/*.js", "desktop/**/*.cjs", "tests/electron/*.cjs"],
      globals: {
        console: "readonly",
        process: "readonly",
        require: "readonly",
        module: "readonly",
        __dirname: "readonly",
        __filename: "readonly",
        Buffer: "readonly",
        setTimeout: "readonly",
        clearTimeout: "readonly",
        setInterval: "readonly",
        clearInterval: "readonly",
        fetch: "readonly",
        AbortSignal: "readonly",
        URL: "readonly",
        Response: "readonly",
      },
      rules: {
        "typescript/no-require-imports": "off",
      },
    },
    ...SYNTAX_CONFIGS,
    {
      files: ["src/lib/battle/types.ts", "src/lib/battle/types/state-types.ts"],
      rules: {
        "alchemy/battle-types-only": "error",
      },
    },
  ],
});
