import { describe, expect, it } from "vitest";
import {
  ATTACK_LUNGE_DURATION_MS,
  AUTO_END_TURN_DELAY_MS,
  AUTOPLAY_POST_PLAY_DELAY_MS,
  AUTOPLAY_PREVIEW_MS,
  AUTOPLAY_RETRY_DELAY_MS,
  CAMPFIRE_ANIMATION_MS,
  CAMPFIRE_CONTINUE_DELAY_MS,
  COMPANION_ATTACK_DELAY_MS,
  ENEMY_ATTACK_RECOVERY_DELAY_MS,
  ENEMY_PHASE_DELAY_MS,
  HIT_SHAKE_DELAY_MS,
  NAVIGATION_DELAY_MS,
  SHAKE_DURATION_MS,
  SHAKE_EXTRA_MS,
  SLICE_DEATH_DURATION_MS,
  BATTLE_END_TRANSITION_DELAY_MS,
} from "@/lib/game-constants";

describe("battle timing constants", () => {
  it("keeps presentation delays positive and ordered", () => {
    for (const value of [
      AUTO_END_TURN_DELAY_MS,
      AUTOPLAY_PREVIEW_MS,
      AUTOPLAY_RETRY_DELAY_MS,
      AUTOPLAY_POST_PLAY_DELAY_MS,
      SLICE_DEATH_DURATION_MS,
      BATTLE_END_TRANSITION_DELAY_MS,
      ENEMY_PHASE_DELAY_MS,
      ENEMY_ATTACK_RECOVERY_DELAY_MS,
      HIT_SHAKE_DELAY_MS,
      ATTACK_LUNGE_DURATION_MS,
      COMPANION_ATTACK_DELAY_MS,
      NAVIGATION_DELAY_MS,
      CAMPFIRE_ANIMATION_MS,
      CAMPFIRE_CONTINUE_DELAY_MS,
    ]) {
      expect(value).toBeGreaterThan(0);
    }

    expect(BATTLE_END_TRANSITION_DELAY_MS).toBeGreaterThanOrEqual(SLICE_DEATH_DURATION_MS);
    expect(SHAKE_DURATION_MS).toBeGreaterThan(HIT_SHAKE_DELAY_MS);
    expect(SHAKE_DURATION_MS).toBe(HIT_SHAKE_DELAY_MS + SHAKE_EXTRA_MS);
    expect(ATTACK_LUNGE_DURATION_MS).toBeGreaterThan(HIT_SHAKE_DELAY_MS);
  });
});
