import { existsSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { allGameArt, essentialGameArt } from "@/lib/game-data";
import { gearArtByDefinitionId } from "@/lib/game-data/gear-art.generated";
import { ART_PRESETS, QUALITY, WIDTH } from "../../scripts/assets/asset-constants.mjs";
import { GEAR_SLOT_IDS } from "../../scripts/assets/gear-filenames.mjs";
import { staticAssets } from "../../scripts/assets/asset-manifest.mjs";
import { readText, repoRoot } from "./helpers";

describe("asset manifest consistency", () => {
  it("uses only frozen WIDTH/QUALITY presets (no magic literals)", () => {
    // WIDTH/QUALITY are pure views over the single ART_PRESETS table.
    expect(new Set(Object.keys(WIDTH))).toEqual(new Set(Object.keys(ART_PRESETS)));
    expect(new Set(Object.keys(QUALITY))).toEqual(new Set(Object.keys(ART_PRESETS)));
    const allowedWidths = new Set(Object.values(WIDTH));
    const allowedQualities = new Set(Object.values(QUALITY));
    for (const entry of staticAssets) {
      expect(allowedWidths.has(entry.width), `${entry.target} width ${entry.width} must be from WIDTH`).toBe(true);
      expect(allowedQualities.has(entry.quality), `${entry.target} quality ${entry.quality} must be from QUALITY`).toBe(
        true,
      );
    }
  });

  it("keeps essentialGameArt as allGameArt minus non-slot gear assets", () => {
    const gearItemSet = new Set(
      Object.entries(gearArtByDefinitionId)
        .filter(([id]) => !id.startsWith("slot-"))
        .map(([, src]) => src),
    );
    const slotSet = new Set(
      Object.entries(gearArtByDefinitionId)
        .filter(([id]) => id.startsWith("slot-"))
        .map(([, src]) => src),
    );
    for (const src of essentialGameArt) {
      expect(gearItemSet.has(src), `${src} should not be in essentialGameArt`).toBe(false);
    }
    for (const src of slotSet) {
      expect(essentialGameArt, `${src} slot background should load with startup art`).toContain(src);
    }
    expect(essentialGameArt.length).toBeLessThan(allGameArt.length);
    expect(essentialGameArt.length + gearItemSet.size).toBe(allGameArt.length);
  });

  it("has no duplicate targets", () => {
    const targets = staticAssets.map((e) => e.target);
    expect(new Set(targets).size).toBe(targets.length);
  });

  it("keeps pipeline slot ids and runtime slot art in agreement", () => {
    for (const slotId of GEAR_SLOT_IDS) {
      expect(
        gearArtByDefinitionId[`slot-${slotId}`],
        `missing runtime art for pipeline slot "${slotId}" (add the slot background or update GEAR_SLOT_IDS)`,
      ).toBeTruthy();
    }
  });
});

describe("committed asset outputs", () => {
  it("keeps generated registries and sample optimized media in the repo", () => {
    const assetsGenerated = join(repoRoot, "src/lib/game-data/assets.generated.ts");
    const gearArt = join(repoRoot, "src/lib/game-data/gear-art.generated.ts");
    const sampleWebp = join(repoRoot, "src/assets/optimized/alchemy-logo.webp");
    const sampleSound = join(repoRoot, "public/sounds/denied-03.ogg");

    expect(existsSync(assetsGenerated)).toBe(true);
    expect(existsSync(gearArt)).toBe(true);
    expect(existsSync(sampleWebp)).toBe(true);
    expect(existsSync(sampleSound)).toBe(true);

    const generated = readText("src/lib/game-data/assets.generated.ts");
    expect(generated).toContain("Generated by scripts/sync-art-barrels.mjs");
    expect(generated).toContain("@/assets/optimized/");
  });
});
