import { execSync } from "node:child_process";
import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { CURRENT_GAME_BUILD_VERSION } from "@/lib/validation";

const ROOT = join(import.meta.dirname, "../..");

function listVersionTags(): string[] {
  try {
    const output = execSync('git tag --list "v*"', { cwd: ROOT, stdio: ["ignore", "pipe", "ignore"] })
      .toString()
      .trim();
    if (!output) return [];
    return output.split("\n").map((tag) => tag.replace(/^v/, ""));
  } catch {
    return [];
  }
}

describe("version sync", () => {
  it("keeps CURRENT_GAME_BUILD_VERSION aligned with package.json", () => {
    const pkg = JSON.parse(readFileSync(join(ROOT, "package.json"), "utf8")) as { version: string };
    expect(CURRENT_GAME_BUILD_VERSION).toBe(pkg.version);
  });

  it("metadata.generated.ts is present and auto-generated", () => {
    const generated = readFileSync(join(ROOT, "src/lib/validation/metadata.generated.ts"), "utf8");
    expect(generated).toContain("AUTO-GENERATED by scripts/sync-version-metadata.mjs");
    expect(generated).toContain(`CURRENT_GAME_BUILD_VERSION = "${CURRENT_GAME_BUILD_VERSION}"`);
  });
});

describe("changelog enforcement", () => {
  it("includes CHANGELOG.md in the repository", () => {
    expect(existsSync(join(ROOT, "CHANGELOG.md"))).toBe(true);
  });

  it("documents each release tag in CHANGELOG.md when tags exist", () => {
    const changelog = readFileSync(join(ROOT, "CHANGELOG.md"), "utf8");
    const tags = listVersionTags();
    if (tags.length === 0) {
      expect(changelog.length).toBeGreaterThan(0);
      return;
    }
    for (const version of tags) {
      expect(changelog).toContain(version);
    }
  });
});

describe("changelog release-time ownership", () => {
  it("syncs and promotes CHANGELOG.md only during release bumps", () => {
    const versionrc = JSON.parse(readFileSync(join(ROOT, ".versionrc.json"), "utf8"));
    expect(versionrc.scripts.prerelease).toBe("node scripts/sync-changelog.mjs");
    expect(versionrc.scripts.postbump).toBe("node scripts/release-changelog.mjs");
    expect(versionrc.skip?.changelog).toBe(true);
  });

  it("does not run day-to-day changelog hooks", () => {
    const hookConfig = readFileSync(join(ROOT, "lefthook.yml"), "utf8");
    expect(hookConfig).not.toContain("sync-changelog");
    expect(hookConfig).not.toMatch(/^post-commit:/m);
    expect(existsSync(join(ROOT, "scripts/sync-changelog-post-commit.mjs"))).toBe(false);
    expect(existsSync(join(ROOT, "scripts/sync-changelog-commit.mjs"))).toBe(false);
  });

  it("generates player patch notes from git, not CHANGELOG.md", () => {
    const source = readFileSync(join(ROOT, "scripts/generate-patch-notes.mjs"), "utf8");
    expect(source).not.toContain("readChangelog");
    expect(source).not.toContain("parseChangelogCommits");
    expect(source).toContain("getCommitsSinceTag");
  });

  it("previews player notes before tagging and supports --dry-run", () => {
    const runner = readFileSync(join(ROOT, "scripts/lib/release-runner.mjs"), "utf8");
    expect(runner).toContain("generate:patch-notes");
    expect(runner).toContain("--dry-run");
    expect(runner).toContain("previewPatchNotes");
    const release = readFileSync(join(ROOT, "scripts/release.mjs"), "utf8");
    expect(release).toContain("parseReleaseArgs");
  });
});
