import { execSync } from "node:child_process";
import { existsSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { CURRENT_GAME_BUILD_VERSION } from "@/lib/validation";
import { readText, repoRoot } from "./helpers";

function listVersionTags(): string[] {
  try {
    const output = execSync('git tag --list "v*"', { cwd: repoRoot, stdio: ["ignore", "pipe", "ignore"] })
      .toString()
      .trim();
    if (!output) return [];
    return output.split("\n").map((tag) => tag.replace(/^v/, ""));
  } catch {
    return [];
  }
}

describe("version sync", () => {
  it("keeps CURRENT_GAME_BUILD_VERSION aligned with package.json", () => {
    const pkg = JSON.parse(readText("package.json")) as { version: string };
    expect(CURRENT_GAME_BUILD_VERSION).toBe(pkg.version);
  });

  it("metadata.generated.ts is present and auto-generated", () => {
    const generated = readText("src/lib/validation/metadata.generated.ts");
    expect(generated).toContain("AUTO-GENERATED by scripts/sync-version-metadata.mjs");
    expect(generated).toContain(`CURRENT_GAME_BUILD_VERSION = "${CURRENT_GAME_BUILD_VERSION}"`);
  });
});

describe("changelog enforcement", () => {
  it("includes CHANGELOG.md in the repository", () => {
    expect(existsSync(join(repoRoot, "CHANGELOG.md"))).toBe(true);
  });

  it("documents each release tag in CHANGELOG.md when tags exist", () => {
    const changelog = readText("CHANGELOG.md");
    const tags = listVersionTags();
    if (tags.length === 0) {
      expect(changelog.length).toBeGreaterThan(0);
      return;
    }
    for (const version of tags) {
      expect(changelog).toContain(version);
    }
  });
});

describe("changelog release-time ownership", () => {
  it("syncs and promotes CHANGELOG.md only during release bumps", () => {
    const versionrc = JSON.parse(readText(".versionrc.json")) as {
      scripts: { prerelease: string; postbump: string };
      skip?: { changelog?: boolean };
    };
    expect(versionrc.scripts.prerelease).toBe("node scripts/sync-changelog.mjs");
    expect(versionrc.scripts.postbump).toBe("node scripts/release-changelog.mjs");
    expect(versionrc.skip?.changelog).toBe(true);
  });

  it("does not run day-to-day changelog hooks", () => {
    const hookConfig = readText("lefthook.yml");
    expect(hookConfig).not.toContain("sync-changelog");
    expect(hookConfig).not.toMatch(/^post-commit:/m);
    expect(existsSync(join(repoRoot, "scripts/sync-changelog-post-commit.mjs"))).toBe(false);
    expect(existsSync(join(repoRoot, "scripts/sync-changelog-commit.mjs"))).toBe(false);
  });

  it("generates player patch notes from git, not CHANGELOG.md", () => {
    const source = readText("scripts/generate-patch-notes.mjs");
    expect(source).not.toContain("readChangelog");
    expect(source).not.toContain("parseChangelogCommits");
    expect(source).toContain("getCommitsSinceTag");
  });

  it("previews player notes before tagging and supports --dry-run", () => {
    const runner = readText("scripts/lib/release-runner.mjs");
    expect(runner).toContain("generate:patch-notes");
    expect(runner).toContain("--dry-run");
    expect(runner).toContain("previewPatchNotes");
    const release = readText("scripts/release.mjs");
    expect(release).toContain("parseReleaseArgs");
  });
});
