import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";

const ROOT = join(import.meta.dirname, "../..");

/**
 * CI/Vercel set ALCHEMY_SKIP_ASSETS=1 and rely on committed optimized outputs.
 * Fail loudly if those outputs are missing so skip stays safe.
 */
describe("committed asset outputs", () => {
  it("keeps generated registries and sample optimized media in the repo", () => {
    const assetsGenerated = join(ROOT, "src/lib/game-data/assets.generated.ts");
    const gearArt = join(ROOT, "src/lib/game-data/gear-art.ts");
    const sampleWebp = join(ROOT, "src/assets/optimized/alchemy-logo.webp");
    const sampleSound = join(ROOT, "public/sounds/denied-03.ogg");

    expect(existsSync(assetsGenerated)).toBe(true);
    expect(existsSync(gearArt)).toBe(true);
    expect(existsSync(sampleWebp)).toBe(true);
    expect(existsSync(sampleSound)).toBe(true);

    const generated = readFileSync(assetsGenerated, "utf8");
    expect(generated).toContain("Generated by scripts/sync-assets.mjs");
    expect(generated).toContain("@/assets/optimized/");
  });
});
