import { readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { CURRENT_GAME_BUILD_VERSION } from "@/lib/validation";

const ROOT = join(import.meta.dirname, "../..");

describe("version sync", () => {
  it("keeps CURRENT_GAME_BUILD_VERSION aligned with package.json", () => {
    const pkg = JSON.parse(readFileSync(join(ROOT, "package.json"), "utf8")) as { version: string };
    expect(CURRENT_GAME_BUILD_VERSION).toBe(pkg.version);
  });

  it("metadata.generated.ts is present and auto-generated", () => {
    const generated = readFileSync(join(ROOT, "src/lib/validation/metadata.generated.ts"), "utf8");
    expect(generated).toContain("AUTO-GENERATED by scripts/sync-version-metadata.mjs");
    expect(generated).toContain(`CURRENT_GAME_BUILD_VERSION = "${CURRENT_GAME_BUILD_VERSION}"`);
  });
});
