import {
  IconBolt,
  IconDroplet,
  IconFlame,
  IconHammer,
  IconHeart,
  IconHourglass,
  IconShield,
  IconSkull,
  IconSnowflake,
  IconSparkles,
  IconSwords,
} from '@tabler/icons-react';

import type { CardKeywordId } from '@/entities/cards/types';

export type TalentAtlasNode = {
  description: string;
  icon: typeof IconShield;
  id: string;
  keywords: [CardKeywordId, CardKeywordId?];
  title: string;
  x: number;
  y: number;
};

export const talentAtlasSize = {
  height: 2200,
  width: 3200,
} as const;

export const talentAtlasNodes: TalentAtlasNode[] = [
  {
    description: 'Your route planning begins here. Max health, recovery, and baseline resilience all feed through this core wheel.',
    icon: IconHeart,
    id: 'vital-source',
    keywords: ['health'],
    title: 'Vital Source',
    x: 1600,
    y: 1100,
  },
  {
    description: 'Convert careful defense into stored momentum. Block and Armor nodes branch outward from this plated hub.',
    icon: IconShield,
    id: 'ward-circuit',
    keywords: ['block', 'armor'],
    title: 'Ward Circuit',
    x: 1190,
    y: 860,
  },
  {
    description: 'Turn raw smithing into offensive pressure. Forge and Physical damage spiral away from this main spoke.',
    icon: IconHammer,
    id: 'anvil-rhythm',
    keywords: ['forge', 'physical'],
    title: 'Anvil Rhythm',
    x: 1200,
    y: 1460,
  },
  {
    description: 'Bottled hazards and caustic reactions collect here before branching into Burn and Poison specializations.',
    icon: IconFlame,
    id: 'volatile-mix',
    keywords: ['burn', 'poison'],
    title: 'Volatile Mix',
    x: 2095,
    y: 820,
  },
  {
    description: 'Cold control, tempo denial, and stun thresholds all converge in this prismatic cluster.',
    icon: IconSnowflake,
    id: 'shiver-web',
    keywords: ['freeze', 'stun'],
    title: 'Shiver Web',
    x: 2200,
    y: 1440,
  },
  {
    description: 'A golden branch for wish effects and economy-focused runs. It sits high because it reshapes entire routes.',
    icon: IconSparkles,
    id: 'gilded-intent',
    keywords: ['gold', 'wish'],
    title: 'Gilded Intent',
    x: 1690,
    y: 570,
  },
  {
    description: 'Mana flow, repeated casts, and clean sequencing all pulse through this lower chamber.',
    icon: IconHourglass,
    id: 'mana-weave',
    keywords: ['mana', 'twice'],
    title: 'Mana Weave',
    x: 1760,
    y: 1675,
  },
  {
    description: 'Earlier blocks stay relevant for longer, letting patient hands absorb more of each exchange.',
    icon: IconShield,
    id: 'braced-core',
    keywords: ['block'],
    title: 'Braced Core',
    x: 920,
    y: 700,
  },
  {
    description: 'Layered plating turns every point of Armor into a steadier long-fight plan.',
    icon: IconShield,
    id: 'fortress-skin',
    keywords: ['armor'],
    title: 'Fortress Skin',
    x: 780,
    y: 980,
  },
  {
    description: 'Defensive timing rewards decks that swap between Block and Armor instead of committing to just one.',
    icon: IconShield,
    id: 'mirror-plating',
    keywords: ['armor', 'block'],
    title: 'Mirror Plating',
    x: 980,
    y: 1210,
  },
  {
    description: 'Physical strikes branch into cleaner lines and more consistent finishing damage.',
    icon: IconSwords,
    id: 'cleaving-arc',
    keywords: ['physical'],
    title: 'Cleaving Arc',
    x: 900,
    y: 1575,
  },
  {
    description: 'Forge becomes a faster engine here, pushing smithing decks toward sharper snowball turns.',
    icon: IconHammer,
    id: 'crucible-pulse',
    keywords: ['forge'],
    title: 'Crucible Pulse',
    x: 1120,
    y: 1800,
  },
  {
    description: 'Bleed and Leech share the same discipline here: convert aggression into staying power.',
    icon: IconDroplet,
    id: 'blood-temper',
    keywords: ['bleed', 'leech'],
    title: 'Blood Temper',
    x: 1440,
    y: 1860,
  },
  {
    description: 'Burn lines grow hotter and faster, encouraging decks that front-load pressure.',
    icon: IconFlame,
    id: 'ember-tax',
    keywords: ['burn'],
    title: 'Ember Tax',
    x: 2340,
    y: 660,
  },
  {
    description: 'Poison routes become steadier and more inevitable as fights go long.',
    icon: IconSkull,
    id: 'venom-loop',
    keywords: ['poison'],
    title: 'Venom Loop',
    x: 2510,
    y: 930,
  },
  {
    description: 'Status overlap lives here, for decks that want Burn and Bleed to stack pressure together.',
    icon: IconDroplet,
    id: 'sanguine-scorch',
    keywords: ['burn', 'bleed'],
    title: 'Sanguine Scorch',
    x: 2270,
    y: 1110,
  },
  {
    description: 'Freeze branches begin with setup and pacing before scaling into full turn denial.',
    icon: IconSnowflake,
    id: 'glacial-prep',
    keywords: ['freeze'],
    title: 'Glacial Prep',
    x: 2440,
    y: 1320,
  },
  {
    description: 'Mana and Stun meet in this node, rewarding decks that convert sequencing into tempo swings.',
    icon: IconBolt,
    id: 'thunder-lattice',
    keywords: ['stun', 'mana'],
    title: 'Thunder Lattice',
    x: 2500,
    y: 1600,
  },
  {
    description: 'Repeated effects, copied plays, and wish branching all link through this late-game route anchor.',
    icon: IconSparkles,
    id: 'double-cast',
    keywords: ['twice', 'wish'],
    title: 'Double Cast',
    x: 1970,
    y: 1860,
  },
];

export const talentAtlasEdges: Array<[string, string]> = [
  ['vital-source', 'ward-circuit'],
  ['vital-source', 'anvil-rhythm'],
  ['vital-source', 'volatile-mix'],
  ['vital-source', 'shiver-web'],
  ['vital-source', 'gilded-intent'],
  ['vital-source', 'mana-weave'],
  ['ward-circuit', 'braced-core'],
  ['ward-circuit', 'fortress-skin'],
  ['ward-circuit', 'mirror-plating'],
  ['anvil-rhythm', 'cleaving-arc'],
  ['anvil-rhythm', 'crucible-pulse'],
  ['anvil-rhythm', 'blood-temper'],
  ['volatile-mix', 'ember-tax'],
  ['volatile-mix', 'venom-loop'],
  ['volatile-mix', 'sanguine-scorch'],
  ['shiver-web', 'glacial-prep'],
  ['shiver-web', 'thunder-lattice'],
  ['mana-weave', 'double-cast'],
  ['gilded-intent', 'double-cast'],
];