import { defaultCompanionBondLevels } from "../companions";
import type { TalentEffectManifest } from "../types";

export const DEFAULT_TALENT_EFFECTS: TalentEffectManifest = {
  flatPhysicalDamage: 0,
  armorToPhysicalDamage: false,
  physicalCritChance: 0,
  firstPhysicalCardFree: false,
  physicalStunChance: 0,
  physicalBleedChance: 0,
  physicalDetonatesBleed: false,
  physicalDoubledBelowHalfHealth: false,
  physicalDoubledVsStunned: false,
  physicalDoubledVsFrozen: false,
  blockToPhysicalDamageMultiplier: 0,
  forgeToPhysicalDamageMultiplier: 0,

  stunThresholdReduction: 0,
  drawOnStun: 0,
  nextCardFreeOnStun: false,
  stunDurationExtension: 0,
  stunDoubleDamage: false,
  flatStunDamage: 0,
  blockOnStun: 0,
  forgeOnStun: 0,
  stunStripArmor: false,
  manaOnStun: 0,

  startBlock: 0,
  blockPreventsBleed: false,
  blockPreventsPoison: false,
  blockPreventsStun: false,
  blockAbsorbPhysicalBonus: 0,
  blockReduceBurnDamage: 0,
  blockDepletedHeal: 0,
  blockToHolyDamage: false,
  blockToStunDamage: false,

  startForge: 0,
  forgeToBurn: false,
  forgeToHoly: false,
  forgeToBlock: false,
  forgeToBleed: false,
  forgeBurnThreshold: 0,
  forgeBurnDamage: 0,
  forgeStripArmorThreshold: 0,
  flatForgeGained: 0,
  forgeDoubledBelowHalfHealth: false,
  forgeBlockThreshold: 0,
  forgeBlockAmount: 0,

  armorMitigatesBurn: false,
  armorBlockThreshold: 0,
  armorBlockAmount: 0,
  armorDoubledBelowHalfHealth: false,
  firstArmorCardDoubled: false,
  startArmor: 0,
  armorMitigatesBleed: false,
  armorBreakBlock: 0,
  armorMitigatesStun: false,
  armorCleanseThreshold: 0,
  flatArmorAmount: 0,

  campfireHealBonus: 0,
  healthThresholdBlock: null,
  maxHealthPerCombat: 0,
  startHealth: 0,
  healMultiplier: 1,
  consumeHealMultiplier: 0,
  healthThresholdArmor: null,
  overhealToBlockRatio: 0,
  healOnStatusCleanse: 0,
  deathsDoorExtension: 0,
  damageReduction: 0,
  burnDamageReduction: 0,
  freezeDamageReduction: 0,
  natureDamageReduction: 0,

  firstBurnCardDoubled: false,
  burnRemovesEnemyArmor: false,
  burnDoubleChance: 0,
  receiveHalfBurnDamage: false,
  flatBurnDamage: 0,
  burnOnWish: 0,
  forgeOnBurnDealt: 0,
  blockToBurnDamage: false,
  consumeBurnDamageBonusPercent: 0,
  firstConsumeCardFree: false,
  consumeDamageBonusPercent: 0,
  burnStunChance: 0,

  shopCardDiscount: 0,
  shopFreeRefresh: false,
  startGold: 0,
  goldPerCombat: 0,
  potionDiscount: 0,
  potionPotency: 1,
  potionMixPotency: 0,
  removeCardDiscount: 0,
  enemyGoldDropBonus: 0,
  eliteGoldDropBonus: 0,
  goldOnWish: 0,
  mixPotionDiscount: 0,
  companionBondLevels: { ...defaultCompanionBondLevels },

  holyLifestealPercent: 0,
  firstHolyCardFree: false,
  holyGoldPercent: 0,
  holyBurnChance: 0,
  receiveHalfHolyDamage: false,
  holyBlockPercent: 0,
  holyWishChance: 0,
  holyBlockPercentFromDamage: 0,
  holyVsBurnMultiplier: 0,
  holyGoldChance: 0,

  goldOnWishAmount: 0,
  wishUndiscoveredCards: false,
  healthOnWish: 0,
  removeHarmfulStatusOnWish: false,
  wishExtraChoiceChance: 0,
  wishDrawsCard: false,
  manaOnWish: 0,
  wishTrinketChoice: false,
  wishBlockBelowHealthPct: 0,
  wishCardsUpgraded: false,
  wishCrystalGold: 0,
  startMana: 0,
  wellspringKeepMana: 0,
  manaBulwarkActive: false,
  manaShellActive: false,
  burnDamagePerManaCrystal: 0,
  freezeDamagePerManaCrystal: 0,
  burnDamageOnManaCrystalLoss: 0,
  companionDamagePerManaCrystal: 0,
  healOnManaGain: 0,

  firstPoisonCardFree: false,
  poisonPhysicalBonus: 0,
  poisonGainChance: 0,
  receiveHalfPoisonDamage: false,
  goldOnFirstPoison: 0,
  poisonHalvesHealing: false,
  poisonStunChance: 0,
  poisonStripArmor: false,
  poisonReducesEnemyDamage: 0,
  poisonLeechChance: 0,

  companionDamage: 0,
  companionGoldFindActive: false,
  companionLeechChance: 0,
  drawOnCompanionCard: 0,
  companionDoubledVsLowHealth: false,
  damageReductionWithCompanion: 0,

  freezeThresholdReduction: 0,
  freezeDoubleDamage: false,
  blockOnFreeze: 0,
  freezeStripArmor: false,
  startFreeze: 0,
  companionVsFrozenBonus: 0,
  freezePreventsPoisonDecay: false,
  freezeBlocksRegen: false,
  freezePreventsEnemyScaling: false,
  receiveHalfFreezeBuildUp: false,
  flatFreezeDamage: 0,

  flatArrowDamage: 0,
  archeryPlayTwiceChance: 0,
  archeryDoubledVsStunned: false,
  archeryDoubledVsFrozen: false,
  archeryDoubledVsHighHealth: false,

  flatNatureDamage: 0,
  naturePoisonChance: 0,
  natureBleedChance: 0,
  natureBonusVsPoisoned: 0,
  receiveHalfNatureDamage: false,

  firstBleedCardFree: false,
  bleedPhysicalBonus: 0,
  bleedLeechChance: 0,
  bleedExecuteThreshold: 0,
  bleedDesperateMultiplier: 1,
  bleedPoisonChance: 0,
  bleedPoisonDamageTakenBonus: 0,
  companionBleedDamageBonus: 0,
  receiveHalfBleedDamage: false,
  bleedHalvesEnemyHealing: false,

  firstLeechCardDoubled: false,
  leechDesperateMultiplier: 0,
  leechMissingHealthStep: 0,
  leechBleedChance: 0,
  leechExecuteMultiplier: 0,
  manaOnLeechChance: 0,
  trinketSiphonChance: 0,
  leechPoisonChance: 0,
  blockEnemyLeech: false,
  natureLeechChance: 0,
};

// Returns a manifest with all zero/false/null values — the safe default when no talents are
// unlocked. Deep-copies the nested companionBondLevels to prevent shared mutation.
