import { defaultCompanionBondLevels } from "../companions";
interface HealthThresholdBonus {
  threshold: number;
  amount: number;
}

export const DEFAULT_TALENT_EFFECTS = {
  // Numeric tuning for current talents; earlier boolean fields remain readable in saved snapshots.
  armorLowHealthBonusPercent: 0,
  partingCutDamagePercent: 0,
  blockHolyDamagePercent: 0,
  blockStunDamagePercent: 0,
  dodgeBlockPercent: 0,
  forgeBurnDamagePercent: 0,
  forgeHolyDamagePercent: 0,
  forgeBlockPercent: 0,
  forgeBleedDamagePercent: 0,
  forgeLowHealthBonusPercent: 0,
  armorNatureDamagePercent: 0,
  armorPhysicalDamagePercent: 0,
  dodgePhysicalDamagePercent: 0,
  physicalLowHealthDamageBonusPercent: 0,
  physicalDoubledBelowQuarterHealth: false,

  cleanseCcOnDodge: false,
  burnOnDodgeBurning: 0,
  consumeDetonatesBurn: false,
  consumeDetonatesBurnChance: 0,
  poisonOnNatureCardVsPoisoned: 0,
  drawNatureCardAtCombatStart: false,
  companionFreezeDamageVsFrozen: 0,
  drawOnArcheryVsStunned: 0,
  archeryCritOnCrowdControl: false,
  // Retained for old battle snapshots; current Hawk Eye uses Crit readiness.
  archeryHolyDamageVsFrozen: 0,
  physicalLeechVsStunned: false,
  forgeOnPhysicalVsFrozen: 0,
  cleanseBelowHealthPercent: 0,
  leechBlockBelowHalfPercent: 0,
  leechHolyDamageVsLowHealth: 0,
  leechCardDamageVsLowHealthPercent: 0,
  armorOnPotionCard: 0,
  armorOnBlockChance: 0,
  armorOnPhysicalDamageChance: 0,
  armorDoubleChance: 0,
  armorCleanseChance: 0,
  drawHolyOnBlockChance: 0,
  holyBlockChance: 0,
  archeryPhysicalWithoutBlock: 0,
  archeryDamageWithoutBlock: 0,
  archerySecondCardDamage: 0,
  blockOnArmorCard: 0,
  bleedUnwoundedBonusPercent: 0,
  cleansePoisonOnBurnCard: 0,
  companionActsOnCard: false,
  forgeOnConsume: 0,
  uncappedDrawOnConsume: 0,
  nextHolyFreeOnCleanse: false,
  poisonCardPhysicalVsPoisoned: 0,
  poisonCardPlayTwiceChance: 0,
  goldOnPoisonedKill: 0,
  // Rotgut now adds this amount to Potion Poison packets, not Consume follow-ups.
  poisonDamageOnConsume: 0,
  bleedPoisonDamageChance: 0,
  bleedPoisonDamageTakenPercent: 0,
  drawOnBleedDamageChance: 0,
  naturePoisonDamageChance: 0,
  holyBurnDamageChance: 0,
  leechPoisonDamageChance: 0,
  archeryBleedDamageChance: 0,
  physicalBleedDamageChance: 0,
  leechBleedDamageChance: 0,

  manaNextTurnOnWish: 0,
  holyReflectionBlockLostPercent: 0,
  blockOnHolyCard: 0,
  forgeOnBurnCard: 0,
  forgeOnBurnCardChance: 0,
  burnCardPlayTwiceChance: 0,
  cardLeechBonusPercent: 0,
  companionNextAttackOnPhysical: 0,
  afflictionLeechBonusPercent: 0,
  manaAfterEmptyTurn: 0,
  blockPerDeclinedWishCard: 0,
  leechGoldChance: 0,
  manaOnLeechToFull: 0,
  nextAttackPhysicalOnLeechToFull: 0,
  drawPhysicalOnBleedTick: false,
  drawOnDodge: 0,
  wishExtraChoices: 0,
  wishCardPlayTwiceChance: 0,
  wishDrawChance: 0,
  declinedWishCardChance: 0,
  companionVictoryGold: 0,
  consecutiveArcheryPhysicalDamage: 0,
  armorStealOnLeechCard: 0,
  cleanseOnCardOverheal: false,
  blockPerGold: 0,
  thornsOnNatureCard: 0,
  physicalAfterNatureBleedDamage: 0,
  natureCardPlayTwiceChance: 0,
  armorOnNatureDamageChance: 0,
  thornsOnNatureDamageChance: 0,
  healOnNatureDamageChance: 0,
  dodgeChanceWhileEnemyBurning: 0,
  holyOnAttackBlocked: 0,
  drawOnThaw: 0,

  dodgeChance: 0,
  healOnDodge: 0,
  forgeOnDodge: 0,
  thornsOnDodge: 0,
  cleanseStacksOnDodge: 0,
  nextAttackPhysicalOnDodge: 0,
  dodgeChanceWithoutBlock: 0,
  stunBuildupReductionPercent: 0,
  dodgeChanceOnHostileDamage: 0,
  armorOnDodge: 0,

  flatPhysicalDamage: 0,
  flatHolyDamage: 0,
  physicalDamageReduction: 0,
  homesteadCriticalDamage: 0,
  homesteadHealing: 0,
  homesteadLeechHealing: 0,
  homesteadPotionBonus: 0,
  homesteadFreeManaChance: 0,
  homesteadForgeBurnPercent: 0,

  armorToPhysicalDamage: false,
  physicalStunChance: 0,
  physicalBleedChance: 0,
  physicalDetonatesBleed: false,
  physicalDoubledBelowHalfHealth: false,
  physicalDoubledVsStunned: false,
  physicalDoubledVsFrozen: false,
  blockToPhysicalDamageMultiplier: 0,
  forgeToPhysicalDamageMultiplier: 0,
  physicalOnDodgeEqualToAttack: false,
  physicalCritOnDodge: false,
  physicalStripArmorWhileBlocked: false,

  stunThresholdReduction: 0,
  drawOnStun: 0,
  nextCardFreeOnStun: false,
  stunDurationExtension: 0,
  stunDoubleDamage: false,
  flatStunDamage: 0,
  stunCardPlayTwiceChance: 0,
  blockOnStun: 0,
  forgeOnStun: 0,
  stunStripArmor: false,
  manaOnStun: 0,

  startBlock: 0,
  blockPreventsBleed: false,
  blockPreventsPoison: false,
  blockPreventsStun: false,
  blockAbsorbPhysicalBonus: 0,
  blockReduceBurnDamage: 0,
  blockDepletedHeal: 0,
  blockToHolyDamage: false,
  blockToStunDamage: false,
  blockOnDodgeEqualToAttack: false,

  startForge: 0,
  forgeBurningBonusPercent: 0,
  forgeDoubleChance: 0,
  forgeOnBlockDepleted: 0,
  forgeToBurn: false,
  forgeToHoly: false,
  forgeToBlock: false,
  forgeToBleed: false,
  forgeBurnThreshold: 0,
  forgeBurnDamage: 0,
  forgeStripArmorThreshold: 0,
  physicalStripArmorByForge: false,
  flatForgeGained: 0,
  forgeDoubledBelowHalfHealth: false,
  forgeBlockThreshold: 0,
  forgeBlockAmount: 0,

  armorMitigatesBurn: false,
  armorBlockThreshold: 0,
  armorBlockAmount: 0,
  armorDoubledBelowHalfHealth: false,
  firstArmorCardDoubled: false,
  startArmor: 0,
  armorMitigatesBleed: false,
  armorBreakBlock: 0,
  armorCleanseThreshold: 0,
  flatArmorAmount: 0,

  campfireHealBonus: 0,
  healthThresholdBlock: null as HealthThresholdBonus | null,
  healthThresholdBlockOnce: null as HealthThresholdBonus | null,
  maxHealthPerCombat: 0,
  healthRestorePerCombat: 0,
  healthLossCleanseChance: 0,
  startHealth: 0,
  healMultiplier: 1,
  consumeHealMultiplier: 0,
  healthThresholdArmor: [] as HealthThresholdBonus[],
  overhealToBlockRatio: 0,
  healOnStatusCleanse: 0,
  deathsDoorExtension: 0,
  damageReduction: 0,
  dodgeChanceBelowHalfHealth: 0,
  burnDamageReduction: 0,
  freezeDamageReduction: 0,
  natureDamageReduction: 0,

  firstBurnCardBonusMultiplier: 0,
  firstBurnCardFree: false,
  burnRemovesEnemyArmor: false,
  burnPreventDecayChance: 0,
  receiveHalfBurnDamage: false,
  flatBurnDamage: 0,
  burnOnWish: 0,
  forgeOnBurnDealt: 0,
  blockToBurnDamage: false,
  consumeBurnDamageBonusPercent: 0,
  firstConsumeCardFree: false,
  consumeDamageBonusPercent: 0,
  burnStunChance: 0,
  healOnConsume: 0,
  goldOnConsume: 0,
  drawOnConsume: 0,
  poisonOnConsume: 0,
  // Retained for old battle snapshots; current Feast uses cardHealMultipliers.
  blockOnConsume: 0,
  cardHealMultipliers: {} as Record<string, number>,

  shopCardDiscount: 0,
  shopFreeRefresh: false,
  shopFreeRefreshChance: 0,
  startGold: 0,
  goldPerCombat: 0,
  goldOnDodge: 0,
  potionDiscount: 0,
  potionPotency: 1,
  mixedPotionPotency: 0,
  potionMixPotency: 0,
  removeCardDiscount: 0,
  enemyGoldDropBonus: 0,
  eliteGoldDropBonus: 0,
  goldOnWish: 0,
  goldOnWishChance: 0,
  goldOnNatureDamageChance: 0,
  goldOnArmorGainChance: 0,
  mixPotionDiscount: 0,
  companionBondLevels: { ...defaultCompanionBondLevels },

  holyLifestealPercent: 0,
  firstHolyCardFree: false,
  holyGoldPercent: 0,
  holyBurnChance: 0,
  receiveHalfHolyDamage: false,
  holyWishChance: 0,
  wishExtraChoiceAfterHolyCard: false,
  holyBlockPercentFromDamage: 0,
  holyVsBurnMultiplier: 0,
  holyGoldChance: 0,

  wishUndiscoveredCards: false,
  healthOnWish: 0,
  removeHarmfulStatusOnWish: false,
  wishExtraChoiceChance: 0,
  wishDrawsCard: false,
  manaOnWish: 0,
  wishTrinketChoice: false,
  wishBlockBelowHealthPct: 0,
  wishBlockAmount: 0,
  wishCardsUpgraded: false,
  wishGemsGold: 0,
  startMana: 0,
  wellspringKeepMana: 0,
  manaBulwarkActive: false,
  manaShellActive: false,
  burnDamagePerManaCrystal: 0,
  burnDamagePerMana: 0,
  freezeDamagePerManaCrystal: 0,
  freezeDamagePerMana: 0,
  burnDamageOnManaCrystalLoss: 0,
  companionDamagePerManaCrystal: 0,
  companionManaChance: 0,
  healOnManaGain: 0,
  healthPerMana: 0,

  runMaxHealthBonus: 0,
  runMaxManaBonus: 0,
  cardHealBonus: {} as Record<string, number>,

  firstPoisonCardFree: false,
  poisonDamageReduction: 0,
  poisonPhysicalBonus: 0,
  poisonDamageBonusVsPoisoned: 0,
  poisonGainChance: 0,
  receiveHalfPoisonDamage: false,
  goldOnFirstPoison: 0,
  poisonHalvesHealing: false,
  poisonStunChance: 0,
  poisonStripArmor: false,
  poisonStripArmorByDamage: false,
  poisonReducesEnemyDamage: 0,
  poisonLeechChance: 0,
  poisonBleedDamageChance: 0,
  poisonPreventsEnemyDodge: false,

  companionDamage: 0,
  companionGoldFindActive: false,
  companionLeechChance: 0,
  drawOnCompanionCard: 0,
  companionDoubledVsLowHealth: false,
  damageReductionWithCompanion: 0,
  blockOnCompanionDamage: 0,
  companionAttackOnBlockDepletedBelowHalf: false,
  companionStunChance: 0,
  firstCompanionCardFree: false,
  companionAttacksOnDodge: false,

  freezeThresholdReduction: 0,
  freezeDamageBonusVsFrozen: 0,
  freezeCardPlayTwiceChance: 0,
  freezeDoubleDamage: false,
  blockOnFreeze: 0,
  freezeStripArmor: false,
  startFreeze: 0,
  companionVsFrozenBonus: 0,
  freezePreventsPoisonDecay: false,
  freezeBlocksRegen: false,
  freezePreventsEnemyScaling: false,
  freezeStripBlock: false,
  freezePreventsEnemyDodge: false,
  receiveHalfFreezeDamage: false,
  flatFreezeDamage: 0,

  flatArrowDamage: 0,
  archeryPlayTwiceChance: 0,
  archeryDoubledVsStunned: false,
  archeryDoubledVsFrozen: false,
  archeryDoubledVsHighHealth: false,
  archeryArmorPiercing: 0,
  firstArcheryCardFree: false,
  archeryDoubledVsLowHealth: false,
  archeryBleedChance: 0,
  goldOnArcheryKill: 0,
  nextArcheryCardFreeOnDodge: false,

  flatNatureDamage: 0,
  naturePoisonChance: 0,
  natureBleedChance: 0,
  natureBonusVsPoisoned: 0,
  receiveHalfNatureDamage: false,
  natureStunChance: 0,
  armorToNatureDamage: false,
  blockOnNatureCard: 0,
  healOnNatureCard: 0,
  nextNatureCardFreeOnDodge: false,

  firstBleedCardFree: false,
  bleedPhysicalBonus: 0,
  bleedLeechChance: 0,
  bleedExecuteThreshold: 0,
  bleedExecuteMultiplier: 1,
  bleedDesperateMultiplier: 1,
  bleedHalveArmorChance: 0,
  bleedPoisonChance: 0,
  bleedPoisonDamageTakenBonus: 0,
  blockHalvesBleedDamage: false,
  blockHalvesPoisonDamage: false,
  dodgeBlockAmount: 0,
  companionBleedDamageBonus: 0,
  receiveHalfBleedDamage: false,
  bleedHalvesEnemyHealing: false,
  partingCutOnDodge: false,

  firstLeechCardDoubled: false,
  leechDesperateMultiplier: 0,
  leechMissingHealthStep: 0,
  leechBleedChance: 0,
  leechExecuteMultiplier: 0,
  manaOnLeechChance: 0,
  trinketSiphonChance: 0,
  leechPoisonChance: 0,
  blockEnemyLeech: false,
  natureLeechChance: 0,
};

export type TalentEffectManifest = typeof DEFAULT_TALENT_EFFECTS;

export function createEmptyTalentEffectManifest(): TalentEffectManifest {
  return {
    ...DEFAULT_TALENT_EFFECTS,
    companionBondLevels: { ...DEFAULT_TALENT_EFFECTS.companionBondLevels },
    healthThresholdArmor: [...DEFAULT_TALENT_EFFECTS.healthThresholdArmor],
    cardHealBonus: { ...DEFAULT_TALENT_EFFECTS.cardHealBonus },
    cardHealMultipliers: { ...DEFAULT_TALENT_EFFECTS.cardHealMultipliers },
  };
}
