import { MANABURN_DAMAGE_PERCENT } from "@/lib/game-constants";
import type { TalentDefinition } from "./types";
import { addEffect, setEffect, type TalentEffectOperation } from "./types";
import type { KeywordId } from "../types";

function talent(
  id: string,
  keywordId: KeywordId,
  name: string,
  description: string,
  icon: string,
  ...ops: [TalentEffectOperation, ...TalentEffectOperation[]]
): TalentDefinition {
  return { id, keywordId, name, description, icon, effects: [...ops] };
}

export const talentPool: TalentDefinition[] = [
  talent("dodge-lightfoot", "dodge", "Lightfoot", "+5% Dodge chance", "Feather", addEffect("dodgeChance", 5)),
  talent(
    "dodge-catch-breath",
    "dodge",
    "Catch Breath",
    "Restore 1 Health when you Dodge",
    "HeartPulse",
    addEffect("healOnDodge", 1),
  ),
  talent("dodge-feint", "dodge", "Feint", "Gain 1 Forge when you Dodge", "Anvil", addEffect("forgeOnDodge", 1)),
  talent(
    "dodge-thornstep",
    "dodge",
    "Thornstep",
    "Gain 1 Thorns when you Dodge",
    "Leaf",
    addEffect("thornsOnDodge", 1),
  ),
  talent(
    "dodge-clean-getaway",
    "dodge",
    "Clean Getaway",
    "When you Dodge, remove 1 stack each of Burn, Poison, and Bleed from yourself",
    "Eraser",
    addEffect("cleanseStacksOnDodge", 1),
  ),
  talent(
    "dodge-open-flank",
    "dodge",
    "Open Flank",
    "When you Dodge, your next attack deals 4 additional Physical damage",
    "Swords",
    addEffect("nextAttackPhysicalOnDodge", 4),
  ),
  talent(
    "dodge-unburdened",
    "dodge",
    "Unburdened",
    "When you Dodge, cleanse your Stun and Freeze buildup",
    "ShieldOff",
    setEffect("cleanseCcOnDodge", true),
  ),
  talent(
    "dodge-rolling-recovery",
    "dodge",
    "Tailwind",
    "When you Dodge, draw a card",
    "ShieldHalf",
    setEffect("drawOnDodge", 1),
  ),
  talent(
    "dodge-finding-rhythm",
    "dodge",
    "Finding Rhythm",
    "Taking damage increases your Dodge chance by 5%, resetting when you Dodge",
    "Activity",
    addEffect("dodgeChanceOnHostileDamage", 5),
  ),
  talent(
    "dodge-perfect-timing",
    "dodge",
    "Perfect Timing",
    "Gain 1 Armor when you Dodge",
    "Shield",
    addEffect("armorOnDodge", 1),
  ),
  talent(
    "archery-damage",
    "archery",
    "Arrow Dance",
    "When you Dodge, your next Archery card is free",
    "Move",
    setEffect("nextArcheryCardFreeOnDodge", true),
  ),
  talent(
    "archery-hail",
    "archery",
    "Follow-through",
    "Archery cards deal 2 additional Physical damage if your previous card this turn was Archery",
    "CloudRain",
    setEffect("consecutiveArcheryPhysicalDamage", 2),
  ),
  talent(
    "archery-eagle-eye",
    "archery",
    "Eagle Eye",
    "When you play an Archery card against a Stunned enemy, draw a card",
    "Eye",
    setEffect("drawOnArcheryVsStunned", 1),
  ),
  talent(
    "archery-hawk-eye",
    "archery",
    "Hawk Eye",
    "Archery hits against Frozen enemies deal 2 additional Holy damage",
    "ScanEye",
    setEffect("archeryHolyDamageVsFrozen", 2),
  ),
  talent(
    "archery-longshot",
    "archery",
    "Longshot",
    "Archery cards deal double damage against enemies at full Health",
    "ArrowRight",
    setEffect("archeryDoubledVsHighHealth", true),
  ),
  talent(
    "archery-piercing-shot",
    "archery",
    "Piercing Shot",
    "Archery cards ignore 1 Armor",
    "Aperture",
    addEffect("archeryArmorPiercing", 1),
  ),
  talent(
    "archery-quickdraw",
    "archery",
    "Quickdraw",
    "Archery cards deal 1 additional Physical damage while you have no Block",
    "Zap",
    setEffect("archeryPhysicalWithoutBlock", 1),
  ),
  talent(
    "archery-kill-shot",
    "archery",
    "Kill Shot",
    "Archery cards deal double damage against enemies below 20% Health",
    "Crosshair",
    setEffect("archeryDoubledVsLowHealth", true),
  ),
  talent(
    "archery-broadhead",
    "archery",
    "Broadhead",
    "Archery hits have a 10% chance to deal 25% of their damage as Bleed damage",
    "Diamond",
    setEffect("archeryBleedDamageChance", 10),
  ),
  talent(
    "archery-trophy-shot",
    "archery",
    "Trophy Shot",
    "Gain 2 Gold when an Archery card defeats an enemy",
    "Award",
    setEffect("goldOnArcheryKill", 2),
  ),
  talent(
    "armor-desperate-double",
    "armor",
    "Last Stand",
    "Armor gained is doubled when Health is below 50%",
    "HeartCrack",
    setEffect("armorDoubledBelowHalfHealth", true),
  ),
  talent(
    "armor-block-burst",
    "armor",
    "Armored Surge",
    "When you reach 4 Armor, gain 8 Block",
    "Shield",
    setEffect("armorBlockThreshold", 4),
    setEffect("armorBlockAmount", 8),
  ),
  talent(
    "armor-burn-mitigate",
    "armor",
    "Fireward",
    "Armor mitigates Burn damage taken",
    "Flame",
    setEffect("armorMitigatesBurn", true),
  ),
  talent(
    "armor-break-block",
    "armor",
    "Reactive Guard",
    "When Armor breaks, gain 5 Block",
    "ShieldPlus",
    setEffect("armorBreakBlock", 5),
  ),
  talent(
    "armor-start-combat",
    "armor",
    "Bulwark",
    "Start each combat with 2 Armor",
    "Square",
    setEffect("startArmor", 2),
  ),
  talent(
    "armor-mitigate-bleed",
    "armor",
    "Thick Hide",
    "Armor mitigates Bleed damage taken",
    "Hexagon",
    setEffect("armorMitigatesBleed", true),
  ),
  talent(
    "armor-first-double",
    "armor",
    "Iron Guard",
    "When you play an Armor card, gain 2 Block",
    "Lock",
    setEffect("blockOnArmorCard", 2),
  ),
  talent(
    "armor-mitigate-stun",
    "armor",
    "Steadfast",
    "When your Health falls below 50%, gain 5 Armor",
    "Anchor",
    setEffect("healthThresholdArmor", [{ threshold: 50, amount: 5 }]),
  ),
  talent(
    "armor-cleanse-threshold",
    "armor",
    "Purification",
    "When you reach 6 Armor, cleanse all harmful status effects",
    "Sparkles",
    setEffect("armorCleanseThreshold", 6),
  ),
  talent(
    "armor-flat-bonus",
    "armor",
    "Reinforced",
    "Increase Armor gained by 1",
    "Plus",
    addEffect("flatArmorAmount", 1),
  ),
  talent(
    "bleed-first-free",
    "bleed",
    "First Blood",
    "Bleed hits deal 50% more damage against enemies that were not already Bleeding",
    "Swords",
    setEffect("bleedUnwoundedBonusPercent", 50),
  ),
  talent(
    "bleed-physical-bonus",
    "bleed",
    "Parting Cut",
    "After you Dodge, your next Physical card deals Bleed damage equal to its damage",
    "Slash",
    setEffect("partingCutOnDodge", true),
  ),
  talent(
    "bleed-leech-chance",
    "bleed",
    "Sanguine",
    "Bleed has a 15% chance to Leech",
    "HeartPulse",
    setEffect("bleedLeechChance", 15),
  ),
  talent(
    "bleed-enemy-weak",
    "bleed",
    "Mortal Wound",
    "Bleeding enemies restore half as much Health",
    "Bone",
    setEffect("bleedHalvesEnemyHealing", true),
  ),
  talent(
    "bleed-wound-care",
    "bleed",
    "Wound Care",
    "Take half Bleed damage",
    "Bandage",
    setEffect("receiveHalfBleedDamage", true),
  ),
  talent(
    "bleed-execute",
    "bleed",
    "Flay",
    "Bleed hits have a 20% chance to halve enemy Armor",
    "Scissors",
    setEffect("bleedHalveArmorChance", 20),
  ),
  talent(
    "bleed-desperate",
    "bleed",
    "Bleeding Out",
    "You deal 50% more Bleed damage while below 50% Health",
    "HeartCrack",
    setEffect("bleedDesperateMultiplier", 1.5),
  ),
  talent(
    "bleed-poison-chance",
    "bleed",
    "Tainted Wound",
    "Bleed hits have a 10% chance to deal 50% of their damage as Poison damage",
    "FlaskConical",
    setEffect("bleedPoisonDamageChance", 10),
  ),
  talent(
    "bleed-septic-shock",
    "bleed",
    "Septic Shock",
    "Bleed increases Poison damage taken by 1",
    "TriangleAlert",
    setEffect("bleedPoisonDamageTakenBonus", 1),
  ),
  talent(
    "bleed-rip-and-tear",
    "bleed",
    "Bloodrush",
    "When an enemy takes damage from a Bleed tick, draw a Physical card",
    "Scissors",
    setEffect("drawPhysicalOnBleedTick", true),
  ),
  talent(
    "block-depleted-heal",
    "block",
    "Second Wind",
    "When Block is depleted, restore 2 Health",
    "Wind",
    setEffect("blockDepletedHeal", 2),
  ),
  talent(
    "block-absorb-physical",
    "block",
    "Reinforce",
    "Block absorbs 20% more Physical damage",
    "ShieldCheck",
    setEffect("blockAbsorbPhysicalBonus", 20),
  ),
  talent(
    "block-to-holy",
    "block",
    "Sacred Shield",
    "Holy damage is increased by 30% of your Block",
    "Sun",
    setEffect("blockToHolyDamage", true),
  ),
  talent(
    "block-to-stun",
    "block",
    "Impact Guard",
    "Stun damage is increased by 30% of your Block",
    "Zap",
    setEffect("blockToStunDamage", true),
  ),
  talent(
    "block-prevent-stun",
    "block",
    "Grounding",
    "While you have Block, prevent Stun buildup",
    "Anchor",
    setEffect("blockPreventsStun", true),
  ),
  talent(
    "block-to-physical",
    "block",
    "Weighted Guard",
    "Physical damage is increased by 30% of your Block",
    "Weight",
    addEffect("blockToPhysicalDamageMultiplier", 0.3),
  ),
  talent(
    "block-reduce-burn",
    "block",
    "Sun-Struck Shield",
    "When an enemy attack removes your Block, reflect 30% of the Block lost as Holy damage",
    "Flame",
    setEffect("holyReflectionBlockLostPercent", 30),
  ),
  talent(
    "block-start",
    "block",
    "Footwork",
    "When you Dodge, gain Block equal to the dodged attack",
    "ChevronsUp",
    setEffect("blockOnDodgeEqualToAttack", true),
  ),
  talent(
    "block-prevent-bleed",
    "block",
    "Coagulate",
    "While you have Block, prevent Bleed buildup",
    "Droplets",
    setEffect("blockPreventsBleed", true),
  ),
  talent(
    "block-prevent-poison",
    "block",
    "Detoxify",
    "While you have Block, prevent Poison buildup",
    "FlaskConical",
    setEffect("blockPreventsPoison", true),
  ),
  talent(
    "burn-dmg-1",
    "burn",
    "Flashpoint",
    "Increase Burn damage by 1",
    "Thermometer",
    addEffect("flatBurnDamage", 1),
  ),
  talent(
    "burn-dmg-2",
    "burn",
    "Thermal Vent",
    "When you play a Burn card, gain 1 Forge",
    "WavesArrowUp",
    addEffect("forgeOnBurnCard", 1),
  ),
  talent(
    "burn-dmg-5",
    "burn",
    "Smoke Screen",
    "When you Dodge a Burning enemy, deal 2 Burn damage",
    "Shield",
    setEffect("burnOnDodgeBurning", 2),
  ),
  talent(
    "burn-dmg-4",
    "burn",
    "Combustible",
    "When you Consume a card, detonate the enemy’s Burn",
    "Bomb",
    setEffect("consumeDetonatesBurn", true),
  ),
  talent(
    "burn-first-double",
    "burn",
    "Wildfire",
    "When you play a Burn card, remove 1 Poison from yourself; if you do, deal 1 Poison damage",
    "TrendingUp",
    setEffect("cleansePoisonOnBurnCard", 1),
  ),
  talent(
    "burn-remove-armor",
    "burn",
    "Melting Point",
    "Burn hits remove enemy Armor equal to the damage dealt",
    "Droplets",
    setEffect("burnRemovesEnemyArmor", true),
  ),
  talent(
    "burn-dmg-3",
    "burn",
    "Heat Exhaustion",
    "Burn hits have a 10% chance to deal Stun damage equal to their damage",
    "TrendingDown",
    setEffect("burnStunChance", 10),
  ),
  talent(
    "burn-dmg-6",
    "burn",
    "Burning Wish",
    "When you Wish, deal 2 Burn damage to the enemy",
    "Sparkles",
    setEffect("burnOnWish", 2),
  ),
  talent(
    "burn-double-chance",
    "burn",
    "Smoldering",
    "Burn stacks have a 10% chance to not decay",
    "Wind",
    setEffect("burnPreventDecayChance", 10),
  ),
  talent(
    "burn-half-damage",
    "burn",
    "Fire Resistance",
    "Take half Burn damage",
    "ShieldCheck",
    setEffect("receiveHalfBurnDamage", true),
  ),
  talent(
    "companion-damage",
    "companion",
    "Feral Strength",
    "Increase Companion damage by 1",
    "Bone",
    addEffect("companionDamage", 1),
  ),
  talent(
    "companion-gold-find",
    "companion",
    "Fetch",
    "Win a combat with a Companion to gain 3 additional Gold",
    "Trash",
    setEffect("companionVictoryGold", 3),
  ),
  talent(
    "companion-leech",
    "companion",
    "Leech Companion",
    "Companions have a 10% chance to Leech",
    "HeartPulse",
    setEffect("companionLeechChance", 10),
  ),
  talent(
    "companion-hunters-bond",
    "companion",
    "Hunter's Bond",
    "When you play a Companion card, draw a card",
    "Link2",
    setEffect("drawOnCompanionCard", 1),
  ),
  talent(
    "companion-predator-instinct",
    "companion",
    "Predator's Instinct",
    "Companions deal double damage against enemies below 30% Health",
    "Eye",
    setEffect("companionDoubledVsLowHealth", true),
  ),
  talent(
    "companion-tame",
    "companion",
    "Coordinated Strike",
    "When you play a Physical card, your Companion’s next attack deals 1 additional damage",
    "Hand",
    setEffect("companionNextAttackOnPhysical", 1),
  ),
  talent(
    "companion-loyal",
    "companion",
    "Pack Weave",
    "When you Dodge, your Companion attacks",
    "PawPrint",
    setEffect("companionAttacksOnDodge", true),
  ),
  talent(
    "companion-watchdog",
    "companion",
    "Watchdog",
    "When your Companion deals damage, gain 2 Block",
    "ShieldAlert",
    setEffect("blockOnCompanionDamage", 2),
  ),
  talent(
    "companion-takedown",
    "companion",
    "Takedown",
    "Companion attacks have a 10% chance to deal Stun damage equal to their damage",
    "Ban",
    setEffect("companionStunChance", 10),
  ),
  talent(
    "companion-whistle",
    "companion",
    "Whistle",
    "After you play a Companion card, your active Companion acts immediately",
    "Bell",
    setEffect("companionActsOnCard", true),
  ),
  talent(
    "consume-gourmand",
    "consume",
    "Gourmand",
    "Consume cards restore 20% more Health",
    "Apple",
    setEffect("consumeHealMultiplier", 0.2),
  ),
  talent(
    "consume-last-supper",
    "consume",
    "Last Supper",
    "When you Consume a card, gain 1 Forge",
    "Gift",
    setEffect("forgeOnConsume", 1),
  ),
  talent(
    "consume-volatility",
    "consume",
    "Volatility",
    "Consume cards deal 20% more damage",
    "Flame",
    setEffect("consumeDamageBonusPercent", 20),
  ),
  talent(
    "consume-distillation",
    "consume",
    "Distillation",
    "Consumed Potions are 20% more potent",
    "FlaskConical",
    addEffect("potionPotency", 0.2),
  ),
  talent(
    "consume-brewmaster",
    "consume",
    "Brewmaster",
    "Consumed Mixed Potions have +1 potency",
    "Wine",
    addEffect("potionMixPotency", 1),
  ),
  talent(
    "consume-aftertaste",
    "consume",
    "Aftertaste",
    "When you Consume a card, restore 1 Health",
    "Cookie",
    setEffect("healOnConsume", 1),
  ),
  talent(
    "consume-leftovers",
    "consume",
    "Leftovers",
    "When you Consume a card, gain 1 Gold",
    "Package",
    setEffect("goldOnConsume", 1),
  ),
  talent(
    "consume-second-helping",
    "consume",
    "Second Helping",
    "When you Consume a card, draw a card",
    "CopyPlus",
    setEffect("uncappedDrawOnConsume", 1),
  ),
  talent(
    "consume-rotgut",
    "consume",
    "Rotgut",
    "When you Consume a card, deal 1 Poison damage",
    "FlaskRound",
    setEffect("poisonDamageOnConsume", 1),
  ),
  talent(
    "consume-feast",
    "consume",
    "Feast",
    "When you Consume a card, gain 2 Block",
    "CookingPot",
    setEffect("blockOnConsume", 2),
  ),
  talent(
    "forge-to-burn",
    "forge",
    "Ignite",
    "Forge also increases Burn damage",
    "Flame",
    setEffect("forgeToBurn", true),
  ),
  talent(
    "forge-to-holy",
    "forge",
    "Sanctify",
    "Forge also increases Holy damage",
    "Sun",
    setEffect("forgeToHoly", true),
  ),
  talent(
    "forge-to-block",
    "forge",
    "Tempered Guard",
    "Forge also increases Block amount",
    "Shield",
    setEffect("forgeToBlock", true),
  ),
  talent(
    "forge-burn-burst",
    "forge",
    "Overheat",
    "When you reach 4 Forge, deal 8 Burn damage",
    "Thermometer",
    setEffect("forgeBurnThreshold", 4),
    setEffect("forgeBurnDamage", 8),
  ),
  talent(
    "forge-strength-1",
    "forge",
    "Forge Mastery",
    "Start each combat with 1 Forge",
    "FlameKindling",
    setEffect("startForge", 1),
  ),
  talent(
    "forge-strength-2",
    "forge",
    "Rust",
    "Forge also increases Bleed damage",
    "Eraser",
    setEffect("forgeToBleed", true),
  ),
  talent(
    "forge-strength-3",
    "forge",
    "Sunder",
    "When you reach 6 Forge, remove all enemy Armor",
    "ShieldOff",
    setEffect("forgeStripArmorThreshold", 6),
  ),
  talent(
    "forge-strength-4",
    "forge",
    "Intensify",
    "Increase Forge gained by 1",
    "ChevronsUp",
    addEffect("flatForgeGained", 1),
  ),
  talent(
    "forge-strength-5",
    "forge",
    "Desperate Forge",
    "Forge gained is doubled when Health is below 50%",
    "HeartCrack",
    setEffect("forgeDoubledBelowHalfHealth", true),
  ),
  talent(
    "forge-strength-6",
    "forge",
    "Forged Bulwark",
    "When you reach 6 Forge, gain 10 Block",
    "Castle",
    setEffect("forgeBlockThreshold", 6),
    setEffect("forgeBlockAmount", 10),
  ),
  talent(
    "freeze-threshold",
    "freeze",
    "Bitter Cold",
    "Freeze threshold reduced by 10%",
    "ThermometerSnowflake",
    setEffect("freezeThresholdReduction", 0.1),
  ),
  talent(
    "freeze-double-damage",
    "freeze",
    "Shatter",
    "Frozen enemies take double damage",
    "Split",
    setEffect("freezeDoubleDamage", true),
  ),
  talent(
    "freeze-start-amount",
    "freeze",
    "Winter's Grasp",
    "Start each combat by dealing 4 Freeze damage",
    "MountainSnow",
    setEffect("startFreeze", 4),
  ),
  talent(
    "freeze-block-grant",
    "freeze",
    "Icebound",
    "When you Freeze an enemy, remove all its Block; Frozen enemies cannot Dodge",
    "Snowflake",
    setEffect("freezeStripBlock", true),
    setEffect("freezePreventsEnemyDodge", true),
  ),
  talent(
    "freeze-companion-bonus",
    "freeze",
    "Snow Pack",
    "Companion hits against Frozen enemies deal 1 additional Freeze damage",
    "CloudSnow",
    setEffect("companionFreezeDamageVsFrozen", 1),
  ),
  talent(
    "freeze-strip-armor",
    "freeze",
    "Brittle Armor",
    "When you Freeze an enemy, remove all its Armor",
    "ShieldOff",
    setEffect("freezeStripArmor", true),
  ),
  talent(
    "freeze-half-damage",
    "freeze",
    "Cold Resistance",
    "Take half Freeze damage",
    "Thermometer",
    setEffect("receiveHalfFreezeDamage", true),
  ),
  talent(
    "freeze-poison-preserve",
    "freeze",
    "Cryo-preservation",
    "Poison stacks on Frozen enemies cannot decay",
    "FlaskConical",
    setEffect("freezePreventsPoisonDecay", true),
  ),
  talent(
    "freeze-prevent-scaling",
    "freeze",
    "Thaw Dividend",
    "When an enemy recovers from Freeze, draw a card",
    "Hexagon",
    setEffect("drawOnThaw", 1),
  ),
  talent(
    "freeze-block-healing",
    "freeze",
    "Glacial Barrier",
    "When you Freeze an enemy, gain 3 Block",
    "Lock",
    setEffect("blockOnFreeze", 3),
  ),
  talent(
    "gold-shop-discount",
    "gold",
    "Haggle",
    "Shop purchases cost 5 less Gold",
    "Tag",
    setEffect("shopCardDiscount", 5),
  ),
  talent(
    "gold-shop-refresh",
    "gold",
    "Restock",
    "Shop refreshes cost 0 Gold",
    "RefreshCw",
    setEffect("shopFreeRefresh", true),
  ),
  talent("gold-start", "gold", "Seed Money", "Start each run with 20 Gold", "Sprout", setEffect("startGold", 20)),
  talent(
    "gold-per-combat",
    "gold",
    "Lucky Foot",
    "Gain 1 Gold when you Dodge",
    "CircleDollarSign",
    setEffect("goldOnDodge", 1),
  ),
  talent(
    "gold-potion-discount",
    "gold",
    "Apothecary’s Guard",
    "When you play a Potion, gain 1 Armor",
    "Beaker",
    setEffect("armorOnPotionCard", 1),
  ),
  talent(
    "gold-remove-discount",
    "gold",
    "Buyout",
    "Card removal costs 10 less Gold",
    "ShoppingCart",
    setEffect("removeCardDiscount", 10),
  ),
  talent(
    "gold-enemy-drop",
    "gold",
    "Plunder",
    "Enemies drop 10% more Gold",
    "HandCoins",
    setEffect("enemyGoldDropBonus", 0.1),
  ),
  talent("gold-on-wish", "gold", "Golden Wish", "Gain 3 Gold when you Wish", "Sparkles", addEffect("goldOnWish", 3)),
  talent(
    "gold-mix-discount",
    "gold",
    "Alchemy Discount",
    "Mixing Potions costs 10 less Gold",
    "FlaskConical",
    setEffect("mixPotionDiscount", 10),
  ),
  talent(
    "gold-elite-drop",
    "gold",
    "Coinmail",
    "Gold gained during combat also grants half as much Block",
    "Trophy",
    setEffect("blockPerGold", 0.5),
  ),
  talent(
    "health-threshold-armor",
    "health",
    "Last Resort",
    "When your Health falls below 25%, cleanse all harmful status effects",
    "HeartCrack",
    setEffect("cleanseBelowHealthPercent", 25),
  ),
  talent(
    "health-threshold-block",
    "health",
    "Desperate Guard",
    "When your Health falls below 50%, gain 6 Block",
    "Shield",
    setEffect("healthThresholdBlock", { threshold: 50, amount: 6 }),
  ),
  talent(
    "health-max-4",
    "health",
    "Will to Live",
    "Death's Door lasts 1 turn longer",
    "Activity",
    setEffect("deathsDoorExtension", 1),
  ),
  talent(
    "health-start",
    "health",
    "Combat Surge",
    "Restore 4 Health at the start of combat",
    "ChevronsUp",
    setEffect("startHealth", 4),
  ),
  talent(
    "health-max-per-combat",
    "health",
    "Vitality",
    "Gain 1 maximum Health after every combat",
    "TrendingUp",
    setEffect("maxHealthPerCombat", 1),
  ),
  talent(
    "health-heal-boost",
    "health",
    "Mending",
    "Health restored is increased by 10%",
    "HeartPulse",
    setEffect("healMultiplier", 1.1),
  ),
  talent(
    "health-max-1",
    "health",
    "Overflow",
    "When you restore Health beyond your maximum, gain 50% of the excess as Block",
    "Container",
    setEffect("overhealToBlockRatio", 0.5),
  ),
  talent(
    "health-max-2",
    "health",
    "Cleansing Status",
    "Cleansing a harmful status effect restores 6 Health",
    "Sparkles",
    setEffect("healOnStatusCleanse", 6),
  ),
  talent(
    "health-max-3",
    "health",
    "Last Gasp",
    "While below 50% Health, gain 20% Dodge chance",
    "ShieldHalf",
    setEffect("dodgeChanceBelowHalfHealth", 20),
  ),
  talent(
    "health-campfire",
    "health",
    "Clean Slate",
    "When a card restores Health beyond your maximum, cleanse a harmful status effect",
    "Flame",
    setEffect("cleanseOnCardOverheal", true),
  ),
  talent(
    "holy-block-scaling",
    "holy",
    "Faith Barrier",
    "When you play a Holy card, gain 2 Block",
    "Shield",
    setEffect("blockOnHolyCard", 2),
  ),
  talent(
    "holy-half-damage",
    "holy",
    "Celestial Ward",
    "Take half Holy damage",
    "ShieldCheck",
    setEffect("receiveHalfHolyDamage", true),
  ),
  talent(
    "holy-vs-burn",
    "holy",
    "Purge",
    "Holy damage is increased by 20% against Burning enemies",
    "Eraser",
    setEffect("holyVsBurnMultiplier", 20),
  ),
  talent(
    "holy-first-free",
    "holy",
    "Divine Favor",
    "When you cleanse a harmful status effect, your next Holy card is free",
    "Gift",
    setEffect("nextHolyFreeOnCleanse", true),
  ),
  talent(
    "holy-gold-scaling",
    "holy",
    "Prosperity",
    "Holy damage is increased by 3% of your Gold",
    "TrendingUp",
    setEffect("holyGoldPercent", 3),
  ),
  talent(
    "holy-burn-chance",
    "holy",
    "Scorching Light",
    "Holy hits have a 10% chance to deal 50% of their damage as Burn damage",
    "Flame",
    setEffect("holyBurnDamageChance", 10),
  ),
  talent(
    "holy-tithe",
    "holy",
    "Tithe",
    "10% chance to gain Gold equal to Holy damage",
    "Cross",
    setEffect("holyGoldChance", 10),
  ),
  talent(
    "holy-block-grant",
    "holy",
    "Radiant Guard",
    "Holy damage grants Block for 15% of the amount dealt",
    "ShieldPlus",
    setEffect("holyBlockPercentFromDamage", 15),
  ),
  talent(
    "holy-lifesteal",
    "holy",
    "Blessed Leech",
    "Holy damage restores 10% of the amount dealt as Health",
    "HeartPulse",
    setEffect("holyLifestealPercent", 10),
  ),
  talent(
    "holy-wish-chance",
    "holy",
    "Divine Intervention",
    "After you play a Holy card, your next Wish offers 1 additional card choice",
    "Sparkles",
    setEffect("wishExtraChoiceAfterHolyCard", true),
  ),
  talent(
    "leech-first-double",
    "leech",
    "Deep Siphon",
    "Leech from your cards restores 25% more Health",
    "Sword",
    setEffect("cardLeechBonusPercent", 25),
  ),
  talent(
    "leech-blood-debt",
    "leech",
    "Blood Debt",
    "Leech restores 1 more Health per 8 missing Health",
    "CircleDollarSign",
    setEffect("leechMissingHealthStep", 8),
  ),
  talent(
    "leech-nature-chance",
    "leech",
    "Affliction Siphon",
    "Leech restores 50% more Health against Poisoned or Bleeding enemies",
    "Utensils",
    setEffect("afflictionLeechBonusPercent", 50),
  ),
  talent(
    "leech-desperate",
    "leech",
    "Desperate Siphon",
    "While below 50% Health, Leech also grants Block equal to half the Health restored",
    "HeartCrack",
    setEffect("leechBlockBelowHalfPercent", 50),
  ),
  talent(
    "leech-cull-weak",
    "leech",
    "Cull the Weak",
    "Leech cards deal 25% more damage against enemies below 50% Health",
    "Skull",
    setEffect("leechCardDamageVsLowHealthPercent", 25),
  ),
  talent(
    "leech-block-enemy",
    "leech",
    "Sanguine Overflow",
    "When Leech fills your Health, your next attack deals 3 additional Physical damage",
    "Hash",
    setEffect("nextAttackPhysicalOnLeechToFull", 3),
  ),
  talent(
    "leech-bleed-chance",
    "leech",
    "Bloodletting",
    "Leech hits have a 10% chance to deal 25% of their damage as Bleed damage",
    "Droplets",
    setEffect("leechBleedDamageChance", 10),
  ),
  talent(
    "leech-mana-siphon",
    "leech",
    "Mana Siphon",
    "Leech has a 10% chance to gain 1 Mana",
    "Gem",
    setEffect("manaOnLeechChance", 10),
  ),
  talent(
    "leech-trinket-siphon",
    "leech",
    "Armor Siphon",
    "Your Leech cards steal 1 Armor before their effects resolve",
    "Wrench",
    setEffect("armorStealOnLeechCard", 1),
  ),
  talent(
    "leech-poison",
    "leech",
    "Virulent Leech",
    "Leech hits have a 10% chance to deal 50% of their damage as Poison damage",
    "FlaskConical",
    setEffect("leechPoisonDamageChance", 10),
  ),
  talent(
    "mana-wellspring",
    "mana",
    "Wellspring",
    "When you end your turn with unspent Mana, keep 1 for next turn",
    "Droplets",
    setEffect("wellspringKeepMana", 1),
  ),
  talent(
    "mana-bulwark",
    "mana",
    "Mana Bulwark",
    "Start each combat with Block equal to your Mana Crystals",
    "ShieldPlus",
    setEffect("manaBulwarkActive", true),
  ),
  talent("mana-leylines", "mana", "Leyline Attunement", "Gain 1 Mana Crystal", "Atom", setEffect("startMana", 1)),
  talent(
    "mana-arcane-wish",
    "mana",
    "Dark Recovery",
    "End your turn with no Mana to gain 1 extra Mana next turn",
    "Sparkles",
    setEffect("manaAfterEmptyTurn", 1),
  ),
  talent(
    "mana-manaburn",
    "mana",
    "Manaburn",
    `Burn damage is increased by ${MANABURN_DAMAGE_PERCENT}% of your Mana Crystals`,
    "Flame",
    setEffect("burnDamagePerManaCrystal", MANABURN_DAMAGE_PERCENT),
  ),
  talent(
    "mana-arcane-frost",
    "mana",
    "Arcane Frost",
    "Freeze damage is increased by 25% of your Mana Crystals",
    "Snowflake",
    setEffect("freezeDamagePerManaCrystal", 0.5),
  ),
  talent(
    "mana-flare",
    "mana",
    "Mana Flare",
    "When you lose a Mana Crystal, deal 3 Burn damage",
    "Bomb",
    setEffect("burnDamageOnManaCrystalLoss", 3),
  ),
  talent(
    "mana-familiar-bond",
    "mana",
    "Familiar Bond",
    "Companion damage is increased by half your Mana Crystals",
    "PawPrint",
    setEffect("companionDamagePerManaCrystal", 1),
  ),
  talent(
    "mana-shell",
    "mana",
    "Mana Shell",
    "Start each combat with Armor equal to your Mana Crystals",
    "ShieldHalf",
    setEffect("manaShellActive", true),
  ),
  talent(
    "mana-arcane-mending",
    "mana",
    "Arcane Mending",
    "Restore 2 Health when you gain Mana",
    "Wand",
    setEffect("healOnManaGain", 2),
  ),
  talent(
    "nature-overgrowth",
    "nature",
    "Overgrowth",
    "Increase Nature damage by 1",
    "TrendingUp",
    addEffect("flatNatureDamage", 1),
  ),
  talent(
    "nature-thornskin",
    "nature",
    "Thornskin",
    "Nature damage is increased by your Armor",
    "Hexagon",
    setEffect("armorToNatureDamage", true),
  ),
  talent(
    "nature-natural-armor",
    "nature",
    "Bramblegrowth",
    "When you play a Nature card, gain 1 Thorns",
    "Shield",
    setEffect("thornsOnNatureCard", 1),
  ),
  talent(
    "nature-photosynthesis",
    "nature",
    "Photosynthesis",
    "Restore 1 Health when you play a Nature card",
    "Leaf",
    setEffect("healOnNatureCard", 1),
  ),
  talent(
    "nature-canopy",
    "nature",
    "Windstep",
    "When you Dodge, your next Nature card is free",
    "Feather",
    setEffect("nextNatureCardFreeOnDodge", true),
  ),
  talent(
    "nature-briar-patch",
    "nature",
    "Briar Patch",
    "Physical cards deal 2 additional Bleed damage if your previous card this turn was Nature",
    "Triangle",
    setEffect("physicalAfterNatureBleedDamage", 2),
  ),
  talent(
    "nature-toxic-pollen",
    "nature",
    "Toxic Pollen",
    "Nature hits have a 10% chance to deal 50% of their damage as Poison damage",
    "Wind",
    setEffect("naturePoisonDamageChance", 10),
  ),
  talent(
    "nature-verdant-cycle",
    "nature",
    "Verdant Cycle",
    "Nature damage has a 10% chance to Leech",
    "RotateCw",
    addEffect("natureLeechChance", 10),
  ),
  talent(
    "nature-ecosystem",
    "nature",
    "Ecosystem",
    "When you play a Nature card against a Poisoned enemy, deal 1 Poison damage",
    "Network",
    setEffect("poisonOnNatureCardVsPoisoned", 1),
  ),
  talent(
    "nature-entangle",
    "nature",
    "Entangle",
    "Nature hits have a 10% chance to deal Stun damage equal to their damage",
    "Link",
    setEffect("natureStunChance", 10),
  ),
  talent(
    "physical-expert-blacksmith",
    "physical",
    "Expert Blacksmith",
    "Physical damage bonus from Forge is increased by 50%",
    "Anvil",
    setEffect("forgeToPhysicalDamageMultiplier", 1.5),
  ),
  talent(
    "physical-shield-bash",
    "physical",
    "Shield Slam",
    "Physical attacks reduce enemy Armor by 2 while you have Block",
    "Shield",
    setEffect("physicalStripArmorWhileBlocked", true),
  ),
  talent(
    "physical-armored-fists",
    "physical",
    "Armored Fists",
    "Physical damage is increased by your Armor",
    "HandFist",
    setEffect("armorToPhysicalDamage", true),
  ),
  talent(
    "physical-heavy-blows",
    "physical",
    "Heavy Blows",
    "Physical hits have a 10% chance to deal Stun damage equal to their damage",
    "Hammer",
    setEffect("physicalStunChance", 10),
  ),
  talent(
    "physical-finish-him",
    "physical",
    "Finish Him",
    "Physical hits against Stunned enemies Leech",
    "Skull",
    setEffect("physicalLeechVsStunned", true),
  ),
  talent(
    "physical-shatter",
    "physical",
    "Icebreaker",
    "Physical hits against Frozen enemies grant 1 Forge",
    "Split",
    setEffect("forgeOnPhysicalVsFrozen", 1),
  ),
  talent(
    "physical-lacerate",
    "physical",
    "Lacerate",
    "Physical hits have a 10% chance to deal 25% of their damage as Bleed damage",
    "Scissors",
    setEffect("physicalBleedDamageChance", 10),
  ),
  talent(
    "physical-hemorrhage",
    "physical",
    "Rupture",
    "Physical hits detonate Bleed",
    "Droplets",
    setEffect("physicalDetonatesBleed", true),
  ),
  talent(
    "physical-brute-force",
    "physical",
    "Riposte",
    "When you Dodge, deal Physical damage equal to the dodged attack",
    "Swords",
    setEffect("physicalOnDodgeEqualToAttack", true),
  ),
  talent(
    "physical-unrelenting",
    "physical",
    "Unrelenting",
    "You deal double Physical damage while below 50% Health",
    "ShieldCheck",
    setEffect("physicalDoubledBelowHalfHealth", true),
  ),
  talent(
    "poison-leech-chance",
    "poison",
    "Hemotoxin",
    "Poison has a 10% chance to Leech",
    "Biohazard",
    setEffect("poisonLeechChance", 10),
  ),
  talent(
    "poison-physical-bonus",
    "poison",
    "Corrosive",
    "Physical hits deal 1 additional damage against Poisoned enemies",
    "Droplets",
    setEffect("poisonPhysicalBonus", 1),
  ),
  talent(
    "poison-strip-armor",
    "poison",
    "Caustic",
    "Poison hits and ticks remove 1 enemy Armor",
    "FlaskRound",
    setEffect("poisonStripArmor", true),
  ),
  talent(
    "poison-half-damage",
    "poison",
    "Toxin Resistance",
    "Take half Poison damage",
    "Shield",
    setEffect("receiveHalfPoisonDamage", true),
  ),
  talent(
    "poison-gold-first",
    "poison",
    "Toxic Profit",
    "Gain 3 additional Gold when you defeat a Poisoned enemy",
    "Coins",
    setEffect("goldOnPoisonedKill", 3),
  ),
  talent(
    "poison-heal-reduce",
    "poison",
    "Necrosis",
    "Poisoned enemies restore half as much Health",
    "Skull",
    setEffect("poisonHalvesHealing", true),
  ),
  talent(
    "poison-stun-chance",
    "poison",
    "Paralytic Venom",
    "Poison hits and ticks have a 10% chance to deal Stun damage equal to their damage",
    "Lock",
    setEffect("poisonStunChance", 10),
  ),
  talent(
    "poison-gain-chance",
    "poison",
    "Virulent",
    "Poison has a 10% chance to gain instead of lose a stack",
    "TrendingUp",
    setEffect("poisonGainChance", 10),
  ),
  talent(
    "poison-reduce-damage",
    "poison",
    "Torpor",
    "Poisoned enemies cannot Dodge",
    "Moon",
    setEffect("poisonPreventsEnemyDodge", true),
  ),
  talent(
    "poison-first-free",
    "poison",
    "Venom Strike",
    "Poison cards deal 1 additional Physical damage against Poisoned enemies",
    "Syringe",
    setEffect("poisonCardPhysicalVsPoisoned", 1),
  ),
  talent(
    "stun-forge-grant",
    "stun",
    "Riled Up",
    "When you Stun an enemy, gain 2 Forge",
    "Flame",
    setEffect("forgeOnStun", 2),
  ),
  talent(
    "stun-double-damage",
    "stun",
    "Exploit Weakness",
    "Stunned enemies take double damage",
    "TrendingUp",
    setEffect("stunDoubleDamage", true),
  ),
  talent(
    "stun-block-grant",
    "stun",
    "Guarded Counter",
    "When you Stun an enemy, gain 3 Block",
    "Shield",
    setEffect("blockOnStun", 3),
  ),
  talent(
    "stun-duration-1",
    "stun",
    "Extended Stun",
    "Stun effects last 1 turn longer",
    "Clock",
    setEffect("stunDurationExtension", 1),
  ),
  talent(
    "stun-strip-armor",
    "stun",
    "Shatter Guard",
    "When you Stun an enemy, remove all its Armor",
    "ShieldOff",
    setEffect("stunStripArmor", true),
  ),
  talent("stun-damage-1", "stun", "Jarring Blow", "Increase Stun damage by 1", "Bolt", addEffect("flatStunDamage", 1)),
  talent(
    "stun-next-free",
    "stun",
    "Free Follow-up",
    "When you Stun an enemy, your next card is free",
    "Gift",
    setEffect("nextCardFreeOnStun", true),
  ),
  talent(
    "stun-threshold",
    "stun",
    "Concussive Force",
    "Stun threshold reduced by 10%",
    "Waves",
    setEffect("stunThresholdReduction", 0.1),
  ),
  talent("stun-draw", "stun", "Stun Insight", "When you Stun an enemy, draw a card", "Eye", setEffect("drawOnStun", 1)),
  talent(
    "stun-mana-grant",
    "stun",
    "Stun Surge",
    "When you Stun an enemy, gain 1 Mana",
    "PlugZap",
    setEffect("manaOnStun", 1),
  ),
  talent(
    "wish-trinket",
    "wish",
    "Wishful Trinket",
    "Gain 1 Forge or Armor when you Wish",
    "Gem",
    setEffect("wishTrinketChoice", true),
  ),
  talent(
    "wish-undiscovered",
    "wish",
    "Discovery",
    "Wish always includes an undiscovered card when one is available",
    "Compass",
    setEffect("wishUndiscoveredCards", true),
  ),
  talent("wish-health", "wish", "Vital Wish", "Restore 2 Health when you Wish", "Heart", setEffect("healthOnWish", 2)),
  talent(
    "wish-cleanse",
    "wish",
    "Purifying Wish",
    "Cleanse 1 harmful status effect when you Wish",
    "Sparkle",
    setEffect("removeHarmfulStatusOnWish", true),
  ),
  talent(
    "wish-extra-choice",
    "wish",
    "Generous Wish",
    "Wish offers 1 additional card choice",
    "Gift",
    setEffect("wishExtraChoices", 1),
  ),
  talent("wish-draw", "wish", "Insight", "Wish also draws a card", "Eye", setEffect("wishDrawsCard", true)),
  talent(
    "wish-powerful",
    "wish",
    "Powerful Wish",
    "Wish card numeric values are increased by 1",
    "Bolt",
    setEffect("wishCardsUpgraded", true),
  ),
  talent(
    "wish-mana",
    "wish",
    "Mana from Heaven",
    "When you Wish, gain 1 additional Mana at the start of your next turn",
    "CloudRain",
    addEffect("manaNextTurnOnWish", 1),
  ),
  talent(
    "wish-gold",
    "wish",
    "Roads Not Taken",
    "When you choose a Wish card, gain 1 Block for each other card offered",
    "Coins",
    setEffect("blockPerDeclinedWishCard", 1),
  ),
  talent(
    "wish-desperate",
    "wish",
    "Desperate Wish",
    "Gain 6 Block when you Wish below 30% Health",
    "HeartCrack",
    setEffect("wishBlockBelowHealthPct", 30),
    setEffect("wishBlockAmount", 6),
  ),
];

export const talentById: ReadonlyMap<string, TalentDefinition> = new Map(
  talentPool.map((talent) => [talent.id, talent]),
);

export function getTalentById(talentId: string): TalentDefinition | undefined {
  return talentById.get(talentId);
}

export const talentPoolByKeyword: ReadonlyMap<KeywordId, TalentDefinition[]> = talentPool.reduce<
  Map<KeywordId, TalentDefinition[]>
>((acc, talent) => {
  const bucket = acc.get(talent.keywordId);
  if (bucket) bucket.push(talent);
  else acc.set(talent.keywordId, [talent]);
  return acc;
}, new Map());

export function getTalentsForKeyword(keywordId: KeywordId): TalentDefinition[] {
  return talentPoolByKeyword.get(keywordId) ?? [];
}
