import { MANABURN_DAMAGE_PERCENT } from "@/lib/game-constants";
import type { TalentDefinition } from "./types";
import { addEffect, setEffect } from "./types";
import type { KeywordId } from "../types";

export const talentPool: TalentDefinition[] = [
  {
    id: "dodge-lightfoot",
    keywordId: "dodge",
    name: "Lightfoot",
    description: "+5% Dodge chance",
    icon: "Feather",
    effects: [addEffect("dodgeChance", 5)],
  },
  {
    id: "dodge-catch-breath",
    keywordId: "dodge",
    name: "Catch Breath",
    description: "Restore 1 Health when you Dodge",
    icon: "HeartPulse",
    effects: [addEffect("healOnDodge", 1)],
  },
  {
    id: "dodge-feint",
    keywordId: "dodge",
    name: "Feint",
    description: "Gain 1 Forge when you Dodge",
    icon: "Anvil",
    effects: [addEffect("forgeOnDodge", 1)],
  },
  {
    id: "dodge-thornstep",
    keywordId: "dodge",
    name: "Thornstep",
    description: "Gain 1 Thorns when you Dodge",
    icon: "Leaf",
    effects: [addEffect("thornsOnDodge", 1)],
  },
  {
    id: "dodge-clean-getaway",
    keywordId: "dodge",
    name: "Clean Getaway",
    description: "When you Dodge, remove 1 stack each of Burn, Poison, and Bleed from yourself",
    icon: "Eraser",
    effects: [addEffect("cleanseStacksOnDodge", 1)],
  },
  {
    id: "dodge-open-flank",
    keywordId: "dodge",
    name: "Open Flank",
    description: "When you Dodge, your next attack deals 4 additional Physical damage",
    icon: "Swords",
    effects: [addEffect("nextAttackPhysicalOnDodge", 4)],
  },
  {
    id: "dodge-unburdened",
    keywordId: "dodge",
    name: "Unburdened",
    description: "When you Dodge, cleanse your Stun and Freeze buildup",
    icon: "ShieldOff",
    effects: [setEffect("cleanseCcOnDodge", true)],
  },
  {
    id: "dodge-rolling-recovery",
    keywordId: "dodge",
    name: "Tailwind",
    description: "When you Dodge, draw a card",
    icon: "ShieldHalf",
    effects: [setEffect("drawOnDodge", 1)],
  },
  {
    id: "dodge-finding-rhythm",
    keywordId: "dodge",
    name: "Finding Rhythm",
    description: "Taking damage increases your Dodge chance by 5%, resetting when you Dodge",
    icon: "Activity",
    effects: [addEffect("dodgeChanceOnHostileDamage", 5)],
  },
  {
    id: "dodge-perfect-timing",
    keywordId: "dodge",
    name: "Perfect Timing",
    description: "Gain 1 Armor when you Dodge",
    icon: "Shield",
    effects: [addEffect("armorOnDodge", 1)],
  },

  {
    id: "archery-damage",
    keywordId: "archery",
    name: "Arrow Dance",
    description: "When you Dodge, your next Archery card is free",
    icon: "Move",
    effects: [setEffect("nextArcheryCardFreeOnDodge", true)],
  },
  {
    id: "archery-hail",
    keywordId: "archery",
    name: "Follow-through",
    description: "Archery cards deal 2 additional Physical damage if your previous card this turn was Archery",
    icon: "CloudRain",
    effects: [setEffect("consecutiveArcheryPhysicalDamage", 2)],
  },
  {
    id: "archery-eagle-eye",
    keywordId: "archery",
    name: "Eagle Eye",
    description: "When you play an Archery card against a Stunned enemy, draw a card",
    icon: "Eye",
    effects: [setEffect("drawOnArcheryVsStunned", 1)],
  },
  {
    id: "archery-hawk-eye",
    keywordId: "archery",
    name: "Hawk Eye",
    description: "Archery hits against Frozen enemies deal 2 additional Holy damage",
    icon: "ScanEye",
    effects: [setEffect("archeryHolyDamageVsFrozen", 2)],
  },
  {
    id: "archery-longshot",
    keywordId: "archery",
    name: "Longshot",
    description: "Archery cards deal double damage against enemies at full Health",
    icon: "ArrowRight",
    effects: [setEffect("archeryDoubledVsHighHealth", true)],
  },
  {
    id: "archery-piercing-shot",
    keywordId: "archery",
    name: "Piercing Shot",
    description: "Archery cards ignore 1 Armor",
    icon: "Aperture",
    effects: [addEffect("archeryArmorPiercing", 1)],
  },
  {
    id: "archery-quickdraw",
    keywordId: "archery",
    name: "Quickdraw",
    description: "Archery cards deal 1 additional Physical damage while you have no Block",
    icon: "Zap",
    effects: [setEffect("archeryPhysicalWithoutBlock", 1)],
  },
  {
    id: "archery-kill-shot",
    keywordId: "archery",
    name: "Kill Shot",
    description: "Archery cards deal double damage against enemies below 20% Health",
    icon: "Crosshair",
    effects: [setEffect("archeryDoubledVsLowHealth", true)],
  },
  {
    id: "archery-broadhead",
    keywordId: "archery",
    name: "Broadhead",
    description: "Archery hits have a 10% chance to deal 25% of their damage as Bleed damage",
    icon: "Diamond",
    effects: [setEffect("archeryBleedDamageChance", 10)],
  },
  {
    id: "archery-trophy-shot",
    keywordId: "archery",
    name: "Trophy Shot",
    description: "Gain 2 Gold when an Archery card defeats an enemy",
    icon: "Award",
    effects: [setEffect("goldOnArcheryKill", 2)],
  },

  {
    id: "armor-desperate-double",
    keywordId: "armor",
    name: "Last Stand",
    description: "Armor gained is doubled when Health is below 50%",
    icon: "HeartCrack",
    effects: [setEffect("armorDoubledBelowHalfHealth", true)],
  },
  {
    id: "armor-block-burst",
    keywordId: "armor",
    name: "Armored Surge",
    description: "When you reach 4 Armor, gain 8 Block",
    icon: "Shield",
    effects: [setEffect("armorBlockThreshold", 4), setEffect("armorBlockAmount", 8)],
  },
  {
    id: "armor-burn-mitigate",
    keywordId: "armor",
    name: "Fireward",
    description: "Armor mitigates Burn damage taken",
    icon: "Flame",
    effects: [setEffect("armorMitigatesBurn", true)],
  },
  {
    id: "armor-break-block",
    keywordId: "armor",
    name: "Reactive Guard",
    description: "When Armor breaks, gain 5 Block",
    icon: "ShieldPlus",
    effects: [setEffect("armorBreakBlock", 5)],
  },
  {
    id: "armor-start-combat",
    keywordId: "armor",
    name: "Bulwark",
    description: "Start each combat with 2 Armor",
    icon: "Square",
    effects: [setEffect("startArmor", 2)],
  },
  {
    id: "armor-mitigate-bleed",
    keywordId: "armor",
    name: "Thick Hide",
    description: "Armor mitigates Bleed damage taken",
    icon: "Hexagon",
    effects: [setEffect("armorMitigatesBleed", true)],
  },
  {
    id: "armor-first-double",
    keywordId: "armor",
    name: "Iron Guard",
    description: "When you play an Armor card, gain 2 Block",
    icon: "Lock",
    effects: [setEffect("blockOnArmorCard", 2)],
  },
  {
    id: "armor-mitigate-stun",
    keywordId: "armor",
    name: "Steadfast",
    description: "When your Health falls below 50%, gain 5 Armor",
    icon: "Anchor",
    effects: [setEffect("healthThresholdArmor", [{ threshold: 50, amount: 5 }])],
  },
  {
    id: "armor-cleanse-threshold",
    keywordId: "armor",
    name: "Purification",
    description: "When you reach 6 Armor, cleanse all harmful status effects",
    icon: "Sparkles",
    effects: [setEffect("armorCleanseThreshold", 6)],
  },
  {
    id: "armor-flat-bonus",
    keywordId: "armor",
    name: "Reinforced",
    description: "Increase Armor gained by 1",
    icon: "Plus",
    effects: [addEffect("flatArmorAmount", 1)],
  },

  {
    id: "bleed-first-free",
    keywordId: "bleed",
    name: "First Blood",
    description: "Bleed hits deal 50% more damage against enemies that were not already Bleeding",
    icon: "Swords",
    effects: [setEffect("bleedUnwoundedBonusPercent", 50)],
  },
  {
    id: "bleed-physical-bonus",
    keywordId: "bleed",
    name: "Parting Cut",
    description: "After you Dodge, your next Physical card deals Bleed damage equal to its damage",
    icon: "Slash",
    effects: [setEffect("partingCutOnDodge", true)],
  },
  {
    id: "bleed-leech-chance",
    keywordId: "bleed",
    name: "Sanguine",
    description: "Bleed has a 15% chance to Leech",
    icon: "HeartPulse",
    effects: [setEffect("bleedLeechChance", 15)],
  },
  {
    id: "bleed-enemy-weak",
    keywordId: "bleed",
    name: "Mortal Wound",
    description: "Bleeding enemies restore half as much Health",
    icon: "Bone",
    effects: [setEffect("bleedHalvesEnemyHealing", true)],
  },
  {
    id: "bleed-wound-care",
    keywordId: "bleed",
    name: "Wound Care",
    description: "Take half Bleed damage",
    icon: "Bandage",
    effects: [setEffect("receiveHalfBleedDamage", true)],
  },
  {
    id: "bleed-execute",
    keywordId: "bleed",
    name: "Flay",
    description: "Bleed hits have a 20% chance to halve enemy Armor",
    icon: "Scissors",
    effects: [setEffect("bleedHalveArmorChance", 20)],
  },
  {
    id: "bleed-desperate",
    keywordId: "bleed",
    name: "Bleeding Out",
    description: "You deal 50% more Bleed damage while below 50% Health",
    icon: "HeartCrack",
    effects: [setEffect("bleedDesperateMultiplier", 1.5)],
  },
  {
    id: "bleed-poison-chance",
    keywordId: "bleed",
    name: "Tainted Wound",
    description: "Bleed hits have a 10% chance to deal 50% of their damage as Poison damage",
    icon: "FlaskConical",
    effects: [setEffect("bleedPoisonDamageChance", 10)],
  },
  {
    id: "bleed-septic-shock",
    keywordId: "bleed",
    name: "Septic Shock",
    description: "Bleed increases Poison damage taken by 1",
    icon: "TriangleAlert",
    effects: [setEffect("bleedPoisonDamageTakenBonus", 1)],
  },
  {
    id: "bleed-rip-and-tear",
    keywordId: "bleed",
    name: "Bloodrush",
    description: "When an enemy takes damage from a Bleed tick, draw a Physical card",
    icon: "Scissors",
    effects: [setEffect("drawPhysicalOnBleedTick", true)],
  },

  {
    id: "block-depleted-heal",
    keywordId: "block",
    name: "Second Wind",
    description: "When Block is depleted, restore 2 Health",
    icon: "Wind",
    effects: [setEffect("blockDepletedHeal", 2)],
  },
  {
    id: "block-absorb-physical",
    keywordId: "block",
    name: "Reinforce",
    description: "Block absorbs 20% more Physical damage",
    icon: "ShieldCheck",
    effects: [setEffect("blockAbsorbPhysicalBonus", 20)],
  },
  {
    id: "block-to-holy",
    keywordId: "block",
    name: "Sacred Shield",
    description: "Holy damage is increased by 30% of your Block",
    icon: "Sun",
    effects: [setEffect("blockToHolyDamage", true)],
  },
  {
    id: "block-to-stun",
    keywordId: "block",
    name: "Impact Guard",
    description: "Stun damage is increased by 30% of your Block",
    icon: "Zap",
    effects: [setEffect("blockToStunDamage", true)],
  },
  {
    id: "block-prevent-stun",
    keywordId: "block",
    name: "Grounding",
    description: "While you have Block, prevent Stun buildup",
    icon: "Anchor",
    effects: [setEffect("blockPreventsStun", true)],
  },
  {
    id: "block-to-physical",
    keywordId: "block",
    name: "Weighted Guard",
    description: "Physical damage is increased by 30% of your Block",
    icon: "Weight",
    effects: [addEffect("blockToPhysicalDamageMultiplier", 0.3)],
  },
  {
    id: "block-reduce-burn",
    keywordId: "block",
    name: "Sun-Struck Shield",
    description: "When an enemy attack removes your Block, reflect 30% of the Block lost as Holy damage",
    icon: "Flame",
    effects: [setEffect("holyReflectionBlockLostPercent", 30)],
  },
  {
    id: "block-start",
    keywordId: "block",
    name: "Footwork",
    description: "When you Dodge, gain Block equal to the dodged attack",
    icon: "ChevronsUp",
    effects: [setEffect("blockOnDodgeEqualToAttack", true)],
  },
  {
    id: "block-prevent-bleed",
    keywordId: "block",
    name: "Coagulate",
    description: "While you have Block, prevent Bleed buildup",
    icon: "Droplets",
    effects: [setEffect("blockPreventsBleed", true)],
  },
  {
    id: "block-prevent-poison",
    keywordId: "block",
    name: "Detoxify",
    description: "While you have Block, prevent Poison buildup",
    icon: "FlaskConical",
    effects: [setEffect("blockPreventsPoison", true)],
  },

  {
    id: "burn-dmg-1",
    keywordId: "burn",
    name: "Flashpoint",
    description: "Increase Burn damage by 1",
    icon: "Thermometer",
    effects: [addEffect("flatBurnDamage", 1)],
  },
  {
    id: "burn-dmg-2",
    keywordId: "burn",
    name: "Thermal Vent",
    description: "When you play a Burn card, gain 1 Forge",
    icon: "WavesArrowUp",
    effects: [addEffect("forgeOnBurnCard", 1)],
  },
  {
    id: "burn-dmg-5",
    keywordId: "burn",
    name: "Smoke Screen",
    description: "When you Dodge a Burning enemy, deal 2 Burn damage",
    icon: "Shield",
    effects: [setEffect("burnOnDodgeBurning", 2)],
  },
  {
    id: "burn-dmg-4",
    keywordId: "burn",
    name: "Combustible",
    description: "When you Consume a card, detonate the enemy’s Burn",
    icon: "Bomb",
    effects: [setEffect("consumeDetonatesBurn", true)],
  },
  {
    id: "burn-first-double",
    keywordId: "burn",
    name: "Wildfire",
    description: "When you play a Burn card, remove 1 Poison from yourself; if you do, deal 1 Poison damage",
    icon: "TrendingUp",
    effects: [setEffect("cleansePoisonOnBurnCard", 1)],
  },
  {
    id: "burn-remove-armor",
    keywordId: "burn",
    name: "Melting Point",
    description: "Burn hits remove enemy Armor equal to the damage dealt",
    icon: "Droplets",
    effects: [setEffect("burnRemovesEnemyArmor", true)],
  },
  {
    id: "burn-dmg-3",
    keywordId: "burn",
    name: "Heat Exhaustion",
    description: "Burn hits have a 10% chance to deal Stun damage equal to their damage",
    icon: "TrendingDown",
    effects: [setEffect("burnStunChance", 10)],
  },
  {
    id: "burn-dmg-6",
    keywordId: "burn",
    name: "Burning Wish",
    description: "When you Wish, deal 2 Burn damage to the enemy",
    icon: "Sparkles",
    effects: [setEffect("burnOnWish", 2)],
  },
  {
    id: "burn-double-chance",
    keywordId: "burn",
    name: "Smoldering",
    description: "Burn stacks have a 10% chance to not decay",
    icon: "Wind",
    effects: [setEffect("burnPreventDecayChance", 10)],
  },
  {
    id: "burn-half-damage",
    keywordId: "burn",
    name: "Fire Resistance",
    description: "Take half Burn damage",
    icon: "ShieldCheck",
    effects: [setEffect("receiveHalfBurnDamage", true)],
  },

  {
    id: "companion-damage",
    keywordId: "companion",
    name: "Feral Strength",
    description: "Increase Companion damage by 1",
    icon: "Bone",
    effects: [addEffect("companionDamage", 1)],
  },
  {
    id: "companion-gold-find",
    keywordId: "companion",
    name: "Fetch",
    description: "Win a combat with a Companion to gain 3 additional Gold",
    icon: "Trash",
    effects: [setEffect("companionVictoryGold", 3)],
  },
  {
    id: "companion-leech",
    keywordId: "companion",
    name: "Leech Companion",
    description: "Companions have a 10% chance to Leech",
    icon: "HeartPulse",
    effects: [setEffect("companionLeechChance", 10)],
  },
  {
    id: "companion-hunters-bond",
    keywordId: "companion",
    name: "Hunter's Bond",
    description: "When you play a Companion card, draw a card",
    icon: "Link2",
    effects: [setEffect("drawOnCompanionCard", 1)],
  },
  {
    id: "companion-predator-instinct",
    keywordId: "companion",
    name: "Predator's Instinct",
    description: "Companions deal double damage against enemies below 30% Health",
    icon: "Eye",
    effects: [setEffect("companionDoubledVsLowHealth", true)],
  },
  {
    id: "companion-tame",
    keywordId: "companion",
    name: "Coordinated Strike",
    description: "When you play a Physical card, your Companion’s next attack deals 1 additional damage",
    icon: "Hand",
    effects: [setEffect("companionNextAttackOnPhysical", 1)],
  },
  {
    id: "companion-loyal",
    keywordId: "companion",
    name: "Pack Weave",
    description: "When you Dodge, your Companion attacks",
    icon: "PawPrint",
    effects: [setEffect("companionAttacksOnDodge", true)],
  },
  {
    id: "companion-watchdog",
    keywordId: "companion",
    name: "Watchdog",
    description: "When your Companion deals damage, gain 2 Block",
    icon: "ShieldAlert",
    effects: [setEffect("blockOnCompanionDamage", 2)],
  },
  {
    id: "companion-takedown",
    keywordId: "companion",
    name: "Takedown",
    description: "Companion attacks have a 10% chance to deal Stun damage equal to their damage",
    icon: "Ban",
    effects: [setEffect("companionStunChance", 10)],
  },
  {
    id: "companion-whistle",
    keywordId: "companion",
    name: "Whistle",
    description: "After you play a Companion card, your active Companion acts immediately",
    icon: "Bell",
    effects: [setEffect("companionActsOnCard", true)],
  },

  {
    id: "consume-gourmand",
    keywordId: "consume",
    name: "Gourmand",
    description: "Consume cards restore 20% more Health",
    icon: "Apple",
    effects: [setEffect("consumeHealMultiplier", 0.2)],
  },
  {
    id: "consume-last-supper",
    keywordId: "consume",
    name: "Last Supper",
    description: "When you Consume a card, gain 1 Forge",
    icon: "Gift",
    effects: [setEffect("forgeOnConsume", 1)],
  },
  {
    id: "consume-volatility",
    keywordId: "consume",
    name: "Volatility",
    description: "Consume cards deal 20% more damage",
    icon: "Flame",
    effects: [setEffect("consumeDamageBonusPercent", 20)],
  },
  {
    id: "consume-distillation",
    keywordId: "consume",
    name: "Distillation",
    description: "Potions are 20% more potent",
    icon: "FlaskConical",
    effects: [addEffect("potionPotency", 0.2)],
  },
  {
    id: "consume-brewmaster",
    keywordId: "consume",
    name: "Brewmaster",
    description: "Mixed Potion potency is increased by 1",
    icon: "Wine",
    effects: [addEffect("potionMixPotency", 1)],
  },
  {
    id: "consume-aftertaste",
    keywordId: "consume",
    name: "Aftertaste",
    description: "When you Consume a card, restore 1 Health",
    icon: "Cookie",
    effects: [setEffect("healOnConsume", 1)],
  },
  {
    id: "consume-leftovers",
    keywordId: "consume",
    name: "Leftovers",
    description: "When you Consume a card, gain 1 Gold",
    icon: "Package",
    effects: [setEffect("goldOnConsume", 1)],
  },
  {
    id: "consume-second-helping",
    keywordId: "consume",
    name: "Second Helping",
    description: "When you Consume a card, draw a card",
    icon: "CopyPlus",
    effects: [setEffect("uncappedDrawOnConsume", 1)],
  },
  {
    id: "consume-rotgut",
    keywordId: "consume",
    name: "Rotgut",
    description: "When you Consume a card, deal 1 Poison damage",
    icon: "FlaskRound",
    effects: [setEffect("poisonDamageOnConsume", 1)],
  },
  {
    id: "consume-feast",
    keywordId: "consume",
    name: "Feast",
    description: "When you Consume a card, gain 2 Block",
    icon: "CookingPot",
    effects: [setEffect("blockOnConsume", 2)],
  },

  {
    id: "forge-to-burn",
    keywordId: "forge",
    name: "Ignite",
    description: "Forge also increases Burn damage",
    icon: "Flame",
    effects: [setEffect("forgeToBurn", true)],
  },
  {
    id: "forge-to-holy",
    keywordId: "forge",
    name: "Sanctify",
    description: "Forge also increases Holy damage",
    icon: "Sun",
    effects: [setEffect("forgeToHoly", true)],
  },
  {
    id: "forge-to-block",
    keywordId: "forge",
    name: "Tempered Guard",
    description: "Forge also increases Block amount",
    icon: "Shield",
    effects: [setEffect("forgeToBlock", true)],
  },
  {
    id: "forge-burn-burst",
    keywordId: "forge",
    name: "Overheat",
    description: "When you reach 4 Forge, deal 8 Burn damage",
    icon: "Thermometer",
    effects: [setEffect("forgeBurnThreshold", 4), setEffect("forgeBurnDamage", 8)],
  },
  {
    id: "forge-strength-1",
    keywordId: "forge",
    name: "Forge Mastery",
    description: "Start each combat with 1 Forge",
    icon: "FlameKindling",
    effects: [setEffect("startForge", 1)],
  },
  {
    id: "forge-strength-2",
    keywordId: "forge",
    name: "Rust",
    description: "Forge also increases Bleed damage",
    icon: "Eraser",
    effects: [setEffect("forgeToBleed", true)],
  },
  {
    id: "forge-strength-3",
    keywordId: "forge",
    name: "Sunder",
    description: "When you reach 6 Forge, remove all enemy Armor",
    icon: "ShieldOff",
    effects: [setEffect("forgeStripArmorThreshold", 6)],
  },
  {
    id: "forge-strength-4",
    keywordId: "forge",
    name: "Intensify",
    description: "Increase Forge gained by 1",
    icon: "ChevronsUp",
    effects: [addEffect("flatForgeGained", 1)],
  },
  {
    id: "forge-strength-5",
    keywordId: "forge",
    name: "Desperate Forge",
    description: "Forge gained is doubled when Health is below 50%",
    icon: "HeartCrack",
    effects: [setEffect("forgeDoubledBelowHalfHealth", true)],
  },
  {
    id: "forge-strength-6",
    keywordId: "forge",
    name: "Forged Bulwark",
    description: "When you reach 6 Forge, gain 10 Block",
    icon: "Castle",
    effects: [setEffect("forgeBlockThreshold", 6), setEffect("forgeBlockAmount", 10)],
  },

  {
    id: "freeze-threshold",
    keywordId: "freeze",
    name: "Bitter Cold",
    description: "Freeze threshold reduced by 10%",
    icon: "ThermometerSnowflake",
    effects: [setEffect("freezeThresholdReduction", 0.1)],
  },
  {
    id: "freeze-double-damage",
    keywordId: "freeze",
    name: "Shatter",
    description: "Frozen enemies take double damage",
    icon: "Split",
    effects: [setEffect("freezeDoubleDamage", true)],
  },
  {
    id: "freeze-start-amount",
    keywordId: "freeze",
    name: "Winter's Grasp",
    description: "Start each combat by dealing 4 Freeze damage",
    icon: "MountainSnow",
    effects: [setEffect("startFreeze", 4)],
  },
  {
    id: "freeze-block-grant",
    keywordId: "freeze",
    name: "Icebound",
    description: "When you Freeze an enemy, remove all its Block; Frozen enemies cannot Dodge",
    icon: "Snowflake",
    effects: [setEffect("freezeStripBlock", true), setEffect("freezePreventsEnemyDodge", true)],
  },
  {
    id: "freeze-companion-bonus",
    keywordId: "freeze",
    name: "Snow Pack",
    description: "Companion hits against Frozen enemies deal 1 additional Freeze damage",
    icon: "CloudSnow",
    effects: [setEffect("companionFreezeDamageVsFrozen", 1)],
  },
  {
    id: "freeze-strip-armor",
    keywordId: "freeze",
    name: "Brittle Armor",
    description: "When you Freeze an enemy, remove all its Armor",
    icon: "ShieldOff",
    effects: [setEffect("freezeStripArmor", true)],
  },
  {
    id: "freeze-half-damage",
    keywordId: "freeze",
    name: "Cold Resistance",
    description: "Take half Freeze damage",
    icon: "Thermometer",
    effects: [setEffect("receiveHalfFreezeDamage", true)],
  },
  {
    id: "freeze-poison-preserve",
    keywordId: "freeze",
    name: "Cryo-preservation",
    description: "Poison stacks on Frozen enemies cannot decay",
    icon: "FlaskConical",
    effects: [setEffect("freezePreventsPoisonDecay", true)],
  },
  {
    id: "freeze-prevent-scaling",
    keywordId: "freeze",
    name: "Thaw Dividend",
    description: "When an enemy recovers from Freeze, draw a card",
    icon: "Hexagon",
    effects: [setEffect("drawOnThaw", 1)],
  },
  {
    id: "freeze-block-healing",
    keywordId: "freeze",
    name: "Glacial Barrier",
    description: "When you Freeze an enemy, gain 3 Block",
    icon: "Lock",
    effects: [setEffect("blockOnFreeze", 3)],
  },

  {
    id: "gold-shop-discount",
    keywordId: "gold",
    name: "Haggle",
    description: "Shop purchases cost 5 less Gold",
    icon: "Tag",
    effects: [setEffect("shopCardDiscount", 5)],
  },
  {
    id: "gold-shop-refresh",
    keywordId: "gold",
    name: "Restock",
    description: "Shop refreshes are free",
    icon: "RefreshCw",
    effects: [setEffect("shopFreeRefresh", true)],
  },
  {
    id: "gold-start",
    keywordId: "gold",
    name: "Seed Money",
    description: "Start each run with 20 Gold",
    icon: "Sprout",
    effects: [setEffect("startGold", 20)],
  },
  {
    id: "gold-per-combat",
    keywordId: "gold",
    name: "Lucky Foot",
    description: "Gain 1 Gold when you Dodge",
    icon: "CircleDollarSign",
    effects: [setEffect("goldOnDodge", 1)],
  },
  {
    id: "gold-potion-discount",
    keywordId: "gold",
    name: "Apothecary’s Guard",
    description: "When you play a Potion, gain 1 Armor",
    icon: "Beaker",
    effects: [setEffect("armorOnPotionCard", 1)],
  },
  {
    id: "gold-remove-discount",
    keywordId: "gold",
    name: "Buyout",
    description: "Card removal costs 10 less Gold",
    icon: "ShoppingCart",
    effects: [setEffect("removeCardDiscount", 10)],
  },
  {
    id: "gold-enemy-drop",
    keywordId: "gold",
    name: "Plunder",
    description: "Enemies drop 10% more Gold",
    icon: "HandCoins",
    effects: [setEffect("enemyGoldDropBonus", 0.1)],
  },
  {
    id: "gold-on-wish",
    keywordId: "gold",
    name: "Golden Wish",
    description: "Gain 3 Gold when you Wish",
    icon: "Sparkles",
    effects: [addEffect("goldOnWish", 3)],
  },
  {
    id: "gold-mix-discount",
    keywordId: "gold",
    name: "Alchemy Discount",
    description: "Mixing Potions costs 10 less Gold",
    icon: "FlaskConical",
    effects: [setEffect("mixPotionDiscount", 10)],
  },
  {
    id: "gold-elite-drop",
    keywordId: "gold",
    name: "Coinmail",
    description: "Gold gained during combat also grants half as much Block",
    icon: "Trophy",
    effects: [setEffect("blockPerGold", 0.5)],
  },

  {
    id: "health-threshold-armor",
    keywordId: "health",
    name: "Last Resort",
    description: "When your Health falls below 25%, cleanse all harmful status effects",
    icon: "HeartCrack",
    effects: [setEffect("cleanseBelowHealthPercent", 25)],
  },
  {
    id: "health-threshold-block",
    keywordId: "health",
    name: "Desperate Guard",
    description: "When your Health falls below 50%, gain 6 Block",
    icon: "Shield",
    effects: [setEffect("healthThresholdBlock", { threshold: 50, amount: 6 })],
  },
  {
    id: "health-max-4",
    keywordId: "health",
    name: "Will to Live",
    description: "Death's Door lasts 1 turn longer",
    icon: "Activity",
    effects: [setEffect("deathsDoorExtension", 1)],
  },
  {
    id: "health-start",
    keywordId: "health",
    name: "Combat Surge",
    description: "Restore 4 Health at the start of combat",
    icon: "ChevronsUp",
    effects: [setEffect("startHealth", 4)],
  },
  {
    id: "health-max-per-combat",
    keywordId: "health",
    name: "Vitality",
    description: "Gain 1 maximum Health after every combat",
    icon: "TrendingUp",
    effects: [setEffect("maxHealthPerCombat", 1)],
  },
  {
    id: "health-heal-boost",
    keywordId: "health",
    name: "Mending",
    description: "Health restored is increased by 10%",
    icon: "HeartPulse",
    effects: [setEffect("healMultiplier", 1.1)],
  },
  {
    id: "health-max-1",
    keywordId: "health",
    name: "Overflow",
    description: "When you restore Health beyond your maximum, gain 50% of the excess as Block",
    icon: "Container",
    effects: [setEffect("overhealToBlockRatio", 0.5)],
  },
  {
    id: "health-max-2",
    keywordId: "health",
    name: "Cleansing Status",
    description: "Cleansing a harmful status effect restores 6 Health",
    icon: "Sparkles",
    effects: [setEffect("healOnStatusCleanse", 6)],
  },
  {
    id: "health-max-3",
    keywordId: "health",
    name: "Last Gasp",
    description: "While below 50% Health, gain 20% Dodge chance",
    icon: "ShieldHalf",
    effects: [setEffect("dodgeChanceBelowHalfHealth", 20)],
  },
  {
    id: "health-campfire",
    keywordId: "health",
    name: "Clean Slate",
    description: "When a card restores Health beyond your maximum, cleanse a harmful status effect",
    icon: "Flame",
    effects: [setEffect("cleanseOnCardOverheal", true)],
  },

  {
    id: "holy-tithe",
    keywordId: "holy",
    name: "Tithe",
    description: "10% chance to gain Gold equal to Holy damage",
    icon: "Cross",
    effects: [setEffect("holyGoldChance", 10)],
  },
  {
    id: "holy-block-scaling",
    keywordId: "holy",
    name: "Faith Barrier",
    description: "When you play a Holy card, gain 2 Block",
    icon: "Shield",
    effects: [setEffect("blockOnHolyCard", 2)],
  },
  {
    id: "holy-wish-chance",
    keywordId: "holy",
    name: "Divine Intervention",
    description: "Holy damage has a 5% chance to Wish",
    icon: "Sparkles",
    effects: [setEffect("holyWishChance", 5)],
  },
  {
    id: "holy-burn-chance",
    keywordId: "holy",
    name: "Scorching Light",
    description: "Holy hits have a 10% chance to deal 50% of their damage as Burn damage",
    icon: "Flame",
    effects: [setEffect("holyBurnDamageChance", 10)],
  },
  {
    id: "holy-half-damage",
    keywordId: "holy",
    name: "Celestial Ward",
    description: "Take half Holy damage",
    icon: "ShieldCheck",
    effects: [setEffect("receiveHalfHolyDamage", true)],
  },
  {
    id: "holy-first-free",
    keywordId: "holy",
    name: "Divine Favor",
    description: "When you cleanse a harmful status effect, your next Holy card is free",
    icon: "Gift",
    effects: [setEffect("nextHolyFreeOnCleanse", true)],
  },
  {
    id: "holy-gold-scaling",
    keywordId: "holy",
    name: "Prosperity",
    description: "Holy damage is increased by 3% of your Gold",
    icon: "TrendingUp",
    effects: [setEffect("holyGoldPercent", 3)],
  },
  {
    id: "holy-block-grant",
    keywordId: "holy",
    name: "Radiant Guard",
    description: "Holy damage grants Block for 15% of the amount dealt",
    icon: "ShieldPlus",
    effects: [setEffect("holyBlockPercentFromDamage", 15)],
  },
  {
    id: "holy-vs-burn",
    keywordId: "holy",
    name: "Purge",
    description: "Holy damage is increased by 20% against Burning enemies",
    icon: "Eraser",
    effects: [setEffect("holyVsBurnMultiplier", 20)],
  },
  {
    id: "holy-lifesteal",
    keywordId: "holy",
    name: "Blessed Leech",
    description: "Holy damage restores 10% of the amount dealt as Health",
    icon: "HeartPulse",
    effects: [setEffect("holyLifestealPercent", 10)],
  },

  {
    id: "leech-first-double",
    keywordId: "leech",
    name: "Deep Siphon",
    description: "Leech from your cards restores 25% more Health",
    icon: "Sword",
    effects: [setEffect("cardLeechBonusPercent", 25)],
  },
  {
    id: "leech-desperate",
    keywordId: "leech",
    name: "Desperate Siphon",
    description: "While below 50% Health, Leech also grants Block equal to half the Health restored",
    icon: "HeartCrack",
    effects: [setEffect("leechBlockBelowHalfPercent", 50)],
  },
  {
    id: "leech-blood-debt",
    keywordId: "leech",
    name: "Blood Debt",
    description: "Leech restores 1 more Health per 8 missing Health",
    icon: "CircleDollarSign",
    effects: [setEffect("leechMissingHealthStep", 8)],
  },
  {
    id: "leech-bleed-chance",
    keywordId: "leech",
    name: "Bloodletting",
    description: "Leech hits have a 10% chance to deal 25% of their damage as Bleed damage",
    icon: "Droplets",
    effects: [setEffect("leechBleedDamageChance", 10)],
  },
  {
    id: "leech-cull-weak",
    keywordId: "leech",
    name: "Cull the Weak",
    description: "Leech hits against enemies below 50% Health deal 1 additional Holy damage",
    icon: "Skull",
    effects: [setEffect("leechHolyDamageVsLowHealth", 1)],
  },
  {
    id: "leech-mana-siphon",
    keywordId: "leech",
    name: "Mana Siphon",
    description: "Leech has a 10% chance to gain 1 Mana",
    icon: "Gem",
    effects: [setEffect("manaOnLeechChance", 10)],
  },
  {
    id: "leech-trinket-siphon",
    keywordId: "leech",
    name: "Armor Siphon",
    description: "Your Leech cards steal 1 Armor before their effects resolve",
    icon: "Wrench",
    effects: [setEffect("armorStealOnLeechCard", 1)],
  },
  {
    id: "leech-poison",
    keywordId: "leech",
    name: "Virulent Leech",
    description: "Leech hits have a 10% chance to deal 50% of their damage as Poison damage",
    icon: "FlaskConical",
    effects: [setEffect("leechPoisonDamageChance", 10)],
  },
  {
    id: "leech-block-enemy",
    keywordId: "leech",
    name: "Sanguine Overflow",
    description: "When Leech fills your Health, your next attack deals 3 additional Physical damage",
    icon: "Hash",
    effects: [setEffect("nextAttackPhysicalOnLeechToFull", 3)],
  },
  {
    id: "leech-nature-chance",
    keywordId: "leech",
    name: "Affliction Siphon",
    description: "Leech restores 50% more Health against Poisoned or Bleeding enemies",
    icon: "Utensils",
    effects: [setEffect("afflictionLeechBonusPercent", 50)],
  },

  {
    id: "mana-wellspring",
    keywordId: "mana",
    name: "Wellspring",
    description: "When you end your turn with unspent Mana, keep 1 for next turn",
    icon: "Droplets",
    effects: [setEffect("wellspringKeepMana", 1)],
  },
  {
    id: "mana-bulwark",
    keywordId: "mana",
    name: "Mana Bulwark",
    description: "Start each combat with Block equal to your Mana Crystals",
    icon: "ShieldPlus",
    effects: [setEffect("manaBulwarkActive", true)],
  },
  {
    id: "mana-leylines",
    keywordId: "mana",
    name: "Leyline Attunement",
    description: "Gain 1 Mana Crystal",
    icon: "Atom",
    effects: [setEffect("startMana", 1)],
  },
  {
    id: "mana-arcane-wish",
    keywordId: "mana",
    name: "Dark Recovery",
    description: "End your turn with no Mana to gain 1 extra Mana next turn",
    icon: "Sparkles",
    effects: [setEffect("manaAfterEmptyTurn", 1)],
  },
  {
    id: "mana-manaburn",
    keywordId: "mana",
    name: "Manaburn",
    description: `Burn damage is increased by ${MANABURN_DAMAGE_PERCENT}% of your Mana Crystals`,
    icon: "Flame",
    effects: [setEffect("burnDamagePerManaCrystal", MANABURN_DAMAGE_PERCENT)],
  },
  {
    id: "mana-arcane-frost",
    keywordId: "mana",
    name: "Arcane Frost",
    description: "Freeze damage is increased by 25% of your Mana Crystals",
    icon: "Snowflake",
    effects: [setEffect("freezeDamagePerManaCrystal", 0.5)],
  },
  {
    id: "mana-flare",
    keywordId: "mana",
    name: "Mana Flare",
    description: "When you lose a Mana Crystal, deal 3 Burn damage",
    icon: "Bomb",
    effects: [setEffect("burnDamageOnManaCrystalLoss", 3)],
  },
  {
    id: "mana-familiar-bond",
    keywordId: "mana",
    name: "Familiar Bond",
    description: "Companion damage is increased by half your Mana Crystals",
    icon: "PawPrint",
    effects: [setEffect("companionDamagePerManaCrystal", 1)],
  },
  {
    id: "mana-shell",
    keywordId: "mana",
    name: "Mana Shell",
    description: "Start each combat with Armor equal to your Mana Crystals",
    icon: "ShieldHalf",
    effects: [setEffect("manaShellActive", true)],
  },
  {
    id: "mana-arcane-mending",
    keywordId: "mana",
    name: "Arcane Mending",
    description: "Restore 2 Health when you gain Mana",
    icon: "Wand",
    effects: [setEffect("healOnManaGain", 2)],
  },

  {
    id: "nature-overgrowth",
    keywordId: "nature",
    name: "Overgrowth",
    description: "Increase Nature damage by 1",
    icon: "TrendingUp",
    effects: [addEffect("flatNatureDamage", 1)],
  },
  {
    id: "nature-toxic-pollen",
    keywordId: "nature",
    name: "Toxic Pollen",
    description: "Nature hits have a 10% chance to deal 50% of their damage as Poison damage",
    icon: "Wind",
    effects: [setEffect("naturePoisonDamageChance", 10)],
  },
  {
    id: "nature-briar-patch",
    keywordId: "nature",
    name: "Briar Patch",
    description: "Physical cards deal 2 additional Bleed damage if your previous card this turn was Nature",
    icon: "Triangle",
    effects: [setEffect("physicalAfterNatureBleedDamage", 2)],
  },
  {
    id: "nature-verdant-cycle",
    keywordId: "nature",
    name: "Verdant Cycle",
    description: "Nature damage has a 10% chance to Leech",
    icon: "RotateCw",
    effects: [addEffect("natureLeechChance", 10)],
  },
  {
    id: "nature-ecosystem",
    keywordId: "nature",
    name: "Ecosystem",
    description: "When you play a Nature card against a Poisoned enemy, deal 1 Poison damage",
    icon: "Network",
    effects: [setEffect("poisonOnNatureCardVsPoisoned", 1)],
  },
  {
    id: "nature-natural-armor",
    keywordId: "nature",
    name: "Bramblegrowth",
    description: "When you play a Nature card, gain 1 Thorns",
    icon: "Shield",
    effects: [setEffect("thornsOnNatureCard", 1)],
  },
  {
    id: "nature-entangle",
    keywordId: "nature",
    name: "Entangle",
    description: "Nature hits have a 10% chance to deal Stun damage equal to their damage",
    icon: "Link",
    effects: [setEffect("natureStunChance", 10)],
  },
  {
    id: "nature-thornskin",
    keywordId: "nature",
    name: "Thornskin",
    description: "Nature damage is increased by your Armor",
    icon: "Hexagon",
    effects: [setEffect("armorToNatureDamage", true)],
  },
  {
    id: "nature-canopy",
    keywordId: "nature",
    name: "Windstep",
    description: "When you Dodge, your next Nature card is free",
    icon: "Feather",
    effects: [setEffect("nextNatureCardFreeOnDodge", true)],
  },
  {
    id: "nature-photosynthesis",
    keywordId: "nature",
    name: "Photosynthesis",
    description: "Restore 1 Health when you play a Nature card",
    icon: "Leaf",
    effects: [setEffect("healOnNatureCard", 1)],
  },

  {
    id: "physical-expert-blacksmith",
    keywordId: "physical",
    name: "Expert Blacksmith",
    description: "Physical damage bonus from Forge is increased by 50%",
    icon: "Anvil",
    effects: [setEffect("forgeToPhysicalDamageMultiplier", 1.5)],
  },
  {
    id: "physical-shield-bash",
    keywordId: "physical",
    name: "Shield Slam",
    description: "Physical attacks reduce enemy Armor by 2 while you have Block",
    icon: "Shield",
    effects: [setEffect("physicalStripArmorWhileBlocked", true)],
  },
  {
    id: "physical-armored-fists",
    keywordId: "physical",
    name: "Armored Fists",
    description: "Physical damage is increased by your Armor",
    icon: "HandFist",
    effects: [setEffect("armorToPhysicalDamage", true)],
  },
  {
    id: "physical-heavy-blows",
    keywordId: "physical",
    name: "Heavy Blows",
    description: "Physical hits have a 10% chance to deal Stun damage equal to their damage",
    icon: "Hammer",
    effects: [setEffect("physicalStunChance", 10)],
  },
  {
    id: "physical-finish-him",
    keywordId: "physical",
    name: "Finish Him",
    description: "Physical hits against Stunned enemies Leech",
    icon: "Skull",
    effects: [setEffect("physicalLeechVsStunned", true)],
  },
  {
    id: "physical-shatter",
    keywordId: "physical",
    name: "Icebreaker",
    description: "Physical hits against Frozen enemies grant 1 Forge",
    icon: "Split",
    effects: [setEffect("forgeOnPhysicalVsFrozen", 1)],
  },
  {
    id: "physical-lacerate",
    keywordId: "physical",
    name: "Lacerate",
    description: "Physical hits have a 10% chance to deal 25% of their damage as Bleed damage",
    icon: "Scissors",
    effects: [setEffect("physicalBleedDamageChance", 10)],
  },
  {
    id: "physical-hemorrhage",
    keywordId: "physical",
    name: "Rupture",
    description: "Physical hits detonate Bleed",
    icon: "Droplets",
    effects: [setEffect("physicalDetonatesBleed", true)],
  },
  {
    id: "physical-brute-force",
    keywordId: "physical",
    name: "Riposte",
    description: "When you Dodge, deal Physical damage equal to the dodged attack",
    icon: "Swords",
    effects: [setEffect("physicalOnDodgeEqualToAttack", true)],
  },
  {
    id: "physical-unrelenting",
    keywordId: "physical",
    name: "Unrelenting",
    description: "You deal double Physical damage while below 50% Health",
    icon: "ShieldCheck",
    effects: [setEffect("physicalDoubledBelowHalfHealth", true)],
  },

  {
    id: "poison-leech-chance",
    keywordId: "poison",
    name: "Hemotoxin",
    description: "Poison has a 10% chance to Leech",
    icon: "Biohazard",
    effects: [setEffect("poisonLeechChance", 10)],
  },
  {
    id: "poison-physical-bonus",
    keywordId: "poison",
    name: "Corrosive",
    description: "Physical hits deal 1 additional damage against Poisoned enemies",
    icon: "Droplets",
    effects: [setEffect("poisonPhysicalBonus", 1)],
  },
  {
    id: "poison-strip-armor",
    keywordId: "poison",
    name: "Caustic",
    description: "Poison hits and ticks remove 1 enemy Armor",
    icon: "FlaskRound",
    effects: [setEffect("poisonStripArmor", true)],
  },
  {
    id: "poison-half-damage",
    keywordId: "poison",
    name: "Toxin Resistance",
    description: "Take half Poison damage",
    icon: "Shield",
    effects: [setEffect("receiveHalfPoisonDamage", true)],
  },
  {
    id: "poison-gold-first",
    keywordId: "poison",
    name: "Toxic Profit",
    description: "Gain 3 additional Gold when you defeat a Poisoned enemy",
    icon: "Coins",
    effects: [setEffect("goldOnPoisonedKill", 3)],
  },
  {
    id: "poison-heal-reduce",
    keywordId: "poison",
    name: "Necrosis",
    description: "Poisoned enemies restore half as much Health",
    icon: "Skull",
    effects: [setEffect("poisonHalvesHealing", true)],
  },
  {
    id: "poison-stun-chance",
    keywordId: "poison",
    name: "Paralytic Venom",
    description: "Poison hits and ticks have a 10% chance to deal Stun damage equal to their damage",
    icon: "Lock",
    effects: [setEffect("poisonStunChance", 10)],
  },
  {
    id: "poison-gain-chance",
    keywordId: "poison",
    name: "Virulent",
    description: "Poison has a 10% chance to gain instead of lose a stack",
    icon: "TrendingUp",
    effects: [setEffect("poisonGainChance", 10)],
  },
  {
    id: "poison-reduce-damage",
    keywordId: "poison",
    name: "Torpor",
    description: "Poisoned enemies cannot Dodge",
    icon: "Moon",
    effects: [setEffect("poisonPreventsEnemyDodge", true)],
  },
  {
    id: "poison-first-free",
    keywordId: "poison",
    name: "Venom Strike",
    description: "Poison cards deal 1 additional Physical damage against Poisoned enemies",
    icon: "Syringe",
    effects: [setEffect("poisonCardPhysicalVsPoisoned", 1)],
  },

  {
    id: "stun-forge-grant",
    keywordId: "stun",
    name: "Riled Up",
    description: "When you Stun an enemy, gain 2 Forge",
    icon: "Flame",
    effects: [setEffect("forgeOnStun", 2)],
  },
  {
    id: "stun-double-damage",
    keywordId: "stun",
    name: "Exploit Weakness",
    description: "Stunned enemies take double damage",
    icon: "TrendingUp",
    effects: [setEffect("stunDoubleDamage", true)],
  },
  {
    id: "stun-block-grant",
    keywordId: "stun",
    name: "Guarded Counter",
    description: "When you Stun an enemy, gain 3 Block",
    icon: "Shield",
    effects: [setEffect("blockOnStun", 3)],
  },
  {
    id: "stun-duration-1",
    keywordId: "stun",
    name: "Extended Stun",
    description: "Stun effects last 1 turn longer",
    icon: "Clock",
    effects: [setEffect("stunDurationExtension", 1)],
  },
  {
    id: "stun-strip-armor",
    keywordId: "stun",
    name: "Shatter Guard",
    description: "When you Stun an enemy, remove all its Armor",
    icon: "ShieldOff",
    effects: [setEffect("stunStripArmor", true)],
  },
  {
    id: "stun-damage-1",
    keywordId: "stun",
    name: "Jarring Blow",
    description: "Increase Stun damage by 1",
    icon: "Bolt",
    effects: [addEffect("flatStunDamage", 1)],
  },
  {
    id: "stun-next-free",
    keywordId: "stun",
    name: "Free Follow-up",
    description: "When you Stun an enemy, your next card is free",
    icon: "Gift",
    effects: [setEffect("nextCardFreeOnStun", true)],
  },
  {
    id: "stun-threshold",
    keywordId: "stun",
    name: "Concussive Force",
    description: "Stun threshold reduced by 10%",
    icon: "Waves",
    effects: [setEffect("stunThresholdReduction", 0.1)],
  },
  {
    id: "stun-draw",
    keywordId: "stun",
    name: "Stun Insight",
    description: "When you Stun an enemy, draw a card",
    icon: "Eye",
    effects: [setEffect("drawOnStun", 1)],
  },
  {
    id: "stun-mana-grant",
    keywordId: "stun",
    name: "Stun Surge",
    description: "When you Stun an enemy, gain 1 Mana",
    icon: "PlugZap",
    effects: [setEffect("manaOnStun", 1)],
  },

  {
    id: "wish-trinket",
    keywordId: "wish",
    name: "Wishful Trinket",
    description: "Gain 1 Forge or Armor when you Wish",
    icon: "Gem",
    effects: [setEffect("wishTrinketChoice", true)],
  },
  {
    id: "wish-undiscovered",
    keywordId: "wish",
    name: "Discovery",
    description: "Wish always includes an undiscovered card when one is available",
    icon: "Compass",
    effects: [setEffect("wishUndiscoveredCards", true)],
  },
  {
    id: "wish-health",
    keywordId: "wish",
    name: "Vital Wish",
    description: "Restore 2 Health when you Wish",
    icon: "Heart",
    effects: [setEffect("healthOnWish", 2)],
  },
  {
    id: "wish-cleanse",
    keywordId: "wish",
    name: "Purifying Wish",
    description: "Cleanse 1 harmful status effect when you Wish",
    icon: "Sparkle",
    effects: [setEffect("removeHarmfulStatusOnWish", true)],
  },
  {
    id: "wish-extra-choice",
    keywordId: "wish",
    name: "Generous Wish",
    description: "Wish offers 1 additional card choice",
    icon: "Gift",
    effects: [setEffect("wishExtraChoices", 1)],
  },
  {
    id: "wish-draw",
    keywordId: "wish",
    name: "Insight",
    description: "Wish also draws a card",
    icon: "Eye",
    effects: [setEffect("wishDrawsCard", true)],
  },
  {
    id: "wish-powerful",
    keywordId: "wish",
    name: "Powerful Wish",
    description: "Wish card numeric values are increased by 1",
    icon: "Bolt",
    effects: [setEffect("wishCardsUpgraded", true)],
  },
  {
    id: "wish-mana",
    keywordId: "wish",
    name: "Mana from Heaven",
    description: "When you Wish, gain 1 additional Mana at the start of your next turn",
    icon: "CloudRain",
    effects: [addEffect("manaNextTurnOnWish", 1)],
  },
  {
    id: "wish-gold",
    keywordId: "wish",
    name: "Roads Not Taken",
    description: "When you choose a Wish card, gain 1 Block for each other card offered",
    icon: "Coins",
    effects: [setEffect("blockPerDeclinedWishCard", 1)],
  },
  {
    id: "wish-desperate",
    keywordId: "wish",
    name: "Desperate Wish",
    description: "Gain 6 Block when you Wish below 30% Health",
    icon: "HeartCrack",
    effects: [setEffect("wishBlockBelowHealthPct", 30), setEffect("wishBlockAmount", 6)],
  },
];

export const talentById: ReadonlyMap<string, TalentDefinition> = new Map(
  talentPool.map((talent) => [talent.id, talent]),
);

export function getTalentById(talentId: string): TalentDefinition | undefined {
  return talentById.get(talentId);
}

export const talentPoolByKeyword: ReadonlyMap<KeywordId, TalentDefinition[]> = talentPool.reduce<
  Map<KeywordId, TalentDefinition[]>
>((acc, talent) => {
  const bucket = acc.get(talent.keywordId);
  if (bucket) bucket.push(talent);
  else acc.set(talent.keywordId, [talent]);
  return acc;
}, new Map());

export function getTalentsForKeyword(keywordId: KeywordId): TalentDefinition[] {
  return talentPoolByKeyword.get(keywordId) ?? [];
}
