import { MANABURN_DAMAGE_PERCENT } from "@/lib/game-constants";
import type { TalentDefinition } from "./types";
import { addEffect, setEffect } from "./types";
import type { KeywordId } from "../types";

export const talentPool: TalentDefinition[] = [
  {
    id: "archery-damage",
    keywordId: "archery",
    name: "Arrow Dance",
    description: "When you Dodge, your next Archery card is free",
    icon: "Move",
    effects: [setEffect("nextArcheryCardFreeOnDodge", true)],
  },
  {
    id: "archery-hail",
    keywordId: "archery",
    name: "Hail of Arrows",
    description: "Archery cards have a 10% chance to deal 50% of their damage a second time",
    icon: "CloudRain",
    effects: [setEffect("archeryPlayTwiceChance", 10)],
  },
  {
    id: "archery-eagle-eye",
    keywordId: "archery",
    name: "Eagle Eye",
    description: "Archery cards deal double damage against Stunned enemies",
    icon: "Eye",
    effects: [setEffect("archeryDoubledVsStunned", true)],
  },
  {
    id: "archery-hawk-eye",
    keywordId: "archery",
    name: "Hawk Eye",
    description: "Archery cards deal double damage against Frozen enemies",
    icon: "ScanEye",
    effects: [setEffect("archeryDoubledVsFrozen", true)],
  },
  {
    id: "archery-longshot",
    keywordId: "archery",
    name: "Longshot",
    description: "Archery cards deal double damage against enemies above 75% Health",
    icon: "ArrowRight",
    effects: [setEffect("archeryDoubledVsHighHealth", true)],
  },
  {
    id: "archery-piercing-shot",
    keywordId: "archery",
    name: "Piercing Shot",
    description: "Archery cards ignore 1 Armor",
    icon: "Aperture",
    effects: [addEffect("archeryArmorPiercing", 1)],
  },
  {
    id: "archery-quickdraw",
    keywordId: "archery",
    name: "Quickdraw",
    description: "Your first Archery card each combat is free",
    icon: "Zap",
    effects: [setEffect("firstArcheryCardFree", true)],
  },
  {
    id: "archery-kill-shot",
    keywordId: "archery",
    name: "Kill Shot",
    description: "Archery cards deal double damage against enemies below 30% Health",
    icon: "Crosshair",
    effects: [setEffect("archeryDoubledVsLowHealth", true)],
  },
  {
    id: "archery-broadhead",
    keywordId: "archery",
    name: "Broadhead",
    description: "Archery cards have a 10% chance to Bleed",
    icon: "Diamond",
    effects: [setEffect("archeryBleedChance", 10)],
  },
  {
    id: "archery-trophy-shot",
    keywordId: "archery",
    name: "Trophy Shot",
    description: "Gain 2 Gold when an Archery card defeats an enemy",
    icon: "Award",
    effects: [setEffect("goldOnArcheryKill", 2)],
  },

  {
    id: "armor-desperate-double",
    keywordId: "armor",
    name: "Last Stand",
    description: "Armor gained is doubled when Health is below 50%",
    icon: "HeartCrack",
    effects: [setEffect("armorDoubledBelowHalfHealth", true)],
  },
  {
    id: "armor-block-burst",
    keywordId: "armor",
    name: "Armored Surge",
    description: "When you reach 4 Armor, gain 8 Block",
    icon: "Shield",
    effects: [setEffect("armorBlockThreshold", 4), setEffect("armorBlockAmount", 8)],
  },
  {
    id: "armor-burn-mitigate",
    keywordId: "armor",
    name: "Fireward",
    description: "Armor now mitigates Burn damage taken",
    icon: "Flame",
    effects: [setEffect("armorMitigatesBurn", true)],
  },
  {
    id: "armor-break-block",
    keywordId: "armor",
    name: "Reactive Guard",
    description: "When Armor breaks, gain 5 Block",
    icon: "ShieldPlus",
    effects: [setEffect("armorBreakBlock", 5)],
  },
  {
    id: "armor-start-combat",
    keywordId: "armor",
    name: "Bulwark",
    description: "Start each combat with 2 Armor",
    icon: "Square",
    effects: [setEffect("startArmor", 2)],
  },
  {
    id: "armor-mitigate-bleed",
    keywordId: "armor",
    name: "Thick Hide",
    description: "Armor now mitigates Bleed damage taken",
    icon: "Hexagon",
    effects: [setEffect("armorMitigatesBleed", true)],
  },
  {
    id: "armor-first-double",
    keywordId: "armor",
    name: "Iron Guard",
    description: "Your first Armor card each combat is doubled",
    icon: "Lock",
    effects: [setEffect("firstArmorCardDoubled", true)],
  },
  {
    id: "armor-mitigate-stun",
    keywordId: "armor",
    name: "Steadfast",
    description: "When Health falls below 50%, gain 5 Armor",
    icon: "Anchor",
    effects: [setEffect("healthThresholdArmor", [{ threshold: 50, amount: 5 }])],
  },
  {
    id: "armor-cleanse-threshold",
    keywordId: "armor",
    name: "Purification",
    description: "When you reach 6 Armor, cleanse all harmful status effects",
    icon: "Sparkles",
    effects: [setEffect("armorCleanseThreshold", 6)],
  },
  {
    id: "armor-flat-bonus",
    keywordId: "armor",
    name: "Reinforced",
    description: "Increase Armor gained by 1",
    icon: "Plus",
    effects: [addEffect("flatArmorAmount", 1)],
  },

  {
    id: "bleed-first-free",
    keywordId: "bleed",
    name: "First Blood",
    description: "Your first Bleed card each combat is free",
    icon: "Swords",
    effects: [setEffect("firstBleedCardFree", true)],
  },
  {
    id: "bleed-physical-bonus",
    keywordId: "bleed",
    name: "Parting Cut",
    description: "After you Dodge, your next Physical card deals Bleed damage equal to its damage",
    icon: "Slash",
    effects: [setEffect("partingCutOnDodge", true)],
  },
  {
    id: "bleed-leech-chance",
    keywordId: "bleed",
    name: "Sanguine",
    description: "Bleed has a 15% chance to Leech",
    icon: "HeartPulse",
    effects: [setEffect("bleedLeechChance", 15)],
  },
  {
    id: "bleed-enemy-weak",
    keywordId: "bleed",
    name: "Mortal Wound",
    description: "Bleed reduces enemy healing by half",
    icon: "Bone",
    effects: [setEffect("bleedHalvesEnemyHealing", true)],
  },
  {
    id: "bleed-wound-care",
    keywordId: "bleed",
    name: "Wound Care",
    description: "Receive half Bleed damage",
    icon: "Bandage",
    effects: [setEffect("receiveHalfBleedDamage", true)],
  },
  {
    id: "bleed-execute",
    keywordId: "bleed",
    name: "Flay",
    description: "Bleed damage has a 20% chance to halve enemy Armor",
    icon: "Scissors",
    effects: [setEffect("bleedHalveArmorChance", 20)],
  },
  {
    id: "bleed-desperate",
    keywordId: "bleed",
    name: "Bleeding Out",
    description: "You deal 50% more Bleed damage while below 50% Health",
    icon: "HeartCrack",
    effects: [setEffect("bleedDesperateMultiplier", 1.5)],
  },
  {
    id: "bleed-poison-chance",
    keywordId: "bleed",
    name: "Tainted Wound",
    description: "Bleed has a 10% chance to Poison",
    icon: "FlaskConical",
    effects: [setEffect("bleedPoisonChance", 10)],
  },
  {
    id: "bleed-septic-shock",
    keywordId: "bleed",
    name: "Septic Shock",
    description: "Bleed increases Poison damage taken by 1",
    icon: "TriangleAlert",
    effects: [setEffect("bleedPoisonDamageTakenBonus", 1)],
  },
  {
    id: "bleed-rip-and-tear",
    keywordId: "bleed",
    name: "Rip and Tear",
    description: "Companion Bleed damage is increased by 1",
    icon: "Scissors",
    effects: [addEffect("companionBleedDamageBonus", 1)],
  },

  {
    id: "block-depleted-heal",
    keywordId: "block",
    name: "Second Wind",
    description: "When Block is depleted, restore 2 Health",
    icon: "Wind",
    effects: [setEffect("blockDepletedHeal", 2)],
  },
  {
    id: "block-absorb-physical",
    keywordId: "block",
    name: "Reinforce",
    description: "Block absorbs 20% more Physical damage",
    icon: "ShieldCheck",
    effects: [setEffect("blockAbsorbPhysicalBonus", 20)],
  },
  {
    id: "block-to-holy",
    keywordId: "block",
    name: "Sacred Shield",
    description: "Increase Holy damage by half your Block",
    icon: "Sun",
    effects: [setEffect("blockToHolyDamage", true)],
  },
  {
    id: "block-to-stun",
    keywordId: "block",
    name: "Impact Guard",
    description: "Stun damage is increased by 30% of your Block",
    icon: "Zap",
    effects: [setEffect("blockToStunDamage", true)],
  },
  {
    id: "block-prevent-stun",
    keywordId: "block",
    name: "Grounding",
    description: "Block prevents receiving Stun buildup",
    icon: "Anchor",
    effects: [setEffect("blockPreventsStun", true)],
  },
  {
    id: "block-to-physical",
    keywordId: "block",
    name: "Weighted Guard",
    description: "Physical damage is increased by 30% of your Block",
    icon: "Weight",
    effects: [addEffect("blockToPhysicalDamageMultiplier", 0.3)],
  },
  {
    id: "block-reduce-burn",
    keywordId: "block",
    name: "Fireproof",
    description: "Block reduces Burn damage by 1",
    icon: "Flame",
    effects: [setEffect("blockReduceBurnDamage", 1)],
  },
  {
    id: "block-start",
    keywordId: "block",
    name: "Footwork",
    description: "When you Dodge, gain Block equal to the dodged attack",
    icon: "ChevronsUp",
    effects: [setEffect("blockOnDodgeEqualToAttack", true)],
  },
  {
    id: "block-prevent-bleed",
    keywordId: "block",
    name: "Coagulate",
    description: "Block prevents receiving Bleed status effects",
    icon: "Droplets",
    effects: [setEffect("blockPreventsBleed", true)],
  },
  {
    id: "block-prevent-poison",
    keywordId: "block",
    name: "Detoxify",
    description: "Block prevents receiving Poison status effects",
    icon: "FlaskConical",
    effects: [setEffect("blockPreventsPoison", true)],
  },

  {
    id: "burn-dmg-1",
    keywordId: "burn",
    name: "Flashpoint",
    description: "Increase Burn damage by 1",
    icon: "Thermometer",
    effects: [addEffect("flatBurnDamage", 1)],
  },
  {
    id: "burn-dmg-2",
    keywordId: "burn",
    name: "Thermal Vent",
    description: "When you deal Burn damage, gain 1 Forge",
    icon: "WavesArrowUp",
    effects: [addEffect("forgeOnBurnDealt", 1)],
  },
  {
    id: "burn-dmg-5",
    keywordId: "burn",
    name: "Flaming Shield",
    description: "Burn damage is increased by 10% of your Block",
    icon: "Shield",
    effects: [setEffect("blockToBurnDamage", true)],
  },
  {
    id: "burn-dmg-4",
    keywordId: "burn",
    name: "Combustible",
    description: "Cards with Consume deal 20% more Burn damage",
    icon: "Bomb",
    effects: [setEffect("consumeBurnDamageBonusPercent", 20)],
  },
  {
    id: "burn-first-double",
    keywordId: "burn",
    name: "Wildfire",
    description: "Your first Burn card each combat deals 50% more damage",
    icon: "TrendingUp",
    effects: [setEffect("firstBurnCardBonusMultiplier", 1.5)],
  },
  {
    id: "burn-remove-armor",
    keywordId: "burn",
    name: "Melting Point",
    description: "Burn damage removes that amount of enemy Armor",
    icon: "Droplets",
    effects: [setEffect("burnRemovesEnemyArmor", true)],
  },
  {
    id: "burn-dmg-3",
    keywordId: "burn",
    name: "Heat Exhaustion",
    description: "Burn damage has a 10% chance to deal Stun damage",
    icon: "TrendingDown",
    effects: [setEffect("burnStunChance", 10)],
  },
  {
    id: "burn-dmg-6",
    keywordId: "burn",
    name: "Burning Wish",
    description: "When you play a Wish, deal 2 Burn damage to the enemy",
    icon: "Sparkles",
    effects: [setEffect("burnOnWish", 2)],
  },
  {
    id: "burn-double-chance",
    keywordId: "burn",
    name: "Smoldering",
    description: "Burn stacks have a 5% chance to double instead of halve",
    icon: "Wind",
    effects: [setEffect("burnDoubleChance", 5)],
  },
  {
    id: "burn-half-damage",
    keywordId: "burn",
    name: "Fire Resistance",
    description: "Receive half Burn damage",
    icon: "ShieldCheck",
    effects: [setEffect("receiveHalfBurnDamage", true)],
  },

  {
    id: "companion-damage",
    keywordId: "companion",
    name: "Feral Strength",
    description: "Increase Companion damage by 1",
    icon: "Bone",
    effects: [addEffect("companionDamage", 1)],
  },
  {
    id: "companion-gold-find",
    keywordId: "companion",
    name: "Scavenger",
    description: "Companions sometimes find Gold after combat",
    icon: "Trash",
    effects: [setEffect("companionGoldFindActive", true)],
  },
  {
    id: "companion-leech",
    keywordId: "companion",
    name: "Leech Companion",
    description: "Companions have a 10% chance to Leech",
    icon: "HeartPulse",
    effects: [setEffect("companionLeechChance", 10)],
  },
  {
    id: "companion-hunters-bond",
    keywordId: "companion",
    name: "Hunter's Bond",
    description: "When you play a Companion card, draw a card",
    icon: "Link2",
    effects: [setEffect("drawOnCompanionCard", 1)],
  },
  {
    id: "companion-predator-instinct",
    keywordId: "companion",
    name: "Predator's Instinct",
    description: "Companions deal double damage against enemies below 30% Health",
    icon: "Eye",
    effects: [setEffect("companionDoubledVsLowHealth", true)],
  },
  {
    id: "companion-tame",
    keywordId: "companion",
    name: "Tame",
    description: "Companions deal 1 additional damage each turn",
    icon: "Hand",
    effects: [addEffect("companionDamage", 1)],
  },
  {
    id: "companion-loyal",
    keywordId: "companion",
    name: "Pack Weave",
    description: "When you Dodge, your Companion attacks",
    icon: "PawPrint",
    effects: [setEffect("companionAttacksOnDodge", true)],
  },
  {
    id: "companion-watchdog",
    keywordId: "companion",
    name: "Watchdog",
    description: "When your Companion deals damage, gain 2 Block",
    icon: "ShieldAlert",
    effects: [setEffect("blockOnCompanionDamage", 2)],
  },
  {
    id: "companion-takedown",
    keywordId: "companion",
    name: "Takedown",
    description: "Companion damage has a 10% chance to deal Stun damage",
    icon: "Ban",
    effects: [setEffect("companionStunChance", 10)],
  },
  {
    id: "companion-whistle",
    keywordId: "companion",
    name: "Whistle",
    description: "Your first Companion card each combat is free",
    icon: "Bell",
    effects: [setEffect("firstCompanionCardFree", true)],
  },

  {
    id: "consume-gourmand",
    keywordId: "consume",
    name: "Gourmand",
    description: "Consume cards heal 20% more",
    icon: "Apple",
    effects: [setEffect("consumeHealMultiplier", 0.2)],
  },
  {
    id: "consume-last-supper",
    keywordId: "consume",
    name: "Last Supper",
    description: "Your first Consume card each combat is free",
    icon: "Gift",
    effects: [setEffect("firstConsumeCardFree", true)],
  },
  {
    id: "consume-volatility",
    keywordId: "consume",
    name: "Volatility",
    description: "Consume cards deal 20% more damage",
    icon: "Flame",
    effects: [setEffect("consumeDamageBonusPercent", 20)],
  },
  {
    id: "consume-distillation",
    keywordId: "consume",
    name: "Distillation",
    description: "Potions are 20% more potent",
    icon: "FlaskConical",
    effects: [addEffect("potionPotency", 0.2)],
  },
  {
    id: "consume-brewmaster",
    keywordId: "consume",
    name: "Brewmaster",
    description: "Mixed Potion potency is increased by 1",
    icon: "Wine",
    effects: [addEffect("potionMixPotency", 1)],
  },
  {
    id: "consume-aftertaste",
    keywordId: "consume",
    name: "Aftertaste",
    description: "When you Consume a card, restore 1 Health",
    icon: "Cookie",
    effects: [setEffect("healOnConsume", 1)],
  },
  {
    id: "consume-leftovers",
    keywordId: "consume",
    name: "Leftovers",
    description: "When you Consume a card, gain 1 Gold",
    icon: "Package",
    effects: [setEffect("goldOnConsume", 1)],
  },
  {
    id: "consume-second-helping",
    keywordId: "consume",
    name: "Second Helping",
    description: "Once per turn, when you Consume a card, draw a card",
    icon: "CopyPlus",
    effects: [setEffect("drawOnConsume", 1)],
  },
  {
    id: "consume-rotgut",
    keywordId: "consume",
    name: "Rotgut",
    description: "When you Consume a card, apply 1 Poison",
    icon: "FlaskRound",
    effects: [setEffect("poisonOnConsume", 1)],
  },
  {
    id: "consume-feast",
    keywordId: "consume",
    name: "Feast",
    description: "When you Consume a card, gain 2 Block",
    icon: "CookingPot",
    effects: [setEffect("blockOnConsume", 2)],
  },

  {
    id: "forge-to-burn",
    keywordId: "forge",
    name: "Ignite",
    description: "Forge also increases Burn damage",
    icon: "Flame",
    effects: [setEffect("forgeToBurn", true)],
  },
  {
    id: "forge-to-holy",
    keywordId: "forge",
    name: "Sanctify",
    description: "Forge also increases Holy damage",
    icon: "Sun",
    effects: [setEffect("forgeToHoly", true)],
  },
  {
    id: "forge-to-block",
    keywordId: "forge",
    name: "Tempered Guard",
    description: "Forge also increases Block amount",
    icon: "Shield",
    effects: [setEffect("forgeToBlock", true)],
  },
  {
    id: "forge-burn-burst",
    keywordId: "forge",
    name: "Overheat",
    description: "When you reach 4 Forge, deal 8 Burn",
    icon: "Thermometer",
    effects: [setEffect("forgeBurnThreshold", 4), setEffect("forgeBurnDamage", 8)],
  },
  {
    id: "forge-strength-1",
    keywordId: "forge",
    name: "Forge Mastery",
    description: "Start each combat with 1 Forge",
    icon: "FlameKindling",
    effects: [setEffect("startForge", 1)],
  },
  {
    id: "forge-strength-2",
    keywordId: "forge",
    name: "Rust",
    description: "Forge also increases Bleed damage",
    icon: "Eraser",
    effects: [setEffect("forgeToBleed", true)],
  },
  {
    id: "forge-strength-3",
    keywordId: "forge",
    name: "Sunder",
    description: "When you reach 6 Forge, remove all enemy Armor",
    icon: "ShieldOff",
    effects: [setEffect("forgeStripArmorThreshold", 6)],
  },
  {
    id: "forge-strength-4",
    keywordId: "forge",
    name: "Intensify",
    description: "Increase Forge gained by 1",
    icon: "ChevronsUp",
    effects: [addEffect("flatForgeGained", 1)],
  },
  {
    id: "forge-strength-5",
    keywordId: "forge",
    name: "Desperate Forge",
    description: "Forge gained is doubled when Health is below 50%",
    icon: "HeartCrack",
    effects: [setEffect("forgeDoubledBelowHalfHealth", true)],
  },
  {
    id: "forge-strength-6",
    keywordId: "forge",
    name: "Forged Bulwark",
    description: "When you reach 6 Forge, gain 10 Block",
    icon: "Castle",
    effects: [setEffect("forgeBlockThreshold", 6), setEffect("forgeBlockAmount", 10)],
  },

  {
    id: "freeze-threshold",
    keywordId: "freeze",
    name: "Bitter Cold",
    description: "Freeze threshold reduced by 10%",
    icon: "ThermometerSnowflake",
    effects: [setEffect("freezeThresholdReduction", 0.1)],
  },
  {
    id: "freeze-double-damage",
    keywordId: "freeze",
    name: "Shatter",
    description: "Frozen enemies take double damage",
    icon: "Split",
    effects: [setEffect("freezeDoubleDamage", true)],
  },
  {
    id: "freeze-start-amount",
    keywordId: "freeze",
    name: "Winter's Grasp",
    description: "Start each combat by dealing 4 Freeze damage",
    icon: "MountainSnow",
    effects: [setEffect("startFreeze", 4)],
  },
  {
    id: "freeze-block-grant",
    keywordId: "freeze",
    name: "Icebound",
    description: "Frozen enemies lose all Block and cannot Dodge",
    icon: "Snowflake",
    effects: [setEffect("freezeStripBlock", true), setEffect("freezePreventsEnemyDodge", true)],
  },
  {
    id: "freeze-companion-bonus",
    keywordId: "freeze",
    name: "Snow Pack",
    description: "Your Companion deals 1 additional damage to Frozen enemies",
    icon: "CloudSnow",
    effects: [addEffect("companionVsFrozenBonus", 1)],
  },
  {
    id: "freeze-strip-armor",
    keywordId: "freeze",
    name: "Brittle Armor",
    description: "Frozen enemies lose all Armor",
    icon: "ShieldOff",
    effects: [setEffect("freezeStripArmor", true)],
  },
  {
    id: "freeze-half-damage",
    keywordId: "freeze",
    name: "Cold Resistance",
    description: "Receive half Freeze damage",
    icon: "Thermometer",
    effects: [setEffect("receiveHalfFreezeDamage", true)],
  },
  {
    id: "freeze-poison-preserve",
    keywordId: "freeze",
    name: "Cryo-preservation",
    description: "Poison stacks on Frozen enemies cannot decay",
    icon: "FlaskConical",
    effects: [setEffect("freezePreventsPoisonDecay", true)],
  },
  {
    id: "freeze-prevent-scaling",
    keywordId: "freeze",
    name: "Glacial Encasement",
    description: "Frozen enemies cannot gain Forge or Armor",
    icon: "Hexagon",
    effects: [setEffect("freezePreventsEnemyScaling", true)],
  },
  {
    id: "freeze-block-healing",
    keywordId: "freeze",
    name: "Permafrost",
    description: "Frozen enemies cannot restore Health",
    icon: "Lock",
    effects: [setEffect("freezeBlocksRegen", true)],
  },

  {
    id: "gold-shop-discount",
    keywordId: "gold",
    name: "Haggle",
    description: "Shop purchases cost 5 less Gold",
    icon: "Tag",
    effects: [setEffect("shopCardDiscount", 5)],
  },
  {
    id: "gold-shop-refresh",
    keywordId: "gold",
    name: "Restock",
    description: "Shop refresh is free once per visit",
    icon: "RefreshCw",
    effects: [setEffect("shopFreeRefresh", true)],
  },
  {
    id: "gold-start",
    keywordId: "gold",
    name: "Seed Money",
    description: "Start each run with 20 Gold",
    icon: "Sprout",
    effects: [setEffect("startGold", 20)],
  },
  {
    id: "gold-per-combat",
    keywordId: "gold",
    name: "Lucky Foot",
    description: "Gain 1 Gold when you Dodge",
    icon: "CircleDollarSign",
    effects: [setEffect("goldOnDodge", 1)],
  },
  {
    id: "gold-potion-discount",
    keywordId: "gold",
    name: "Apothecary Bargain",
    description: "Potions cost 5 less Gold",
    icon: "Beaker",
    effects: [setEffect("potionDiscount", 5)],
  },
  {
    id: "gold-remove-discount",
    keywordId: "gold",
    name: "Buyout",
    description: "Card removal costs 10 less Gold",
    icon: "ShoppingCart",
    effects: [setEffect("removeCardDiscount", 10)],
  },
  {
    id: "gold-enemy-drop",
    keywordId: "gold",
    name: "Plunder",
    description: "Enemies drop 10% more Gold",
    icon: "HandCoins",
    effects: [setEffect("enemyGoldDropBonus", 0.1)],
  },
  {
    id: "gold-on-wish",
    keywordId: "gold",
    name: "Golden Wish",
    description: "Gain 3 Gold when you Wish",
    icon: "Sparkles",
    effects: [addEffect("goldOnWish", 3)],
  },
  {
    id: "gold-mix-discount",
    keywordId: "gold",
    name: "Alchemy Discount",
    description: "Mix Potions costs 10 less Gold",
    icon: "FlaskConical",
    effects: [setEffect("mixPotionDiscount", 10)],
  },
  {
    id: "gold-elite-drop",
    keywordId: "gold",
    name: "Spoils of War",
    description: "Elites drop 10% more Gold",
    icon: "Trophy",
    effects: [setEffect("eliteGoldDropBonus", 0.1)],
  },

  {
    id: "health-threshold-armor",
    keywordId: "health",
    name: "Last Resort",
    description: "When Health drops below 25%, gain 3 Armor",
    icon: "HeartCrack",
    effects: [setEffect("healthThresholdArmor", [{ threshold: 25, amount: 3 }])],
  },
  {
    id: "health-threshold-block",
    keywordId: "health",
    name: "Desperate Guard",
    description: "When Health drops below 50%, gain 6 Block",
    icon: "Shield",
    effects: [setEffect("healthThresholdBlock", { threshold: 50, amount: 6 })],
  },
  {
    id: "health-max-4",
    keywordId: "health",
    name: "Will to Live",
    description: "Death's Door lasts 1 turn longer",
    icon: "Activity",
    effects: [setEffect("deathsDoorExtension", 1)],
  },
  {
    id: "health-start",
    keywordId: "health",
    name: "Combat Surge",
    description: "Restore 4 Health at the start of combat",
    icon: "ChevronsUp",
    effects: [setEffect("startHealth", 4)],
  },
  {
    id: "health-max-per-combat",
    keywordId: "health",
    name: "Vitality",
    description: "Gain 1 Max Health after every combat",
    icon: "TrendingUp",
    effects: [setEffect("maxHealthPerCombat", 1)],
  },
  {
    id: "health-heal-boost",
    keywordId: "health",
    name: "Mending",
    description: "Healing effects are 10% stronger",
    icon: "HeartPulse",
    effects: [setEffect("healMultiplier", 1.1)],
  },
  {
    id: "health-max-1",
    keywordId: "health",
    name: "Overflow",
    description: "When you overheal, gain 50% of the excess as Block",
    icon: "Container",
    effects: [setEffect("overhealToBlockRatio", 0.5)],
  },
  {
    id: "health-max-2",
    keywordId: "health",
    name: "Cleansing Status",
    description: "Cleansing a status restores 6 Health",
    icon: "Sparkles",
    effects: [setEffect("healOnStatusCleanse", 6)],
  },
  {
    id: "health-max-3",
    keywordId: "health",
    name: "Last Gasp",
    description: "While below 50% Health, gain 20% Dodge chance",
    icon: "ShieldHalf",
    effects: [setEffect("dodgeChanceBelowHalfHealth", 20)],
  },
  {
    id: "health-campfire",
    keywordId: "health",
    name: "Warm Rest",
    description: "Campfire heals 10% more Health",
    icon: "Flame",
    effects: [setEffect("campfireHealBonus", 0.1)],
  },

  {
    id: "holy-tithe",
    keywordId: "holy",
    name: "Tithe",
    description: "10% chance to gain Gold equal to Holy damage",
    icon: "Cross",
    effects: [setEffect("holyGoldChance", 10)],
  },
  {
    id: "holy-block-scaling",
    keywordId: "holy",
    name: "Faith Barrier",
    description: "Holy damage is increased by half your Block",
    icon: "Shield",
    effects: [setEffect("blockToHolyDamage", true)],
  },
  {
    id: "holy-wish-chance",
    keywordId: "holy",
    name: "Divine Intervention",
    description: "Holy damage has a 5% chance to Wish",
    icon: "Sparkles",
    effects: [setEffect("holyWishChance", 5)],
  },
  {
    id: "holy-burn-chance",
    keywordId: "holy",
    name: "Scorching Light",
    description: "Holy damage has a 10% chance to Burn",
    icon: "Flame",
    effects: [setEffect("holyBurnChance", 10)],
  },
  {
    id: "holy-half-damage",
    keywordId: "holy",
    name: "Celestial Ward",
    description: "Receive half Holy damage",
    icon: "ShieldCheck",
    effects: [setEffect("receiveHalfHolyDamage", true)],
  },
  {
    id: "holy-first-free",
    keywordId: "holy",
    name: "Divine Favor",
    description: "Your first Holy card each combat is free",
    icon: "Gift",
    effects: [setEffect("firstHolyCardFree", true)],
  },
  {
    id: "holy-gold-scaling",
    keywordId: "holy",
    name: "Prosperity",
    description: "Holy damage is increased by 3% of your Gold",
    icon: "TrendingUp",
    effects: [setEffect("holyGoldPercent", 3)],
  },
  {
    id: "holy-block-grant",
    keywordId: "holy",
    name: "Radiant Guard",
    description: "Holy damage grants Block for 15% of the amount dealt",
    icon: "ShieldPlus",
    effects: [setEffect("holyBlockPercentFromDamage", 15)],
  },
  {
    id: "holy-vs-burn",
    keywordId: "holy",
    name: "Purge",
    description: "Holy damage is increased by 20% against Burning enemies",
    icon: "Eraser",
    effects: [setEffect("holyVsBurnMultiplier", 20)],
  },
  {
    id: "holy-lifesteal",
    keywordId: "holy",
    name: "Blessed Leech",
    description: "Holy damage heals you for 10% of the amount dealt",
    icon: "HeartPulse",
    effects: [setEffect("holyLifestealPercent", 10)],
  },

  {
    id: "leech-first-double",
    keywordId: "leech",
    name: "First Siphon",
    description: "Your first Leech card each combat heals for double",
    icon: "Sword",
    effects: [setEffect("firstLeechCardDoubled", true)],
  },
  {
    id: "leech-desperate",
    keywordId: "leech",
    name: "Desperate Siphon",
    description: "Leech is 20% more effective while below 50% Health",
    icon: "HeartCrack",
    effects: [setEffect("leechDesperateMultiplier", 20)],
  },
  {
    id: "leech-blood-debt",
    keywordId: "leech",
    name: "Blood Debt",
    description: "Leech heals for 1 more per 8 missing Health",
    icon: "CircleDollarSign",
    effects: [setEffect("leechMissingHealthStep", 8)],
  },
  {
    id: "leech-bleed-chance",
    keywordId: "leech",
    name: "Hemorrhage",
    description: "Leech has a 10% chance to Bleed",
    icon: "Droplets",
    effects: [setEffect("leechBleedChance", 10)],
  },
  {
    id: "leech-cull-weak",
    keywordId: "leech",
    name: "Cull the Weak",
    description: "Leech is 20% more effective against enemies below 50% Health",
    icon: "Skull",
    effects: [setEffect("leechExecuteMultiplier", 20)],
  },
  {
    id: "leech-mana-siphon",
    keywordId: "leech",
    name: "Mana Siphon",
    description: "Leech has a 10% chance to gain 1 Mana",
    icon: "Gem",
    effects: [setEffect("manaOnLeechChance", 10)],
  },
  {
    id: "leech-trinket-siphon",
    keywordId: "leech",
    name: "Trinket Siphon",
    description: "Leech has a 20% chance to steal 1 Forge, Armor, or Block",
    icon: "Wrench",
    effects: [setEffect("trinketSiphonChance", 20)],
  },
  {
    id: "leech-poison",
    keywordId: "leech",
    name: "Virulent Leech",
    description: "Leech has a 10% chance to Poison",
    icon: "FlaskConical",
    effects: [setEffect("leechPoisonChance", 10)],
  },
  {
    id: "leech-block-enemy",
    keywordId: "leech",
    name: "Blood Type",
    description: "Enemies cannot restore Health when they Leech",
    icon: "Hash",
    effects: [setEffect("blockEnemyLeech", true)],
  },
  {
    id: "leech-nature-chance",
    keywordId: "leech",
    name: "Carnivorous Nature",
    description: "Nature damage has a 10% chance to Leech",
    icon: "Utensils",
    effects: [addEffect("natureLeechChance", 10)],
  },

  {
    id: "mana-wellspring",
    keywordId: "mana",
    name: "Wellspring",
    description: "When you end your turn with unspent Mana, keep 1 for next turn",
    icon: "Droplets",
    effects: [setEffect("wellspringKeepMana", 1)],
  },
  {
    id: "mana-bulwark",
    keywordId: "mana",
    name: "Mana Bulwark",
    description: "Start each combat with Block equal to your Mana Crystals",
    icon: "ShieldPlus",
    effects: [setEffect("manaBulwarkActive", true)],
  },
  {
    id: "mana-leylines",
    keywordId: "mana",
    name: "Leyline Attunement",
    description: "Gain 1 Mana Crystal",
    icon: "Atom",
    effects: [setEffect("startMana", 1)],
  },
  {
    id: "mana-arcane-wish",
    keywordId: "mana",
    name: "Arcane Wish",
    description: "Gain 1 Mana when you Wish",
    icon: "Sparkles",
    effects: [addEffect("manaOnWish", 1)],
  },
  {
    id: "mana-manaburn",
    keywordId: "mana",
    name: "Manaburn",
    description: `Burn damage is increased by ${MANABURN_DAMAGE_PERCENT}% of your Mana Crystals`,
    icon: "Flame",
    effects: [setEffect("burnDamagePerManaCrystal", MANABURN_DAMAGE_PERCENT)],
  },
  {
    id: "mana-arcane-frost",
    keywordId: "mana",
    name: "Arcane Frost",
    description: "Freeze damage is increased by half your Mana Crystals",
    icon: "Snowflake",
    effects: [setEffect("freezeDamagePerManaCrystal", 1)],
  },
  {
    id: "mana-flare",
    keywordId: "mana",
    name: "Mana Flare",
    description: "When you lose a Mana Crystal, deal 3 Burn damage",
    icon: "Bomb",
    effects: [setEffect("burnDamageOnManaCrystalLoss", 3)],
  },
  {
    id: "mana-familiar-bond",
    keywordId: "mana",
    name: "Familiar Bond",
    description: "Companion damage is increased by half your Mana Crystals",
    icon: "PawPrint",
    effects: [setEffect("companionDamagePerManaCrystal", 1)],
  },
  {
    id: "mana-shell",
    keywordId: "mana",
    name: "Mana Shell",
    description: "Start each combat with Armor equal to your Mana Crystals",
    icon: "ShieldHalf",
    effects: [setEffect("manaShellActive", true)],
  },
  {
    id: "mana-arcane-mending",
    keywordId: "mana",
    name: "Arcane Mending",
    description: "Restore 2 Health when you gain Mana",
    icon: "Wand",
    effects: [setEffect("healOnManaGain", 2)],
  },

  {
    id: "nature-overgrowth",
    keywordId: "nature",
    name: "Overgrowth",
    description: "Increase Nature damage dealt by 1",
    icon: "TrendingUp",
    effects: [addEffect("flatNatureDamage", 1)],
  },
  {
    id: "nature-toxic-pollen",
    keywordId: "nature",
    name: "Toxic Pollen",
    description: "Nature damage has a 10% chance to Poison",
    icon: "Wind",
    effects: [setEffect("naturePoisonChance", 10)],
  },
  {
    id: "nature-briar-patch",
    keywordId: "nature",
    name: "Briar Patch",
    description: "Nature damage has a 10% chance to Bleed",
    icon: "Triangle",
    effects: [setEffect("natureBleedChance", 10)],
  },
  {
    id: "nature-verdant-cycle",
    keywordId: "nature",
    name: "Verdant Cycle",
    description: "Nature damage has a 10% chance to Leech",
    icon: "RotateCw",
    effects: [addEffect("natureLeechChance", 10)],
  },
  {
    id: "nature-ecosystem",
    keywordId: "nature",
    name: "Ecosystem",
    description: "Deal +1 Nature damage against Poisoned enemies",
    icon: "Network",
    effects: [setEffect("natureBonusVsPoisoned", 1)],
  },
  {
    id: "nature-natural-armor",
    keywordId: "nature",
    name: "Natural Armor",
    description: "Nature damage taken is reduced by half",
    icon: "Shield",
    effects: [setEffect("receiveHalfNatureDamage", true)],
  },
  {
    id: "nature-entangle",
    keywordId: "nature",
    name: "Entangle",
    description: "Nature damage has a 10% chance to deal Stun damage",
    icon: "Link",
    effects: [setEffect("natureStunChance", 10)],
  },
  {
    id: "nature-thornskin",
    keywordId: "nature",
    name: "Thornskin",
    description: "Nature damage is increased by your Armor",
    icon: "Hexagon",
    effects: [setEffect("armorToNatureDamage", true)],
  },
  {
    id: "nature-canopy",
    keywordId: "nature",
    name: "Windstep",
    description: "When you Dodge, your next Nature card is free",
    icon: "Feather",
    effects: [setEffect("nextNatureCardFreeOnDodge", true)],
  },
  {
    id: "nature-photosynthesis",
    keywordId: "nature",
    name: "Photosynthesis",
    description: "Restore 1 Health when you play a Nature card",
    icon: "Leaf",
    effects: [setEffect("healOnNatureCard", 1)],
  },

  {
    id: "physical-expert-blacksmith",
    keywordId: "physical",
    name: "Expert Blacksmith",
    description: "Physical damage bonus from Forge is increased by 50%",
    icon: "Anvil",
    effects: [setEffect("forgeToPhysicalDamageMultiplier", 1.5)],
  },
  {
    id: "physical-shield-bash",
    keywordId: "physical",
    name: "Shield Bash",
    description: "Physical damage is increased by 30% of your Block",
    icon: "Shield",
    effects: [addEffect("blockToPhysicalDamageMultiplier", 0.3)],
  },
  {
    id: "physical-armored-fists",
    keywordId: "physical",
    name: "Armored Fists",
    description: "Physical damage is increased by your Armor",
    icon: "HandFist",
    effects: [setEffect("armorToPhysicalDamage", true)],
  },
  {
    id: "physical-heavy-blows",
    keywordId: "physical",
    name: "Heavy Blows",
    description: "Physical damage has a 10% chance to deal Stun damage",
    icon: "Hammer",
    effects: [setEffect("physicalStunChance", 10)],
  },
  {
    id: "physical-finish-him",
    keywordId: "physical",
    name: "Finish Him",
    description: "Physical damage is doubled against Stunned enemies",
    icon: "Skull",
    effects: [setEffect("physicalDoubledVsStunned", true)],
  },
  {
    id: "physical-shatter",
    keywordId: "physical",
    name: "Shatter",
    description: "Physical damage is doubled against Frozen enemies",
    icon: "Split",
    effects: [setEffect("physicalDoubledVsFrozen", true)],
  },
  {
    id: "physical-lacerate",
    keywordId: "physical",
    name: "Lacerate",
    description: "Physical damage has a 10% chance to Bleed",
    icon: "Scissors",
    effects: [setEffect("physicalBleedChance", 10)],
  },
  {
    id: "physical-hemorrhage",
    keywordId: "physical",
    name: "Hemorrhage",
    description: "Physical damage detonates Bleed",
    icon: "Droplets",
    effects: [setEffect("physicalDetonatesBleed", true)],
  },
  {
    id: "physical-brute-force",
    keywordId: "physical",
    name: "Riposte",
    description: "When you Dodge, deal Physical damage equal to the dodged attack",
    icon: "Swords",
    effects: [setEffect("physicalOnDodgeEqualToAttack", true)],
  },
  {
    id: "physical-unrelenting",
    keywordId: "physical",
    name: "Unrelenting",
    description: "You deal double Physical damage while below 50% Health",
    icon: "ShieldCheck",
    effects: [setEffect("physicalDoubledBelowHalfHealth", true)],
  },

  {
    id: "poison-leech-chance",
    keywordId: "poison",
    name: "Hemotoxin",
    description: "Poison has a 10% chance to Leech",
    icon: "Biohazard",
    effects: [setEffect("poisonLeechChance", 10)],
  },
  {
    id: "poison-physical-bonus",
    keywordId: "poison",
    name: "Corrosive",
    description: "Poisoned enemies take +1 Physical damage",
    icon: "Droplets",
    effects: [setEffect("poisonPhysicalBonus", 1)],
  },
  {
    id: "poison-strip-armor",
    keywordId: "poison",
    name: "Caustic",
    description: "Poison removes 1 Armor",
    icon: "FlaskRound",
    effects: [setEffect("poisonStripArmor", true)],
  },
  {
    id: "poison-half-damage",
    keywordId: "poison",
    name: "Toxin Resistance",
    description: "Receive half Poison damage",
    icon: "Shield",
    effects: [setEffect("receiveHalfPoisonDamage", true)],
  },
  {
    id: "poison-gold-first",
    keywordId: "poison",
    name: "Toxic Profit",
    description: "The first time you Poison each combat, gain 4 Gold",
    icon: "Coins",
    effects: [setEffect("goldOnFirstPoison", 4)],
  },
  {
    id: "poison-heal-reduce",
    keywordId: "poison",
    name: "Necrosis",
    description: "Poison reduces enemy healing by half",
    icon: "Skull",
    effects: [setEffect("poisonHalvesHealing", true)],
  },
  {
    id: "poison-stun-chance",
    keywordId: "poison",
    name: "Paralytic Venom",
    description: "Poison damage and ticks have a 10% chance to deal Stun damage",
    icon: "Lock",
    effects: [setEffect("poisonStunChance", 10)],
  },
  {
    id: "poison-gain-chance",
    keywordId: "poison",
    name: "Virulent",
    description: "Poison has a 10% chance to gain instead of lose a stack",
    icon: "TrendingUp",
    effects: [setEffect("poisonGainChance", 10)],
  },
  {
    id: "poison-reduce-damage",
    keywordId: "poison",
    name: "Torpor",
    description: "Poisoned enemies cannot Dodge",
    icon: "Moon",
    effects: [setEffect("poisonPreventsEnemyDodge", true)],
  },
  {
    id: "poison-first-free",
    keywordId: "poison",
    name: "Venom Strike",
    description: "Your first Poison card each combat is free",
    icon: "Syringe",
    effects: [setEffect("firstPoisonCardFree", true)],
  },

  {
    id: "stun-forge-grant",
    keywordId: "stun",
    name: "Riled Up",
    description: "When you Stun an enemy, gain 2 Forge",
    icon: "Flame",
    effects: [setEffect("forgeOnStun", 2)],
  },
  {
    id: "stun-double-damage",
    keywordId: "stun",
    name: "Exploit Weakness",
    description: "Stunned enemies take double damage",
    icon: "TrendingUp",
    effects: [setEffect("stunDoubleDamage", true)],
  },
  {
    id: "stun-block-grant",
    keywordId: "stun",
    name: "Guarded Counter",
    description: "When you Stun an enemy, gain 3 Block",
    icon: "Shield",
    effects: [setEffect("blockOnStun", 3)],
  },
  {
    id: "stun-duration-1",
    keywordId: "stun",
    name: "Extended Stun",
    description: "Stun effects last 1 turn longer",
    icon: "Clock",
    effects: [setEffect("stunDurationExtension", 1)],
  },
  {
    id: "stun-strip-armor",
    keywordId: "stun",
    name: "Shatter Guard",
    description: "Stunned enemies lose all Armor",
    icon: "ShieldOff",
    effects: [setEffect("stunStripArmor", true)],
  },
  {
    id: "stun-damage-1",
    keywordId: "stun",
    name: "Jarring Blow",
    description: "Increase Stun damage by 1",
    icon: "Bolt",
    effects: [addEffect("flatStunDamage", 1)],
  },
  {
    id: "stun-next-free",
    keywordId: "stun",
    name: "Free Follow-up",
    description: "When you Stun an enemy, your next card is free",
    icon: "Gift",
    effects: [setEffect("nextCardFreeOnStun", true)],
  },
  {
    id: "stun-threshold",
    keywordId: "stun",
    name: "Concussive Force",
    description: "Stun threshold reduced by 10%",
    icon: "Waves",
    effects: [setEffect("stunThresholdReduction", 0.1)],
  },
  {
    id: "stun-draw",
    keywordId: "stun",
    name: "Stun Insight",
    description: "When you Stun an enemy, draw a card",
    icon: "Eye",
    effects: [setEffect("drawOnStun", 1)],
  },
  {
    id: "stun-mana-grant",
    keywordId: "stun",
    name: "Stun Surge",
    description: "When you Stun an enemy, gain 1 Mana",
    icon: "PlugZap",
    effects: [setEffect("manaOnStun", 1)],
  },

  {
    id: "wish-trinket",
    keywordId: "wish",
    name: "Wishful Trinket",
    description: "Gain 1 Forge or Armor when you Wish",
    icon: "Gem",
    effects: [setEffect("wishTrinketChoice", true)],
  },
  {
    id: "wish-undiscovered",
    keywordId: "wish",
    name: "Discovery",
    description: "Wish can offer cards not yet in your collection",
    icon: "Compass",
    effects: [setEffect("wishUndiscoveredCards", true)],
  },
  {
    id: "wish-health",
    keywordId: "wish",
    name: "Vital Wish",
    description: "Gain 2 Health when you Wish",
    icon: "Heart",
    effects: [setEffect("healthOnWish", 2)],
  },
  {
    id: "wish-cleanse",
    keywordId: "wish",
    name: "Purifying Wish",
    description: "Cleanse a harmful status effect when you Wish",
    icon: "Sparkle",
    effects: [setEffect("removeHarmfulStatusOnWish", true)],
  },
  {
    id: "wish-extra-choice",
    keywordId: "wish",
    name: "Generous Wish",
    description: "Wish has a 20% chance to offer an extra card choice",
    icon: "Gift",
    effects: [setEffect("wishExtraChoiceChance", 20)],
  },
  {
    id: "wish-draw",
    keywordId: "wish",
    name: "Insight",
    description: "Wish also draws a card",
    icon: "Eye",
    effects: [setEffect("wishDrawsCard", true)],
  },
  {
    id: "wish-powerful",
    keywordId: "wish",
    name: "Powerful Wish",
    description: "Wish card numeric values are increased by 1",
    icon: "Bolt",
    effects: [setEffect("wishCardsUpgraded", true)],
  },
  {
    id: "wish-mana",
    keywordId: "wish",
    name: "Mana from Heaven",
    description: "Gain 1 Mana when you Wish",
    icon: "CloudRain",
    effects: [addEffect("manaOnWish", 1)],
  },
  {
    id: "wish-gold",
    keywordId: "wish",
    name: "Golden Opportunity",
    description: "Gain 2 Gold when you Wish",
    icon: "Coins",
    effects: [addEffect("goldOnWish", 2)],
  },
  {
    id: "wish-desperate",
    keywordId: "wish",
    name: "Desperate Wish",
    description: "Gain 6 Block when you Wish below 30% Health",
    icon: "HeartCrack",
    effects: [setEffect("wishBlockBelowHealthPct", 30), setEffect("wishBlockAmount", 6)],
  },
];

export const talentById: ReadonlyMap<string, TalentDefinition> = new Map(
  talentPool.map((talent) => [talent.id, talent]),
);

export function getTalentById(talentId: string): TalentDefinition | undefined {
  return talentById.get(talentId);
}

export const talentPoolByKeyword: ReadonlyMap<KeywordId, TalentDefinition[]> = talentPool.reduce<
  Map<KeywordId, TalentDefinition[]>
>((acc, talent) => {
  const bucket = acc.get(talent.keywordId);
  if (bucket) bucket.push(talent);
  else acc.set(talent.keywordId, [talent]);
  return acc;
}, new Map());

export function getTalentsForKeyword(keywordId: KeywordId): TalentDefinition[] {
  return talentPoolByKeyword.get(keywordId) ?? [];
}
