import { describe, expect, it } from "vitest";
import * as writePort from "@/features/alchemy/shared/stores/run-session-write-port";
import * as lifecyclePort from "@/features/alchemy/shared/stores/run-session-lifecycle-port";

const WRITE_PORT_EXPORTS = [
  "abandonCorruptionDestinationVisit",
  "abandonMysteryDestinationVisit",
  "addMaterials",
  "addRunGold",
  "addRunMaterialsEarned",
  "applyRunStartSnapshot",
  "awardCardXP",
  "awardMaterialsDuringRun",
  "awardMysteryXP",
  "beginBattleTransition",
  "beginDestinationClaim",
  "beginRewardClaim",
  "bondCompanion",
  "cancelDestinationClaim",
  "clearBattleTransition",
  "clearMysteryVisitState",
  "clearRunMaterialsEarned",
  "clearShopOfferings",
  "clearTransientSession",
  "commitBattleTransition",
  "commitDestinationClaim",
  "completeResearch",
  "constructBuilding",
  "createDraftRunRandomSource",
  "withDraftWorldBattleRng",
  "withRestingEndPlayerTurnResolution",
  "withRestingWorldBattleRng",
  "finalizeRunXP",
  "initializeActiveBattle",
  "plantFarm",
  "releaseRewardClaim",
  "resetUnlockedTalents",
  "setActiveLabyrinthModifiers",
  "setActiveLabyrinthPendingNode",
  "setActiveLabyrinthRewardModifiers",
  "setAlchemistState",
  "setBattleStartState",
  "setBattleState",
  "setCompanionRewardCards",
  "setCompletedDestinations",
  "setContentSystemType",
  "setCorruptionResult",
  "setCurrentAct",
  "setDestinationIndexInAct",
  "setDestinationOfferState",
  "setEncounteredRunEnemyIds",
  "setEquipmentShopState",
  "setHasActiveBattle",
  "setLabyrinthMap",
  "setMaterials",
  "setMysteryCardChoices",
  "setMysteryChosenCardId",
  "setMysteryChosenChoice",
  "setMysteryEvent",
  "setMysteryGrantedGearInstances",
  "setMysteryGrantedTrinketIds",
  "setMysteryPendingRemoval",
  "setPendingCharacterId",
  "setPendingContentSystemType",
  "setRewardState",
  "setRoomsEncountered",
  "setRunDeck",
  "setRunEndMaterials",
  "setRunGold",
  "setRunMaxHealth",
  "setRunPlayerHealth",
  "setRunTrinkets",
  "setScreen",
  "setShopState",
  "setStarterDraftChoices",
  "setTrinketShopState",
  "setWildwoodDraft",
  "unlockAllTalents",
  "unlockTalent",
] as const;

const LIFECYCLE_PORT_EXPORTS = [
  "applyRunDefeatTeardown",
  "clearBattlePresentationUi",
  "clearBattleUi",
  "finalizeRunEndSession",
  "flushSaveAfterGearMutation",
  "hydrateModeRunInDraft",
  "onClearBattlePresentation",
  "onRunTeardown",
  "resolveActiveRunForSave",
  "restoreRun",
  "snapshotRun",
  "syncBattleToRun",
  "syncRunMaxHealthFromGearMutation",
  "syncRunToBattleStart",
  "teardownRun",
] as const;

describe("session port export inventory", () => {
  it("keeps the write-port public surface intact", () => {
    expect(Object.keys(writePort).sort()).toEqual([...WRITE_PORT_EXPORTS].sort());
  });

  it("keeps the lifecycle-port public surface intact", () => {
    expect(Object.keys(lifecyclePort).sort()).toEqual([...LIFECYCLE_PORT_EXPORTS].sort());
  });
});
