export const INVENTORY_SNAP_RADIUS_CELLS = 0.28;
export const MAGNET_SWITCH_MARGIN_PX = 14;
export const MAGNET_RELEASE_HYSTERESIS_PX = 18;
export const DOUBLE_CLICK_FLYOVER_MS = 280;
export const MAGNET_RELEASE_EASE_MS = 140;
export const DRAG_POINTER_ACTIVATE_DISTANCE_PX = 4;
export const EQUIPMENT_SNAP_INSET_RATIO = 0.3;
