// Public gameplay write capability for feature code.
// Domain mutators live in write-port-*.ts; import from this barrel only.
// Every export is an explicit draft-first mutator. Event handlers own the surrounding
// `dispatchRunSessionCommand`; compound recipes compose these helpers without nesting.
export {
  addRunGold,
  addRunMaterialsEarned,
  awardCardXP,
  awardMysteryXP,
  clearRunMaterialsEarned,
  createDraftRunRandomSource,
  withDraftWorldBattleRng,
  setCompletedDestinations,
  setContentSystemType,
  setCurrentAct,
  setDestinationIndexInAct,
  setDestinationOfferState,
  setEncounteredRunEnemyIds,
  setRoomsEncountered,
  setRunDeck,
  setRunGold,
  setRunMaxHealth,
  setRunPlayerHealth,
  setRunBoons,
  setScreen,
} from "./write-port-run";
export {
  addMaterials,
  awardMaterialsDuringRun,
  bondCompanion,
  clearPermanentData,
  completeResearch,
  constructBuilding,
  finalizeRunXP,
  handleCollectionTabChange,
  plantFarm,
  resetToDefaults,
  resetUnlockedTalents,
  setCollectionPage,
  setMaterials,
  unlockAllTalents,
  unlockTalent,
} from "./write-port-profile";
export {
  beginBattleTransition,
  clearBattleTransition,
  commitBattleTransition,
  initializeActiveBattle,
  setBattleStartState,
  setBattleState,
  setHasActiveBattle,
  withRestingEndPlayerTurnResolution,
  withRestingWorldBattleRng,
} from "./write-port-battle";
export {
  abandonCorruptionDestinationVisit,
  abandonMysteryDestinationVisit,
  applyRunStartSnapshot,
  beginDestinationClaim,
  beginRewardClaim,
  cancelDestinationClaim,
  clearMysteryVisitState,
  clearShopOfferings,
  commitDestinationClaim,
  releaseRewardClaim,
  setActiveLabyrinthModifiers,
  setActiveLabyrinthPendingNode,
  setActiveLabyrinthRewardModifiers,
  setAlchemistState,
  setCompanionRewardCards,
  setCorruptionResult,
  setEquipmentShopState,
  setLabyrinthMap,
  setMysteryCardChoices,
  setMysteryChosenCardId,
  setMysteryChosenChoice,
  setMysteryEvent,
  setMysteryGrantedGearInstances,
  setMysteryGrantedTrinketIds,
  setMysteryPendingRemoval,
  setPendingCharacterId,
  setPendingContentSystemType,
  setRewardState,
  setRunEndMaterials,
  setShopState,
  setStarterDraftChoices,
  setTrinketShopState,
  setWildwoodDraft,
  clearTransientSession,
} from "./write-port-session";
