// Deprecated shim — profile/permanent mutators now live in write-port-session.ts.
// Keep for one cycle; new code should import via run-session-write-port or write-port-session.
export {
  grantMaterials,
  awardMaterialsDuringRun,
  setMaterials,
  addMaterials,
  constructBuilding,
  plantFarm,
  completeResearch,
  bondCompanion,
  unlockTalent,
  resetUnlockedTalents,
  unlockAllTalents,
  applyTalentState,
  clearPermanentData,
  finalizeRunXP,
  setDiscoveredCardIds,
  setEncounteredEnemyIds,
  setDiscoveredTrinketIds,
  setDiscoveredUniqueIds,
  setCompletedDifficulties,
  setFinishedRunCharacters,
  setCollectionPage,
  handleCollectionTabChange,
  resetToDefaults,
} from "./write-port-session";
