// Talent definitions for keyword: archery.
import type { TalentDefinition } from "../types";
import { addEffect, setEffect } from "../types";

export const archeryTalents: TalentDefinition[] = [
  {
    id: "archery-damage",
    keywordId: "archery",
    name: "Arrow Dance",
    description: "When you Dodge, your next Archery card is free",
    icon: "Move",
    effects: [setEffect("nextArcheryCardFreeOnDodge", true)],
  },
  {
    id: "archery-hail",
    keywordId: "archery",
    name: "Hail of Arrows",
    description: "Archery cards have a 10% chance to deal 50% of their damage a second time",
    icon: "CloudRain",
    effects: [setEffect("archeryPlayTwiceChance", 10)],
  },
  {
    id: "archery-eagle-eye",
    keywordId: "archery",
    name: "Eagle Eye",
    description: "Archery cards deal double damage against Stunned enemies",
    icon: "Eye",
    effects: [setEffect("archeryDoubledVsStunned", true)],
  },
  {
    id: "archery-hawk-eye",
    keywordId: "archery",
    name: "Hawk Eye",
    description: "Archery cards deal double damage against Frozen enemies",
    icon: "ScanEye",
    effects: [setEffect("archeryDoubledVsFrozen", true)],
  },
  {
    id: "archery-longshot",
    keywordId: "archery",
    name: "Longshot",
    description: "Archery cards deal double damage against enemies above 75% Health",
    icon: "ArrowRight",
    effects: [setEffect("archeryDoubledVsHighHealth", true)],
  },
  {
    id: "archery-piercing-shot",
    keywordId: "archery",
    name: "Piercing Shot",
    description: "Archery cards ignore 1 Armor",
    icon: "Aperture",
    effects: [addEffect("archeryArmorPiercing", 1)],
  },
  {
    id: "archery-quickdraw",
    keywordId: "archery",
    name: "Quickdraw",
    description: "Your first Archery card each combat is free",
    icon: "Zap",
    effects: [setEffect("firstArcheryCardFree", true)],
  },
  {
    id: "archery-kill-shot",
    keywordId: "archery",
    name: "Kill Shot",
    description: "Archery cards deal double damage against enemies below 30% Health",
    icon: "Crosshair",
    effects: [setEffect("archeryDoubledVsLowHealth", true)],
  },
  {
    id: "archery-broadhead",
    keywordId: "archery",
    name: "Broadhead",
    description: "Archery cards have a 10% chance to Bleed",
    icon: "Diamond",
    effects: [setEffect("archeryBleedChance", 10)],
  },
  {
    id: "archery-trophy-shot",
    keywordId: "archery",
    name: "Trophy Shot",
    description: "Gain 2 Gold when an Archery card defeats an enemy",
    icon: "Award",
    effects: [setEffect("goldOnArcheryKill", 2)],
  },
];
