// Talent definitions for keyword: consume.
import {
  Apple,
  Gift,
  Flame,
  FlaskConical,
  Wine,
  Cookie,
  Package,
  CopyPlus,
  FlaskRound,
  CookingPot,
} from "lucide-react";
import type { TalentDefinition } from "../types";
import { addEffect, setEffect } from "../types";

export const consumeTalents: TalentDefinition[] = [
  {
    id: "consume-gourmand",
    keywordId: "consume",
    name: "Gourmand",
    description: "Consume cards heal 20% more",
    icon: Apple,
    effects: [setEffect("consumeHealMultiplier", 0.2)],
  },
  {
    id: "consume-last-supper",
    keywordId: "consume",
    name: "Last Supper",
    description: "Your first Consume card each combat is free",
    icon: Gift,
    effects: [setEffect("firstConsumeCardFree", true)],
  },
  {
    id: "consume-volatility",
    keywordId: "consume",
    name: "Volatility",
    description: "Consume cards deal 20% more damage",
    icon: Flame,
    effects: [setEffect("consumeDamageBonusPercent", 20)],
  },
  {
    id: "consume-distillation",
    keywordId: "consume",
    name: "Distillation",
    description: "Potions are 20% more potent",
    icon: FlaskConical,
    effects: [addEffect("potionPotency", 0.2)],
  },
  {
    id: "consume-brewmaster",
    keywordId: "consume",
    name: "Brewmaster",
    description: "Mixed Potion potency is increased by 1",
    icon: Wine,
    effects: [addEffect("potionMixPotency", 1)],
  },
  {
    id: "consume-aftertaste",
    keywordId: "consume",
    name: "Aftertaste",
    description: "When you Consume a card, restore 1 Health",
    icon: Cookie,
    effects: [setEffect("healOnConsume", 1)],
  },
  {
    id: "consume-leftovers",
    keywordId: "consume",
    name: "Leftovers",
    description: "When you Consume a card, gain 1 Gold",
    icon: Package,
    effects: [setEffect("goldOnConsume", 1)],
  },
  {
    id: "consume-second-helping",
    keywordId: "consume",
    name: "Second Helping",
    description: "Once per turn, when you Consume a card, draw a card",
    icon: CopyPlus,
    effects: [setEffect("drawOnConsume", 1)],
  },
  {
    id: "consume-rotgut",
    keywordId: "consume",
    name: "Rotgut",
    description: "When you Consume a card, apply 1 Poison",
    icon: FlaskRound,
    effects: [setEffect("poisonOnConsume", 1)],
  },
  {
    id: "consume-feast",
    keywordId: "consume",
    name: "Feast",
    description: "When you Consume a card, gain 2 Block",
    icon: CookingPot,
    effects: [setEffect("blockOnConsume", 2)],
  },
];
