// Talent definitions for keyword: freeze.
import {
  ThermometerSnowflake,
  Split,
  MountainSnow,
  Snowflake,
  CloudSnow,
  ShieldOff,
  Thermometer,
  FlaskConical,
  Hexagon,
  Lock,
} from "lucide-react";
import type { TalentDefinition } from "../types";
import { addEffect, setEffect } from "../types";

export const freezeTalents: TalentDefinition[] = [
  {
    id: "freeze-threshold",
    keywordId: "freeze",
    name: "Bitter Cold",
    description: "Freeze threshold reduced by 10%",
    icon: ThermometerSnowflake,
    effects: [setEffect("freezeThresholdReduction", 0.1)],
  },
  {
    id: "freeze-double-damage",
    keywordId: "freeze",
    name: "Shatter",
    description: "Frozen enemies take double damage",
    icon: Split,
    effects: [setEffect("freezeDoubleDamage", true)],
  },
  {
    id: "freeze-start-amount",
    keywordId: "freeze",
    name: "Winter's Grasp",
    description: "Start each combat by dealing 4 Freeze damage",
    icon: MountainSnow,
    effects: [setEffect("startFreeze", 4)],
  },
  {
    id: "freeze-block-grant",
    keywordId: "freeze",
    name: "Icebound",
    description: "Frozen enemies lose all Block and cannot Dodge",
    icon: Snowflake,
    effects: [setEffect("freezeStripBlock", true), setEffect("freezePreventsEnemyDodge", true)],
  },
  {
    id: "freeze-companion-bonus",
    keywordId: "freeze",
    name: "Snow Pack",
    description: "Your Companion deals 1 additional damage to Frozen enemies",
    icon: CloudSnow,
    effects: [addEffect("companionVsFrozenBonus", 1)],
  },
  {
    id: "freeze-strip-armor",
    keywordId: "freeze",
    name: "Brittle Armor",
    description: "Frozen enemies lose all Armor",
    icon: ShieldOff,
    effects: [setEffect("freezeStripArmor", true)],
  },
  {
    id: "freeze-half-damage",
    keywordId: "freeze",
    name: "Cold Resistance",
    description: "Receive half Freeze damage",
    icon: Thermometer,
    effects: [setEffect("receiveHalfFreezeDamage", true)],
  },
  {
    id: "freeze-poison-preserve",
    keywordId: "freeze",
    name: "Cryo-preservation",
    description: "Poison stacks on Frozen enemies cannot decay",
    icon: FlaskConical,
    effects: [setEffect("freezePreventsPoisonDecay", true)],
  },
  {
    id: "freeze-prevent-scaling",
    keywordId: "freeze",
    name: "Glacial Encasement",
    description: "Frozen enemies cannot gain Forge or Armor",
    icon: Hexagon,
    effects: [setEffect("freezePreventsEnemyScaling", true)],
  },
  {
    id: "freeze-block-healing",
    keywordId: "freeze",
    name: "Permafrost",
    description: "Frozen enemies cannot restore Health",
    icon: Lock,
    effects: [setEffect("freezeBlocksRegen", true)],
  },
];
