// Phase 1 talent pool: monolithic list moved from talents.ts; per-keyword files may follow.
import type { TalentDefinition } from "../types";
import { addEffect, placeholderTalents, setEffect } from "../types";

export const talentPool: TalentDefinition[] = [
  // --- Physical ---
  {
    id: "physical-expert-blacksmith",
    keywordId: "physical",
    name: "Expert Blacksmith",
    description: "Physical damage bonus from Forge is doubled",
    effects: [setEffect("forgeToPhysicalDamageMultiplier", 2)],
  },
  {
    id: "physical-shield-bash",
    keywordId: "physical",
    name: "Shield Bash",
    description: "Physical damage is increased by half your Block",
    effects: [setEffect("blockToPhysicalDamageMultiplier", 0.5)],
  },
  {
    id: "physical-armored-fists",
    keywordId: "physical",
    name: "Armored Fists",
    description: "Physical damage is increased by your Armor",
    effects: [setEffect("armorToPhysicalDamage", true)],
  },
  {
    id: "physical-heavy-blows",
    keywordId: "physical",
    name: "Heavy Blows",
    description: "Physical damage has a 10% chance to Stun",
    effects: [setEffect("physicalStunChance", 10)],
  },
  {
    id: "physical-finish-him",
    keywordId: "physical",
    name: "Finish Him",
    description: "Physical damage is doubled against Stunned enemies",
    effects: [setEffect("physicalDoubledVsStunned", true)],
  },
  {
    id: "physical-shatter",
    keywordId: "physical",
    name: "Shatter",
    description: "Physical damage is doubled against Frozen enemies",
    effects: [setEffect("physicalDoubledVsFrozen", true)],
  },
  {
    id: "physical-lacerate",
    keywordId: "physical",
    name: "Lacerate",
    description: "Physical damage has a 10% chance to Bleed",
    effects: [setEffect("physicalBleedChance", 10)],
  },
  {
    id: "physical-hemorrhage",
    keywordId: "physical",
    name: "Hemorrhage",
    description: "Physical damage detonates Bleed",
    effects: [setEffect("physicalDetonatesBleed", true)],
  },
  {
    id: "physical-brute-force",
    keywordId: "physical",
    name: "Brute Force",
    description: "Increase Physical damage by 1",
    effects: [addEffect("flatPhysicalDamage", 1)],
  },
  {
    id: "physical-unrelenting",
    keywordId: "physical",
    name: "Unrelenting",
    description: "You deal double Physical damage while below 50% Health",
    effects: [setEffect("physicalDoubledBelowHalfHealth", true)],
  },

  // --- Stun ---
  {
    id: "stun-forge-grant",
    keywordId: "stun",
    name: "Riled Up",
    description: "When you Stun an enemy, gain 2 Forge",
    effects: [setEffect("forgeOnStun", 2)],
  },
  {
    id: "stun-double-damage",
    keywordId: "stun",
    name: "Exploit Weakness",
    description: "Stunned enemies take double damage",
    effects: [setEffect("stunDoubleDamage", true)],
  },
  {
    id: "stun-block-grant",
    keywordId: "stun",
    name: "Guarded Counter",
    description: "When you Stun an enemy, gain 3 Block",
    effects: [setEffect("blockOnStun", 3)],
  },
  {
    id: "stun-duration-1",
    keywordId: "stun",
    name: "Extended Stun",
    description: "Stun effects last 1 turn longer",
    effects: [setEffect("stunDurationExtension", 1)],
  },
  {
    id: "stun-strip-armor",
    keywordId: "stun",
    name: "Shatter Guard",
    description: "Stunned enemies lose all Armor",
    effects: [setEffect("stunStripArmor", true)],
  },
  {
    id: "stun-damage-1",
    keywordId: "stun",
    name: "Jarring Blow",
    description: "Increase Stun damage by 1",
    effects: [addEffect("flatStunDamage", 1)],
  },
  {
    id: "stun-next-free",
    keywordId: "stun",
    name: "Free Follow-up",
    description: "When you Stun an enemy, your next card is free",
    effects: [setEffect("nextCardFreeOnStun", true)],
  },
  {
    id: "stun-threshold",
    keywordId: "stun",
    name: "Concussive Force",
    description: "Stun threshold reduced by 10%",
    effects: [setEffect("stunThresholdReduction", 0.1)],
  },
  {
    id: "stun-draw",
    keywordId: "stun",
    name: "Stun Insight",
    description: "When you Stun an enemy, draw a card",
    effects: [setEffect("drawOnStun", 1)],
  },
  {
    id: "stun-mana-grant",
    keywordId: "stun",
    name: "Stun Surge",
    description: "When you Stun an enemy, gain 1 Mana",
    effects: [setEffect("manaOnStun", 1)],
  },

  // --- Block ---
  {
    id: "block-depleted-heal",
    keywordId: "block",
    name: "Second Wind",
    description: "When Block is depleted, Restore 2 Health",
    effects: [setEffect("blockDepletedHeal", 2)],
  },
  {
    id: "block-absorb-physical",
    keywordId: "block",
    name: "Reinforce",
    description: "Block absorbs 20% more Physical damage",
    effects: [setEffect("blockAbsorbPhysicalBonus", 20)],
  },
  {
    id: "block-to-holy",
    keywordId: "block",
    name: "Sacred Shield",
    description: "Increase Holy damage by half your Block",
    effects: [setEffect("blockToHolyDamage", true)],
  },
  {
    id: "block-to-stun",
    keywordId: "block",
    name: "Impact Guard",
    description: "Increase Stun damage by half your Block",
    effects: [setEffect("blockToStunDamage", true)],
  },
  {
    id: "block-prevent-stun",
    keywordId: "block",
    name: "Grounding",
    description: "Block prevents receiving Stun buildup",
    effects: [setEffect("blockPreventsStun", true)],
  },
  {
    id: "block-to-physical",
    keywordId: "block",
    name: "Weighted Guard",
    description: "Increase Physical damage by half your Block",
    effects: [setEffect("blockToPhysicalDamage", true)],
  },
  {
    id: "block-reduce-burn",
    keywordId: "block",
    name: "Fireproof",
    description: "Block reduces Burn damage by 1",
    effects: [setEffect("blockReduceBurnDamage", 1)],
  },
  {
    id: "block-start",
    keywordId: "block",
    name: "Fortify",
    description: "Start each combat with 10 Block",
    effects: [setEffect("startBlock", 10)],
  },
  {
    id: "block-prevent-bleed",
    keywordId: "block",
    name: "Coagulate",
    description: "Block prevents receiving Bleed status effects",
    effects: [setEffect("blockPreventsBleed", true)],
  },
  {
    id: "block-prevent-poison",
    keywordId: "block",
    name: "Detoxify",
    description: "Block prevents receiving Poison status effects",
    effects: [setEffect("blockPreventsPoison", true)],
  },

  // --- Forge ---
  {
    id: "forge-to-burn",
    keywordId: "forge",
    name: "Ignite",
    description: "Forge also increases Burn damage",
    effects: [setEffect("forgeToBurn", true)],
  },
  {
    id: "forge-to-holy",
    keywordId: "forge",
    name: "Sanctify",
    description: "Forge also increases Holy damage",
    effects: [setEffect("forgeToHoly", true)],
  },
  {
    id: "forge-to-block",
    keywordId: "forge",
    name: "Tempered Guard",
    description: "Forge also increases Block amount",
    effects: [setEffect("forgeToBlock", true)],
  },
  {
    id: "forge-burn-burst",
    keywordId: "forge",
    name: "Overheat",
    description: "When you reach 4 Forge, deal 8 Burn",
    effects: [setEffect("forgeBurnThreshold", 4), setEffect("forgeBurnDamage", 8)],
  },
  {
    id: "forge-strength-1",
    keywordId: "forge",
    name: "Forge Mastery",
    description: "Start each combat with 2 Forge",
    effects: [setEffect("startForge", 2)],
  },
  {
    id: "forge-strength-2",
    keywordId: "forge",
    name: "Rust",
    description: "Forge also increases Bleed damage",
    effects: [setEffect("forgeToBleed", true)],
  },
  {
    id: "forge-strength-3",
    keywordId: "forge",
    name: "Sunder",
    description: "When you reach 6 Forge, remove all enemy Armor",
    effects: [setEffect("forgeStripArmorThreshold", 6)],
  },
  {
    id: "forge-strength-4",
    keywordId: "forge",
    name: "Intensify",
    description: "Increase Forge gained by 1",
    effects: [addEffect("flatForgeGained", 1)],
  },
  {
    id: "forge-strength-5",
    keywordId: "forge",
    name: "Desperate Forge",
    description: "Forge gained is doubled when Health is below 50%",
    effects: [setEffect("forgeDoubledBelowHalfHealth", true)],
  },
  {
    id: "forge-strength-6",
    keywordId: "forge",
    name: "Forged Bulwark",
    description: "When you reach 6 Forge, gain 10 Block",
    effects: [setEffect("forgeBlockThreshold", 6), setEffect("forgeBlockAmount", 10)],
  },

  // --- Armor ---
  {
    id: "armor-desperate-double",
    keywordId: "armor",
    name: "Last Stand",
    description: "Armor gained is doubled when Health is below 50%",
    effects: [setEffect("armorDoubledBelowHalfHealth", true)],
  },
  {
    id: "armor-block-burst",
    keywordId: "armor",
    name: "Armored Surge",
    description: "When you reach 4 Armor, gain 8 Block",
    effects: [setEffect("armorBlockThreshold", 4), setEffect("armorBlockAmount", 8)],
  },
  {
    id: "armor-burn-mitigate",
    keywordId: "armor",
    name: "Fireward",
    description: "Armor now mitigates Burn damage taken",
    effects: [setEffect("armorMitigatesBurn", true)],
  },
  {
    id: "armor-break-block",
    keywordId: "armor",
    name: "Reactive Guard",
    description: "When Armor breaks, gain 5 Block",
    effects: [setEffect("armorBreakBlock", 5)],
  },
  {
    id: "armor-start-combat",
    keywordId: "armor",
    name: "Bulwark",
    description: "Start each combat with 2 Armor",
    effects: [setEffect("startArmor", 2)],
  },
  {
    id: "armor-mitigate-bleed",
    keywordId: "armor",
    name: "Thick Hide",
    description: "Armor now mitigates Bleed damage taken",
    effects: [setEffect("armorMitigatesBleed", true)],
  },
  {
    id: "armor-first-double",
    keywordId: "armor",
    name: "Iron Guard",
    description: "Your first Armor card each combat is doubled",
    effects: [setEffect("firstArmorCardDoubled", true)],
  },
  {
    id: "armor-mitigate-stun",
    keywordId: "armor",
    name: "Steadfast",
    description: "Armor now reduces Stun buildup",
    effects: [setEffect("armorMitigatesStun", true)],
  },
  {
    id: "armor-cleanse-threshold",
    keywordId: "armor",
    name: "Purification",
    description: "When you reach 6 Armor, cleanse all harmful status effects",
    effects: [setEffect("armorCleanseThreshold", 6)],
  },
  {
    id: "armor-flat-bonus",
    keywordId: "armor",
    name: "Reinforced",
    description: "Increase Armor gained by 1",
    effects: [addEffect("flatArmorAmount", 1)],
  },

  // --- Health ---
  {
    id: "health-threshold-armor",
    keywordId: "health",
    name: "Last Resort",
    description: "When Health drops below 25%, gain 3 Armor",
    effects: [setEffect("healthThresholdArmor", { threshold: 25, amount: 3 })],
  },
  {
    id: "health-threshold-block",
    keywordId: "health",
    name: "Desperate Guard",
    description: "When Health drops below 50%, gain 6 Block",
    effects: [setEffect("healthThresholdBlock", { threshold: 50, amount: 6 })],
  },
  {
    id: "health-max-4",
    keywordId: "health",
    name: "Will to Live",
    description: "Death's Door lasts 1 turn longer",
    effects: [setEffect("deathsDoorExtension", 1)],
  },
  {
    id: "health-start",
    keywordId: "health",
    name: "Combat Surge",
    description: "Restore 4 Health at the start of each combat",
    effects: [setEffect("startHealth", 4)],
  },
  {
    id: "health-max-per-combat",
    keywordId: "health",
    name: "Vitality",
    description: "Gain 1 Max Health after every combat",
    effects: [setEffect("maxHealthPerCombat", 1)],
  },
  {
    id: "health-heal-boost",
    keywordId: "health",
    name: "Mending",
    description: "Healing effects are 10% stronger",
    effects: [setEffect("healMultiplier", 1.1)],
  },
  {
    id: "health-max-1",
    keywordId: "health",
    name: "Overflow",
    description: "When you overheal, gain 50% of the excess as Block",
    effects: [setEffect("overhealToBlockRatio", 0.5)],
  },
  {
    id: "health-max-2",
    keywordId: "health",
    name: "Cleansing Status",
    description: "Cleansing a status restores 6 Health",
    effects: [setEffect("healOnStatusCleanse", 6)],
  },
  {
    id: "health-max-3",
    keywordId: "health",
    name: "Thick Skin",
    description: "Reduce all damage taken by 1",
    effects: [setEffect("damageReduction", 1)],
  },
  {
    id: "health-campfire",
    keywordId: "health",
    name: "Warm Rest",
    description: "Campfire heals 10% more Health",
    effects: [setEffect("campfireHealBonus", 0.1)],
  },

  // --- Burn ---
  {
    id: "burn-dmg-1",
    keywordId: "burn",
    name: "Flashpoint",
    description: "Increase Burn damage by 1",
    effects: [addEffect("flatBurnDamage", 1)],
  },
  {
    id: "burn-dmg-2",
    keywordId: "burn",
    name: "Thermal Vent",
    description: "When you deal Burn damage, gain 1 Forge",
    effects: [addEffect("forgeOnBurnDealt", 1)],
  },
  {
    id: "burn-dmg-5",
    keywordId: "burn",
    name: "Flaming Shield",
    description: "Burn damage is increased by half your Block",
    effects: [setEffect("blockToBurnDamage", true)],
  },
  {
    id: "burn-dmg-4",
    keywordId: "burn",
    name: "Combustible",
    description: "Consume cards deal double Burn damage",
    effects: [setEffect("consumeDoubleBurnDamage", true)],
  },
  {
    id: "burn-first-double",
    keywordId: "burn",
    name: "Wildfire",
    description: "Your first Burn card each combat is doubled",
    effects: [setEffect("firstBurnCardDoubled", true)],
  },
  {
    id: "burn-remove-armor",
    keywordId: "burn",
    name: "Melting Point",
    description: "Burn damage removes that amount of enemy Armor",
    effects: [setEffect("burnRemovesEnemyArmor", true)],
  },
  {
    id: "burn-dmg-3",
    keywordId: "burn",
    name: "Heat Exhaustion",
    description: "Burn has a 10% chance to Stun",
    effects: [setEffect("burnStunChance", 10)],
  },
  {
    id: "burn-dmg-6",
    keywordId: "burn",
    name: "Burning Wish",
    description: "When you play a Wish, deal 2 Burn damage to the enemy",
    effects: [setEffect("burnOnWish", 2)],
  },
  {
    id: "burn-double-chance",
    keywordId: "burn",
    name: "Smoldering",
    description: "Burn stacks have a 5% chance to double instead of halve",
    effects: [setEffect("burnDoubleChance", 5)],
  },
  {
    id: "burn-half-damage",
    keywordId: "burn",
    name: "Fire Resistance",
    description: "Receive half Burn damage",
    effects: [setEffect("receiveHalfBurnDamage", true)],
  },

  // --- Gold ---
  {
    id: "gold-shop-discount",
    keywordId: "gold",
    name: "Haggle",
    description: "Shop cards cost 5 less Gold",
    effects: [setEffect("shopCardDiscount", 5)],
  },
  {
    id: "gold-shop-refresh",
    keywordId: "gold",
    name: "Restock",
    description: "Shop refresh is free once per visit",
    effects: [setEffect("shopFreeRefresh", true)],
  },
  {
    id: "gold-start",
    keywordId: "gold",
    name: "Seed Money",
    description: "Start each run with 20 Gold",
    effects: [setEffect("startGold", 20)],
  },
  {
    id: "gold-per-combat",
    keywordId: "gold",
    name: "Bounty",
    description: "Gain +5 Gold after each combat",
    effects: [setEffect("goldPerCombat", 5)],
  },
  {
    id: "gold-potion-discount",
    keywordId: "gold",
    name: "Apothecary Bargain",
    description: "Potions cost 5 less Gold",
    effects: [setEffect("potionDiscount", 5)],
  },
  {
    id: "gold-remove-discount",
    keywordId: "gold",
    name: "Buyout",
    description: "Card removal costs 10 less Gold",
    effects: [setEffect("removeCardDiscount", 10)],
  },
  {
    id: "gold-enemy-drop",
    keywordId: "gold",
    name: "Plunder",
    description: "Enemies drop 10% more Gold",
    effects: [setEffect("enemyGoldDropBonus", 0.1)],
  },
  {
    id: "gold-on-wish",
    keywordId: "gold",
    name: "Golden Wish",
    description: "Gain 3 Gold when you Wish",
    effects: [setEffect("goldOnWish", 3)],
  },
  {
    id: "gold-mix-discount",
    keywordId: "gold",
    name: "Alchemy Discount",
    description: "Mix Potions costs 10 less Gold",
    effects: [setEffect("mixPotionDiscount", 10)],
  },
  {
    id: "gold-elite-drop",
    keywordId: "gold",
    name: "Spoils of War",
    description: "Elites drop 10% more Gold",
    effects: [setEffect("eliteGoldDropBonus", 0.1)],
  },

  // --- Holy ---
  {
    id: "holy-tithe",
    keywordId: "holy",
    name: "Tithe",
    description: "10% chance to gain Gold equal to Holy damage",
    effects: [setEffect("holyGoldChance", 10)],
  },
  {
    id: "holy-block-scaling",
    keywordId: "holy",
    name: "Faith Barrier",
    description: "Holy damage is increased by half your Block",
    effects: [setEffect("blockToHolyDamage", true)],
  },
  {
    id: "holy-wish-chance",
    keywordId: "holy",
    name: "Divine Intervention",
    description: "Holy damage has a 5% chance to Wish",
    effects: [setEffect("holyWishChance", 5)],
  },
  {
    id: "holy-burn-chance",
    keywordId: "holy",
    name: "Scorching Light",
    description: "Holy damage has a 10% chance to Burn",
    effects: [setEffect("holyBurnChance", 10)],
  },
  {
    id: "holy-half-damage",
    keywordId: "holy",
    name: "Celestial Ward",
    description: "Receive half Holy damage",
    effects: [setEffect("receiveHalfHolyDamage", true)],
  },
  {
    id: "holy-first-free",
    keywordId: "holy",
    name: "Divine Favor",
    description: "Your first Holy card each combat is free",
    effects: [setEffect("firstHolyCardFree", true)],
  },
  {
    id: "holy-gold-scaling",
    keywordId: "holy",
    name: "Prosperity",
    description: "Holy damage is increased by 3% of your Gold",
    effects: [setEffect("holyGoldPercent", 3)],
  },
  {
    id: "holy-block-grant",
    keywordId: "holy",
    name: "Radiant Guard",
    description: "Holy damage grants Block for 15% of the amount dealt",
    effects: [setEffect("holyBlockPercentFromDamage", 15)],
  },
  {
    id: "holy-vs-burn",
    keywordId: "holy",
    name: "Purge",
    description: "Holy damage is increased by 20% against enemies with Burn",
    effects: [setEffect("holyVsBurnMultiplier", 20)],
  },
  {
    id: "holy-lifesteal",
    keywordId: "holy",
    name: "Blessed Leech",
    description: "Holy damage heals you for 10% of the amount dealt",
    effects: [setEffect("holyLifestealPercent", 10)],
  },

  // --- Wish ---
  {
    id: "wish-boon",
    keywordId: "wish",
    name: "Wishful Boon",
    description: "Gain 1 Forge or Armor when you Wish",
    effects: [setEffect("wishBoonChoice", true)],
  },
  {
    id: "wish-undiscovered",
    keywordId: "wish",
    name: "Discovery",
    description: "Wish can offer cards not yet in your collection",
    effects: [setEffect("wishUndiscoveredCards", true)],
  },
  {
    id: "wish-health",
    keywordId: "wish",
    name: "Vital Wish",
    description: "Gain 2 Health when you Wish",
    effects: [setEffect("healthOnWish", 2)],
  },
  {
    id: "wish-cleanse",
    keywordId: "wish",
    name: "Purifying Wish",
    description: "Cleanse a harmful status effect when you Wish",
    effects: [setEffect("removeHarmfulStatusOnWish", true)],
  },
  {
    id: "wish-extra-choice",
    keywordId: "wish",
    name: "Generous Wish",
    description: "Wish has a 20% chance to offer an extra card choice",
    effects: [setEffect("wishExtraChoiceChance", 20)],
  },
  {
    id: "wish-draw",
    keywordId: "wish",
    name: "Insight",
    description: "Wish also draws a card",
    effects: [setEffect("wishDrawsCard", true)],
  },
  {
    id: "wish-powerful",
    keywordId: "wish",
    name: "Powerful Wish",
    description: "Wish card numeric values are increased by 1",
    effects: [setEffect("wishCardsUpgraded", true)],
  },
  {
    id: "wish-mana",
    keywordId: "wish",
    name: "Mana from Heaven",
    description: "Gain 1 Mana when you Wish",
    effects: [addEffect("manaOnWish", 1)],
  },
  {
    id: "wish-gold",
    keywordId: "wish",
    name: "Golden Opportunity",
    description: "Gain 2 Gold when you Wish",
    effects: [setEffect("goldOnWishAmount", 2)],
  },
  {
    id: "wish-desperate",
    keywordId: "wish",
    name: "Desperate Wish",
    description: "Gain 6 Block when you Wish below 30% Health",
    effects: [setEffect("wishBlockBelowHealthPct", 30)],
  },
  // --- Poison ---
  {
    id: "poison-leech-chance",
    keywordId: "poison",
    name: "Hemotoxin",
    description: "Poison has a 10% chance to Leech",
    effects: [setEffect("poisonLeechChance", 10)],
  },
  {
    id: "poison-physical-bonus",
    keywordId: "poison",
    name: "Corrosive",
    description: "Enemies with Poison take +1 Physical damage",
    effects: [setEffect("poisonPhysicalBonus", 1)],
  },
  {
    id: "poison-strip-armor",
    keywordId: "poison",
    name: "Caustic",
    description: "Poison removes 1 Armor",
    effects: [setEffect("poisonStripArmor", true)],
  },
  {
    id: "poison-half-damage",
    keywordId: "poison",
    name: "Toxin Resistance",
    description: "Receive half Poison damage",
    effects: [setEffect("receiveHalfPoisonDamage", true)],
  },
  {
    id: "poison-gold-first",
    keywordId: "poison",
    name: "Toxic Profit",
    description: "The first time you Poison each combat, gain 4 Gold",
    effects: [setEffect("goldOnFirstPoison", 4)],
  },
  {
    id: "poison-heal-reduce",
    keywordId: "poison",
    name: "Necrosis",
    description: "Poison reduces enemy healing by half",
    effects: [setEffect("poisonHalvesHealing", true)],
  },
  {
    id: "poison-stun-chance",
    keywordId: "poison",
    name: "Paralytic Venom",
    description: "Poison has a 10% chance to also Stun",
    effects: [setEffect("poisonStunChance", 10)],
  },
  {
    id: "poison-gain-chance",
    keywordId: "poison",
    name: "Virulent",
    description: "Poison has a 10% chance to gain instead of lose a stack",
    effects: [setEffect("poisonGainChance", 10)],
  },
  {
    id: "poison-reduce-damage",
    keywordId: "poison",
    name: "Crippling Toxin",
    description: "Enemies with Poison deal 1 less damage",
    effects: [setEffect("poisonReducesEnemyDamage", 1)],
  },
  {
    id: "poison-first-free",
    keywordId: "poison",
    name: "Venom Strike",
    description: "Your first Poison card each combat is free",
    effects: [setEffect("firstPoisonCardFree", true)],
  },

  // --- Bleed ---
  {
    id: "bleed-first-free",
    keywordId: "bleed",
    name: "First Blood",
    description: "Your first Bleed card each combat is free",
    effects: [setEffect("firstBleedCardFree", true)],
  },
  {
    id: "bleed-physical-bonus",
    keywordId: "bleed",
    name: "Open Wound",
    description: "Enemies with Bleed take +1 Physical damage",
    effects: [setEffect("bleedPhysicalBonus", 1)],
  },
  {
    id: "bleed-leech-chance",
    keywordId: "bleed",
    name: "Sanguine",
    description: "Bleed has a 15% chance to Leech",
    effects: [setEffect("bleedLeechChance", 15)],
  },
  {
    id: "bleed-enemy-weak",
    keywordId: "bleed",
    name: "Mortal Wound",
    description: "Bleed reduces enemy healing by half",
    effects: [setEffect("bleedHalvesEnemyHealing", true)],
  },
  {
    id: "bleed-wound-care",
    keywordId: "bleed",
    name: "Wound Care",
    description: "Receive half Bleed damage",
    effects: [setEffect("receiveHalfBleedDamage", true)],
  },
  {
    id: "bleed-execute",
    keywordId: "bleed",
    name: "Exsanguinate",
    description: "Bleed deals double damage against enemies below 30% Health",
    effects: [setEffect("bleedExecuteThreshold", 30)],
  },
  {
    id: "bleed-desperate",
    keywordId: "bleed",
    name: "Bleeding Out",
    description: "You deal double Bleed damage while below 50% Health",
    effects: [setEffect("bleedDesperateMultiplier", 2)],
  },
  {
    id: "bleed-poison-chance",
    keywordId: "bleed",
    name: "Tainted Wound",
    description: "Bleed has a 10% chance to Poison",
    effects: [setEffect("bleedPoisonChance", 10)],
  },
  {
    id: "bleed-septic-shock",
    keywordId: "bleed",
    name: "Septic Shock",
    description: "Bleed increases Poison damage taken by 1",
    effects: [setEffect("bleedPoisonDamageTakenBonus", 1)],
  },
  {
    id: "bleed-rip-and-tear",
    keywordId: "bleed",
    name: "Rip and Tear",
    description: "Companion Bleed damage is increased by 1",
    effects: [addEffect("companionBleedDamageBonus", 1)],
  },

  // --- Leech ---
  {
    id: "leech-first-double",
    keywordId: "leech",
    name: "First Blood",
    description: "Your first Leech card each combat heals for double",
    effects: [setEffect("firstLeechCardDoubled", true)],
  },
  {
    id: "leech-desperate",
    keywordId: "leech",
    name: "Desperate Siphon",
    description: "Leech is 20% more effective while below 50% Health",
    effects: [setEffect("leechDesperateMultiplier", 20)],
  },
  {
    id: "leech-blood-debt",
    keywordId: "leech",
    name: "Blood Debt",
    description: "Leech heals for 1 more per 8 missing Health",
    effects: [setEffect("leechMissingHealthStep", 8)],
  },
  {
    id: "leech-bleed-chance",
    keywordId: "leech",
    name: "Hemorrhage",
    description: "Leech has a 10% chance to Bleed",
    effects: [setEffect("leechBleedChance", 10)],
  },
  {
    id: "leech-cull-weak",
    keywordId: "leech",
    name: "Cull the Weak",
    description: "Leech is 20% more effective against enemies below 50% Health",
    effects: [setEffect("leechExecuteMultiplier", 20)],
  },
  {
    id: "leech-mana-siphon",
    keywordId: "leech",
    name: "Mana Siphon",
    description: "Leech has a 10% chance to gain 1 Mana",
    effects: [setEffect("manaOnLeechChance", 10)],
  },
  {
    id: "leech-boon-siphon",
    keywordId: "leech",
    name: "Boon Siphon",
    description: "Leech has a 20% chance to steal 1 Forge, Armor, or Block",
    effects: [setEffect("boonSiphonChance", 20)],
  },
  {
    id: "leech-poison",
    keywordId: "leech",
    name: "Virulent Leech",
    description: "Leech has a 10% chance to Poison",
    effects: [setEffect("leechPoisonChance", 10)],
  },
  {
    id: "leech-block-enemy",
    keywordId: "leech",
    name: "Blood Type",
    description: "Enemies cannot restore Health when they Leech",
    effects: [setEffect("blockEnemyLeech", true)],
  },
  {
    id: "leech-nature-chance",
    keywordId: "leech",
    name: "Carnivorous Nature",
    description: "Nature damage has a 10% chance to Leech",
    effects: [setEffect("natureLeechChance", 10)],
  },

  {
    id: "freeze-threshold",
    keywordId: "freeze",
    name: "Bitter Cold",
    description: "Freeze threshold reduced by 10%",
    effects: [setEffect("freezeThresholdReduction", 0.1)],
  },
  {
    id: "freeze-double-damage",
    keywordId: "freeze",
    name: "Shatter",
    description: "Frozen enemies take double damage",
    effects: [setEffect("freezeDoubleDamage", true)],
  },
  {
    id: "freeze-start-amount",
    keywordId: "freeze",
    name: "Winter's Grasp",
    description: "Start each combat by applying 4 Freeze to the enemy",
    effects: [setEffect("startFreeze", 4)],
  },
  {
    id: "freeze-block-grant",
    keywordId: "freeze",
    name: "Frost Ward",
    description: "Gain 6 Block when you Freeze an enemy",
    effects: [setEffect("blockOnFreeze", 6)],
  },
  {
    id: "freeze-companion-bonus",
    keywordId: "freeze",
    name: "Snow Pack",
    description: "Your Companion deals 1 additional damage to Frozen enemies",
    effects: [addEffect("companionVsFrozenBonus", 1)],
  },
  {
    id: "freeze-strip-armor",
    keywordId: "freeze",
    name: "Brittle Armor",
    description: "Frozen enemies lose all Armor",
    effects: [setEffect("freezeStripArmor", true)],
  },
  {
    id: "freeze-half-damage",
    keywordId: "freeze",
    name: "Cold Resistance",
    description: "Receive half Freeze damage",
    effects: [setEffect("receiveHalfFreezeBuildUp", true)],
  },
  {
    id: "freeze-poison-preserve",
    keywordId: "freeze",
    name: "Cryo-preservation",
    description: "Poison stacks on Frozen enemies cannot decay",
    effects: [setEffect("freezePreventsPoisonDecay", true)],
  },
  {
    id: "freeze-prevent-scaling",
    keywordId: "freeze",
    name: "Glacial Encasement",
    description: "Frozen enemies cannot gain Forge or Armor",
    effects: [setEffect("freezePreventsEnemyScaling", true)],
  },
  {
    id: "freeze-block-healing",
    keywordId: "freeze",
    name: "Permafrost",
    description: "Frozen enemies cannot restore Health",
    effects: [setEffect("freezeBlocksRegen", true)],
  },

  {
    id: "mana-wellspring",
    keywordId: "mana",
    name: "Wellspring",
    description: "When you end your turn with unspent Mana, keep 1 for next turn",
    effects: [setEffect("wellspringKeepMana", 1)],
  },
  {
    id: "mana-bulwark",
    keywordId: "mana",
    name: "Mana Bulwark",
    description: "Start each combat with Block equal to your Mana Crystals",
    effects: [setEffect("manaBulwarkActive", true)],
  },
  {
    id: "mana-leylines",
    keywordId: "mana",
    name: "Leyline Attunement",
    description: "Gain 1 Mana Crystal",
    effects: [setEffect("startMana", 1)],
  },
  {
    id: "mana-arcane-wish",
    keywordId: "mana",
    name: "Arcane Wish",
    description: "Gain 1 Mana when you Wish",
    effects: [addEffect("manaOnWish", 1)],
  },
  {
    id: "mana-manaburn",
    keywordId: "mana",
    name: "Manaburn",
    description: "Burn damage is increased by half your Mana Crystals",
    effects: [setEffect("burnDamagePerManaCrystal", 1)],
  },
  {
    id: "mana-arcane-frost",
    keywordId: "mana",
    name: "Arcane Frost",
    description: "Freeze damage is increased by half your Mana Crystals",
    effects: [setEffect("freezeDamagePerManaCrystal", 1)],
  },
  {
    id: "mana-flare",
    keywordId: "mana",
    name: "Mana Flare",
    description: "When you lose a Mana Crystal, deal 3 Burn damage",
    effects: [setEffect("burnDamageOnManaCrystalLoss", 3)],
  },
  {
    id: "mana-familiar-bond",
    keywordId: "mana",
    name: "Familiar Bond",
    description: "Companion damage is increased by half your Mana Crystals",
    effects: [setEffect("companionDamagePerManaCrystal", 1)],
  },
  {
    id: "mana-shell",
    keywordId: "mana",
    name: "Mana Shell",
    description: "Start each combat with Armor equal to your Mana Crystals",
    effects: [setEffect("manaShellActive", true)],
  },
  {
    id: "mana-arcane-mending",
    keywordId: "mana",
    name: "Arcane Mending",
    description: "Restore 2 Health when you gain Mana",
    effects: [setEffect("healOnManaGain", 2)],
  },

  ...placeholderTalents("nature", "nature-placeholder", 1, 10),

  {
    id: "companion-damage",
    keywordId: "companion",
    name: "Feral Strength",
    description: "Increase Companion damage by 1",
    effects: [addEffect("companionDamage", 1)],
  },
  {
    id: "companion-gold-find",
    keywordId: "companion",
    name: "Scavenger",
    description: "Companions sometimes find Gold after combat",
    effects: [setEffect("companionGoldFindActive", true)],
  },
  ...placeholderTalents("companion", "companion-placeholder", 3, 10),

  {
    id: "arrow-damage",
    keywordId: "arrow",
    name: "Tripwire",
    description: "Increase Arrow damage by 1",
    effects: [addEffect("flatArrowDamage", 1)],
  },
  ...placeholderTalents("arrow", "arrow-placeholder", 2, 10),

  // --- Consume (placeholders for grid completeness) ---
  ...placeholderTalents("consume", "consume", 1, 10),
];
