export { talentPool, talentPoolByKeyword, getTalentsForKeyword } from "../talent-pool-definitions";
import { getTalentsForKeyword } from "../talent-pool-definitions";

export const physicalTalents = getTalentsForKeyword("physical");
export const stunTalents = getTalentsForKeyword("stun");
export const blockTalents = getTalentsForKeyword("block");
export const forgeTalents = getTalentsForKeyword("forge");
export const armorTalents = getTalentsForKeyword("armor");
export const healthTalents = getTalentsForKeyword("health");
export const burnTalents = getTalentsForKeyword("burn");
export const goldTalents = getTalentsForKeyword("gold");
export const holyTalents = getTalentsForKeyword("holy");
export const wishTalents = getTalentsForKeyword("wish");
export const poisonTalents = getTalentsForKeyword("poison");
export const bleedTalents = getTalentsForKeyword("bleed");
export const leechTalents = getTalentsForKeyword("leech");
export const freezeTalents = getTalentsForKeyword("freeze");
export const manaTalents = getTalentsForKeyword("mana");
export const natureTalents = getTalentsForKeyword("nature");
export const companionTalents = getTalentsForKeyword("companion");
export const archeryTalents = getTalentsForKeyword("archery");
export const consumeTalents = getTalentsForKeyword("consume");
