// Talent definitions for keyword: leech.
import {
  Sword,
  HeartCrack,
  CircleDollarSign,
  Droplets,
  Skull,
  Gem,
  Wrench,
  FlaskConical,
  Hash,
  Utensils,
} from "lucide-react";
import type { TalentDefinition } from "../types";
import { setEffect } from "../types";

export const leechTalents: TalentDefinition[] = [
  {
    id: "leech-first-double",
    keywordId: "leech",
    name: "First Blood",
    description: "Your first Leech card each combat heals for double",
    icon: Sword,
    effects: [setEffect("firstLeechCardDoubled", true)],
  },
  {
    id: "leech-desperate",
    keywordId: "leech",
    name: "Desperate Siphon",
    description: "Leech is 20% more effective while below 50% Health",
    icon: HeartCrack,
    effects: [setEffect("leechDesperateMultiplier", 20)],
  },
  {
    id: "leech-blood-debt",
    keywordId: "leech",
    name: "Blood Debt",
    description: "Leech heals for 1 more per 8 missing Health",
    icon: CircleDollarSign,
    effects: [setEffect("leechMissingHealthStep", 8)],
  },
  {
    id: "leech-bleed-chance",
    keywordId: "leech",
    name: "Hemorrhage",
    description: "Leech has a 10% chance to Bleed",
    icon: Droplets,
    effects: [setEffect("leechBleedChance", 10)],
  },
  {
    id: "leech-cull-weak",
    keywordId: "leech",
    name: "Cull the Weak",
    description: "Leech is 20% more effective against enemies below 50% Health",
    icon: Skull,
    effects: [setEffect("leechExecuteMultiplier", 20)],
  },
  {
    id: "leech-mana-siphon",
    keywordId: "leech",
    name: "Mana Siphon",
    description: "Leech has a 10% chance to gain 1 Mana",
    icon: Gem,
    effects: [setEffect("manaOnLeechChance", 10)],
  },
  {
    id: "leech-trinket-siphon",
    keywordId: "leech",
    name: "Trinket Siphon",
    description: "Leech has a 20% chance to steal 1 Forge, Armor, or Block",
    icon: Wrench,
    effects: [setEffect("trinketSiphonChance", 20)],
  },
  {
    id: "leech-poison",
    keywordId: "leech",
    name: "Virulent Leech",
    description: "Leech has a 10% chance to Poison",
    icon: FlaskConical,
    effects: [setEffect("leechPoisonChance", 10)],
  },
  {
    id: "leech-block-enemy",
    keywordId: "leech",
    name: "Blood Type",
    description: "Enemies cannot restore Health when they Leech",
    icon: Hash,
    effects: [setEffect("blockEnemyLeech", true)],
  },
  {
    id: "leech-nature-chance",
    keywordId: "leech",
    name: "Carnivorous Nature",
    description: "Nature damage has a 10% chance to Leech",
    icon: Utensils,
    effects: [setEffect("natureLeechChance", 10)],
  },
];
