// Controller action surface passed from App into the screen renderer.
import type { BattleCard, CharacterId, DifficultyId, KeywordId } from "@/lib/game-data";
import type { MysteryChoice } from "@/features/alchemy/mystery-events";
import type { Destination, Screen } from "@/features/alchemy/types";

export type ControllerActions = {
  navigateTo: (screen: Screen) => void;
  goToScreen: (screen: Screen) => void;
  beginCampaign: () => void;
  beginLabyrinth: () => void;
  beginWildwood: () => void;
  handleCharacterSelect: (id: CharacterId) => void;
  handleDraftComplete: (draftedCards: BattleCard[]) => void;
  handleDifficultySelect: (id: DifficultyId) => void;
  handleBackFromDifficultySelect: () => void;
  handleWildwoodBossSelect: (id: string) => void;
  handleCardClick: (card: BattleCard, index: number, event: React.MouseEvent<HTMLButtonElement>) => void;
  handleWishChoice: (card: BattleCard | null) => void;
  handleEndTurn: () => void;
  handleEndRun: () => void;
  skipCombatDevMode: () => void;
  removeCardGhost: (id: string) => void;
  finishRewards: () => void;
  handleDestinationChoice: (dest: Destination) => void;
  handleCampfireContinue: () => void;
  handleShopContinue: () => void;
  handleShopBuyCard: (card: BattleCard) => void | null;
  handleShopRemoveCard: (index: number) => void;
  handleShopRefresh: () => void;
  handleAlchemistBuyCard: (card: BattleCard) => void | null;
  handleAlchemistContinue: () => void;
  handleAlchemistRefresh: () => void;
  handleAlchemistMixPotions: (a: number, b: number) => BattleCard | null;
  handleMysteryChoice: (choice: MysteryChoice) => void;
  handleMysteryChooseCard: (cardId: string) => void;
  handleMysteryRemoveCard: (index: number) => void;
  handleMysteryContinue: () => void;
  handleCorruptCard: (index: number) => void;
  handleCorruptionExit: () => void;
  handleLabyrinthNodeEnter: (row: number, col: number) => void;
  handleLabyrinthEndRun: () => void;
  resetRunState: () => void;
  returnToBattle: () => void;
  unlockTalent: (keywordId: KeywordId, talentId: string) => void;
  resetUnlockedTalents: () => void;
};
