export const LOADING_WORDS = [
  "Forging",
  "Growing",
  "Brewing",
  "Simmering",
  "Tinkering",
  "Prestidigitating",
  "Discombobulating",
  "Preparing your adventure",
  "Polishing ancient trinkets",
  "Shuffling the battle deck",
  "Awakening dungeon monsters",
  "Brewing health potions",
  "Gathering mana crystals",
  "Sharpening rusty blades",
  "Mapping labyrinth corridors",
  "Attuning magic relics",
  "Consulting the oracle",
  "Enchanting arcane baubles",
  "Counting monster loot",
  "Training animal companions",
  "Building a homestead",
  "Restocking mystery shops",
] as const;
