export const LOADING_WORDS = [
  "Adventure awaits",
  "Polishing trinkets",
  "Shuffling decks",
  "Waking monsters",
  "Brewing potions",
  "Gathering crystals",
  "Sharpening blades",
  "Mapping labyrinth",
  "Attuning relics",
  "Consulting oracle",
  "Enchanting baubles",
  "Counting loot",
  "Training companions",
  "Building homestead",
  "Restocking shops",
] as const;
