import { isRunResumeScreen, SCREEN_PHASE } from "./run-screen-router";
import { ROUTE_SCREENS, type Screen } from "./screens";

const META_DESTINATIONS = [
  ROUTE_SCREENS.MENU,
  ROUTE_SCREENS.COLLECTION,
  ROUTE_SCREENS.TALENTS,
  ROUTE_SCREENS.HOMESTEAD,
  ROUTE_SCREENS.ARMORY,
  ROUTE_SCREENS.OPTIONS,
] as const;

const RUN_LOOP_SHELL_DESTINATIONS = [...META_DESTINATIONS, ROUTE_SCREENS.GAME_OVER] as const;
const RUN_NODE_LEAVE_DESTINATIONS = [
  ...RUN_LOOP_SHELL_DESTINATIONS,
  ROUTE_SCREENS.DESTINATION,
  ROUTE_SCREENS.LABYRINTH_MAP,
] as const;
export interface ScreenTransitionOptions {
  delayMs?: number;
  immediate?: boolean;
  prepare?: () => void;

  guard?: () => boolean;
}

export const ALLOWED_SCREEN_TRANSITIONS: Record<Screen, readonly Screen[]> = {
  [ROUTE_SCREENS.MENU]: [ROUTE_SCREENS.GAME_MODE_SELECT, ...META_DESTINATIONS],
  [ROUTE_SCREENS.GAME_MODE_SELECT]: [...META_DESTINATIONS, ROUTE_SCREENS.CHARACTER_SELECT],
  [ROUTE_SCREENS.CHARACTER_SELECT]: [
    ...META_DESTINATIONS,
    ROUTE_SCREENS.GAME_MODE_SELECT,
    ROUTE_SCREENS.DIFFICULTY_SELECT,
    ROUTE_SCREENS.DRAFT_DECK,
    ROUTE_SCREENS.BATTLE,
    ROUTE_SCREENS.LABYRINTH_MAP,
  ],
  [ROUTE_SCREENS.DIFFICULTY_SELECT]: [
    ...META_DESTINATIONS,
    ROUTE_SCREENS.CHARACTER_SELECT,
    ROUTE_SCREENS.DRAFT_DECK,
    ROUTE_SCREENS.BATTLE,
  ],
  [ROUTE_SCREENS.DRAFT_DECK]: [
    ...META_DESTINATIONS,
    ROUTE_SCREENS.DIFFICULTY_SELECT,
    ROUTE_SCREENS.BATTLE,
    ROUTE_SCREENS.LABYRINTH_MAP,
  ],

  [ROUTE_SCREENS.OPTIONS]: [
    ...META_DESTINATIONS,
    ROUTE_SCREENS.GAME_OVER,
    ROUTE_SCREENS.RUN_VICTORY,
    ROUTE_SCREENS.GAME_MODE_SELECT,
    ROUTE_SCREENS.CHARACTER_SELECT,
    ROUTE_SCREENS.DIFFICULTY_SELECT,
    ROUTE_SCREENS.DESTINATION,
  ],
  [ROUTE_SCREENS.COLLECTION]: META_DESTINATIONS,
  [ROUTE_SCREENS.TALENTS]: META_DESTINATIONS,
  [ROUTE_SCREENS.HOMESTEAD]: META_DESTINATIONS,
  [ROUTE_SCREENS.ARMORY]: META_DESTINATIONS,
  [ROUTE_SCREENS.BATTLE]: [
    ...RUN_LOOP_SHELL_DESTINATIONS,
    ROUTE_SCREENS.REWARDS,
    ROUTE_SCREENS.RUN_VICTORY,
    ROUTE_SCREENS.LABYRINTH_MAP,
  ],
  [ROUTE_SCREENS.REWARDS]: [
    ...RUN_LOOP_SHELL_DESTINATIONS,
    ROUTE_SCREENS.BATTLE,
    ROUTE_SCREENS.DESTINATION,
    ROUTE_SCREENS.LABYRINTH_MAP,
    ROUTE_SCREENS.RUN_VICTORY,
    ROUTE_SCREENS.WILDWOOD_REMOVAL,
  ],
  [ROUTE_SCREENS.DESTINATION]: [
    ...RUN_LOOP_SHELL_DESTINATIONS,
    ROUTE_SCREENS.BATTLE,
    ROUTE_SCREENS.CAMPFIRE,
    ROUTE_SCREENS.SHOP,
    ROUTE_SCREENS.ALCHEMIST,
    ROUTE_SCREENS.TRINKET_SHOP,
    ROUTE_SCREENS.EQUIPMENT_SHOP,
    ROUTE_SCREENS.MYSTERY,
    ROUTE_SCREENS.CORRUPTION,
    ROUTE_SCREENS.LABYRINTH_MAP,
  ],
  [ROUTE_SCREENS.CAMPFIRE]: RUN_NODE_LEAVE_DESTINATIONS,
  [ROUTE_SCREENS.SHOP]: RUN_NODE_LEAVE_DESTINATIONS,
  [ROUTE_SCREENS.ALCHEMIST]: RUN_NODE_LEAVE_DESTINATIONS,
  [ROUTE_SCREENS.TRINKET_SHOP]: RUN_NODE_LEAVE_DESTINATIONS,
  [ROUTE_SCREENS.EQUIPMENT_SHOP]: RUN_NODE_LEAVE_DESTINATIONS,
  [ROUTE_SCREENS.MYSTERY]: RUN_NODE_LEAVE_DESTINATIONS,
  [ROUTE_SCREENS.CORRUPTION]: RUN_NODE_LEAVE_DESTINATIONS,
  [ROUTE_SCREENS.LABYRINTH_MAP]: [
    ...RUN_LOOP_SHELL_DESTINATIONS,
    ROUTE_SCREENS.BATTLE,
    ROUTE_SCREENS.DESTINATION,
    ROUTE_SCREENS.CAMPFIRE,
    ROUTE_SCREENS.SHOP,
    ROUTE_SCREENS.ALCHEMIST,
    ROUTE_SCREENS.TRINKET_SHOP,
    ROUTE_SCREENS.EQUIPMENT_SHOP,
    ROUTE_SCREENS.MYSTERY,
    ROUTE_SCREENS.CORRUPTION,
  ],
  [ROUTE_SCREENS.WILDWOOD_REMOVAL]: [...RUN_LOOP_SHELL_DESTINATIONS, ROUTE_SCREENS.BATTLE],
  [ROUTE_SCREENS.GAME_OVER]: META_DESTINATIONS,
  [ROUTE_SCREENS.RUN_VICTORY]: META_DESTINATIONS,
};

export function isScreenTransitionAllowed(from: Screen, to: Screen): boolean {
  return from === to || ALLOWED_SCREEN_TRANSITIONS[from].includes(to);
}

export function assertScreenTransitionAllowed(from: Screen, to: Screen): void {
  if (isScreenTransitionAllowed(from, to)) return;
  throw new Error(`Disallowed screen transition: ${from} -> ${to}`);
}

export function isRunResumeTransitionAllowed(from: Screen, to: Screen): boolean {
  return SCREEN_PHASE[from] === "meta" && isRunResumeScreen(to);
}

export function assertRunResumeTransitionAllowed(from: Screen, to: Screen): void {
  if (isRunResumeTransitionAllowed(from, to)) return;
  throw new Error(`Disallowed run resume transition: ${from} -> ${to}`);
}
