import { ROUTE_SCREENS, type Screen } from "./screens";

const META_DESTINATIONS = [
  ROUTE_SCREENS.MENU,
  ROUTE_SCREENS.COLLECTION,
  ROUTE_SCREENS.TALENTS,
  ROUTE_SCREENS.HOMESTEAD,
  ROUTE_SCREENS.ARMORY,
  ROUTE_SCREENS.OPTIONS,
] as const;

const RUN_LOOP_SCREENS = [
  ROUTE_SCREENS.BATTLE,
  ROUTE_SCREENS.REWARDS,
  ROUTE_SCREENS.DESTINATION,
  ROUTE_SCREENS.CAMPFIRE,
  ROUTE_SCREENS.SHOP,
  ROUTE_SCREENS.ALCHEMIST,
  ROUTE_SCREENS.TRINKET_SHOP,
  ROUTE_SCREENS.EQUIPMENT_SHOP,
  ROUTE_SCREENS.MYSTERY,
  ROUTE_SCREENS.CORRUPTION,
  ROUTE_SCREENS.LABYRINTH_MAP,
  ROUTE_SCREENS.WILDWOOD_REMOVAL,
] as const;

const RUN_LOOP_SHELL_DESTINATIONS = [...META_DESTINATIONS, ROUTE_SCREENS.GAME_OVER] as const;
const META_AND_RUN_RETURN_DESTINATIONS = [...META_DESTINATIONS, ...RUN_LOOP_SCREENS] as const;

/**
 * Runtime transition policy for every routed screen. Restore/hydration writes
 * bypass this table intentionally; interactive navigation must use it through
 * useScreenTransitions. Same-screen transitions are universally allowed so a
 * route can commit deferred state without remounting its screen.
 */
export const ALLOWED_SCREEN_TRANSITIONS: Record<Screen, readonly Screen[]> = {
  [ROUTE_SCREENS.MENU]: [
    ROUTE_SCREENS.GAME_MODE_SELECT,
    ROUTE_SCREENS.COLLECTION,
    ROUTE_SCREENS.TALENTS,
    ROUTE_SCREENS.HOMESTEAD,
    ROUTE_SCREENS.ARMORY,
    ROUTE_SCREENS.OPTIONS,
  ],
  [ROUTE_SCREENS.GAME_MODE_SELECT]: [
    ...META_DESTINATIONS,
    ROUTE_SCREENS.CHARACTER_SELECT,
    ROUTE_SCREENS.DRAFT_DECK,
    ...RUN_LOOP_SCREENS,
  ],
  [ROUTE_SCREENS.CHARACTER_SELECT]: [
    ...META_DESTINATIONS,
    ROUTE_SCREENS.GAME_MODE_SELECT,
    ROUTE_SCREENS.DIFFICULTY_SELECT,
    ROUTE_SCREENS.DRAFT_DECK,
    ROUTE_SCREENS.BATTLE,
    ROUTE_SCREENS.LABYRINTH_MAP,
  ],
  [ROUTE_SCREENS.DIFFICULTY_SELECT]: [...META_DESTINATIONS, ROUTE_SCREENS.CHARACTER_SELECT, ROUTE_SCREENS.BATTLE],
  [ROUTE_SCREENS.DRAFT_DECK]: [
    ...META_DESTINATIONS,
    ROUTE_SCREENS.DIFFICULTY_SELECT,
    ROUTE_SCREENS.BATTLE,
    ROUTE_SCREENS.LABYRINTH_MAP,
  ],
  [ROUTE_SCREENS.OPTIONS]: Object.values(ROUTE_SCREENS),
  [ROUTE_SCREENS.COLLECTION]: META_AND_RUN_RETURN_DESTINATIONS,
  [ROUTE_SCREENS.TALENTS]: META_AND_RUN_RETURN_DESTINATIONS,
  [ROUTE_SCREENS.HOMESTEAD]: META_AND_RUN_RETURN_DESTINATIONS,
  [ROUTE_SCREENS.ARMORY]: META_AND_RUN_RETURN_DESTINATIONS,
  [ROUTE_SCREENS.BATTLE]: [
    ...RUN_LOOP_SHELL_DESTINATIONS,
    ROUTE_SCREENS.REWARDS,
    ROUTE_SCREENS.RUN_VICTORY,
    ROUTE_SCREENS.LABYRINTH_MAP,
  ],
  [ROUTE_SCREENS.REWARDS]: [
    ...RUN_LOOP_SHELL_DESTINATIONS,
    ROUTE_SCREENS.BATTLE,
    ROUTE_SCREENS.DESTINATION,
    ROUTE_SCREENS.LABYRINTH_MAP,
    ROUTE_SCREENS.RUN_VICTORY,
    ROUTE_SCREENS.WILDWOOD_REMOVAL,
  ],
  [ROUTE_SCREENS.DESTINATION]: [
    ...RUN_LOOP_SHELL_DESTINATIONS,
    ROUTE_SCREENS.BATTLE,
    ROUTE_SCREENS.CAMPFIRE,
    ROUTE_SCREENS.SHOP,
    ROUTE_SCREENS.ALCHEMIST,
    ROUTE_SCREENS.TRINKET_SHOP,
    ROUTE_SCREENS.EQUIPMENT_SHOP,
    ROUTE_SCREENS.MYSTERY,
    ROUTE_SCREENS.CORRUPTION,
    ROUTE_SCREENS.LABYRINTH_MAP,
  ],
  [ROUTE_SCREENS.CAMPFIRE]: [...RUN_LOOP_SHELL_DESTINATIONS, ROUTE_SCREENS.DESTINATION, ROUTE_SCREENS.LABYRINTH_MAP],
  [ROUTE_SCREENS.SHOP]: [...RUN_LOOP_SHELL_DESTINATIONS, ROUTE_SCREENS.DESTINATION, ROUTE_SCREENS.LABYRINTH_MAP],
  [ROUTE_SCREENS.ALCHEMIST]: [...RUN_LOOP_SHELL_DESTINATIONS, ROUTE_SCREENS.DESTINATION, ROUTE_SCREENS.LABYRINTH_MAP],
  [ROUTE_SCREENS.TRINKET_SHOP]: [
    ...RUN_LOOP_SHELL_DESTINATIONS,
    ROUTE_SCREENS.DESTINATION,
    ROUTE_SCREENS.LABYRINTH_MAP,
  ],
  [ROUTE_SCREENS.EQUIPMENT_SHOP]: [
    ...RUN_LOOP_SHELL_DESTINATIONS,
    ROUTE_SCREENS.DESTINATION,
    ROUTE_SCREENS.LABYRINTH_MAP,
  ],
  [ROUTE_SCREENS.MYSTERY]: [...RUN_LOOP_SHELL_DESTINATIONS, ROUTE_SCREENS.DESTINATION, ROUTE_SCREENS.LABYRINTH_MAP],
  [ROUTE_SCREENS.CORRUPTION]: [...RUN_LOOP_SHELL_DESTINATIONS, ROUTE_SCREENS.DESTINATION, ROUTE_SCREENS.LABYRINTH_MAP],
  [ROUTE_SCREENS.LABYRINTH_MAP]: [
    ...RUN_LOOP_SHELL_DESTINATIONS,
    ROUTE_SCREENS.BATTLE,
    ROUTE_SCREENS.CAMPFIRE,
    ROUTE_SCREENS.SHOP,
    ROUTE_SCREENS.ALCHEMIST,
    ROUTE_SCREENS.TRINKET_SHOP,
    ROUTE_SCREENS.EQUIPMENT_SHOP,
    ROUTE_SCREENS.MYSTERY,
  ],
  [ROUTE_SCREENS.WILDWOOD_REMOVAL]: [...RUN_LOOP_SHELL_DESTINATIONS, ROUTE_SCREENS.BATTLE],
  [ROUTE_SCREENS.GAME_OVER]: META_DESTINATIONS,
  [ROUTE_SCREENS.RUN_VICTORY]: META_DESTINATIONS,
};

export function isScreenTransitionAllowed(from: Screen, to: Screen): boolean {
  return from === to || ALLOWED_SCREEN_TRANSITIONS[from].includes(to);
}

export function assertScreenTransitionAllowed(from: Screen, to: Screen): void {
  if (isScreenTransitionAllowed(from, to)) return;
  throw new Error(`Disallowed screen transition: ${from} -> ${to}`);
}
