import type { GearAffixId } from "./affix-ids";

export type GearAffixNameParts = {
  prefix?: string;
  suffix?: string;
};

export const gearAffixNameParts: Record<GearAffixId, GearAffixNameParts> = {
  "flat-physical": { prefix: "Ironbound", suffix: "the Crusher" },
  "flat-stun": { prefix: "Concussive", suffix: "the Stagger" },
  "flat-holy": { prefix: "Sanctified", suffix: "the Radiant" },
  "flat-burn": { prefix: "Blazing", suffix: "Embers" },
  "flat-poison": { prefix: "Venomous", suffix: "the Toxin" },
  "flat-bleed": { prefix: "Serrated", suffix: "the Rend" },
  "flat-freeze": { prefix: "Glacial", suffix: "the Rime" },
  "flat-nature": { prefix: "Wildheart", suffix: "the Grove" },
  "start-block": { prefix: "Bastioned", suffix: "the Bulwark" },
  "armor-pierce": { prefix: "Piercing", suffix: "the Breach" },
  "damage-on-stun": { prefix: "Stunning", suffix: "the Impact" },
  "forge-on-stun": { prefix: "Forged", suffix: "the Anvil" },
  "poison-leech": { prefix: "Leeching", suffix: "the Miasma" },
  "companion-damage": { prefix: "Packbound", suffix: "the Kin" },
  "start-heal": { prefix: "Vital", suffix: "Renewal" },
  "heal-on-kill": { prefix: "Gravebound", suffix: "the Reaper's Gift" },
  "start-forge": { prefix: "Tempered", suffix: "the Smith" },
  "start-armor": { prefix: "Plated", suffix: "the Ward" },
  "block-on-stun": { prefix: "Steadfast", suffix: "the Counter" },
  "mana-on-stun": { prefix: "Arcane", suffix: "the Spark" },
  "physical-bleed-chance": { prefix: "Bloodletting", suffix: "the Cut" },
  "burn-per-mana": { prefix: "Pyric", suffix: "the Conduit" },
  "gold-on-wish": { prefix: "Wishful", suffix: "Fortune" },
  "burn-on-wish": { prefix: "Wishfire", suffix: "the Cinder" },
  "gold-on-kill": { suffix: "Greed" },
  "physical-stun-chance": { prefix: "Thunderous", suffix: "the Tremor" },
  "nature-leech": { prefix: "Sylvan", suffix: "the Draught" },
  "forge-on-burn": { prefix: "Emberforged", suffix: "the Crucible" },
  "draw-on-wish": { prefix: "Fateful", suffix: "the Draw" },
  "consume-heal-bonus": { prefix: "Nourishing", suffix: "the Feast" },
  "archery-damage": { prefix: "Fletched", suffix: "the Quiver" },
  "damage-on-freeze": { prefix: "Shattering", suffix: "the Frostbite" },
  "heal-on-block-depleted": { prefix: "Resolute", suffix: "the Last Stand" },
  "health-on-wish": { prefix: "Wishborn", suffix: "the Boon" },
  "mana-on-wish": { prefix: "Wishwoven", suffix: "the Well" },
  "start-freeze": { prefix: "Bitter", suffix: "the Chill" },
  "holy-from-block": { prefix: "Aegis", suffix: "the Sanctum" },
  "leech-potency": { prefix: "Leeching" },
  "frozen-vulnerable": { prefix: "Frigid", suffix: "the Shatter" },
  "companion-forge-power": { prefix: "Bonded", suffix: "the Hammer" },
  "gold-blessed-holy": { prefix: "Aureate", suffix: "the Benediction" },
  "resist-physical": { prefix: "Stoneward", suffix: "the Bastion" },
  "resist-stun": { prefix: "Unshaken", suffix: "the Anchor" },
  "resist-holy": { prefix: "Shadowveiled", suffix: "the Veil" },
  "resist-burn": { prefix: "Fireproof", suffix: "the Ashen Shell" },
  "resist-poison": { prefix: "Antivenom", suffix: "the Filter" },
  "resist-bleed": { prefix: "Scarbound", suffix: "the Scar" },
  "resist-freeze": { prefix: "Warmblooded", suffix: "the Hearth" },
  "resist-nature": { prefix: "Thornward", suffix: "the Bramble" },
  "health-per-turn": { prefix: "Lifegiving", suffix: "the Pulse" },
  "block-gain": { prefix: "Warding", suffix: "the Rampart" },
  "gold-gain": { prefix: "Prosperous", suffix: "the Hoard" },
  "max-health": { prefix: "Enduring", suffix: "the Titan" },
  "burn-on-consume": { prefix: "Consuming", suffix: "the Pyre" },
  "archery-ignore-armor": { prefix: "Armorbreaking", suffix: "the Piercer" },
  "absorb-per-mana": { prefix: "Aegis", suffix: "the Conduit" },
  "heal-on-burn-death": { prefix: "Cauterizing", suffix: "the Ashes" },
  "mana-on-leech-chance": { prefix: "Siphoning", suffix: "the Spark" },
  "poison-reduces-armor": { prefix: "Corrosive", suffix: "the Acid" },
  "nature-mana-refund-chance": { prefix: "Bloomwoven", suffix: "the Spring" },
  "burn-on-bleed": { prefix: "Cinderbound", suffix: "the Flayer" },
  "stun-on-block-hit": { prefix: "Reactive", suffix: "the Rebound" },
  "companion-leech": { prefix: "Kinbound", suffix: "the Pack's Aid" },
  "armor-on-cc": { prefix: "Stalwart", suffix: "the Resilient" },
};
