import type { KeywordId } from "@/lib/game-data";
import type { GearEffectManifest } from "./gear-effect-manifest";
import type { GearRarity } from "./types";

export type GearAffixAspect = "offensive" | "defensive";

type AffixRollRange = Record<GearRarity, { min: number; max: number }>;

function rollRange(basicMin: number, basicMax: number, astralMin: number, astralMax: number): AffixRollRange {
  return {
    basic: { min: basicMin, max: basicMax },
    astral: { min: astralMin, max: astralMax },
    unique: { min: astralMin, max: astralMax },
  };
}

function uniqueRoll(value: number): AffixRollRange {
  return {
    basic: { min: value, max: value },
    astral: { min: value, max: value },
    unique: { min: value, max: value },
  };
}

const ROLL_SMALL = rollRange(1, 2, 3, 4);
const ROLL_RESIST = rollRange(10, 15, 15, 20);
// Percent-based bonuses share the resist numbers today but tune independently:
// retuning resists must never silently retune the economy.
const ROLL_PERCENT = rollRange(10, 15, 15, 20);
const ROLL_MEDIUM = rollRange(3, 4, 5, 6);

export interface GearAffixDefinition {
  id: GearAffixId;
  name: string;
  aspect: GearAffixAspect;
  keywordId: KeywordId;
  secondaryKeywordId?: KeywordId;
  descriptionTemplate: string;
  effectKey: keyof GearEffectManifest;
  roll: AffixRollRange;
  uniqueOnly?: boolean;
}

type AffixRowInput = Omit<GearAffixDefinition, "id"> & { id: string };

// Single description formatter for every consumer (tooltips and the unique
// catalog). Templates may contain more than one {value} placeholder.
export function formatAffixDescription(template: string, value: number): string {
  return template.replaceAll("{value}", String(value));
}

function uniqueAffix<const T extends string>(
  id: T,
  name: string,
  aspect: GearAffixAspect,
  keywordId: KeywordId,
  descriptionTemplate: string,
  effectKey: keyof GearEffectManifest,
  secondaryKeywordId?: KeywordId,
  rollValue = 1,
): AffixRowInput & { id: T } {
  return {
    id,
    name,
    aspect,
    keywordId,
    ...(secondaryKeywordId ? { secondaryKeywordId } : {}),
    descriptionTemplate,
    effectKey,
    roll: uniqueRoll(rollValue),
    uniqueOnly: true,
  };
}

function resistAffix<const T extends string>(
  id: T,
  name: string,
  keywordId: KeywordId,
  effectKey: keyof GearEffectManifest,
): AffixRowInput & { id: T } {
  const label = keywordId.charAt(0).toUpperCase() + keywordId.slice(1);
  return {
    id,
    name,
    aspect: "defensive",
    keywordId,
    descriptionTemplate: `Reduce ${label} damage taken by {value}%`,
    effectKey,
    roll: ROLL_RESIST,
  };
}

const affixRows = [
  uniqueAffix(
    "the-unclosing-wound",
    "The Unclosing Wound",
    "offensive",
    "bleed",
    "Enemy Bleed halves each turn instead of expiring.",
    "bleedDecaysByHalf",
    "physical",
  ),
  uniqueAffix(
    "kingbreaker",
    "Kingbreaker",
    "offensive",
    "stun",
    "Enemy Armor increases your Stun damage instead of reducing it.",
    "armorIncreasesStun",
    "physical",
  ),
  uniqueAffix(
    "everkeen",
    "Everkeen",
    "offensive",
    "forge",
    "Gaining Forge makes your next Physical card strike twice.",
    "forgeReadiesPhysicalRepeat",
    "physical",
  ),
  uniqueAffix(
    "red-harvest",
    "Red Harvest",
    "offensive",
    "physical",
    "Each turn, return your first Physical card to hand. It costs 1 less Mana.",
    "returnFirstPhysicalCard",
    "bleed",
  ),
  uniqueAffix(
    "oathkeeper",
    "Oathkeeper",
    "offensive",
    "forge",
    "Forge also strengthens Holy damage. Holy damage never spends Forge.",
    "holyPreservesForge",
    "holy",
  ),
  uniqueAffix(
    "the-patient-edge",
    "The Patient Edge",
    "offensive",
    "forge",
    "Recover Forge spent on attacks at the start of your next turn.",
    "recoverSpentForge",
    "physical",
  ),
  uniqueAffix(
    "vipers-courtesy",
    "Viper’s Courtesy",
    "offensive",
    "dodge",
    "After Dodging, your next Physical hit adds half its damage as Poison and Bleed.",
    "dodgeReadiesVenomousHit",
    "poison",
  ),
  uniqueAffix(
    "the-lingering-bell",
    "The Lingering Bell",
    "offensive",
    "stun",
    "Stunning an enemy preserves a quarter of its Stun buildup.",
    "retainStunBuildup",
    "holy",
  ),
  uniqueAffix(
    "huntsmasters-call",
    "Huntsmaster’s Call",
    "offensive",
    "archery",
    "Your first Archery card each turn makes all Companions attack again.",
    "firstArcheryCompanionAttack",
    "companion",
  ),
  uniqueAffix(
    "wrenflight",
    "Wrenflight",
    "offensive",
    "archery",
    "Archery grants 10% Dodge until your next turn. Dodging draws an Archery card.",
    "archeryDodgeAndDraw",
    "dodge",
  ),
  uniqueAffix(
    "the-returning-gale",
    "The Returning Gale",
    "offensive",
    "archery",
    "Archery cards repeat their damage at half strength next turn.",
    "archeryEchoNextTurn",
    "nature",
  ),
  uniqueAffix(
    "the-final-spark",
    "The Final Spark",
    "offensive",
    "mana",
    "Spend your last Mana to repeat a Burn or Freeze card’s damage. Once per turn.",
    "lastManaElementalRepeat",
    "burn",
  ),
  uniqueAffix(
    "laughing-guard",
    "Laughing Guard",
    "defensive",
    "block",
    "Keep Block between turns. Dodging spends half your Block to deal that much Physical damage.",
    "dodgeSpendsPreservedBlock",
    "dodge",
  ),
  uniqueAffix(
    "the-knights-answer",
    "The Knight’s Answer",
    "defensive",
    "block",
    "Blocking an attack makes your next Physical card free.",
    "blockReadiesFreePhysical",
    "physical",
  ),
  uniqueAffix(
    "the-returning-flight",
    "The Returning Flight",
    "offensive",
    "archery",
    "Each turn, recover your last Archery card. It costs 1 less Mana.",
    "recoverLastArcheryCard",
    "dodge",
  ),
  uniqueAffix(
    "threefold-grace",
    "Threefold Grace",
    "offensive",
    "burn",
    "Your first Burn, Freeze, and Holy card each turn costs no Mana.",
    "firstElementalCardsFree",
    "freeze",
  ),
  uniqueAffix(
    "bloodember-pendant",
    "Bloodember Pendant",
    "offensive",
    "burn",
    "Burn and Bleed share their damage bonuses.",
    "sharedBurnBleedBonuses",
    "bleed",
  ),
  uniqueAffix(
    "winters-credit",
    "Winter’s Credit",
    "offensive",
    "freeze",
    "Spend 3 Block per missing Mana to play Freeze cards.",
    "blockPaysFreezeMana",
    "mana",
  ),
  uniqueAffix(
    "serpents-eye",
    "Serpent’s Eye",
    "offensive",
    "poison",
    "Attacks against Poisoned enemies ignore Armor and cannot be Dodged.",
    "poisonedAttacksPierce",
    "archery",
  ),
  uniqueAffix(
    "wildhearts-favor",
    "Wildheart’s Favor",
    "defensive",
    "dodge",
    "Dodging makes your next Nature card free and guarantees its damage Critically Hits.",
    "dodgeReadiesNatureCrit",
    "nature",
  ),
  uniqueAffix(
    "the-golden-crucible",
    "The Golden Crucible",
    "offensive",
    "gold",
    "Without Forge, combat Gold gains grant equal Forge. Forge also increases Holy damage",
    "goldGrantsForgeAndHoly",
    "forge",
  ),
  {
    id: "flat-physical",
    name: "Ironbound",
    aspect: "offensive",
    keywordId: "physical",
    descriptionTemplate: "Increases Physical damage by {value}",
    effectKey: "flatPhysicalDamage",
    roll: ROLL_SMALL,
  },
  {
    id: "flat-stun",
    name: "Concussive",
    aspect: "offensive",
    keywordId: "stun",
    descriptionTemplate: "Increases Stun damage by {value}",
    effectKey: "flatStunDamage",
    roll: ROLL_SMALL,
  },
  {
    id: "flat-holy",
    name: "Sanctified",
    aspect: "offensive",
    keywordId: "holy",
    descriptionTemplate: "Increases Holy damage by {value}",
    effectKey: "flatHolyDamage",
    roll: ROLL_SMALL,
  },
  {
    id: "flat-burn",
    name: "Blazing",
    aspect: "offensive",
    keywordId: "burn",
    descriptionTemplate: "Increases Burn damage by {value}",
    effectKey: "flatBurnDamage",
    roll: ROLL_SMALL,
  },
  {
    id: "flat-poison",
    name: "Venomous",
    aspect: "offensive",
    keywordId: "poison",
    descriptionTemplate: "Increases Poison damage by {value}",
    effectKey: "flatPoisonDamage",
    roll: ROLL_SMALL,
  },
  {
    id: "flat-bleed",
    name: "Serrated",
    aspect: "offensive",
    keywordId: "bleed",
    descriptionTemplate: "Increases Bleed damage by {value}",
    effectKey: "flatBleedDamage",
    roll: ROLL_SMALL,
  },
  {
    id: "flat-freeze",
    name: "Glacial",
    aspect: "offensive",
    keywordId: "freeze",
    descriptionTemplate: "Increases Freeze damage by {value}",
    effectKey: "flatFreezeDamage",
    roll: ROLL_SMALL,
  },
  {
    id: "flat-nature",
    name: "Wildheart",
    aspect: "offensive",
    keywordId: "nature",
    descriptionTemplate: "Increases Nature damage by {value}",
    effectKey: "flatNatureDamage",
    roll: ROLL_SMALL,
  },
  {
    id: "start-block",
    name: "Bastioned",
    aspect: "defensive",
    keywordId: "block",
    descriptionTemplate: "Gain {value} Block at the start of combat",
    effectKey: "startBlock",
    roll: rollRange(4, 6, 7, 9),
  },
  {
    id: "armor-pierce",
    name: "Piercing",
    aspect: "offensive",
    keywordId: "physical",
    descriptionTemplate: "Ignore {value} enemy Armor",
    effectKey: "armorPiercing",
    roll: rollRange(1, 2, 2, 4),
  },
  {
    id: "damage-on-stun",
    name: "Stunning",
    aspect: "offensive",
    keywordId: "physical",
    descriptionTemplate: "Deal {value} Physical damage when you Stun an enemy",
    effectKey: "damageOnStunPhysical",
    roll: ROLL_MEDIUM,
  },
  {
    id: "forge-on-stun",
    name: "Forged",
    aspect: "offensive",
    keywordId: "forge",
    descriptionTemplate: "If you have no Forge, Stunning an enemy grants {value} Forge",
    effectKey: "forgeOnStun",
    roll: rollRange(1, 2, 2, 4),
  },
  {
    id: "poison-leech",
    name: "Leeching",
    aspect: "offensive",
    keywordId: "leech",
    descriptionTemplate: "Poison has a {value}% chance to Leech",
    effectKey: "poisonLeechChance",
    roll: rollRange(5, 7, 8, 10),
    secondaryKeywordId: "poison",
  },
  {
    id: "companion-damage",
    name: "Packbound",
    aspect: "offensive",
    keywordId: "companion",
    descriptionTemplate: "Increases Companion damage by {value}",
    effectKey: "companionDamageBonus",
    roll: rollRange(1, 2, 2, 4),
  },
  {
    id: "start-heal",
    name: "Vital",
    aspect: "defensive",
    keywordId: "health",
    descriptionTemplate: "Restore {value} Health at the start of combat",
    effectKey: "startHeal",
    roll: ROLL_MEDIUM,
  },
  {
    id: "heal-on-kill",
    name: "Gravebound",
    aspect: "defensive",
    keywordId: "health",
    descriptionTemplate: "Restore {value} Health on kill",
    effectKey: "healOnKill",
    roll: ROLL_MEDIUM,
  },
  {
    id: "start-forge",
    name: "Tempered",
    aspect: "defensive",
    keywordId: "forge",
    descriptionTemplate: "Gain {value} Forge at the start of combat",
    effectKey: "startForge",
    roll: rollRange(1, 2, 2, 4),
  },
  {
    id: "start-armor",
    name: "Plated",
    aspect: "defensive",
    keywordId: "armor",
    descriptionTemplate: "Gain {value} Armor at the start of combat",
    effectKey: "startArmor",
    roll: rollRange(1, 2, 2, 4),
  },
  {
    id: "block-on-stun",
    name: "Steadfast",
    aspect: "defensive",
    keywordId: "block",
    descriptionTemplate: "If you have no Block, Stunning an enemy grants {value} Block",
    effectKey: "blockOnStun",
    roll: ROLL_MEDIUM,
  },
  {
    id: "mana-on-stun",
    name: "Arcane",
    aspect: "offensive",
    keywordId: "mana",
    descriptionTemplate: "If you have no Mana, Stunning an enemy grants {value} Mana",
    effectKey: "manaOnStun",
    roll: rollRange(1, 1, 2, 2),
  },
  {
    id: "physical-bleed-chance",
    name: "Bloodletting",
    aspect: "offensive",
    keywordId: "bleed",
    descriptionTemplate: "{value}% chance for Physical damage to Bleed",
    effectKey: "physicalBleedChance",
    roll: rollRange(7, 8, 9, 10),
    secondaryKeywordId: "physical",
  },
  {
    id: "burn-per-mana",
    name: "Pyric",
    aspect: "offensive",
    keywordId: "burn",
    descriptionTemplate: "Increases Burn damage by {value}% per Mana Crystal",
    effectKey: "burnDamagePerManaPercent",
    roll: ROLL_PERCENT,
    secondaryKeywordId: "mana",
  },
  {
    id: "gold-on-wish",
    name: "Wishful",
    aspect: "offensive",
    keywordId: "gold",
    descriptionTemplate: "When you Wish, sometimes gain {value} Gold (50% chance)",
    effectKey: "goldOnWish",
    roll: ROLL_SMALL,
    secondaryKeywordId: "wish",
  },
  {
    id: "burn-on-wish",
    name: "Wishfire",
    aspect: "offensive",
    keywordId: "burn",
    descriptionTemplate: "When you Wish, deal {value} Burn damage to Burning enemies",
    effectKey: "burnOnWish",
    roll: ROLL_SMALL,
    secondaryKeywordId: "wish",
  },
  {
    id: "gold-on-kill",
    name: "Greed",
    aspect: "offensive",
    keywordId: "gold",
    descriptionTemplate: "Gain {value} Gold on kill",
    effectKey: "goldOnKill",
    roll: rollRange(4, 5, 6, 7),
  },
  {
    id: "physical-stun-chance",
    name: "Thunderous",
    aspect: "offensive",
    keywordId: "stun",
    descriptionTemplate: "{value}% chance for Physical damage to Stun",
    effectKey: "physicalStunChance",
    roll: rollRange(5, 10, 10, 15),
    secondaryKeywordId: "physical",
  },
  {
    id: "nature-leech",
    name: "Sylvan",
    aspect: "offensive",
    keywordId: "leech",
    descriptionTemplate: "Nature damage has a {value}% chance to Leech",
    effectKey: "natureLeechChance",
    roll: rollRange(7, 8, 9, 10),
    secondaryKeywordId: "nature",
  },
  {
    id: "forge-on-burn",
    name: "Emberforged",
    aspect: "offensive",
    keywordId: "forge",
    descriptionTemplate: "Your first Burn attack each turn grants {value} Forge",
    effectKey: "forgeOnBurnDealt",
    roll: rollRange(1, 1, 2, 2),
    secondaryKeywordId: "burn",
  },
  {
    id: "draw-on-wish",
    name: "Fateful",
    aspect: "offensive",
    keywordId: "wish",
    descriptionTemplate: "Draw {value} Cards on Wish",
    effectKey: "drawOnWish",
    roll: rollRange(1, 1, 2, 2),
  },
  {
    id: "consume-heal-bonus",
    name: "Nourishing",
    aspect: "defensive",
    keywordId: "consume",
    descriptionTemplate: "Increases Health restored by Consumed cards by {value}%",
    effectKey: "consumeHealBonusPercent",
    roll: ROLL_PERCENT,
    secondaryKeywordId: "health",
  },
  {
    id: "archery-damage",
    name: "Fletched",
    aspect: "offensive",
    keywordId: "archery",
    descriptionTemplate: "Increases Archery damage by {value}",
    effectKey: "flatArrowDamage",
    roll: rollRange(2, 3, 4, 5),
  },
  {
    id: "damage-on-freeze",
    name: "Shattering",
    aspect: "offensive",
    keywordId: "physical",
    descriptionTemplate: "Deal {value} Physical damage when you Freeze an enemy",
    effectKey: "damageOnFreezePhysical",
    roll: ROLL_MEDIUM,
    secondaryKeywordId: "freeze",
  },
  {
    id: "heal-on-block-depleted",
    name: "Resolute",
    aspect: "defensive",
    keywordId: "health",
    descriptionTemplate: "Restore {value} Health when Block is depleted",
    effectKey: "blockDepletedHeal",
    roll: rollRange(2, 3, 4, 5),
    secondaryKeywordId: "block",
  },
  {
    id: "health-on-wish",
    name: "Wishborn",
    aspect: "defensive",
    keywordId: "health",
    descriptionTemplate: "When you Wish below half Health, restore {value} Health",
    effectKey: "healthOnWish",
    roll: rollRange(2, 3, 4, 5),
    secondaryKeywordId: "wish",
  },
  {
    id: "mana-on-wish",
    name: "Wishwoven",
    aspect: "offensive",
    keywordId: "mana",
    descriptionTemplate: "When you Wish without Mana, gain {value} Mana",
    effectKey: "manaOnWish",
    roll: rollRange(1, 1, 2, 2),
    secondaryKeywordId: "wish",
  },
  {
    id: "start-freeze",
    name: "Bitter",
    aspect: "defensive",
    keywordId: "freeze",
    descriptionTemplate: "Deal {value} Freeze damage at the start of combat",
    effectKey: "startFreeze",
    roll: rollRange(4, 5, 6, 7),
  },
  {
    id: "holy-from-block",
    name: "Aegis",
    aspect: "offensive",
    keywordId: "holy",
    descriptionTemplate: "Increases Holy damage by {value}% of your Block",
    effectKey: "holyDamageFromBlockPercent",
    roll: ROLL_PERCENT,
    secondaryKeywordId: "block",
  },
  {
    id: "leech-potency",
    name: "Sanguine",
    aspect: "offensive",
    keywordId: "leech",
    descriptionTemplate: "Leech restores {value}% more Health",
    effectKey: "leechHealBonusPercent",
    roll: ROLL_PERCENT,
  },
  {
    id: "frozen-vulnerable",
    name: "Frigid",
    aspect: "offensive",
    keywordId: "freeze",
    descriptionTemplate: "Frozen enemies take {value}% more damage",
    effectKey: "frozenEnemyDamageBonusPercent",
    roll: ROLL_PERCENT,
  },
  uniqueAffix(
    "companion-forge-power",
    "Bonded",
    "offensive",
    "companion",
    "Companions benefit from Forge",
    "companionBenefitsFromForge",
    "forge",
  ),
  {
    id: "gold-blessed-holy",
    name: "Aureate",
    aspect: "offensive",
    keywordId: "holy",
    descriptionTemplate: "Increases Holy damage by {value}% of your Gold",
    effectKey: "holyDamageFromGoldPercent",
    roll: rollRange(2, 3, 4, 5),
    secondaryKeywordId: "gold",
  },
  resistAffix("resist-physical", "Stoneward", "physical", "resistPhysical"),
  resistAffix("resist-stun", "Unshaken", "stun", "resistStun"),
  resistAffix("resist-holy", "Shadowveiled", "holy", "resistHoly"),
  resistAffix("resist-burn", "Fireproof", "burn", "resistBurn"),
  resistAffix("resist-poison", "Antivenom", "poison", "resistPoison"),
  resistAffix("resist-bleed", "Scarbound", "bleed", "resistBleed"),
  resistAffix("resist-freeze", "Warmblooded", "freeze", "resistFreeze"),
  resistAffix("resist-nature", "Thornward", "nature", "resistNature"),
  {
    id: "health-per-turn",
    name: "Lifegiving",
    aspect: "defensive",
    keywordId: "health",
    descriptionTemplate: "Restore {value} Health each turn",
    effectKey: "healthPerTurn",
    roll: rollRange(1, 1, 1, 1),
  },
  {
    id: "block-gain",
    name: "Warding",
    aspect: "defensive",
    keywordId: "block",
    descriptionTemplate: "Increases Block gained by {value}",
    effectKey: "flatBlockGained",
    roll: ROLL_SMALL,
  },
  {
    id: "gold-gain",
    name: "Prosperous",
    aspect: "defensive",
    keywordId: "gold",
    descriptionTemplate: "Increases Gold gained by {value}%",
    effectKey: "goldGainPercent",
    roll: ROLL_PERCENT,
  },
  {
    id: "max-health",
    name: "Enduring",
    aspect: "defensive",
    keywordId: "health",
    descriptionTemplate: "Increases Health by {value}",
    effectKey: "maxHealth",
    roll: rollRange(7, 8, 9, 10),
  },
  {
    id: "burn-on-consume",
    name: "Consuming",
    aspect: "offensive",
    keywordId: "consume",
    descriptionTemplate: "Burn cards with Consume deal {value} additional Burn damage",
    effectKey: "burnOnConsume",
    roll: rollRange(2, 3, 4, 6),
    secondaryKeywordId: "burn",
  },
  {
    id: "archery-ignore-armor",
    name: "Armorbreaking",
    aspect: "offensive",
    keywordId: "archery",
    descriptionTemplate: "Archery attacks ignore {value} Armor",
    effectKey: "archeryArmorPiercing",
    roll: ROLL_SMALL,
    secondaryKeywordId: "physical",
  },
  {
    id: "absorb-per-mana",
    name: "Aetherward",
    aspect: "defensive",
    keywordId: "mana",
    descriptionTemplate: "Reduce damage taken by {value} for each full Mana Crystal",
    effectKey: "damageReductionPerMana",
    roll: rollRange(2, 3, 4, 5),
    secondaryKeywordId: "block",
  },
  {
    id: "heal-on-burn-death",
    name: "Cauterizing",
    aspect: "defensive",
    keywordId: "burn",
    descriptionTemplate: "Restore {value} Health when an enemy with Burn is defeated",
    effectKey: "healOnBurnEnemyDefeated",
    roll: rollRange(4, 5, 6, 7),
    secondaryKeywordId: "health",
  },
  {
    id: "mana-on-leech-chance",
    name: "Siphoning",
    aspect: "offensive",
    keywordId: "leech",
    descriptionTemplate: "Leech has a {value}% chance to restore 1 Mana",
    effectKey: "manaOnLeechChance",
    roll: ROLL_PERCENT,
    secondaryKeywordId: "mana",
  },
  {
    id: "poison-reduces-armor",
    name: "Corrosive",
    aspect: "offensive",
    keywordId: "poison",
    descriptionTemplate: "Poison has a {value}% chance to remove 1 Armor",
    effectKey: "poisonArmorShredChance",
    roll: ROLL_PERCENT,
    secondaryKeywordId: "armor",
  },
  {
    id: "nature-mana-refund-chance",
    name: "Bloomwoven",
    aspect: "offensive",
    keywordId: "nature",
    descriptionTemplate: "Nature damage has a {value}% chance to restore 1 Mana",
    effectKey: "manaOnNatureDamageChance",
    roll: ROLL_PERCENT,
    secondaryKeywordId: "mana",
  },
  {
    id: "burn-on-bleed",
    name: "Cinderbound",
    aspect: "offensive",
    keywordId: "bleed",
    descriptionTemplate: "Burn deals {value}% more damage to Bleeding enemies",
    effectKey: "burnDamageBonusToBleedingPercent",
    roll: ROLL_PERCENT,
    secondaryKeywordId: "burn",
  },
  {
    id: "stun-on-block-hit",
    name: "Reactive",
    aspect: "defensive",
    keywordId: "block",
    descriptionTemplate: "Deal {value} Stun damage when your Block is depleted",
    effectKey: "stunOnBlockDepleted",
    roll: rollRange(2, 3, 4, 5),
    secondaryKeywordId: "stun",
  },
  {
    id: "companion-leech",
    name: "Kinbound",
    aspect: "defensive",
    keywordId: "companion",
    descriptionTemplate: "Below half Health, restore {value} Health when your Companion deals damage",
    effectKey: "healOnCompanionAttack",
    roll: ROLL_SMALL,
    secondaryKeywordId: "health",
  },
  {
    id: "armor-on-cc",
    name: "Stalwart",
    aspect: "defensive",
    keywordId: "armor",
    descriptionTemplate: "Gain {value} Armor when you are Stunned or Frozen",
    effectKey: "armorOnStunOrFreeze",
    roll: ROLL_SMALL,
    secondaryKeywordId: "stun",
  },
  uniqueAffix(
    "wardbreaker-purge",
    "Wardbreaking",
    "offensive",
    "stun",
    "Your attacks Purge one enemy buff and deal {value} Holy damage",
    "attackPurgeDealHolyPerEffect",
    "holy",
  ),
  uniqueAffix(
    "dance-of-blades",
    "Bladedance",
    "defensive",
    "dodge",
    "When you Dodge, you have a 25% chance to draw and play a random card",
    "dodgeDrawAndPlay",
    "physical",
  ),
  {
    id: "dodge-chance",
    name: "Elusive",
    aspect: "defensive",
    keywordId: "dodge",
    descriptionTemplate: "Increases Dodge chance by {value}%",
    effectKey: "dodgeChance",
    roll: rollRange(1, 2, 2, 3),
  },
  {
    id: "dodge-block",
    name: "Nimble",
    aspect: "defensive",
    keywordId: "dodge",
    descriptionTemplate: "When you Dodge without Block, gain {value} Block",
    effectKey: "blockOnDodge",
    roll: rollRange(2, 3, 4, 5),
  },
  {
    id: "dodge-heal",
    name: "Winded",
    aspect: "defensive",
    keywordId: "dodge",
    descriptionTemplate: "When you Dodge below half Health, restore {value} Health",
    effectKey: "healOnDodge",
    roll: rollRange(1, 2, 2, 3),
  },
  {
    id: "dodge-armor",
    name: "Wardplate",
    aspect: "defensive",
    keywordId: "dodge",
    descriptionTemplate: "When you Dodge without Armor, gain {value} Armor",
    effectKey: "armorOnDodge",
    roll: rollRange(1, 2, 2, 3),
  },
  {
    id: "dodge-riposte",
    name: "Riposting",
    aspect: "offensive",
    keywordId: "dodge",
    descriptionTemplate: "When you Dodge, sometimes deal {value} Physical damage (50% chance)",
    effectKey: "physicalOnDodge",
    roll: rollRange(2, 3, 4, 6),
  },
  {
    id: "dodge-opening",
    name: "Opportunist",
    aspect: "offensive",
    keywordId: "dodge",
    descriptionTemplate: "Your next attack deals {value} additional Physical damage when you Dodge",
    effectKey: "nextAttackPhysicalOnDodge",
    roll: rollRange(2, 3, 4, 6),
  },
  uniqueAffix(
    "dodge-crit",
    "Off-Balance",
    "offensive",
    "dodge",
    "Your next attack is guaranteed to Critically Hit when you Dodge",
    "nextAttackCritOnDodge",
  ),
  {
    id: "dodge-bleed",
    name: "Fleeting",
    aspect: "offensive",
    keywordId: "dodge",
    descriptionTemplate: "When you Dodge a Bleeding enemy, deal {value} Bleed damage",
    effectKey: "bleedOnDodge",
    roll: rollRange(2, 3, 4, 5),
  },
  uniqueAffix(
    "bloodfire",
    "Bloodfire",
    "offensive",
    "burn",
    "Burn has a 20% chance to inflict Bleed, and vice versa. Both gain Leech against enemies already Burning and Bleeding",
    "burnBleedMirrorAndLeech",
    "bleed",
  ),
  uniqueAffix(
    "rimeheart",
    "Rimeheart",
    "offensive",
    "freeze",
    "While you have no Block, Freeze damage grants equal Block. Freezing an enemy while you have no Mana restores Mana equal to half your Block",
    "freezeGrantsBlockAndMana",
    "block",
  ),
  uniqueAffix(
    "blackfletch",
    "Blackfletch",
    "offensive",
    "archery",
    "Against enemies below 30% Health, Archery attacks deal all remaining Bleed and Poison damage and remove both",
    "archeryDetonateBleedPoison",
    "poison",
  ),
  uniqueAffix(
    "twin-casting",
    "Twincasting",
    "offensive",
    "burn",
    "Playing a Burn card draws a Freeze card, and vice versa",
    "elementalTwinCasting",
    "freeze",
  ),
  uniqueAffix(
    "saintfall",
    "Saintfall",
    "defensive",
    "block",
    "When Block is depleted, deal {value} Holy to the attacker and restore {value} Health",
    "saintfallRetribution",
    "holy",
    4,
  ),
  uniqueAffix(
    "golden-verdict",
    "Verdict",
    "offensive",
    "holy",
    "Holy damage builds Stun. The first time you Stun an enemy each combat, gain {value} Gold",
    "holyStunBuildupGold",
    "stun",
  ),
] as const satisfies readonly AffixRowInput[];

export type GearAffixId = (typeof affixRows)[number]["id"];

export const GEAR_AFFIX_IDS = affixRows.map((row) => row.id) as [GearAffixId, ...GearAffixId[]];

export const gearAffixCatalog: Record<GearAffixId, GearAffixDefinition> = Object.fromEntries(
  affixRows.map((row) => [row.id, { ...row }]),
) as Record<GearAffixId, GearAffixDefinition>;

// Object.fromEntries silently overwrites duplicate ids, so fail fast here
// instead of shipping a catalog that lost a row.
if (affixRows.length !== new Set(affixRows.map((row) => row.id)).size) {
  throw new Error("gearAffixCatalog has duplicate affix ids");
}

export const gearAffixList = Object.values(gearAffixCatalog);
