import type { KeywordId } from "@/lib/game-data";
import type { GearAffixId } from "./affix-ids";
import type { GearEffectManifest } from "./gear-effect-manifest";
import type { GearRarity } from "./types";

export type GearAffixAspect = "offensive" | "defensive";

export type GearAffixDefinition = {
  id: GearAffixId;
  aspect: GearAffixAspect;
  keywordId: KeywordId;
  secondaryKeywordId?: KeywordId;
  descriptionTemplate: string;
  effectKey: keyof GearEffectManifest;
  roll: Record<GearRarity, { min: number; max: number }>;
};

function affix(
  id: GearAffixId,
  aspect: GearAffixAspect,
  keywordId: KeywordId,
  descriptionTemplate: string,
  effectKey: keyof GearEffectManifest,
  basicRange: { min: number; max: number },
  astralRange: { min: number; max: number },
  secondaryKeywordId?: KeywordId,
): GearAffixDefinition {
  return {
    id,
    aspect,
    keywordId,
    ...(secondaryKeywordId !== undefined ? { secondaryKeywordId } : {}),
    descriptionTemplate,
    effectKey,
    roll: {
      basic: basicRange,
      astral: astralRange,
    },
  };
}

export const gearAffixCatalog: Record<GearAffixId, GearAffixDefinition> = {
  "flat-physical": affix(
    "flat-physical",
    "offensive",
    "physical",
    "Increases Physical damage by {value}",
    "flatPhysicalDamage",
    { min: 1, max: 2 },
    { min: 3, max: 4 },
  ),
  "flat-stun": affix(
    "flat-stun",
    "offensive",
    "stun",
    "Increases Stun damage by {value}",
    "flatStunDamage",
    { min: 1, max: 2 },
    { min: 3, max: 4 },
  ),
  "flat-holy": affix(
    "flat-holy",
    "offensive",
    "holy",
    "Increases Holy damage by {value}",
    "flatHolyDamage",
    { min: 1, max: 2 },
    { min: 3, max: 4 },
  ),
  "flat-burn": affix(
    "flat-burn",
    "offensive",
    "burn",
    "Increases Burn damage by {value}",
    "flatBurnDamage",
    { min: 1, max: 2 },
    { min: 3, max: 4 },
  ),
  "flat-poison": affix(
    "flat-poison",
    "offensive",
    "poison",
    "Increases Poison damage by {value}",
    "flatPoisonDamage",
    { min: 1, max: 2 },
    { min: 3, max: 4 },
  ),
  "flat-bleed": affix(
    "flat-bleed",
    "offensive",
    "bleed",
    "Increases Bleed damage by {value}",
    "flatBleedDamage",
    { min: 1, max: 2 },
    { min: 3, max: 4 },
  ),
  "flat-freeze": affix(
    "flat-freeze",
    "offensive",
    "freeze",
    "Increases Freeze damage by {value}",
    "flatFreezeDamage",
    { min: 1, max: 2 },
    { min: 3, max: 4 },
  ),
  "flat-nature": affix(
    "flat-nature",
    "offensive",
    "nature",
    "Increases Nature damage by {value}",
    "flatNatureDamage",
    { min: 1, max: 2 },
    { min: 3, max: 4 },
  ),
  "start-block": affix(
    "start-block",
    "defensive",
    "block",
    "Gain {value} Block at the start of combat",
    "startBlock",
    { min: 4, max: 6 },
    { min: 7, max: 9 },
  ),
  "armor-pierce": affix(
    "armor-pierce",
    "offensive",
    "physical",
    "Ignore {value} enemy Armor",
    "armorPiercing",
    { min: 1, max: 2 },
    { min: 2, max: 4 },
  ),
  "damage-on-stun": affix(
    "damage-on-stun",
    "offensive",
    "physical",
    "On Stun: Deal {value} Physical damage",
    "damageOnStunPhysical",
    { min: 3, max: 4 },
    { min: 5, max: 6 },
  ),
  "forge-on-stun": affix(
    "forge-on-stun",
    "offensive",
    "forge",
    "On Stun: Gain {value} Forge",
    "forgeOnStun",
    { min: 1, max: 2 },
    { min: 2, max: 4 },
  ),
  "poison-leech": affix(
    "poison-leech",
    "offensive",
    "leech",
    "Poison has a {value}% chance to Leech",
    "poisonLeechChance",
    { min: 5, max: 7 },
    { min: 8, max: 10 },
    "poison",
  ),
  "companion-damage": affix(
    "companion-damage",
    "offensive",
    "companion",
    "Increases Companion damage by {value}",
    "companionDamageBonus",
    { min: 1, max: 2 },
    { min: 2, max: 4 },
  ),
  "start-heal": affix(
    "start-heal",
    "defensive",
    "health",
    "Restore {value} Health at the start of combat",
    "startHeal",
    { min: 3, max: 4 },
    { min: 5, max: 6 },
  ),
  "heal-on-kill": affix(
    "heal-on-kill",
    "defensive",
    "health",
    "Restore {value} Health on kill",
    "healOnKill",
    { min: 3, max: 4 },
    { min: 5, max: 6 },
  ),
  "start-forge": affix(
    "start-forge",
    "defensive",
    "forge",
    "Gain {value} Forge at the start of combat",
    "startForge",
    { min: 1, max: 2 },
    { min: 2, max: 4 },
  ),
  "start-armor": affix(
    "start-armor",
    "defensive",
    "armor",
    "Gain {value} Armor at the start of combat",
    "startArmor",
    { min: 1, max: 2 },
    { min: 2, max: 4 },
  ),
  "block-on-stun": affix(
    "block-on-stun",
    "defensive",
    "block",
    "On Stun: Gain {value} Block",
    "blockOnStun",
    { min: 3, max: 4 },
    { min: 5, max: 6 },
  ),
  "mana-on-stun": affix(
    "mana-on-stun",
    "offensive",
    "mana",
    "On Stun: Gain {value} Mana",
    "manaOnStun",
    { min: 1, max: 1 },
    { min: 2, max: 2 },
  ),
  "physical-bleed-chance": affix(
    "physical-bleed-chance",
    "offensive",
    "bleed",
    "{value}% chance for Physical damage to Bleed",
    "physicalBleedChance",
    { min: 7, max: 8 },
    { min: 9, max: 10 },
    "physical",
  ),
  "burn-per-mana": affix(
    "burn-per-mana",
    "offensive",
    "burn",
    "Increases Burn damage by {value}% per Mana Crystal",
    "burnDamagePerManaPercent",
    { min: 10, max: 15 },
    { min: 15, max: 20 },
    "mana",
  ),
  "gold-on-wish": affix(
    "gold-on-wish",
    "offensive",
    "gold",
    "Gain {value} Gold on Wish",
    "goldOnWish",
    { min: 1, max: 2 },
    { min: 3, max: 4 },
    "wish",
  ),
  "burn-on-wish": affix(
    "burn-on-wish",
    "offensive",
    "burn",
    "Deal {value} Burn on Wish",
    "burnOnWish",
    { min: 1, max: 2 },
    { min: 3, max: 4 },
    "wish",
  ),
  "gold-on-kill": affix(
    "gold-on-kill",
    "offensive",
    "gold",
    "Gain {value} Gold on kill",
    "goldOnKill",
    { min: 4, max: 5 },
    { min: 6, max: 7 },
  ),
  "physical-stun-chance": affix(
    "physical-stun-chance",
    "offensive",
    "stun",
    "{value}% chance for Physical damage to Stun",
    "physicalStunChance",
    { min: 5, max: 10 },
    { min: 10, max: 15 },
    "physical",
  ),
  "nature-leech": affix(
    "nature-leech",
    "offensive",
    "leech",
    "Nature has a {value}% chance to Leech",
    "natureLeechChance",
    { min: 7, max: 8 },
    { min: 9, max: 10 },
    "nature",
  ),
  "forge-on-burn": affix(
    "forge-on-burn",
    "offensive",
    "forge",
    "Gain {value} Forge when you deal Burn damage",
    "forgeOnBurnDealt",
    { min: 1, max: 2 },
    { min: 2, max: 4 },
    "burn",
  ),
  "draw-on-wish": affix(
    "draw-on-wish",
    "offensive",
    "wish",
    "Draw {value} cards on Wish",
    "drawOnWish",
    { min: 1, max: 1 },
    { min: 2, max: 2 },
  ),
  "consume-heal-bonus": affix(
    "consume-heal-bonus",
    "defensive",
    "consume",
    "Increases Healing from Consumed cards by {value}%",
    "consumeHealBonusPercent",
    { min: 10, max: 15 },
    { min: 15, max: 20 },
    "health",
  ),
  "archery-damage": affix(
    "archery-damage",
    "offensive",
    "archery",
    "Increases Archery damage by {value}",
    "flatArrowDamage",
    { min: 2, max: 3 },
    { min: 4, max: 5 },
  ),
  "damage-on-freeze": affix(
    "damage-on-freeze",
    "offensive",
    "physical",
    "On Freeze: Deal {value} Physical damage",
    "damageOnFreezePhysical",
    { min: 3, max: 4 },
    { min: 5, max: 6 },
    "freeze",
  ),
  "heal-on-block-depleted": affix(
    "heal-on-block-depleted",
    "defensive",
    "health",
    "Restore {value} Health when Block is depleted",
    "blockDepletedHeal",
    { min: 2, max: 3 },
    { min: 4, max: 5 },
    "block",
  ),
  "health-on-wish": affix(
    "health-on-wish",
    "defensive",
    "health",
    "Restore {value} Health on Wish",
    "healthOnWish",
    { min: 2, max: 3 },
    { min: 4, max: 5 },
    "wish",
  ),
  "mana-on-wish": affix(
    "mana-on-wish",
    "offensive",
    "mana",
    "Gain {value} Mana on Wish",
    "manaOnWish",
    { min: 1, max: 1 },
    { min: 2, max: 2 },
    "wish",
  ),
  "start-freeze": affix(
    "start-freeze",
    "defensive",
    "freeze",
    "Apply {value} Freeze at the start of combat",
    "startFreeze",
    { min: 4, max: 5 },
    { min: 6, max: 7 },
  ),
  "holy-from-block": affix(
    "holy-from-block",
    "offensive",
    "holy",
    "Increases Holy damage by {value}% of your Block",
    "holyDamageFromBlockPercent",
    { min: 10, max: 15 },
    { min: 15, max: 20 },
    "block",
  ),
  "leech-potency": affix(
    "leech-potency",
    "offensive",
    "leech",
    "Leech restores {value}% more Health",
    "leechHealBonusPercent",
    { min: 10, max: 15 },
    { min: 15, max: 20 },
  ),
  "frozen-vulnerable": affix(
    "frozen-vulnerable",
    "offensive",
    "freeze",
    "Frozen enemies take {value}% more damage",
    "frozenEnemyDamageBonusPercent",
    { min: 10, max: 15 },
    { min: 15, max: 20 },
  ),
  "companion-forge-power": affix(
    "companion-forge-power",
    "offensive",
    "companion",
    "Companions benefit from Forge",
    "companionBenefitsFromForge",
    { min: 1, max: 1 },
    { min: 1, max: 1 },
    "forge",
  ),
  "gold-blessed-holy": affix(
    "gold-blessed-holy",
    "offensive",
    "holy",
    "Increases Holy damage by {value}% of your Gold",
    "holyDamageFromGoldPercent",
    { min: 2, max: 3 },
    { min: 4, max: 5 },
    "gold",
  ),
  "resist-physical": affix(
    "resist-physical",
    "defensive",
    "physical",
    "Reduces Physical damage taken by {value}%",
    "resistPhysical",
    { min: 10, max: 15 },
    { min: 15, max: 20 },
  ),
  "resist-stun": affix(
    "resist-stun",
    "defensive",
    "stun",
    "Reduces Stun damage taken by {value}%",
    "resistStun",
    { min: 10, max: 15 },
    { min: 15, max: 20 },
  ),
  "resist-holy": affix(
    "resist-holy",
    "defensive",
    "holy",
    "Reduces Holy damage taken by {value}%",
    "resistHoly",
    { min: 10, max: 15 },
    { min: 15, max: 20 },
  ),
  "resist-burn": affix(
    "resist-burn",
    "defensive",
    "burn",
    "Reduces Burn damage taken by {value}%",
    "resistBurn",
    { min: 10, max: 15 },
    { min: 15, max: 20 },
  ),
  "resist-poison": affix(
    "resist-poison",
    "defensive",
    "poison",
    "Reduces Poison damage taken by {value}%",
    "resistPoison",
    { min: 10, max: 15 },
    { min: 15, max: 20 },
  ),
  "resist-bleed": affix(
    "resist-bleed",
    "defensive",
    "bleed",
    "Reduces Bleed damage taken by {value}%",
    "resistBleed",
    { min: 10, max: 15 },
    { min: 15, max: 20 },
  ),
  "resist-freeze": affix(
    "resist-freeze",
    "defensive",
    "freeze",
    "Reduces Freeze damage taken by {value}%",
    "resistFreeze",
    { min: 10, max: 15 },
    { min: 15, max: 20 },
  ),
  "resist-nature": affix(
    "resist-nature",
    "defensive",
    "nature",
    "Reduces Nature damage taken by {value}%",
    "resistNature",
    { min: 10, max: 15 },
    { min: 15, max: 20 },
  ),
  "health-per-turn": affix(
    "health-per-turn",
    "defensive",
    "health",
    "Restores {value} Health each turn",
    "healthPerTurn",
    { min: 1, max: 2 },
    { min: 3, max: 4 },
  ),
  "block-gain": affix(
    "block-gain",
    "defensive",
    "block",
    "Increases Block gained by {value}",
    "flatBlockGained",
    { min: 1, max: 2 },
    { min: 3, max: 4 },
  ),
  "gold-gain": affix(
    "gold-gain",
    "defensive",
    "gold",
    "Increases Gold gained by {value}%",
    "goldGainPercent",
    { min: 10, max: 15 },
    { min: 15, max: 20 },
  ),
  "max-health": affix(
    "max-health",
    "defensive",
    "health",
    "Increases Health by {value}",
    "maxHealth",
    { min: 7, max: 8 },
    { min: 9, max: 10 },
  ),
  "burn-on-consume": affix(
    "burn-on-consume",
    "offensive",
    "consume",
    "Deal {value} Burn damage when you Consume",
    "burnOnConsume",
    { min: 2, max: 3 },
    { min: 4, max: 6 },
    "burn",
  ),
  "archery-ignore-armor": affix(
    "archery-ignore-armor",
    "offensive",
    "archery",
    "Archery attacks ignore {value} Armor",
    "archeryArmorPiercing",
    { min: 1, max: 2 },
    { min: 3, max: 4 },
    "physical",
  ),
  "absorb-per-mana": affix(
    "absorb-per-mana",
    "defensive",
    "mana",
    "Reduce damage taken by {value} for each full Mana Crystal",
    "damageReductionPerMana",
    { min: 2, max: 3 },
    { min: 4, max: 5 },
    "block",
  ),
  "heal-on-burn-death": affix(
    "heal-on-burn-death",
    "defensive",
    "burn",
    "Restore {value} Health when an enemy with Burn is defeated",
    "healOnBurnEnemyDefeated",
    { min: 4, max: 5 },
    { min: 6, max: 7 },
    "health",
  ),
  "mana-on-leech-chance": affix(
    "mana-on-leech-chance",
    "offensive",
    "leech",
    "Leech has a {value}% chance to restore 1 Mana",
    "manaOnLeechChance",
    { min: 10, max: 15 },
    { min: 15, max: 20 },
    "mana",
  ),
  "poison-reduces-armor": affix(
    "poison-reduces-armor",
    "offensive",
    "poison",
    "Poison has a {value}% chance to remove 1 Armor",
    "poisonArmorShredChance",
    { min: 10, max: 15 },
    { min: 15, max: 20 },
    "armor",
  ),
  "nature-mana-refund-chance": affix(
    "nature-mana-refund-chance",
    "offensive",
    "nature",
    "Nature damage has a {value}% chance to restore 1 Mana",
    "manaOnNatureDamageChance",
    { min: 10, max: 15 },
    { min: 15, max: 20 },
    "mana",
  ),
  "burn-on-bleed": affix(
    "burn-on-bleed",
    "offensive",
    "bleed",
    "Burn deals {value}% more damage to Bleeding enemies",
    "burnDamageBonusToBleedingPercent",
    { min: 10, max: 15 },
    { min: 15, max: 20 },
    "burn",
  ),
  "stun-on-block-hit": affix(
    "stun-on-block-hit",
    "defensive",
    "block",
    "Deal {value} Stun damage when your Block is depleted",
    "stunOnBlockDepleted",
    { min: 2, max: 3 },
    { min: 4, max: 5 },
    "stun",
  ),
  "companion-leech": affix(
    "companion-leech",
    "defensive",
    "companion",
    "Restore {value} Health when your Companion attacks",
    "healOnCompanionAttack",
    { min: 1, max: 2 },
    { min: 3, max: 4 },
    "health",
  ),
  "armor-on-cc": affix(
    "armor-on-cc",
    "defensive",
    "armor",
    "Gain {value} Armor when you are Stunned or Frozen",
    "armorOnStunOrFreeze",
    { min: 1, max: 2 },
    { min: 3, max: 4 },
    "stun",
  ),
};

export const gearAffixList = Object.values(gearAffixCatalog);
