import type { KeywordId } from "@/lib/game-data";
import type { GearEffectManifest } from "./gear-effect-manifest";
import type { GearRarity } from "./types";

export type GearAffixAspect = "offensive" | "defensive";

type AffixRollRange = Record<GearRarity, { min: number; max: number }>;

function rollRange(basicMin: number, basicMax: number, astralMin: number, astralMax: number): AffixRollRange {
  return {
    basic: { min: basicMin, max: basicMax },
    astral: { min: astralMin, max: astralMax },
    unique: { min: astralMin, max: astralMax },
  };
}

function uniqueRoll(value: number): AffixRollRange {
  return {
    basic: { min: value, max: value },
    astral: { min: value, max: value },
    unique: { min: value, max: value },
  };
}

const ROLL_SMALL = rollRange(1, 2, 3, 4);
const ROLL_RESIST = rollRange(10, 15, 15, 20);
const ROLL_MEDIUM = rollRange(3, 4, 5, 6);

export interface GearAffixDefinition {
  id: GearAffixId;
  name: string;
  aspect: GearAffixAspect;
  keywordId: KeywordId;
  secondaryKeywordId?: KeywordId;
  descriptionTemplate: string;
  effectKey: keyof GearEffectManifest;
  roll: AffixRollRange;
  uniqueOnly?: boolean;
}

type AffixRowInput = Omit<GearAffixDefinition, "id"> & { id: string };

const affixRows = [
  {
    id: "the-unclosing-wound",
    name: "The Unclosing Wound",
    aspect: "offensive",
    keywordId: "bleed",
    secondaryKeywordId: "physical",
    descriptionTemplate: "Enemy Bleed halves each turn instead of expiring.",
    effectKey: "bleedDecaysByHalf",
    roll: uniqueRoll(1),
    uniqueOnly: true,
  },
  {
    id: "kingbreaker",
    name: "Kingbreaker",
    aspect: "offensive",
    keywordId: "stun",
    secondaryKeywordId: "physical",
    descriptionTemplate: "Enemy Armor increases your Stun damage instead of reducing it.",
    effectKey: "armorIncreasesStun",
    roll: uniqueRoll(1),
    uniqueOnly: true,
  },
  {
    id: "everkeen",
    name: "Everkeen",
    aspect: "offensive",
    keywordId: "forge",
    secondaryKeywordId: "physical",
    descriptionTemplate: "Gaining Forge makes your next Physical card strike twice.",
    effectKey: "forgeReadiesPhysicalRepeat",
    roll: uniqueRoll(1),
    uniqueOnly: true,
  },
  {
    id: "red-harvest",
    name: "Red Harvest",
    aspect: "offensive",
    keywordId: "physical",
    secondaryKeywordId: "bleed",
    descriptionTemplate: "Each turn, return your first Physical card to hand. It costs 1 less Mana.",
    effectKey: "returnFirstPhysicalCard",
    roll: uniqueRoll(1),
    uniqueOnly: true,
  },
  {
    id: "oathkeeper",
    name: "Oathkeeper",
    aspect: "offensive",
    keywordId: "forge",
    secondaryKeywordId: "holy",
    descriptionTemplate: "Forge also strengthens Holy damage. Holy damage never spends Forge.",
    effectKey: "holyPreservesForge",
    roll: uniqueRoll(1),
    uniqueOnly: true,
  },
  {
    id: "the-patient-edge",
    name: "The Patient Edge",
    aspect: "offensive",
    keywordId: "forge",
    secondaryKeywordId: "physical",
    descriptionTemplate: "Recover Forge spent on attacks at the start of your next turn.",
    effectKey: "recoverSpentForge",
    roll: uniqueRoll(1),
    uniqueOnly: true,
  },
  {
    id: "vipers-courtesy",
    name: "Viper’s Courtesy",
    aspect: "offensive",
    keywordId: "dodge",
    secondaryKeywordId: "poison",
    descriptionTemplate: "After Dodging, your next Physical hit adds half its damage as Poison and Bleed.",
    effectKey: "dodgeReadiesVenomousHit",
    roll: uniqueRoll(1),
    uniqueOnly: true,
  },
  {
    id: "the-lingering-bell",
    name: "The Lingering Bell",
    aspect: "offensive",
    keywordId: "stun",
    secondaryKeywordId: "holy",
    descriptionTemplate: "Stunning an enemy preserves a quarter of its Stun buildup.",
    effectKey: "retainStunBuildup",
    roll: uniqueRoll(1),
    uniqueOnly: true,
  },
  {
    id: "huntsmasters-call",
    name: "Huntsmaster’s Call",
    aspect: "offensive",
    keywordId: "archery",
    secondaryKeywordId: "companion",
    descriptionTemplate: "Your first Archery card each turn makes all Companions attack again.",
    effectKey: "firstArcheryCompanionAttack",
    roll: uniqueRoll(1),
    uniqueOnly: true,
  },
  {
    id: "wrenflight",
    name: "Wrenflight",
    aspect: "offensive",
    keywordId: "archery",
    secondaryKeywordId: "dodge",
    descriptionTemplate: "Archery grants 10% Dodge until your next turn. Dodging draws an Archery card.",
    effectKey: "archeryDodgeAndDraw",
    roll: uniqueRoll(1),
    uniqueOnly: true,
  },
  {
    id: "the-returning-gale",
    name: "The Returning Gale",
    aspect: "offensive",
    keywordId: "archery",
    secondaryKeywordId: "nature",
    descriptionTemplate: "Archery cards repeat their damage at half strength next turn.",
    effectKey: "archeryEchoNextTurn",
    roll: uniqueRoll(1),
    uniqueOnly: true,
  },
  {
    id: "the-final-spark",
    name: "The Final Spark",
    aspect: "offensive",
    keywordId: "mana",
    secondaryKeywordId: "burn",
    descriptionTemplate: "Spend your last Mana to repeat a Burn or Freeze card’s damage. Once per turn.",
    effectKey: "lastManaElementalRepeat",
    roll: uniqueRoll(1),
    uniqueOnly: true,
  },
  {
    id: "laughing-guard",
    name: "Laughing Guard",
    aspect: "defensive",
    keywordId: "block",
    secondaryKeywordId: "dodge",
    descriptionTemplate: "Keep Block between turns. Dodging spends half your Block to deal that much Physical damage.",
    effectKey: "dodgeSpendsPreservedBlock",
    roll: uniqueRoll(1),
    uniqueOnly: true,
  },
  {
    id: "the-knights-answer",
    name: "The Knight’s Answer",
    aspect: "defensive",
    keywordId: "block",
    secondaryKeywordId: "physical",
    descriptionTemplate: "Blocking an attack makes your next Physical card free.",
    effectKey: "blockReadiesFreePhysical",
    roll: uniqueRoll(1),
    uniqueOnly: true,
  },
  {
    id: "the-returning-flight",
    name: "The Returning Flight",
    aspect: "offensive",
    keywordId: "archery",
    secondaryKeywordId: "dodge",
    descriptionTemplate: "Each turn, recover your last Archery card. It costs 1 less Mana.",
    effectKey: "recoverLastArcheryCard",
    roll: uniqueRoll(1),
    uniqueOnly: true,
  },
  {
    id: "threefold-grace",
    name: "Threefold Grace",
    aspect: "offensive",
    keywordId: "burn",
    secondaryKeywordId: "freeze",
    descriptionTemplate: "Your first Burn, Freeze, and Holy card each turn costs no Mana.",
    effectKey: "firstElementalCardsFree",
    roll: uniqueRoll(1),
    uniqueOnly: true,
  },
  {
    id: "bloodember-pendant",
    name: "Bloodember Pendant",
    aspect: "offensive",
    keywordId: "burn",
    secondaryKeywordId: "bleed",
    descriptionTemplate: "Burn and Bleed share their damage bonuses.",
    effectKey: "sharedBurnBleedBonuses",
    roll: uniqueRoll(1),
    uniqueOnly: true,
  },
  {
    id: "winters-credit",
    name: "Winter’s Credit",
    aspect: "offensive",
    keywordId: "freeze",
    secondaryKeywordId: "mana",
    descriptionTemplate: "Spend 3 Block per missing Mana to play Freeze cards.",
    effectKey: "blockPaysFreezeMana",
    roll: uniqueRoll(1),
    uniqueOnly: true,
  },
  {
    id: "serpents-eye",
    name: "Serpent’s Eye",
    aspect: "offensive",
    keywordId: "poison",
    secondaryKeywordId: "archery",
    descriptionTemplate: "Attacks against Poisoned enemies ignore Armor and cannot be Dodged.",
    effectKey: "poisonedAttacksPierce",
    roll: uniqueRoll(1),
    uniqueOnly: true,
  },
  {
    id: "wildhearts-favor",
    name: "Wildheart’s Favor",
    aspect: "defensive",
    keywordId: "dodge",
    secondaryKeywordId: "nature",
    descriptionTemplate: "Dodging makes your next Nature card free and guarantees its damage Critically Hits.",
    effectKey: "dodgeReadiesNatureCrit",
    roll: uniqueRoll(1),
    uniqueOnly: true,
  },
  {
    id: "the-golden-crucible",
    name: "The Golden Crucible",
    aspect: "offensive",
    keywordId: "gold",
    secondaryKeywordId: "forge",
    descriptionTemplate: "Gold gained in combat grants equal Forge. Forge also strengthens Holy damage.",
    effectKey: "goldGrantsForgeAndHoly",
    roll: uniqueRoll(1),
    uniqueOnly: true,
  },
  {
    id: "flat-physical",
    name: "Ironbound",
    aspect: "offensive",
    keywordId: "physical",
    descriptionTemplate: "Increases Physical damage by {value}",
    effectKey: "flatPhysicalDamage",
    roll: ROLL_SMALL,
  },
  {
    id: "flat-stun",
    name: "Concussive",
    aspect: "offensive",
    keywordId: "stun",
    descriptionTemplate: "Increases Stun damage by {value}",
    effectKey: "flatStunDamage",
    roll: ROLL_SMALL,
  },
  {
    id: "flat-holy",
    name: "Sanctified",
    aspect: "offensive",
    keywordId: "holy",
    descriptionTemplate: "Increases Holy damage by {value}",
    effectKey: "flatHolyDamage",
    roll: ROLL_SMALL,
  },
  {
    id: "flat-burn",
    name: "Blazing",
    aspect: "offensive",
    keywordId: "burn",
    descriptionTemplate: "Increases Burn damage by {value}",
    effectKey: "flatBurnDamage",
    roll: ROLL_SMALL,
  },
  {
    id: "flat-poison",
    name: "Venomous",
    aspect: "offensive",
    keywordId: "poison",
    descriptionTemplate: "Increases Poison damage by {value}",
    effectKey: "flatPoisonDamage",
    roll: ROLL_SMALL,
  },
  {
    id: "flat-bleed",
    name: "Serrated",
    aspect: "offensive",
    keywordId: "bleed",
    descriptionTemplate: "Increases Bleed damage by {value}",
    effectKey: "flatBleedDamage",
    roll: ROLL_SMALL,
  },
  {
    id: "flat-freeze",
    name: "Glacial",
    aspect: "offensive",
    keywordId: "freeze",
    descriptionTemplate: "Increases Freeze damage by {value}",
    effectKey: "flatFreezeDamage",
    roll: ROLL_SMALL,
  },
  {
    id: "flat-nature",
    name: "Wildheart",
    aspect: "offensive",
    keywordId: "nature",
    descriptionTemplate: "Increases Nature damage by {value}",
    effectKey: "flatNatureDamage",
    roll: ROLL_SMALL,
  },
  {
    id: "start-block",
    name: "Bastioned",
    aspect: "defensive",
    keywordId: "block",
    descriptionTemplate: "Gain {value} Block at the start of combat",
    effectKey: "startBlock",
    roll: rollRange(4, 6, 7, 9),
  },
  {
    id: "armor-pierce",
    name: "Piercing",
    aspect: "offensive",
    keywordId: "physical",
    descriptionTemplate: "Ignore {value} enemy Armor",
    effectKey: "armorPiercing",
    roll: rollRange(1, 2, 2, 4),
  },
  {
    id: "damage-on-stun",
    name: "Stunning",
    aspect: "offensive",
    keywordId: "physical",
    descriptionTemplate: "Deal {value} Physical damage when you Stun an enemy",
    effectKey: "damageOnStunPhysical",
    roll: ROLL_MEDIUM,
  },
  {
    id: "forge-on-stun",
    name: "Forged",
    aspect: "offensive",
    keywordId: "forge",
    descriptionTemplate: "Gain {value} Forge when you Stun an enemy",
    effectKey: "forgeOnStun",
    roll: rollRange(1, 2, 2, 4),
  },
  {
    id: "poison-leech",
    name: "Leeching",
    aspect: "offensive",
    keywordId: "leech",
    descriptionTemplate: "Poison has a {value}% chance to Leech",
    effectKey: "poisonLeechChance",
    roll: rollRange(5, 7, 8, 10),
    secondaryKeywordId: "poison",
  },
  {
    id: "companion-damage",
    name: "Packbound",
    aspect: "offensive",
    keywordId: "companion",
    descriptionTemplate: "Increases Companion damage by {value}",
    effectKey: "companionDamageBonus",
    roll: rollRange(1, 2, 2, 4),
  },
  {
    id: "start-heal",
    name: "Vital",
    aspect: "defensive",
    keywordId: "health",
    descriptionTemplate: "Restore {value} Health at the start of combat",
    effectKey: "startHeal",
    roll: ROLL_MEDIUM,
  },
  {
    id: "heal-on-kill",
    name: "Gravebound",
    aspect: "defensive",
    keywordId: "health",
    descriptionTemplate: "Restore {value} Health on kill",
    effectKey: "healOnKill",
    roll: ROLL_MEDIUM,
  },
  {
    id: "start-forge",
    name: "Tempered",
    aspect: "defensive",
    keywordId: "forge",
    descriptionTemplate: "Gain {value} Forge at the start of combat",
    effectKey: "startForge",
    roll: rollRange(1, 2, 2, 4),
  },
  {
    id: "start-armor",
    name: "Plated",
    aspect: "defensive",
    keywordId: "armor",
    descriptionTemplate: "Gain {value} Armor at the start of combat",
    effectKey: "startArmor",
    roll: rollRange(1, 2, 2, 4),
  },
  {
    id: "block-on-stun",
    name: "Steadfast",
    aspect: "defensive",
    keywordId: "block",
    descriptionTemplate: "Gain {value} Block when you Stun an enemy",
    effectKey: "blockOnStun",
    roll: ROLL_MEDIUM,
  },
  {
    id: "mana-on-stun",
    name: "Arcane",
    aspect: "offensive",
    keywordId: "mana",
    descriptionTemplate: "Gain {value} Mana when you Stun an enemy",
    effectKey: "manaOnStun",
    roll: rollRange(1, 1, 2, 2),
  },
  {
    id: "physical-bleed-chance",
    name: "Bloodletting",
    aspect: "offensive",
    keywordId: "bleed",
    descriptionTemplate: "{value}% chance for Physical damage to Bleed",
    effectKey: "physicalBleedChance",
    roll: rollRange(7, 8, 9, 10),
    secondaryKeywordId: "physical",
  },
  {
    id: "burn-per-mana",
    name: "Pyric",
    aspect: "offensive",
    keywordId: "burn",
    descriptionTemplate: "Increases Burn damage by {value}% per Mana Crystal",
    effectKey: "burnDamagePerManaPercent",
    roll: ROLL_RESIST,
    secondaryKeywordId: "mana",
  },
  {
    id: "gold-on-wish",
    name: "Wishful",
    aspect: "offensive",
    keywordId: "gold",
    descriptionTemplate: "Gain {value} Gold on Wish",
    effectKey: "goldOnWish",
    roll: ROLL_SMALL,
    secondaryKeywordId: "wish",
  },
  {
    id: "burn-on-wish",
    name: "Wishfire",
    aspect: "offensive",
    keywordId: "burn",
    descriptionTemplate: "Deal {value} Burn damage on Wish",
    effectKey: "burnOnWish",
    roll: ROLL_SMALL,
    secondaryKeywordId: "wish",
  },
  {
    id: "gold-on-kill",
    name: "Greed",
    aspect: "offensive",
    keywordId: "gold",
    descriptionTemplate: "Gain {value} Gold on kill",
    effectKey: "goldOnKill",
    roll: rollRange(4, 5, 6, 7),
  },
  {
    id: "physical-stun-chance",
    name: "Thunderous",
    aspect: "offensive",
    keywordId: "stun",
    descriptionTemplate: "{value}% chance for Physical damage to Stun",
    effectKey: "physicalStunChance",
    roll: rollRange(5, 10, 10, 15),
    secondaryKeywordId: "physical",
  },
  {
    id: "nature-leech",
    name: "Sylvan",
    aspect: "offensive",
    keywordId: "leech",
    descriptionTemplate: "Nature damage has a {value}% chance to Leech",
    effectKey: "natureLeechChance",
    roll: rollRange(7, 8, 9, 10),
    secondaryKeywordId: "nature",
  },
  {
    id: "forge-on-burn",
    name: "Emberforged",
    aspect: "offensive",
    keywordId: "forge",
    descriptionTemplate: "Your first Burn attack each turn grants {value} Forge",
    effectKey: "forgeOnBurnDealt",
    roll: rollRange(1, 1, 2, 2),
    secondaryKeywordId: "burn",
  },
  {
    id: "draw-on-wish",
    name: "Fateful",
    aspect: "offensive",
    keywordId: "wish",
    descriptionTemplate: "Draw {value} Cards on Wish",
    effectKey: "drawOnWish",
    roll: rollRange(1, 1, 2, 2),
  },
  {
    id: "consume-heal-bonus",
    name: "Nourishing",
    aspect: "defensive",
    keywordId: "consume",
    descriptionTemplate: "Increases Health restored by Consumed cards by {value}%",
    effectKey: "consumeHealBonusPercent",
    roll: ROLL_RESIST,
    secondaryKeywordId: "health",
  },
  {
    id: "archery-damage",
    name: "Fletched",
    aspect: "offensive",
    keywordId: "archery",
    descriptionTemplate: "Increases Archery damage by {value}",
    effectKey: "flatArrowDamage",
    roll: rollRange(2, 3, 4, 5),
  },
  {
    id: "damage-on-freeze",
    name: "Shattering",
    aspect: "offensive",
    keywordId: "physical",
    descriptionTemplate: "Deal {value} Physical damage when you Freeze an enemy",
    effectKey: "damageOnFreezePhysical",
    roll: ROLL_MEDIUM,
    secondaryKeywordId: "freeze",
  },
  {
    id: "heal-on-block-depleted",
    name: "Resolute",
    aspect: "defensive",
    keywordId: "health",
    descriptionTemplate: "Restore {value} Health when Block is depleted",
    effectKey: "blockDepletedHeal",
    roll: rollRange(2, 3, 4, 5),
    secondaryKeywordId: "block",
  },
  {
    id: "health-on-wish",
    name: "Wishborn",
    aspect: "defensive",
    keywordId: "health",
    descriptionTemplate: "Restore {value} Health on Wish",
    effectKey: "healthOnWish",
    roll: rollRange(2, 3, 4, 5),
    secondaryKeywordId: "wish",
  },
  {
    id: "mana-on-wish",
    name: "Wishwoven",
    aspect: "offensive",
    keywordId: "mana",
    descriptionTemplate: "Gain {value} Mana on Wish",
    effectKey: "manaOnWish",
    roll: rollRange(1, 1, 2, 2),
    secondaryKeywordId: "wish",
  },
  {
    id: "start-freeze",
    name: "Bitter",
    aspect: "defensive",
    keywordId: "freeze",
    descriptionTemplate: "Deal {value} Freeze damage at the start of combat",
    effectKey: "startFreeze",
    roll: rollRange(4, 5, 6, 7),
  },
  {
    id: "holy-from-block",
    name: "Aegis",
    aspect: "offensive",
    keywordId: "holy",
    descriptionTemplate: "Increases Holy damage by {value}% of your Block",
    effectKey: "holyDamageFromBlockPercent",
    roll: ROLL_RESIST,
    secondaryKeywordId: "block",
  },
  {
    id: "leech-potency",
    name: "Sanguine",
    aspect: "offensive",
    keywordId: "leech",
    descriptionTemplate: "Leech restores {value}% more Health",
    effectKey: "leechHealBonusPercent",
    roll: ROLL_RESIST,
  },
  {
    id: "frozen-vulnerable",
    name: "Frigid",
    aspect: "offensive",
    keywordId: "freeze",
    descriptionTemplate: "Frozen enemies take {value}% more damage",
    effectKey: "frozenEnemyDamageBonusPercent",
    roll: ROLL_RESIST,
  },
  {
    id: "companion-forge-power",
    name: "Bonded",
    aspect: "offensive",
    keywordId: "companion",
    descriptionTemplate: "Companions benefit from Forge",
    effectKey: "companionBenefitsFromForge",
    roll: uniqueRoll(1),
    secondaryKeywordId: "forge",
    uniqueOnly: true,
  },
  {
    id: "gold-blessed-holy",
    name: "Aureate",
    aspect: "offensive",
    keywordId: "holy",
    descriptionTemplate: "Increases Holy damage by {value}% of your Gold",
    effectKey: "holyDamageFromGoldPercent",
    roll: rollRange(2, 3, 4, 5),
    secondaryKeywordId: "gold",
  },
  {
    id: "resist-physical",
    name: "Stoneward",
    aspect: "defensive",
    keywordId: "physical",
    descriptionTemplate: "Reduce Physical damage taken by {value}%",
    effectKey: "resistPhysical",
    roll: ROLL_RESIST,
  },
  {
    id: "resist-stun",
    name: "Unshaken",
    aspect: "defensive",
    keywordId: "stun",
    descriptionTemplate: "Reduce Stun damage taken by {value}%",
    effectKey: "resistStun",
    roll: ROLL_RESIST,
  },
  {
    id: "resist-holy",
    name: "Shadowveiled",
    aspect: "defensive",
    keywordId: "holy",
    descriptionTemplate: "Reduce Holy damage taken by {value}%",
    effectKey: "resistHoly",
    roll: ROLL_RESIST,
  },
  {
    id: "resist-burn",
    name: "Fireproof",
    aspect: "defensive",
    keywordId: "burn",
    descriptionTemplate: "Reduce Burn damage taken by {value}%",
    effectKey: "resistBurn",
    roll: ROLL_RESIST,
  },
  {
    id: "resist-poison",
    name: "Antivenom",
    aspect: "defensive",
    keywordId: "poison",
    descriptionTemplate: "Reduce Poison damage taken by {value}%",
    effectKey: "resistPoison",
    roll: ROLL_RESIST,
  },
  {
    id: "resist-bleed",
    name: "Scarbound",
    aspect: "defensive",
    keywordId: "bleed",
    descriptionTemplate: "Reduce Bleed damage taken by {value}%",
    effectKey: "resistBleed",
    roll: ROLL_RESIST,
  },
  {
    id: "resist-freeze",
    name: "Warmblooded",
    aspect: "defensive",
    keywordId: "freeze",
    descriptionTemplate: "Reduce Freeze damage taken by {value}%",
    effectKey: "resistFreeze",
    roll: ROLL_RESIST,
  },
  {
    id: "resist-nature",
    name: "Thornward",
    aspect: "defensive",
    keywordId: "nature",
    descriptionTemplate: "Reduce Nature damage taken by {value}%",
    effectKey: "resistNature",
    roll: ROLL_RESIST,
  },
  {
    id: "health-per-turn",
    name: "Lifegiving",
    aspect: "defensive",
    keywordId: "health",
    descriptionTemplate: "Restore {value} Health each turn",
    effectKey: "healthPerTurn",
    roll: rollRange(1, 1, 1, 1),
  },
  {
    id: "block-gain",
    name: "Warding",
    aspect: "defensive",
    keywordId: "block",
    descriptionTemplate: "Increases Block gained by {value}",
    effectKey: "flatBlockGained",
    roll: ROLL_SMALL,
  },
  {
    id: "gold-gain",
    name: "Prosperous",
    aspect: "defensive",
    keywordId: "gold",
    descriptionTemplate: "Increases Gold gained by {value}%",
    effectKey: "goldGainPercent",
    roll: ROLL_RESIST,
  },
  {
    id: "max-health",
    name: "Enduring",
    aspect: "defensive",
    keywordId: "health",
    descriptionTemplate: "Increases Health by {value}",
    effectKey: "maxHealth",
    roll: rollRange(7, 8, 9, 10),
  },
  {
    id: "burn-on-consume",
    name: "Consuming",
    aspect: "offensive",
    keywordId: "consume",
    descriptionTemplate: "Deal {value} Burn damage when you Consume",
    effectKey: "burnOnConsume",
    roll: rollRange(2, 3, 4, 6),
    secondaryKeywordId: "burn",
  },
  {
    id: "archery-ignore-armor",
    name: "Armorbreaking",
    aspect: "offensive",
    keywordId: "archery",
    descriptionTemplate: "Archery attacks ignore {value} Armor",
    effectKey: "archeryArmorPiercing",
    roll: ROLL_SMALL,
    secondaryKeywordId: "physical",
  },
  {
    id: "absorb-per-mana",
    name: "Aetherward",
    aspect: "defensive",
    keywordId: "mana",
    descriptionTemplate: "Reduce damage taken by {value} for each full Mana Crystal",
    effectKey: "damageReductionPerMana",
    roll: rollRange(2, 3, 4, 5),
    secondaryKeywordId: "block",
  },
  {
    id: "heal-on-burn-death",
    name: "Cauterizing",
    aspect: "defensive",
    keywordId: "burn",
    descriptionTemplate: "Restore {value} Health when an enemy with Burn is defeated",
    effectKey: "healOnBurnEnemyDefeated",
    roll: rollRange(4, 5, 6, 7),
    secondaryKeywordId: "health",
  },
  {
    id: "mana-on-leech-chance",
    name: "Siphoning",
    aspect: "offensive",
    keywordId: "leech",
    descriptionTemplate: "Leech has a {value}% chance to restore 1 Mana",
    effectKey: "manaOnLeechChance",
    roll: ROLL_RESIST,
    secondaryKeywordId: "mana",
  },
  {
    id: "poison-reduces-armor",
    name: "Corrosive",
    aspect: "offensive",
    keywordId: "poison",
    descriptionTemplate: "Poison has a {value}% chance to remove 1 Armor",
    effectKey: "poisonArmorShredChance",
    roll: ROLL_RESIST,
    secondaryKeywordId: "armor",
  },
  {
    id: "nature-mana-refund-chance",
    name: "Bloomwoven",
    aspect: "offensive",
    keywordId: "nature",
    descriptionTemplate: "Nature damage has a {value}% chance to restore 1 Mana",
    effectKey: "manaOnNatureDamageChance",
    roll: ROLL_RESIST,
    secondaryKeywordId: "mana",
  },
  {
    id: "burn-on-bleed",
    name: "Cinderbound",
    aspect: "offensive",
    keywordId: "bleed",
    descriptionTemplate: "Burn deals {value}% more damage to Bleeding enemies",
    effectKey: "burnDamageBonusToBleedingPercent",
    roll: ROLL_RESIST,
    secondaryKeywordId: "burn",
  },
  {
    id: "stun-on-block-hit",
    name: "Reactive",
    aspect: "defensive",
    keywordId: "block",
    descriptionTemplate: "Deal {value} Stun damage when your Block is depleted",
    effectKey: "stunOnBlockDepleted",
    roll: rollRange(2, 3, 4, 5),
    secondaryKeywordId: "stun",
  },
  {
    id: "companion-leech",
    name: "Kinbound",
    aspect: "defensive",
    keywordId: "companion",
    descriptionTemplate: "Restore {value} Health when your Companion attacks",
    effectKey: "healOnCompanionAttack",
    roll: ROLL_SMALL,
    secondaryKeywordId: "health",
  },
  {
    id: "armor-on-cc",
    name: "Stalwart",
    aspect: "defensive",
    keywordId: "armor",
    descriptionTemplate: "Gain {value} Armor when you are Stunned or Frozen",
    effectKey: "armorOnStunOrFreeze",
    roll: ROLL_SMALL,
    secondaryKeywordId: "stun",
  },
  {
    id: "wardbreaker-purge",
    name: "Wardbreaking",
    aspect: "offensive",
    keywordId: "stun",
    secondaryKeywordId: "holy",
    descriptionTemplate: "Your attacks Purge one enemy buff and deal {value} Holy damage",
    effectKey: "attackPurgeDealHolyPerEffect",
    roll: uniqueRoll(1),
    uniqueOnly: true,
  },
  {
    id: "dance-of-blades",
    name: "Bladedance",
    aspect: "defensive",
    keywordId: "dodge",
    secondaryKeywordId: "physical",
    descriptionTemplate: "When you Dodge an attack, draw and play a random card",
    effectKey: "dodgeDrawAndPlay",
    roll: uniqueRoll(1),
    uniqueOnly: true,
  },
  {
    id: "dodge-chance",
    name: "Elusive",
    aspect: "defensive",
    keywordId: "dodge",
    descriptionTemplate: "Increases Dodge chance by {value}%",
    effectKey: "dodgeChance",
    roll: rollRange(1, 2, 2, 3),
  },
  {
    id: "dodge-block",
    name: "Nimble",
    aspect: "defensive",
    keywordId: "dodge",
    descriptionTemplate: "Gain {value} Block when you Dodge",
    effectKey: "blockOnDodge",
    roll: rollRange(2, 3, 4, 5),
  },
  {
    id: "dodge-heal",
    name: "Winded",
    aspect: "defensive",
    keywordId: "dodge",
    descriptionTemplate: "Restore {value} Health when you Dodge",
    effectKey: "healOnDodge",
    roll: rollRange(1, 2, 2, 3),
  },
  {
    id: "dodge-armor",
    name: "Wardplate",
    aspect: "defensive",
    keywordId: "dodge",
    descriptionTemplate: "Gain {value} Armor when you Dodge",
    effectKey: "armorOnDodge",
    roll: rollRange(1, 2, 2, 3),
  },
  {
    id: "dodge-riposte",
    name: "Riposting",
    aspect: "offensive",
    keywordId: "dodge",
    descriptionTemplate: "Deal {value} Physical damage when you Dodge",
    effectKey: "physicalOnDodge",
    roll: rollRange(2, 3, 4, 6),
  },
  {
    id: "dodge-opening",
    name: "Opportunist",
    aspect: "offensive",
    keywordId: "dodge",
    descriptionTemplate: "Your next attack deals {value} additional Physical damage when you Dodge",
    effectKey: "nextAttackPhysicalOnDodge",
    roll: rollRange(2, 3, 4, 6),
  },
  {
    id: "dodge-crit",
    name: "Off-Balance",
    aspect: "offensive",
    keywordId: "dodge",
    descriptionTemplate: "Your next attack is guaranteed to Critically Hit when you Dodge",
    effectKey: "nextAttackCritOnDodge",
    roll: uniqueRoll(1),
    uniqueOnly: true,
  },
  {
    id: "dodge-bleed",
    name: "Fleeting",
    aspect: "offensive",
    keywordId: "dodge",
    descriptionTemplate: "Deal {value} Bleed damage when you Dodge",
    effectKey: "bleedOnDodge",
    roll: rollRange(2, 3, 4, 5),
  },
  {
    id: "bloodfire",
    name: "Bloodfire",
    aspect: "offensive",
    keywordId: "burn",
    secondaryKeywordId: "bleed",
    descriptionTemplate:
      "Burn damage has a 20% chance to cause Bleed, Bleed damage has a 20% chance to cause Burn, and both gain Leech",
    effectKey: "burnBleedMirrorAndLeech",
    roll: uniqueRoll(1),
    uniqueOnly: true,
  },
  {
    id: "rimeheart",
    name: "Rimeheart",
    aspect: "offensive",
    keywordId: "freeze",
    secondaryKeywordId: "block",
    descriptionTemplate: "Freeze damage grants Block and Freezing an enemy restores Mana equal to half your Block",
    effectKey: "freezeGrantsBlockAndMana",
    roll: uniqueRoll(1),
    uniqueOnly: true,
  },
  {
    id: "blackfletch",
    name: "Blackfletch",
    aspect: "offensive",
    keywordId: "archery",
    secondaryKeywordId: "poison",
    descriptionTemplate:
      "Against enemies below 30% Health, Archery attacks deal all remaining Bleed and Poison damage and remove both",
    effectKey: "archeryDetonateBleedPoison",
    roll: uniqueRoll(1),
    uniqueOnly: true,
  },
  {
    id: "twin-casting",
    name: "Twincasting",
    aspect: "offensive",
    keywordId: "burn",
    secondaryKeywordId: "freeze",
    descriptionTemplate: "Playing a Burn card draws a Freeze card, and vice versa",
    effectKey: "elementalTwinCasting",
    roll: uniqueRoll(1),
    uniqueOnly: true,
  },
  {
    id: "saintfall",
    name: "Saintfall",
    aspect: "defensive",
    keywordId: "block",
    secondaryKeywordId: "holy",
    descriptionTemplate: "When Block is depleted, deal {value} Holy to the attacker and restore {value} Health",
    effectKey: "saintfallRetribution",
    roll: uniqueRoll(4),
    uniqueOnly: true,
  },
  {
    id: "golden-verdict",
    name: "Verdict",
    aspect: "offensive",
    keywordId: "holy",
    secondaryKeywordId: "stun",
    descriptionTemplate: "Holy damage causes Stun build-up and you gain {value} Gold when you Stun an enemy",
    effectKey: "holyStunBuildupGold",
    roll: uniqueRoll(1),
    uniqueOnly: true,
  },
] as const satisfies readonly AffixRowInput[];

export type GearAffixId = (typeof affixRows)[number]["id"];

export const GEAR_AFFIX_IDS = affixRows.map((row) => row.id) as [GearAffixId, ...GearAffixId[]];

export const gearAffixCatalog: Record<GearAffixId, GearAffixDefinition> = Object.fromEntries(
  affixRows.map((row) => [row.id, { ...row }]),
) as Record<GearAffixId, GearAffixDefinition>;

export const gearAffixList = Object.values(gearAffixCatalog);
