export const GEAR_AFFIX_IDS = [
  "flat-physical",
  "flat-stun",
  "flat-holy",
  "flat-burn",
  "flat-poison",
  "flat-bleed",
  "flat-freeze",
  "flat-nature",
  "start-block",
  "armor-pierce",
  "damage-on-stun",
  "forge-on-stun",
  "poison-leech",
  "companion-damage",
  "start-heal",
  "heal-on-kill",
  "start-forge",
  "start-armor",
  "block-on-stun",
  "mana-on-stun",
  "physical-bleed-chance",
  "burn-per-mana",
  "gold-on-wish",
  "burn-on-wish",
  "gold-on-kill",
  "physical-stun-chance",
  "nature-leech",
  "forge-on-burn",
  "draw-on-wish",
  "consume-heal-bonus",
  "archery-damage",
  "damage-on-freeze",
  "heal-on-block-depleted",
  "health-on-wish",
  "mana-on-wish",
  "start-freeze",
  "holy-from-block",
  "leech-potency",
  "frozen-vulnerable",
  "companion-forge-power",
  "gold-blessed-holy",
  "resist-physical",
  "resist-stun",
  "resist-holy",
  "resist-burn",
  "resist-poison",
  "resist-bleed",
  "resist-freeze",
  "resist-nature",
  "health-per-turn",
  "block-gain",
  "gold-gain",
  "max-health",
] as const;

export type GearAffixId = (typeof GEAR_AFFIX_IDS)[number];

/** @deprecated Legacy affix IDs normalized on load. */
export const LEGACY_GEAR_AFFIX_IDS = [
  "flat-physical-1",
  "flat-stun-1",
  "flat-holy-1",
  "flat-burn-1",
  "flat-poison-1",
  "flat-bleed-1",
  "flat-freeze-1",
  "flat-nature-1",
] as const;
