import type { KeywordId } from "@/lib/game-data";
import { emptyInventory } from "@/lib/homestead/inventory";
import type { MaterialInventory } from "@/lib/homestead/types";
import type { GearRarity, GearSlot } from "./types";

export interface GearBaseItemDefinition {
  id: string;
  displayName: string;
  compatibleSlots: GearSlot[];
  requiresTwoHands: boolean;
  affinityKeywords: KeywordId[];
  availableRarities: readonly GearRarity[];
  salvageByRarity: Record<GearRarity, MaterialInventory>;
  rangedWeapon?: boolean;
  quiver?: boolean;
}

function salvage(basicIron: number, astralIron: number, astralCrystal = 1): Record<GearRarity, MaterialInventory> {
  return {
    basic: { ...emptyInventory(), iron: basicIron },
    astral: { ...emptyInventory(), iron: astralIron, crystal: astralCrystal },
  };
}

const lightSalvage = salvage(1, 2);
const mediumSalvage = salvage(2, 3);
const heavySalvage = salvage(3, 4);

export const gearBaseItems = {
  "double-axe": {
    id: "double-axe",
    displayName: "Double Axe",
    compatibleSlots: ["main-hand"],
    requiresTwoHands: true,
    affinityKeywords: ["physical", "stun", "bleed"],
    availableRarities: ["basic", "astral"],
    salvageByRarity: heavySalvage,
    rangedWeapon: false,
  },
  maul: {
    id: "maul",
    displayName: "Maul",
    compatibleSlots: ["main-hand"],
    requiresTwoHands: true,
    affinityKeywords: ["physical", "stun", "holy"],
    availableRarities: ["basic", "astral"],
    salvageByRarity: heavySalvage,
    rangedWeapon: false,
  },
  greatsword: {
    id: "greatsword",
    displayName: "Greatsword",
    compatibleSlots: ["main-hand"],
    requiresTwoHands: true,
    affinityKeywords: ["physical", "stun", "forge"],
    availableRarities: ["basic", "astral"],
    salvageByRarity: heavySalvage,
    rangedWeapon: false,
  },
  hatchet: {
    id: "hatchet",
    displayName: "Hatchet",
    compatibleSlots: ["main-hand"],
    requiresTwoHands: false,
    affinityKeywords: ["physical", "bleed"],
    availableRarities: ["basic", "astral"],
    salvageByRarity: mediumSalvage,
    rangedWeapon: false,
  },
  longsword: {
    id: "longsword",
    displayName: "Longsword",
    compatibleSlots: ["main-hand"],
    requiresTwoHands: false,
    affinityKeywords: ["physical", "forge", "holy"],
    availableRarities: ["basic", "astral"],
    salvageByRarity: mediumSalvage,
    rangedWeapon: false,
  },
  shortsword: {
    id: "shortsword",
    displayName: "Shortsword",
    compatibleSlots: ["main-hand"],
    requiresTwoHands: false,
    affinityKeywords: ["physical", "forge", "bleed"],
    availableRarities: ["basic", "astral"],
    salvageByRarity: lightSalvage,
    rangedWeapon: false,
  },
  dagger: {
    id: "dagger",
    displayName: "Dagger",
    compatibleSlots: ["main-hand"],
    requiresTwoHands: false,
    affinityKeywords: ["physical", "bleed", "poison"],
    availableRarities: ["basic", "astral"],
    salvageByRarity: lightSalvage,
    rangedWeapon: false,
  },
  mace: {
    id: "mace",
    displayName: "Mace",
    compatibleSlots: ["main-hand"],
    requiresTwoHands: false,
    affinityKeywords: ["physical", "stun", "holy"],
    availableRarities: ["basic", "astral"],
    salvageByRarity: mediumSalvage,
    rangedWeapon: false,
  },
  flail: {
    id: "flail",
    displayName: "Flail",
    compatibleSlots: ["main-hand"],
    requiresTwoHands: false,
    affinityKeywords: ["physical", "stun"],
    availableRarities: ["basic", "astral"],
    salvageByRarity: mediumSalvage,
    rangedWeapon: false,
  },
  longbow: {
    id: "longbow",
    displayName: "Longbow",
    compatibleSlots: ["main-hand"],
    requiresTwoHands: false,
    affinityKeywords: ["archery", "physical", "nature", "companion"],
    availableRarities: ["basic", "astral"],
    salvageByRarity: mediumSalvage,
    rangedWeapon: true,
  },
  shortbow: {
    id: "shortbow",
    displayName: "Shortbow",
    compatibleSlots: ["main-hand"],
    requiresTwoHands: false,
    affinityKeywords: ["archery", "physical", "nature", "companion"],
    availableRarities: ["basic", "astral"],
    salvageByRarity: lightSalvage,
    rangedWeapon: true,
  },
  "recurve-bow": {
    id: "recurve-bow",
    displayName: "Recurve Bow",
    compatibleSlots: ["main-hand"],
    requiresTwoHands: false,
    affinityKeywords: ["archery", "nature", "physical", "companion"],
    availableRarities: ["basic", "astral"],
    salvageByRarity: mediumSalvage,
    rangedWeapon: true,
  },
  crossbow: {
    id: "crossbow",
    displayName: "Crossbow",
    compatibleSlots: ["main-hand"],
    requiresTwoHands: false,
    affinityKeywords: ["archery", "physical"],
    availableRarities: ["basic", "astral"],
    salvageByRarity: heavySalvage,
    rangedWeapon: true,
  },
  staff: {
    id: "staff",
    displayName: "Staff",
    compatibleSlots: ["main-hand"],
    requiresTwoHands: true,
    affinityKeywords: ["burn", "freeze", "mana"],
    availableRarities: ["basic", "astral"],
    salvageByRarity: mediumSalvage,
    rangedWeapon: false,
  },
  wand: {
    id: "wand",
    displayName: "Wand",
    compatibleSlots: ["main-hand"],
    requiresTwoHands: false,
    affinityKeywords: ["burn", "freeze", "mana"],
    availableRarities: ["basic", "astral"],
    salvageByRarity: lightSalvage,
    rangedWeapon: false,
  },
  "leather-buckler": {
    id: "leather-buckler",
    displayName: "Leather Buckler",
    compatibleSlots: ["off-hand"],
    requiresTwoHands: false,
    affinityKeywords: ["block", "armor", "physical"],
    availableRarities: ["basic", "astral"],
    salvageByRarity: lightSalvage,
  },
  "kite-shield": {
    id: "kite-shield",
    displayName: "Kite Shield",
    compatibleSlots: ["off-hand"],
    requiresTwoHands: false,
    affinityKeywords: ["block", "armor", "stun", "physical"],
    availableRarities: ["basic", "astral"],
    salvageByRarity: heavySalvage,
  },
  quiver: {
    id: "quiver",
    displayName: "Quiver",
    compatibleSlots: ["off-hand"],
    requiresTwoHands: false,
    affinityKeywords: ["archery", "physical"],
    availableRarities: ["basic", "astral"],
    salvageByRarity: lightSalvage,
    quiver: true,
  },
  spellbook: {
    id: "spellbook",
    displayName: "Spellbook",
    compatibleSlots: ["off-hand"],
    requiresTwoHands: false,
    affinityKeywords: ["burn", "freeze", "holy"],
    availableRarities: ["basic", "astral"],
    salvageByRarity: mediumSalvage,
  },
  "leather-armor": {
    id: "leather-armor",
    displayName: "Leather Armor",
    compatibleSlots: ["body"],
    requiresTwoHands: false,
    affinityKeywords: ["physical", "health", "armor"],
    availableRarities: ["basic", "astral"],
    salvageByRarity: mediumSalvage,
  },
  "plate-armor": {
    id: "plate-armor",
    displayName: "Plate Armor",
    compatibleSlots: ["body"],
    requiresTwoHands: false,
    affinityKeywords: ["armor", "block", "stun", "physical"],
    availableRarities: ["basic", "astral"],
    salvageByRarity: heavySalvage,
  },
  "leather-helm": {
    id: "leather-helm",
    displayName: "Leather Helm",
    compatibleSlots: ["helm"],
    requiresTwoHands: false,
    affinityKeywords: ["physical", "armor", "health"],
    availableRarities: ["basic", "astral"],
    salvageByRarity: mediumSalvage,
  },
  "plate-helm": {
    id: "plate-helm",
    displayName: "Plate Helm",
    compatibleSlots: ["helm"],
    requiresTwoHands: false,
    affinityKeywords: ["armor", "stun", "block"],
    availableRarities: ["basic", "astral"],
    salvageByRarity: heavySalvage,
  },
  "leather-boots": {
    id: "leather-boots",
    displayName: "Leather Boots",
    compatibleSlots: ["boots"],
    requiresTwoHands: false,
    affinityKeywords: ["physical", "armor", "health"],
    availableRarities: ["basic", "astral"],
    salvageByRarity: lightSalvage,
  },
  "plate-boots": {
    id: "plate-boots",
    displayName: "Plate Boots",
    compatibleSlots: ["boots"],
    requiresTwoHands: false,
    affinityKeywords: ["armor", "stun", "physical", "health"],
    availableRarities: ["basic", "astral"],
    salvageByRarity: heavySalvage,
  },
  "leather-gloves": {
    id: "leather-gloves",
    displayName: "Leather Gloves",
    compatibleSlots: ["gloves"],
    requiresTwoHands: false,
    affinityKeywords: ["physical", "armor", "health", "gold"],
    availableRarities: ["basic", "astral"],
    salvageByRarity: lightSalvage,
  },
  "leather-belt": {
    id: "leather-belt",
    displayName: "Leather Belt",
    compatibleSlots: ["belt"],
    requiresTwoHands: false,
    affinityKeywords: ["physical", "gold", "armor", "health", "consume"],
    availableRarities: ["basic", "astral"],
    salvageByRarity: lightSalvage,
  },
  "ruby-ring": {
    id: "ruby-ring",
    displayName: "Ruby Ring",
    compatibleSlots: ["left-ring", "right-ring"],
    requiresTwoHands: false,
    affinityKeywords: ["burn", "bleed", "leech"],
    availableRarities: ["basic", "astral"],
    salvageByRarity: lightSalvage,
  },
  "sapphire-ring": {
    id: "sapphire-ring",
    displayName: "Sapphire Ring",
    compatibleSlots: ["left-ring", "right-ring"],
    requiresTwoHands: false,
    affinityKeywords: ["freeze", "mana", "block"],
    availableRarities: ["basic", "astral"],
    salvageByRarity: lightSalvage,
  },
  "emerald-ring": {
    id: "emerald-ring",
    displayName: "Emerald Ring",
    compatibleSlots: ["left-ring", "right-ring"],
    requiresTwoHands: false,
    affinityKeywords: ["nature", "poison", "archery"],
    availableRarities: ["basic", "astral"],
    salvageByRarity: lightSalvage,
  },
  "topaz-ring": {
    id: "topaz-ring",
    displayName: "Topaz Ring",
    compatibleSlots: ["left-ring", "right-ring"],
    requiresTwoHands: false,
    affinityKeywords: ["holy", "gold", "forge", "stun"],
    availableRarities: ["basic", "astral"],
    salvageByRarity: lightSalvage,
  },
  "ruby-amulet": {
    id: "ruby-amulet",
    displayName: "Ruby Amulet",
    compatibleSlots: ["amulet"],
    requiresTwoHands: false,
    affinityKeywords: ["burn", "bleed", "leech"],
    availableRarities: ["basic", "astral"],
    salvageByRarity: lightSalvage,
  },
  "sapphire-amulet": {
    id: "sapphire-amulet",
    displayName: "Sapphire Amulet",
    compatibleSlots: ["amulet"],
    requiresTwoHands: false,
    affinityKeywords: ["freeze", "mana", "block"],
    availableRarities: ["basic", "astral"],
    salvageByRarity: lightSalvage,
  },
  "emerald-amulet": {
    id: "emerald-amulet",
    displayName: "Emerald Amulet",
    compatibleSlots: ["amulet"],
    requiresTwoHands: false,
    affinityKeywords: ["nature", "poison", "archery"],
    availableRarities: ["basic", "astral"],
    salvageByRarity: lightSalvage,
  },
  "topaz-amulet": {
    id: "topaz-amulet",
    displayName: "Topaz Amulet",
    compatibleSlots: ["amulet"],
    requiresTwoHands: false,
    affinityKeywords: ["holy", "gold", "forge", "stun"],
    availableRarities: ["basic", "astral"],
    salvageByRarity: lightSalvage,
  },
} satisfies Record<string, GearBaseItemDefinition>;

export type GearBaseItemId = keyof typeof gearBaseItems;

export const gearBaseItemList = Object.values(gearBaseItems);
