export const GEAR_NUMERIC_EFFECT_KEYS = [
  "bleedDecaysByHalf",
  "armorIncreasesStun",
  "forgeReadiesPhysicalRepeat",
  "physicalCritDetonatesBleed",
  "oathkeeperHolyAndBlock",
  "forgeEveryThreeTurns",
  "dodgeReadiesVenomousHit",
  "retainStunBuildup",
  "archeryCritDrawsCompanion",
  "archeryDodgeAndDraw",
  "archeryEchoNextTurn",
  "lastManaElementalRepeat",
  "dodgeSpendsPreservedBlock",
  "blockReadiesFreePhysical",
  "recoverLastArcheryCard",
  "elementalDamageManaChance",
  "sharedBurnBleedBonuses",
  "blockPaysFreezeMana",
  "poisonedAttacksPierce",
  "dodgeReadiesNatureCrit",
  "goldGrantsForgeAndHoly",
  "flatPhysicalDamage",
  "flatStunDamage",
  "flatHolyDamage",
  "flatBurnDamage",
  "flatPoisonDamage",
  "flatBleedDamage",
  "flatFreezeDamage",
  "flatNatureDamage",
  "flatArrowDamage",
  "startBlock",
  "startArmor",
  "startForge",
  "startHeal",
  "startFreeze",
  "maxHealth",
  "armorPiercing",
  "burnDamagePerManaPercent",
  "holyDamageFromBlockPercent",
  "holyDamageFromGoldPercent",
  "frozenEnemyDamageBonusPercent",
  "flatBlockGained",
  "consumeHealBonusPercent",
  "leechHealBonusPercent",
  "goldGainPercent",
  "companionDamageBonus",
  "resistPhysical",
  "resistStun",
  "resistHoly",
  "resistBurn",
  "resistPoison",
  "resistBleed",
  "resistFreeze",
  "resistNature",
  "healthPerTurn",
  "damageOnStunPhysical",
  "blockOnStun",
  "manaOnStun",
  "poisonLeechChance",
  "natureLeechChance",
  "physicalBleedChance",
  "physicalStunChance",
  "goldOnWish",
  "burnOnWish",
  "drawOnWish",
  "healthOnWish",
  "manaOnWish",
  "healOnKill",
  "goldOnKill",
  "damageOnFreezePhysical",
  "blockDepletedHeal",
  "burnOnConsume",
  "archeryArmorPiercing",
  "damageReductionPerMana",
  "healOnBurnEnemyDefeated",
  "manaOnLeechChance",
  "poisonArmorShredChance",
  "manaOnNatureDamageChance",
  "burnDamageBonusToBleedingPercent",
  "stunOnBlockDepleted",
  "healOnCompanionAttack",
  "armorOnStunOrFreeze",
  "startThorns",
  "flatThornsDamage",
  "thornsOnBlockDepleted",
  "armorOnThornsDamage",
  "manaOnPaidConsume",
  "poisonTickOnConsume",
  "drawOnLastHandConsume",
  "blockOnCompanionSummon",
  "archeryDrawChance",
  "blockOnArcheryWithoutBlock",
  "flatArmorGained",
  "armorOnNatureCard",
  "blockOnWish",
  "leechBlockChance",
  "blockOnForgeGain",
  "thornsOnNatureCardWithoutThorns",
  "poisonOnThornsDamage",
  "healOnCombatGoldGain",
  "goldOnKillWithForge",
  "thornsOnLeechWithoutThorns",
  "stunOnLeechBelowHalfHealth",
  "nextCardDiscountOnEmptyHandWish",
  "freezeOnWish",
  "armorOnConsume",
  "holyOnConsumeWithoutMana",
  "stunOnArmorLostToAttack",
  "natureLeechVsPoisoned",
  "poisonBonusVsBleeding",
  "physicalLeechBelowHalfHealth",
  "blockOnHolyHitWithoutBlock",
  "holyBonusVsStunnedPercent",
  "thornsOnRetainedBlock",
  "healOnFirstThornsDamageEachTurn",
  "thornsDamageWhileBlocked",
  "blockOnCleanse",
  "manaOnCleanse",
  "healCleanseChance",
  "burnOnDeathsDoorEntry",
  "criticalChanceWhileDeathsDoor",
  "healOnDeathsDoorSurvival",
  "blockOnPurge",
  "holyOnPurge",
  "turnStartPurgeChance",
  "attackPurgeOncePerTurn",
  "dodgeDrawAndPlay",
  "dodgeChance",
  "blockOnDodge",
  "healOnDodge",
  "armorOnDodge",
  "physicalOnDodge",
  "nextAttackPhysicalOnDodge",
  "nextAttackCritOnDodge",
  "bleedOnDodge",
  "burnBleedMirrorAndLeech",
  "freezeGrantsBlockAndMana",
  "archeryDetonateBleedPoison",
  "elementalTwinCasting",
  "saintfallRetribution",
  "holyStunBuildupGold",
] as const;

import { createNumericManifest } from "@/lib/manifest-utils";

export const GEAR_CHANCE_EFFECT_KEYS = [
  "forgeOnStunChances",
  "forgeOnBurnVsUnburnedChances",
  "forgeOnConsumeBurnCardChances",
  "forgeOnCompanionDamageVsBurningChances",
] as const;

export const GEAR_EFFECT_KEYS = [...GEAR_NUMERIC_EFFECT_KEYS, ...GEAR_CHANCE_EFFECT_KEYS] as const;

export type GearChanceEffectKey = (typeof GEAR_CHANCE_EFFECT_KEYS)[number];

export type GearEffectManifest = {
  [K in (typeof GEAR_NUMERIC_EFFECT_KEYS)[number]]: number;
} & { [K in GearChanceEffectKey]: number[] };

export const defaultGearEffects: GearEffectManifest = {
  ...createNumericManifest(GEAR_NUMERIC_EFFECT_KEYS),
  forgeOnStunChances: [],
  forgeOnBurnVsUnburnedChances: [],
  forgeOnConsumeBurnCardChances: [],
  forgeOnCompanionDamageVsBurningChances: [],
};

export function mergeGearEffectManifests(base: GearEffectManifest, addition: GearEffectManifest): GearEffectManifest {
  const merged = { ...base };
  for (const key of GEAR_NUMERIC_EFFECT_KEYS) merged[key] += addition[key];
  return {
    ...merged,
    forgeOnStunChances: [...base.forgeOnStunChances, ...addition.forgeOnStunChances],
    forgeOnBurnVsUnburnedChances: [...base.forgeOnBurnVsUnburnedChances, ...addition.forgeOnBurnVsUnburnedChances],
    forgeOnConsumeBurnCardChances: [...base.forgeOnConsumeBurnCardChances, ...addition.forgeOnConsumeBurnCardChances],
    forgeOnCompanionDamageVsBurningChances: [
      ...base.forgeOnCompanionDamageVsBurningChances,
      ...addition.forgeOnCompanionDamageVsBurningChances,
    ],
  };
}
