export const GEAR_EFFECT_KEYS = [
  "flatPhysicalDamage",
  "flatStunDamage",
  "flatHolyDamage",
  "flatBurnDamage",
  "flatPoisonDamage",
  "flatBleedDamage",
  "flatFreezeDamage",
  "flatNatureDamage",
  "flatArrowDamage",
  "startBlock",
  "startArmor",
  "startForge",
  "startHeal",
  "startFreeze",
  "maxHealth",
  "armorPiercing",
  "burnDamagePerManaPercent",
  "holyDamageFromBlockPercent",
  "holyDamageFromGoldPercent",
  "frozenEnemyDamageBonusPercent",
  "flatBlockGained",
  "consumeHealBonusPercent",
  "leechHealBonusPercent",
  "goldGainPercent",
  "companionDamageBonus",
  "companionBenefitsFromForge",
  "resistPhysical",
  "resistStun",
  "resistHoly",
  "resistBurn",
  "resistPoison",
  "resistBleed",
  "resistFreeze",
  "resistNature",
  "healthPerTurn",
  "damageOnStunPhysical",
  "forgeOnStun",
  "blockOnStun",
  "manaOnStun",
  "poisonLeechChance",
  "natureLeechChance",
  "physicalBleedChance",
  "physicalStunChance",
  "goldOnWish",
  "burnOnWish",
  "drawOnWish",
  "healthOnWish",
  "manaOnWish",
  "healOnKill",
  "goldOnKill",
  "forgeOnBurnDealt",
  "damageOnFreezePhysical",
  "blockDepletedHeal",
  "burnOnConsume",
  "archeryArmorPiercing",
  "damageReductionPerMana",
  "healOnBurnEnemyDefeated",
  "manaOnLeechChance",
  "poisonArmorShredChance",
  "manaOnNatureDamageChance",
  "burnDamageBonusToBleedingPercent",
  "stunOnBlockDepleted",
  "healOnCompanionAttack",
  "armorOnStunOrFreeze",
  "stunPurgeDealHolyPerEffect",
  "dodgeDrawAndPlay",
  "dodgeChance",
  "blockOnDodge",
  "healOnDodge",
  "armorOnDodge",
  "physicalOnDodge",
  "nextAttackPhysicalOnDodge",
  "nextAttackCritOnDodge",
  "bleedOnDodge",
  "burnBleedMirrorAndLeech",
  "freezeGrantsBlockAndMana",
  "archeryDetonateBleedPoison",
  "elementalTwinCasting",
  "saintfallRetribution",
  "holyStunBuildupGold",
] as const;

import { createNumericManifest, mergeNumericManifests } from "@/lib/manifest-utils";

export type GearEffectManifest = {
  [K in (typeof GEAR_EFFECT_KEYS)[number]]: number;
};

export const defaultGearEffects: GearEffectManifest = createNumericManifest(GEAR_EFFECT_KEYS);

export function mergeGearEffectManifests(base: GearEffectManifest, addition: GearEffectManifest): GearEffectManifest {
  return mergeNumericManifests(base, addition, GEAR_EFFECT_KEYS);
}
