import { rollRange, type AffixRowInput } from "./affix-definition";

export const keywordExpansionAffixes = [
  {
    id: "thorns-on-retained-block",
    name: "Ironbriar",
    aspect: "defensive",
    keywordId: "thorns",
    secondaryKeywordId: "block",
    descriptionTemplate: "Gain {value} Thorns each turn you retain Block",
    effectKey: "thornsOnRetainedBlock",
    roll: rollRange(1, 2, 2, 4),
  },
  {
    id: "heal-on-first-thorns-damage",
    name: "Spiteful",
    aspect: "defensive",
    keywordId: "thorns",
    secondaryKeywordId: "health",
    descriptionTemplate: "Restore {value} Health the first time Thorns deal damage each turn",
    effectKey: "healOnFirstThornsDamageEachTurn",
    roll: rollRange(1, 3, 3, 5),
  },
  {
    id: "thorns-damage-while-blocked",
    name: "Bristling",
    aspect: "defensive",
    keywordId: "thorns",
    secondaryKeywordId: "block",
    descriptionTemplate: "Increase Thorns damage by {value} while you have Block",
    effectKey: "thornsDamageWhileBlocked",
    roll: rollRange(1, 3, 3, 5),
  },
  {
    id: "block-on-cleanse",
    name: "Clearheaded",
    aspect: "defensive",
    keywordId: "block",
    secondaryKeywordId: "holy",
    descriptionTemplate: "Gain {value} Block when you Cleanse a harmful status",
    effectKey: "blockOnCleanse",
    roll: rollRange(1, 3, 3, 5),
  },
  {
    id: "heal-cleanse-chance",
    name: "Restorative",
    aspect: "defensive",
    keywordId: "health",
    secondaryKeywordId: "holy",
    descriptionTemplate: "Restoring Health has a {value}% chance to Cleanse a harmful status",
    effectKey: "healCleanseChance",
    roll: rollRange(8, 12, 15, 25),
  },
  {
    id: "mana-on-cleanse",
    name: "Solace",
    aspect: "defensive",
    keywordId: "mana",
    secondaryKeywordId: "holy",
    descriptionTemplate: "Gain {value} Mana when you Cleanse a harmful status",
    effectKey: "manaOnCleanse",
    roll: rollRange(1, 2, 1, 3),
  },
  {
    id: "purge-on-first-paid-card",
    name: "Spellrending",
    aspect: "offensive",
    keywordId: "mana",
    secondaryKeywordId: "holy",
    descriptionTemplate: "The first time you spend Mana each turn, Purge an enemy's beneficial status effect",
    effectKey: "purgeOnFirstPaidCard",
    roll: rollRange(1, 1, 1, 1),
  },
  {
    id: "block-on-purge",
    name: "Unraveling",
    aspect: "offensive",
    keywordId: "block",
    secondaryKeywordId: "holy",
    descriptionTemplate: "Gain {value} Block when you Purge an enemy",
    effectKey: "blockOnPurge",
    roll: rollRange(1, 3, 3, 5),
  },
  {
    id: "holy-on-purge",
    name: "Denouncing",
    aspect: "offensive",
    keywordId: "holy",
    secondaryKeywordId: "mana",
    descriptionTemplate: "Deal {value} Holy damage when you Purge an enemy",
    effectKey: "holyOnPurge",
    roll: rollRange(1, 3, 3, 5),
  },
  {
    id: "burn-on-deaths-door-entry",
    name: "Emberwake",
    aspect: "defensive",
    keywordId: "burn",
    secondaryKeywordId: "leech",
    descriptionTemplate: "Deal {value} Burn damage when you enter Death’s Door",
    effectKey: "burnOnDeathsDoorEntry",
    roll: rollRange(2, 4, 5, 7),
  },
  {
    id: "crit-on-deaths-door",
    name: "Lastwatch",
    aspect: "defensive",
    keywordId: "leech",
    secondaryKeywordId: "burn",
    descriptionTemplate: "Gain {value}% Critical Hit chance while on Death's Door",
    effectKey: "criticalChanceWhileDeathsDoor",
    roll: rollRange(8, 12, 15, 25),
  },
  {
    id: "heal-on-deaths-door-survival",
    name: "Rekindled",
    aspect: "defensive",
    keywordId: "health",
    secondaryKeywordId: "leech",
    descriptionTemplate: "Restore {value} Health when you survive Death’s Door",
    effectKey: "healOnDeathsDoorSurvival",
    roll: rollRange(2, 4, 5, 7),
  },
] as const satisfies readonly AffixRowInput[];
