import { rollRange, resistAffix, ROLL_SMALL, ROLL_PERCENT, ROLL_MEDIUM, type AffixRowInput } from "./affix-definition";

export const primaryAffixes = [
  {
    id: "flat-physical",
    name: "Ironbound",
    aspect: "offensive",
    keywordId: "physical",
    descriptionTemplate: "Increases Physical damage by {value}",
    effectKey: "flatPhysicalDamage",
    roll: ROLL_SMALL,
  },
  {
    id: "flat-stun",
    name: "Concussive",
    aspect: "offensive",
    keywordId: "stun",
    descriptionTemplate: "Increases Stun damage by {value}",
    effectKey: "flatStunDamage",
    roll: ROLL_SMALL,
  },
  {
    id: "flat-holy",
    name: "Sanctified",
    aspect: "offensive",
    keywordId: "holy",
    descriptionTemplate: "Increases Holy damage by {value}",
    effectKey: "flatHolyDamage",
    roll: ROLL_SMALL,
  },
  {
    id: "flat-burn",
    name: "Blazing",
    aspect: "offensive",
    keywordId: "burn",
    descriptionTemplate: "Increases Burn damage by {value}",
    effectKey: "flatBurnDamage",
    roll: ROLL_SMALL,
  },
  {
    id: "flat-poison",
    name: "Venomous",
    aspect: "offensive",
    keywordId: "poison",
    descriptionTemplate: "Increases Poison damage by {value}",
    effectKey: "flatPoisonDamage",
    roll: ROLL_SMALL,
  },
  {
    id: "flat-bleed",
    name: "Serrated",
    aspect: "offensive",
    keywordId: "bleed",
    descriptionTemplate: "Increases Bleed damage by {value}",
    effectKey: "flatBleedDamage",
    roll: ROLL_SMALL,
  },
  {
    id: "flat-freeze",
    name: "Glacial",
    aspect: "offensive",
    keywordId: "freeze",
    descriptionTemplate: "Increases Freeze damage by {value}",
    effectKey: "flatFreezeDamage",
    roll: ROLL_SMALL,
  },
  {
    id: "flat-nature",
    name: "Wildheart",
    aspect: "offensive",
    keywordId: "nature",
    descriptionTemplate: "Increases Nature damage by {value}",
    effectKey: "flatNatureDamage",
    roll: ROLL_SMALL,
  },
  {
    id: "start-block",
    name: "Bastioned",
    aspect: "defensive",
    keywordId: "block",
    descriptionTemplate: "Gain {value} Block at the start of combat",
    effectKey: "startBlock",
    roll: rollRange(4, 6, 7, 9),
  },
  {
    id: "armor-pierce",
    name: "Piercing",
    aspect: "offensive",
    keywordId: "physical",
    descriptionTemplate: "Ignore {value} enemy Armor",
    effectKey: "armorPiercing",
    roll: rollRange(1, 2, 2, 4),
  },
  {
    id: "damage-on-stun",
    name: "Stunning",
    aspect: "offensive",
    keywordId: "physical",
    descriptionTemplate: "Deal {value} Physical damage when you Stun an enemy",
    effectKey: "damageOnStunPhysical",
    roll: ROLL_MEDIUM,
  },
  {
    id: "forge-on-stun",
    name: "Forged",
    aspect: "offensive",
    keywordId: "forge",
    descriptionTemplate: "If you have no Forge, Stunning an enemy grants {value} Forge",
    effectKey: "forgeOnStun",
    roll: rollRange(1, 2, 2, 4),
  },
  {
    id: "poison-leech",
    name: "Leeching",
    aspect: "offensive",
    keywordId: "leech",
    descriptionTemplate: "Poison has a {value}% chance to Leech",
    effectKey: "poisonLeechChance",
    roll: rollRange(5, 7, 8, 10),
    secondaryKeywordId: "poison",
  },
  {
    id: "companion-damage",
    name: "Packbound",
    aspect: "offensive",
    keywordId: "companion",
    descriptionTemplate: "Increases Companion damage by {value}",
    effectKey: "companionDamageBonus",
    roll: rollRange(1, 2, 2, 4),
  },
  {
    id: "start-heal",
    name: "Vital",
    aspect: "defensive",
    keywordId: "health",
    descriptionTemplate: "Restore {value} Health at the start of combat",
    effectKey: "startHeal",
    roll: ROLL_MEDIUM,
  },
  {
    id: "heal-on-kill",
    name: "Gravebound",
    aspect: "defensive",
    keywordId: "health",
    descriptionTemplate: "Restore {value} Health on kill",
    effectKey: "healOnKill",
    roll: ROLL_MEDIUM,
  },
  {
    id: "start-forge",
    name: "Tempered",
    aspect: "defensive",
    keywordId: "forge",
    descriptionTemplate: "Gain {value} Forge at the start of combat",
    effectKey: "startForge",
    roll: rollRange(1, 2, 2, 4),
  },
  {
    id: "start-armor",
    name: "Plated",
    aspect: "defensive",
    keywordId: "armor",
    descriptionTemplate: "Gain {value} Armor at the start of combat",
    effectKey: "startArmor",
    roll: rollRange(1, 2, 2, 4),
  },
  {
    id: "block-on-stun",
    name: "Steadfast",
    aspect: "defensive",
    keywordId: "block",
    descriptionTemplate: "If you have no Block, Stunning an enemy grants {value} Block",
    effectKey: "blockOnStun",
    roll: ROLL_MEDIUM,
  },
  {
    id: "mana-on-stun",
    name: "Arcane",
    aspect: "offensive",
    keywordId: "mana",
    descriptionTemplate: "If you have no Mana, Stunning an enemy grants {value} Mana",
    effectKey: "manaOnStun",
    roll: rollRange(1, 1, 2, 2),
  },
  {
    id: "physical-bleed-chance",
    name: "Bloodletting",
    aspect: "offensive",
    keywordId: "bleed",
    descriptionTemplate: "{value}% chance for Physical damage to Bleed",
    effectKey: "physicalBleedChance",
    roll: rollRange(7, 8, 9, 10),
    secondaryKeywordId: "physical",
  },
  {
    id: "burn-per-mana",
    name: "Pyric",
    aspect: "offensive",
    keywordId: "burn",
    descriptionTemplate: "Increases Burn damage by {value}% per Mana Crystal",
    effectKey: "burnDamagePerManaPercent",
    roll: ROLL_PERCENT,
    secondaryKeywordId: "mana",
  },
  {
    id: "gold-on-wish",
    name: "Wishful",
    aspect: "offensive",
    keywordId: "gold",
    descriptionTemplate: "When you Wish, sometimes gain {value} Gold (50% chance)",
    effectKey: "goldOnWish",
    roll: ROLL_SMALL,
    secondaryKeywordId: "wish",
  },
  {
    id: "burn-on-wish",
    name: "Wishfire",
    aspect: "offensive",
    keywordId: "burn",
    descriptionTemplate: "When you Wish, deal {value} Burn damage to Burning enemies",
    effectKey: "burnOnWish",
    roll: ROLL_SMALL,
    secondaryKeywordId: "wish",
  },
  {
    id: "gold-on-kill",
    name: "Greed",
    aspect: "offensive",
    keywordId: "gold",
    descriptionTemplate: "Gain {value} Gold on kill",
    effectKey: "goldOnKill",
    roll: rollRange(4, 5, 6, 7),
  },
  {
    id: "physical-stun-chance",
    name: "Thunderous",
    aspect: "offensive",
    keywordId: "stun",
    descriptionTemplate: "{value}% chance for Physical damage to Stun",
    effectKey: "physicalStunChance",
    roll: rollRange(5, 10, 10, 15),
    secondaryKeywordId: "physical",
  },
  {
    id: "nature-leech",
    name: "Sylvan",
    aspect: "offensive",
    keywordId: "leech",
    descriptionTemplate: "Nature damage has a {value}% chance to Leech",
    effectKey: "natureLeechChance",
    roll: rollRange(7, 8, 9, 10),
    secondaryKeywordId: "nature",
  },
  {
    id: "forge-on-burn",
    name: "Emberforged",
    aspect: "offensive",
    keywordId: "forge",
    descriptionTemplate: "Burn damage against non-Burning enemies gains {value} Forge",
    effectKey: "forgeOnBurnVsUnburned",
    roll: rollRange(1, 1, 2, 2),
    secondaryKeywordId: "burn",
  },
  {
    id: "draw-on-wish",
    name: "Fateful",
    aspect: "offensive",
    keywordId: "wish",
    descriptionTemplate: "Draw {value} Cards on Wish",
    effectKey: "drawOnWish",
    roll: rollRange(1, 1, 2, 2),
  },
  {
    id: "consume-heal-bonus",
    name: "Nourishing",
    aspect: "defensive",
    keywordId: "consume",
    descriptionTemplate: "Increases Health restored by Consumed cards by {value}%",
    effectKey: "consumeHealBonusPercent",
    roll: ROLL_PERCENT,
    secondaryKeywordId: "health",
  },
  {
    id: "archery-damage",
    name: "Fletched",
    aspect: "offensive",
    keywordId: "archery",
    descriptionTemplate: "Increases Archery damage by {value}",
    effectKey: "flatArrowDamage",
    roll: rollRange(2, 3, 4, 5),
  },
  {
    id: "damage-on-freeze",
    name: "Shattering",
    aspect: "offensive",
    keywordId: "physical",
    descriptionTemplate: "Deal {value} Physical damage when you Freeze an enemy",
    effectKey: "damageOnFreezePhysical",
    roll: ROLL_MEDIUM,
    secondaryKeywordId: "freeze",
  },
  {
    id: "heal-on-block-depleted",
    name: "Resolute",
    aspect: "defensive",
    keywordId: "health",
    descriptionTemplate: "Restore {value} Health when Block is depleted",
    effectKey: "blockDepletedHeal",
    roll: rollRange(2, 3, 4, 5),
    secondaryKeywordId: "block",
  },
  {
    id: "health-on-wish",
    name: "Wishborn",
    aspect: "defensive",
    keywordId: "health",
    descriptionTemplate: "When you Wish below half Health, restore {value} Health",
    effectKey: "healthOnWish",
    roll: rollRange(2, 3, 4, 5),
    secondaryKeywordId: "wish",
  },
  {
    id: "mana-on-wish",
    name: "Wishwoven",
    aspect: "offensive",
    keywordId: "mana",
    descriptionTemplate: "When you Wish without Mana, gain {value} Mana",
    effectKey: "manaOnWish",
    roll: rollRange(1, 1, 2, 2),
    secondaryKeywordId: "wish",
  },
  {
    id: "start-freeze",
    name: "Bitter",
    aspect: "defensive",
    keywordId: "freeze",
    descriptionTemplate: "Deal {value} Freeze damage at the start of combat",
    effectKey: "startFreeze",
    roll: rollRange(4, 5, 6, 7),
  },
  {
    id: "holy-from-block",
    name: "Aegis",
    aspect: "offensive",
    keywordId: "holy",
    descriptionTemplate: "Increases Holy damage by {value}% of your Block",
    effectKey: "holyDamageFromBlockPercent",
    roll: ROLL_PERCENT,
    secondaryKeywordId: "block",
  },
  {
    id: "leech-potency",
    name: "Sanguine",
    aspect: "offensive",
    keywordId: "leech",
    descriptionTemplate: "Leech restores {value}% more Health",
    effectKey: "leechHealBonusPercent",
    roll: ROLL_PERCENT,
  },
  {
    id: "frozen-vulnerable",
    name: "Frigid",
    aspect: "offensive",
    keywordId: "freeze",
    descriptionTemplate: "Frozen enemies take {value}% more damage",
    effectKey: "frozenEnemyDamageBonusPercent",
    roll: ROLL_PERCENT,
  },
] as const satisfies readonly AffixRowInput[];

export const secondaryAffixes = [
  {
    id: "gold-blessed-holy",
    name: "Aureate",
    aspect: "offensive",
    keywordId: "holy",
    descriptionTemplate: "Increases Holy damage by {value}% of your Gold",
    effectKey: "holyDamageFromGoldPercent",
    roll: rollRange(2, 3, 4, 5),
    secondaryKeywordId: "gold",
  },
  resistAffix("resist-physical", "Stoneward", "physical", "resistPhysical"),
  resistAffix("resist-stun", "Unshaken", "stun", "resistStun"),
  resistAffix("resist-holy", "Shadowveiled", "holy", "resistHoly"),
  resistAffix("resist-burn", "Fireproof", "burn", "resistBurn"),
  resistAffix("resist-poison", "Antivenom", "poison", "resistPoison"),
  resistAffix("resist-bleed", "Scarbound", "bleed", "resistBleed"),
  resistAffix("resist-freeze", "Warmblooded", "freeze", "resistFreeze"),
  resistAffix("resist-nature", "Thornward", "nature", "resistNature"),
  {
    id: "health-per-turn",
    name: "Lifegiving",
    aspect: "defensive",
    keywordId: "health",
    descriptionTemplate: "Restore {value} Health each turn",
    effectKey: "healthPerTurn",
    roll: rollRange(1, 1, 1, 1),
  },
  {
    id: "block-gain",
    name: "Warding",
    aspect: "defensive",
    keywordId: "block",
    descriptionTemplate: "Increases Block gained by {value}",
    effectKey: "flatBlockGained",
    roll: ROLL_SMALL,
  },
  {
    id: "gold-gain",
    name: "Prosperous",
    aspect: "defensive",
    keywordId: "gold",
    descriptionTemplate: "Increases Gold gained by {value}%",
    effectKey: "goldGainPercent",
    roll: ROLL_PERCENT,
  },
  {
    id: "max-health",
    name: "Enduring",
    aspect: "defensive",
    keywordId: "health",
    descriptionTemplate: "Increases Health by {value}",
    effectKey: "maxHealth",
    roll: rollRange(7, 8, 9, 10),
  },
  {
    id: "burn-on-consume",
    name: "Consuming",
    aspect: "offensive",
    keywordId: "consume",
    descriptionTemplate: "Burn cards with Consume deal {value} additional Burn damage",
    effectKey: "burnOnConsume",
    roll: rollRange(2, 3, 4, 6),
    secondaryKeywordId: "burn",
  },
  {
    id: "archery-ignore-armor",
    name: "Armorbreaking",
    aspect: "offensive",
    keywordId: "archery",
    descriptionTemplate: "Archery attacks ignore {value} Armor",
    effectKey: "archeryArmorPiercing",
    roll: ROLL_SMALL,
    secondaryKeywordId: "physical",
  },
  {
    id: "absorb-per-mana",
    name: "Aetherward",
    aspect: "defensive",
    keywordId: "mana",
    descriptionTemplate: "Reduce damage taken by your number of full Mana Crystals",
    effectKey: "damageReductionPerMana",
    roll: rollRange(1, 1, 1, 1),
    secondaryKeywordId: "block",
  },
  {
    id: "heal-on-burn-death",
    name: "Cauterizing",
    aspect: "defensive",
    keywordId: "burn",
    descriptionTemplate: "Restore {value} Health when an enemy with Burn is defeated",
    effectKey: "healOnBurnEnemyDefeated",
    roll: rollRange(4, 5, 6, 7),
    secondaryKeywordId: "health",
  },
  {
    id: "mana-on-leech-chance",
    name: "Siphoning",
    aspect: "offensive",
    keywordId: "leech",
    descriptionTemplate: "Leech has a {value}% chance to restore 1 Mana",
    effectKey: "manaOnLeechChance",
    roll: ROLL_PERCENT,
    secondaryKeywordId: "mana",
  },
  {
    id: "poison-reduces-armor",
    name: "Corrosive",
    aspect: "offensive",
    keywordId: "poison",
    descriptionTemplate: "Poison has a {value}% chance to remove 1 Armor",
    effectKey: "poisonArmorShredChance",
    roll: ROLL_PERCENT,
    secondaryKeywordId: "armor",
  },
  {
    id: "nature-mana-refund-chance",
    name: "Bloomwoven",
    aspect: "offensive",
    keywordId: "nature",
    descriptionTemplate: "Nature damage has a {value}% chance to restore 1 Mana",
    effectKey: "manaOnNatureDamageChance",
    roll: ROLL_PERCENT,
    secondaryKeywordId: "mana",
  },
  {
    id: "burn-on-bleed",
    name: "Cinderbound",
    aspect: "offensive",
    keywordId: "bleed",
    descriptionTemplate: "Burn deals {value}% more damage to Bleeding enemies",
    effectKey: "burnDamageBonusToBleedingPercent",
    roll: ROLL_PERCENT,
    secondaryKeywordId: "burn",
  },
  {
    id: "stun-on-block-hit",
    name: "Reactive",
    aspect: "defensive",
    keywordId: "block",
    descriptionTemplate: "Deal {value} Stun damage when your Block is depleted",
    effectKey: "stunOnBlockDepleted",
    roll: rollRange(2, 3, 4, 5),
    secondaryKeywordId: "stun",
  },
  {
    id: "companion-leech",
    name: "Kinbound",
    aspect: "defensive",
    keywordId: "companion",
    descriptionTemplate: "Below half Health, restore {value} Health when your Companion deals damage",
    effectKey: "healOnCompanionAttack",
    roll: ROLL_SMALL,
    secondaryKeywordId: "health",
  },
  {
    id: "armor-on-cc",
    name: "Stalwart",
    aspect: "defensive",
    keywordId: "armor",
    descriptionTemplate: "Gain {value} Armor when you are Stunned or Frozen",
    effectKey: "armorOnStunOrFreeze",
    roll: ROLL_SMALL,
    secondaryKeywordId: "stun",
  },
  {
    id: "start-thorns",
    name: "Thornwrought",
    aspect: "defensive",
    keywordId: "thorns",
    secondaryKeywordId: "armor",
    descriptionTemplate: "Gain {value} Thorns at the start of combat",
    effectKey: "startThorns",
    roll: rollRange(1, 2, 3, 4),
  },
  {
    id: "thorns-damage",
    name: "Barbed",
    aspect: "offensive",
    keywordId: "thorns",
    secondaryKeywordId: "nature",
    descriptionTemplate: "Increases Thorns damage by {value}",
    effectKey: "flatThornsDamage",
    roll: ROLL_SMALL,
  },
  {
    id: "thorns-on-block-depleted",
    name: "Briarward",
    aspect: "defensive",
    keywordId: "thorns",
    secondaryKeywordId: "block",
    descriptionTemplate: "When your Block is depleted, gain {value} Thorns",
    effectKey: "thornsOnBlockDepleted",
    roll: rollRange(2, 3, 4, 5),
  },
  {
    id: "forge-on-consume-burn",
    name: "Cinderfed",
    aspect: "offensive",
    keywordId: "consume",
    secondaryKeywordId: "burn",
    descriptionTemplate: "When you Consume a Burn card, gain {value} Forge",
    effectKey: "forgeOnConsumeBurnCard",
    roll: rollRange(1, 1, 2, 2),
  },
  {
    id: "armor-on-thorns-damage",
    name: "Briarplate",
    aspect: "defensive",
    keywordId: "thorns",
    secondaryKeywordId: "armor",
    descriptionTemplate: "When your Thorns deal damage, gain {value} Armor",
    effectKey: "armorOnThornsDamage",
    roll: rollRange(1, 1, 2, 2),
  },
  {
    id: "mana-on-paid-consume",
    name: "Distilled",
    aspect: "offensive",
    keywordId: "consume",
    secondaryKeywordId: "mana",
    descriptionTemplate: "When you Consume a card that cost Mana, restore {value} Mana",
    effectKey: "manaOnPaidConsume",
    roll: rollRange(1, 1, 1, 2),
  },
  {
    id: "poison-tick-on-consume",
    name: "Rotbloom",
    aspect: "offensive",
    keywordId: "consume",
    secondaryKeywordId: "poison",
    descriptionTemplate: "When you Consume a card, your Poison deals damage immediately",
    effectKey: "poisonTickOnConsume",
    roll: rollRange(1, 1, 1, 1),
  },
  {
    id: "draw-on-last-hand-consume",
    name: "Afterglow",
    aspect: "offensive",
    keywordId: "consume",
    secondaryKeywordId: "mana",
    descriptionTemplate: "When you Consume your last card in hand, draw {value} Cards",
    effectKey: "drawOnLastHandConsume",
    roll: rollRange(1, 1, 1, 2),
  },
  {
    id: "block-on-companion-summon",
    name: "Packguard",
    aspect: "defensive",
    keywordId: "companion",
    secondaryKeywordId: "block",
    descriptionTemplate: "When you summon a Companion, gain {value} Block",
    effectKey: "blockOnCompanionSummon",
    roll: rollRange(2, 3, 4, 5),
  },
  {
    id: "forge-on-companion-burning-damage",
    name: "Trailforged",
    aspect: "offensive",
    keywordId: "companion",
    secondaryKeywordId: "forge",
    descriptionTemplate: "When your Companion damages a Burning enemy, gain {value} Forge",
    effectKey: "forgeOnCompanionDamageVsBurning",
    roll: rollRange(1, 1, 2, 2),
  },
  {
    id: "archery-draw-chance",
    name: "Quickfletched",
    aspect: "offensive",
    keywordId: "archery",
    descriptionTemplate: "Archery cards have a {value}% chance to draw a card",
    effectKey: "archeryDrawChance",
    roll: ROLL_PERCENT,
  },
  {
    id: "block-on-archery-without-block",
    name: "Covering",
    aspect: "defensive",
    keywordId: "archery",
    secondaryKeywordId: "block",
    descriptionTemplate: "When you play an Archery card without Block, gain {value} Block",
    effectKey: "blockOnArcheryWithoutBlock",
    roll: rollRange(2, 3, 4, 5),
  },
  {
    id: "armor-gain",
    name: "Layered",
    aspect: "defensive",
    keywordId: "armor",
    descriptionTemplate: "Increases Armor gained by {value}",
    effectKey: "flatArmorGained",
    roll: rollRange(1, 1, 1, 2),
  },
  {
    id: "armor-on-nature-card",
    name: "Ironroot",
    aspect: "defensive",
    keywordId: "armor",
    secondaryKeywordId: "nature",
    descriptionTemplate: "Gain {value} Armor when you play a Nature card",
    effectKey: "armorOnNatureCard",
    roll: rollRange(1, 1, 2, 2),
  },
  {
    id: "block-on-wish",
    name: "Wishguard",
    aspect: "defensive",
    keywordId: "wish",
    secondaryKeywordId: "block",
    descriptionTemplate: "When you Wish, gain {value} Block",
    effectKey: "blockOnWish",
    roll: rollRange(1, 2, 2, 3),
  },
  {
    id: "leech-block-chance",
    name: "Bloodward",
    aspect: "defensive",
    keywordId: "leech",
    secondaryKeywordId: "block",
    descriptionTemplate: "Leech has a {value}% chance to also grant an equal amount of Block",
    effectKey: "leechBlockChance",
    roll: ROLL_PERCENT,
  },
  {
    id: "block-on-last-forge-spent",
    name: "Smithguard",
    aspect: "defensive",
    keywordId: "forge",
    secondaryKeywordId: "block",
    descriptionTemplate: "When you spend your last Forge, gain {value} Block",
    effectKey: "blockOnLastForgeSpent",
    roll: rollRange(2, 3, 4, 5),
  },
] as const satisfies readonly AffixRowInput[];

export const dodgeAffixes = [
  {
    id: "dodge-chance",
    name: "Elusive",
    aspect: "defensive",
    keywordId: "dodge",
    descriptionTemplate: "Increases Dodge chance by {value}%",
    effectKey: "dodgeChance",
    roll: rollRange(1, 2, 2, 3),
  },
  {
    id: "dodge-block",
    name: "Nimble",
    aspect: "defensive",
    keywordId: "dodge",
    descriptionTemplate: "When you Dodge without Block, gain {value} Block",
    effectKey: "blockOnDodge",
    roll: rollRange(2, 3, 4, 5),
  },
  {
    id: "dodge-heal",
    name: "Winded",
    aspect: "defensive",
    keywordId: "dodge",
    descriptionTemplate: "When you Dodge below half Health, restore {value} Health",
    effectKey: "healOnDodge",
    roll: rollRange(1, 2, 2, 3),
  },
  {
    id: "dodge-armor",
    name: "Wardplate",
    aspect: "defensive",
    keywordId: "dodge",
    descriptionTemplate: "When you Dodge without Armor, gain {value} Armor",
    effectKey: "armorOnDodge",
    roll: rollRange(1, 2, 2, 3),
  },
  {
    id: "dodge-riposte",
    name: "Riposting",
    aspect: "offensive",
    keywordId: "dodge",
    descriptionTemplate: "When you Dodge, sometimes deal {value} Physical damage (50% chance)",
    effectKey: "physicalOnDodge",
    roll: rollRange(2, 3, 4, 6),
  },
  {
    id: "dodge-opening",
    name: "Opportunist",
    aspect: "offensive",
    keywordId: "dodge",
    descriptionTemplate: "Your next attack deals {value} additional Physical damage when you Dodge",
    effectKey: "nextAttackPhysicalOnDodge",
    roll: rollRange(2, 3, 4, 6),
  },
] as const satisfies readonly AffixRowInput[];

export const dodgeBleedAffixes = [
  {
    id: "dodge-bleed",
    name: "Fleeting",
    aspect: "offensive",
    keywordId: "dodge",
    descriptionTemplate: "When you Dodge a Bleeding enemy, deal {value} Bleed damage",
    effectKey: "bleedOnDodge",
    roll: rollRange(2, 3, 4, 5),
  },
] as const satisfies readonly AffixRowInput[];

export const keywordGapAffixes = [
  {
    id: "thorns-on-nature-without-thorns",
    name: "Bramblecall",
    aspect: "defensive",
    keywordId: "thorns",
    secondaryKeywordId: "nature",
    descriptionTemplate: "When you play a Nature card without Thorns, gain {value} Thorns",
    effectKey: "thornsOnNatureCardWithoutThorns",
    roll: rollRange(1, 2, 2, 3),
  },
  {
    id: "poison-on-thorns-damage",
    name: "Spitebloom",
    aspect: "offensive",
    keywordId: "thorns",
    secondaryKeywordId: "poison",
    descriptionTemplate: "When your Thorns deal damage, deal {value} Poison damage",
    effectKey: "poisonOnThornsDamage",
    roll: rollRange(1, 2, 2, 3),
  },
  {
    id: "heal-on-combat-gold",
    name: "Gildmend",
    aspect: "defensive",
    keywordId: "gold",
    secondaryKeywordId: "health",
    descriptionTemplate: "When you gain Gold in combat, restore {value} Health",
    effectKey: "healOnCombatGoldGain",
    roll: rollRange(1, 2, 2, 3),
  },
  {
    id: "gold-on-kill-with-forge",
    name: "Tithebound",
    aspect: "offensive",
    keywordId: "gold",
    secondaryKeywordId: "forge",
    descriptionTemplate: "Gain {value} Gold when you defeat an enemy with Forge remaining",
    effectKey: "goldOnKillWithForge",
    roll: rollRange(2, 3, 4, 5),
  },
  {
    id: "thorns-on-leech-without-thorns",
    name: "Bloodroot",
    aspect: "defensive",
    keywordId: "leech",
    secondaryKeywordId: "thorns",
    descriptionTemplate: "When Leech restores Health while you have no Thorns, gain {value} Thorns",
    effectKey: "thornsOnLeechWithoutThorns",
    roll: rollRange(1, 2, 2, 3),
  },
  {
    id: "stun-on-leech-below-half",
    name: "Heartshock",
    aspect: "offensive",
    keywordId: "leech",
    secondaryKeywordId: "stun",
    descriptionTemplate: "When Leech restores Health while you are below half Health, deal {value} Stun damage",
    effectKey: "stunOnLeechBelowHalfHealth",
    roll: rollRange(1, 2, 2, 3),
  },
  {
    id: "discount-on-empty-hand-wish",
    name: "Starcatcher",
    aspect: "offensive",
    keywordId: "wish",
    secondaryKeywordId: "mana",
    descriptionTemplate: "When you Wish with an empty hand, the next card you play costs {value} less Mana",
    effectKey: "nextCardDiscountOnEmptyHandWish",
    roll: rollRange(1, 1, 1, 2),
  },
  {
    id: "freeze-on-wish",
    name: "Starfall",
    aspect: "offensive",
    keywordId: "wish",
    secondaryKeywordId: "freeze",
    descriptionTemplate: "When you Wish, deal {value} Freeze damage",
    effectKey: "freezeOnWish",
    roll: rollRange(2, 3, 4, 5),
  },
  {
    id: "armor-on-consume",
    name: "Ashkeeper",
    aspect: "defensive",
    keywordId: "consume",
    secondaryKeywordId: "armor",
    descriptionTemplate: "When you Consume a card, gain {value} Armor",
    effectKey: "armorOnConsume",
    roll: rollRange(1, 1, 1, 2),
  },
  {
    id: "holy-on-consume-without-mana",
    name: "Lastlight",
    aspect: "offensive",
    keywordId: "consume",
    secondaryKeywordId: "holy",
    descriptionTemplate: "When you Consume a card while you have no Mana, deal {value} Holy damage",
    effectKey: "holyOnConsumeWithoutMana",
    roll: rollRange(1, 2, 2, 3),
  },
  {
    id: "stun-on-armor-lost-to-attack",
    name: "Counterplate",
    aspect: "defensive",
    keywordId: "armor",
    secondaryKeywordId: "stun",
    descriptionTemplate: "When an attack removes your Armor, deal {value} Stun damage",
    effectKey: "stunOnArmorLostToAttack",
    roll: rollRange(2, 3, 4, 5),
  },
  {
    id: "nature-leech-vs-poisoned",
    name: "Rootmender",
    aspect: "offensive",
    keywordId: "nature",
    secondaryKeywordId: "leech",
    descriptionTemplate: "Nature damage against Poisoned enemies gains Leech",
    effectKey: "natureLeechVsPoisoned",
    roll: rollRange(1, 1, 1, 1),
  },
  {
    id: "poison-bonus-vs-bleeding",
    name: "Venomtrail",
    aspect: "offensive",
    keywordId: "poison",
    secondaryKeywordId: "bleed",
    descriptionTemplate: "Poison deals {value} additional damage against Bleeding enemies",
    effectKey: "poisonBonusVsBleeding",
    roll: rollRange(1, 2, 2, 3),
  },
  {
    id: "physical-leech-below-half",
    name: "Scarfeast",
    aspect: "offensive",
    keywordId: "physical",
    secondaryKeywordId: "leech",
    descriptionTemplate: "Physical attacks gain Leech while you're below half Health",
    effectKey: "physicalLeechBelowHalfHealth",
    roll: rollRange(1, 1, 1, 1),
  },
  {
    id: "block-on-holy-hit-without-block",
    name: "Hallowguard",
    aspect: "defensive",
    keywordId: "holy",
    secondaryKeywordId: "block",
    descriptionTemplate: "When a Holy attack damages an enemy while you have no Block, gain {value} Block",
    effectKey: "blockOnHolyHitWithoutBlock",
    roll: rollRange(2, 3, 4, 5),
  },
  {
    id: "holy-bonus-vs-stunned",
    name: "Hallowbreak",
    aspect: "offensive",
    keywordId: "holy",
    secondaryKeywordId: "stun",
    descriptionTemplate: "Stunned enemies take {value}% more Holy damage",
    effectKey: "holyBonusVsStunnedPercent",
    roll: rollRange(20, 25, 30, 35),
  },
] as const satisfies readonly AffixRowInput[];
