import { uniqueAffix, type AffixRowInput } from "./affix-definition";

export const primaryUniqueAffixes = [
  uniqueAffix(
    "the-unclosing-wound",
    "The Unclosing Wound",
    "offensive",
    "bleed",
    "Enemy Bleed halves each turn instead of expiring.",
    "bleedDecaysByHalf",
    "physical",
  ),
  uniqueAffix(
    "kingbreaker",
    "Kingbreaker",
    "offensive",
    "stun",
    "Enemy Armor increases your Stun damage instead of reducing it.",
    "armorIncreasesStun",
    "physical",
  ),
  uniqueAffix(
    "everkeen",
    "Everkeen",
    "offensive",
    "forge",
    "Gaining Forge makes your next Physical card strike twice.",
    "forgeReadiesPhysicalRepeat",
    "physical",
  ),
  uniqueAffix(
    "red-harvest",
    "Red Harvest",
    "offensive",
    "physical",
    "Each turn, return your first Physical card to hand. It costs 1 less Mana.",
    "returnFirstPhysicalCard",
    "bleed",
  ),
  uniqueAffix(
    "oathkeeper",
    "Oathkeeper",
    "offensive",
    "forge",
    "Forge also strengthens Holy damage. Holy damage never spends Forge.",
    "holyPreservesForge",
    "holy",
  ),
  uniqueAffix(
    "the-patient-edge",
    "The Patient Edge",
    "offensive",
    "forge",
    "Recover Forge spent on attacks at the start of your next turn.",
    "recoverSpentForge",
    "physical",
  ),
  uniqueAffix(
    "vipers-courtesy",
    "Viper’s Courtesy",
    "offensive",
    "dodge",
    "After Dodging, your next Physical hit adds half its damage as Poison and Bleed.",
    "dodgeReadiesVenomousHit",
    "poison",
  ),
  uniqueAffix(
    "the-lingering-bell",
    "The Lingering Bell",
    "offensive",
    "stun",
    "Stunning an enemy preserves a quarter of its Stun buildup.",
    "retainStunBuildup",
    "holy",
  ),
  uniqueAffix(
    "huntsmasters-call",
    "Huntsmaster’s Call",
    "offensive",
    "archery",
    "Your first Archery card each turn makes all Companions attack again.",
    "firstArcheryCompanionAttack",
    "companion",
  ),
  uniqueAffix(
    "wrenflight",
    "Wrenflight",
    "offensive",
    "archery",
    "Archery grants 10% Dodge until your next turn. Dodging draws an Archery card.",
    "archeryDodgeAndDraw",
    "dodge",
  ),
  uniqueAffix(
    "the-returning-gale",
    "The Returning Gale",
    "offensive",
    "archery",
    "Archery cards repeat their damage at half strength next turn.",
    "archeryEchoNextTurn",
    "nature",
  ),
  uniqueAffix(
    "the-final-spark",
    "The Final Spark",
    "offensive",
    "mana",
    "Spend your last Mana to repeat a Burn or Freeze card’s damage. Once per turn.",
    "lastManaElementalRepeat",
    "burn",
  ),
  uniqueAffix(
    "laughing-guard",
    "Laughing Guard",
    "defensive",
    "block",
    "Keep Block between turns. Dodging spends half your Block to deal that much Physical damage.",
    "dodgeSpendsPreservedBlock",
    "dodge",
  ),
  uniqueAffix(
    "the-knights-answer",
    "The Knight’s Answer",
    "defensive",
    "block",
    "Blocking an attack makes your next Physical card free.",
    "blockReadiesFreePhysical",
    "physical",
  ),
  uniqueAffix(
    "the-returning-flight",
    "The Returning Flight",
    "offensive",
    "archery",
    "Each turn, recover your last Archery card. It costs 1 less Mana.",
    "recoverLastArcheryCard",
    "dodge",
  ),
  uniqueAffix(
    "threefold-grace",
    "Threefold Grace",
    "offensive",
    "burn",
    "Your first Burn, Freeze, and Holy card each turn costs no Mana.",
    "firstElementalCardsFree",
    "freeze",
  ),
  uniqueAffix(
    "bloodember-pendant",
    "Bloodember Pendant",
    "offensive",
    "burn",
    "Burn and Bleed share their damage bonuses.",
    "sharedBurnBleedBonuses",
    "bleed",
  ),
  uniqueAffix(
    "winters-credit",
    "Winter’s Credit",
    "offensive",
    "freeze",
    "Spend 3 Block per missing Mana to play Freeze cards.",
    "blockPaysFreezeMana",
    "mana",
  ),
  uniqueAffix(
    "serpents-eye",
    "Serpent’s Eye",
    "offensive",
    "poison",
    "Attacks against Poisoned enemies ignore Armor and cannot be Dodged.",
    "poisonedAttacksPierce",
    "archery",
  ),
  uniqueAffix(
    "wildhearts-favor",
    "Wildheart’s Favor",
    "defensive",
    "dodge",
    "Dodging makes your next Nature card free and guarantees its damage Critically Hits.",
    "dodgeReadiesNatureCrit",
    "nature",
  ),
  uniqueAffix(
    "the-golden-crucible",
    "The Golden Crucible",
    "offensive",
    "gold",
    "Without Forge, combat Gold gains grant equal Forge. Forge also increases Holy damage",
    "goldGrantsForgeAndHoly",
    "forge",
  ),
] as const satisfies readonly AffixRowInput[];

export const companionUniqueAffixes = [
  uniqueAffix(
    "companion-forge-power",
    "Bonded",
    "offensive",
    "companion",
    "Companions benefit from Forge",
    "companionBenefitsFromForge",
    "forge",
  ),
] as const satisfies readonly AffixRowInput[];

export const wardUniqueAffixes = [
  uniqueAffix(
    "wardbreaker-purge",
    "Wardbreaking",
    "offensive",
    "stun",
    "Your attacks Purge one enemy buff and deal {value} Holy damage",
    "attackPurgeDealHolyPerEffect",
    "holy",
  ),
  uniqueAffix(
    "dance-of-blades",
    "Bladedance",
    "defensive",
    "dodge",
    "When you Dodge, you have a 25% chance to draw and play a random card",
    "dodgeDrawAndPlay",
    "physical",
  ),
] as const satisfies readonly AffixRowInput[];

export const dodgeUniqueAffixes = [
  uniqueAffix(
    "dodge-crit",
    "Off-Balance",
    "offensive",
    "dodge",
    "Your next attack is guaranteed to Critically Hit when you Dodge",
    "nextAttackCritOnDodge",
  ),
] as const satisfies readonly AffixRowInput[];

export const reactionUniqueAffixes = [
  uniqueAffix(
    "bloodfire",
    "Bloodfire",
    "offensive",
    "burn",
    "Burn has a 20% chance to inflict Bleed, and vice versa. Both gain Leech against enemies already Burning and Bleeding",
    "burnBleedMirrorAndLeech",
    "bleed",
  ),
  uniqueAffix(
    "rimeheart",
    "Rimeheart",
    "offensive",
    "freeze",
    "While you have no Block, Freeze damage grants equal Block. Freezing an enemy while you have no Mana restores Mana equal to half your Block",
    "freezeGrantsBlockAndMana",
    "block",
  ),
  uniqueAffix(
    "blackfletch",
    "Blackfletch",
    "offensive",
    "archery",
    "Against enemies below 30% Health, Archery attacks deal all remaining Bleed and Poison damage and remove both",
    "archeryDetonateBleedPoison",
    "poison",
  ),
  uniqueAffix(
    "twin-casting",
    "Twincasting",
    "offensive",
    "burn",
    "Playing a Burn card draws a Freeze card, and vice versa",
    "elementalTwinCasting",
    "freeze",
  ),
  uniqueAffix(
    "saintfall",
    "Saintfall",
    "defensive",
    "block",
    "When Block is depleted, deal {value} Holy to the attacker and restore {value} Health",
    "saintfallRetribution",
    "holy",
    4,
  ),
  uniqueAffix(
    "golden-verdict",
    "Verdict",
    "offensive",
    "holy",
    "Holy damage builds Stun. The first time you Stun an enemy each combat, gain {value} Gold",
    "holyStunBuildupGold",
    "stun",
  ),
] as const satisfies readonly AffixRowInput[];
