import path from "node:path";
import { fileURLToPath } from "node:url";

import { syncGeneratedModule } from "./lib/generated-module.mjs";
import { isMainModule } from "./lib/is-main-module.mjs";
import { kebabToCamel } from "./lib/kebab-to-camel.mjs";

const currentFile = fileURLToPath(import.meta.url);
const rootDir = path.resolve(path.dirname(currentFile), "..");
const optimizedDir = path.join(rootDir, "src", "assets", "optimized");
const manifestPath = path.join(optimizedDir, ".asset-hashes.json");
const outputFile = path.join(rootDir, "src", "lib", "game-data", "assets.generated.ts");

function buildAssetsContent(manifest) {
  const files = Object.keys(manifest)
    .filter((name) => name.endsWith(".webp"))
    .sort();

  const lines = ["// Generated by scripts/sync-assets.mjs — do not edit manually.", ""];

  for (const file of files) {
    const baseName = file.replace(/\.webp$/, "");
    const exportName = kebabToCamel(baseName);
    lines.push(`export { default as ${exportName} } from "@/assets/optimized/${file}";`);
  }

  lines.push("");
  return { files, content: `${lines.join("\n")}` };
}

export async function syncAssets({ check = false } = {}) {
  const { files, wrote } = await syncGeneratedModule({
    manifestPath,
    outputFile,
    check,
    build: buildAssetsContent,
  });
  console.log(
    check
      ? `Asset exports are current (${files.length} entries)`
      : wrote
        ? `Wrote ${files.length} asset exports to ${path.relative(rootDir, outputFile)}`
        : `Asset exports unchanged (${files.length} entries)`,
  );
}

if (isMainModule(import.meta.url)) {
  syncAssets({ check: process.argv.includes("--check") }).catch((error) => {
    console.error("Failed to sync assets:", error);
    process.exitCode = 1;
  });
}
