import path from "node:path";

import { isMainModule } from "./lib/is-main-module.mjs";
import { kebabToCamel } from "./lib/kebab-to-camel.mjs";
import {
  getAssetFiles,
  getOptimizedManifestPath,
  resolveRootDir,
  runSyncGenerated,
} from "./lib/sync-generated-helpers.mjs";

const rootDir = resolveRootDir(import.meta.url);
const manifestPath = getOptimizedManifestPath(rootDir);
const outputFile = path.join(rootDir, "src", "lib", "game-data", "assets.generated.ts");

function buildAssetsContent(manifest) {
  const files = getAssetFiles(manifest);

  const lines = ["// Generated by scripts/sync-assets.mjs — do not edit manually.", ""];

  for (const file of files) {
    const baseName = file.replace(/\.webp$/, "");
    const exportName = kebabToCamel(baseName);
    lines.push(`export { default as ${exportName} } from "@/assets/optimized/${file}";`);
  }

  lines.push("");
  return { files, content: `${lines.join("\n")}` };
}

export async function syncAssets({ check = false } = {}) {
  await runSyncGenerated({
    manifestPath,
    outputFile,
    rootDir,
    check,
    build: buildAssetsContent,
    onCount: (result) => result.files.length,
    label: "Asset exports",
  });
}

if (isMainModule(import.meta.url)) {
  syncAssets({ check: process.argv.includes("--check") }).catch((error) => {
    console.error("Failed to sync assets:", error);
    process.exitCode = 1;
  });
}
