import { readdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const currentFile = fileURLToPath(import.meta.url);
const rootDir = path.resolve(path.dirname(currentFile), "..");
const optimizedDir = path.join(rootDir, "src", "assets", "optimized");
const outputFile = path.join(rootDir, "src", "lib", "game-data", "assets.generated.ts");

function kebabToCamel(name) {
  return name.replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase());
}

async function main() {
  let entries;
  try {
    entries = await readdir(optimizedDir);
  } catch {
    entries = [];
  }

  const files = entries.filter((name) => name.endsWith(".webp")).sort();
  const lines = ["// Generated by scripts/sync-assets.mjs — do not edit manually.", ""];

  for (const file of files) {
    const baseName = file.replace(/\.webp$/, "");
    const exportName = kebabToCamel(baseName);
    lines.push(`export { default as ${exportName} } from "@/assets/optimized/${file}";`);
  }

  lines.push("");
  await writeFile(outputFile, `${lines.join("\n")}`, "utf8");
  console.log(`Wrote ${files.length} asset exports to ${path.relative(rootDir, outputFile)}`);
}

main().catch((error) => {
  console.error("Failed to sync assets:", error);
  process.exit(1);
});
