// Card library — every playable BattleCard in the game, authored as data.
// Depends on art assets and card type shapes. Each card is an effect pipeline; no logic.
import {
  anvil,
  apple,
  bash,
  blessedAegis,
  block,
  bread,
  cleanse,
  fangs,
  fireball,
  frostbolt,
  haste,
  heal,
  healthPotion,
  impCompanion,
  lizardScoutCompanion,
  manaBerries,
  manaCrystal,
  manaPotion,
  meteor,
  panaceaPotion,
  mixedPotion,
  plateMail,
  poisonDagger,
  slash,
  stab,
  steal,
  wish,
  wolfCompanion,
  placeholderCard,
} from "./assets";
import type { BattleCard } from "./types";

export const cardLibrary: BattleCard[] = [
  { id: "slash", title: "Slash", descriptionLines: ["Deal 6 Physical damage"], art: slash, cost: 1, effects: [{ kind: "damage", damageType: "physical", amount: 6 }] },
  { id: "stab", title: "Stab", descriptionLines: ["Deal 3 Bleed damage"], art: stab, cost: 1, effects: [{ kind: "damage", damageType: "bleed", amount: 3 }] },
  { id: "bash", title: "Bash", descriptionLines: ["Deal 4 Stun damage"], art: bash, cost: 1, effects: [{ kind: "damage", damageType: "stun", amount: 4 }] },
  { id: "block", title: "Block", descriptionLines: ["Gain 5 Block"], art: block, cost: 1, effects: [{ kind: "player-status", status: "block", amount: 5 }] },
  { id: "anvil", title: "Anvil", descriptionLines: ["Gain 1 Forge"], art: anvil, cost: 1, effects: [{ kind: "player-status", status: "forge", amount: 1 }] },
  { id: "plate-mail", title: "Plate Mail", descriptionLines: ["Gain 1 Armor"], art: plateMail, cost: 1, effects: [{ kind: "player-status", status: "armor", amount: 1 }] },
  { id: "apple", title: "Apple", descriptionLines: ["Gain 5 Health", "Consume"], art: apple, cost: 1, consume: true, effects: [{ kind: "heal", amount: 5 }] },
  { id: "bread", title: "Bread", descriptionLines: ["Gain 5 Health", "Consume"], art: bread, cost: 1, consume: true, effects: [{ kind: "heal", amount: 5 }] },
  { id: "meteor", title: "Meteor", descriptionLines: ["Deal 10 Burn damage", "Lose 1 Mana Crystal", "Consume"], art: meteor, cost: 1, consume: true, effects: [{ kind: "damage", damageType: "burn", amount: 10 }, { kind: "lose-max-mana", amount: 1 }] },
  { id: "steal", title: "Steal", descriptionLines: ["Steal 4 Gold"], art: steal, cost: 1, effects: [{ kind: "gain-gold", amount: 4 }] },
  { id: "blessed-aegis", title: "Blessed Aegis", descriptionLines: ["Deal Holy damage equal to your Block"], art: blessedAegis, cost: 1, effects: [{ kind: "damage", damageType: "holy", amount: 0, equalToBlock: true }] },
  { id: "wish", title: "Wish", descriptionLines: ["Wish 1"], art: wish, cost: 1, effects: [{ kind: "wish", amount: 1 }] },
  { id: "cleanse", title: "Cleanse", descriptionLines: ["Remove a harmful status effect"], art: cleanse, cost: 1, effects: [{ kind: "remove-harmful-status", amount: 1 }] },
  { id: "heal", title: "Heal", descriptionLines: ["Restore 5 Health"], art: heal, cost: 1, effects: [{ kind: "heal", amount: 5 }] },
  { id: "haste", title: "Haste", descriptionLines: ["Take an extra turn after this one", "Consume"], art: haste, cost: 1, consume: true, effects: [{ kind: "player-status", status: "haste", amount: 1 }] },
  { id: "poison-dagger", title: "Poison Dagger", descriptionLines: ["Deal 2 Poison damage"], art: poisonDagger, cost: 1, effects: [{ kind: "damage", damageType: "poison", amount: 2 }] },
  { id: "fireball", title: "Fireball", descriptionLines: ["Deal 3 Burn damage"], art: fireball, cost: 1, effects: [{ kind: "damage", damageType: "burn", amount: 3 }] },
  { id: "fangs", title: "Fangs", descriptionLines: ["Deal 2 Bleed damage", "Leech"], art: fangs, cost: 1, effects: [{ kind: "damage", damageType: "bleed", amount: 2, lifesteal: true }] },
  { id: "frostbolt", title: "Frostbolt", descriptionLines: ["Deal 3 Freeze damage"], art: frostbolt, cost: 1, effects: [{ kind: "damage", damageType: "freeze", amount: 3 }] },
  { id: "health-potion", title: "Health Potion", descriptionLines: ["Restore 8 Health", "Consume"], art: healthPotion, cost: 1, consume: true, effects: [{ kind: "heal", amount: 8 }] },
  { id: "mana-berries", title: "Mana Berries", descriptionLines: ["Restore 2 Mana", "Consume"], art: manaBerries, cost: 1, consume: true, effects: [{ kind: "restore-mana", amount: 2 }] },
  { id: "mana-crystals", title: "Mana Crystals", descriptionLines: ["Gain 1 Maximum Mana", "Consume"], art: manaCrystal, cost: 1, consume: true, effects: [{ kind: "gain-max-mana", amount: 1 }] },
  { id: "mana-potion", title: "Mana Potion", descriptionLines: ["Restore 2 Mana", "Consume"], art: manaPotion, cost: 1, consume: true, effects: [{ kind: "restore-mana", amount: 2 }] },
  { id: "panacea-potion", title: "Panacea Potion", descriptionLines: ["Remove 1 harmful status effect", "Consume"], art: panaceaPotion, cost: 1, consume: true, effects: [{ kind: "remove-harmful-status", amount: 1 }] },
  { id: "stoneskin-potion", title: "Stoneskin Potion", descriptionLines: ["Gain 2 Armor", "Consume"], art: placeholderCard, cost: 1, consume: true, effects: [{ kind: "player-status", status: "armor", amount: 2 }] },
  { id: "acid-potion", title: "Acid Potion", descriptionLines: ["Deal 3 Poison", "Consume"], art: placeholderCard, cost: 1, consume: true, effects: [{ kind: "damage", damageType: "poison", amount: 3 }] },
  { id: "luck-potion", title: "Luck Potion", descriptionLines: ["Gain 7 Gold", "Consume"], art: placeholderCard, cost: 1, consume: true, effects: [{ kind: "gain-gold", amount: 7 }] },
  { id: "wishing-potion", title: "Wishing Potion", descriptionLines: ["Wish 2", "Consume"], art: placeholderCard, cost: 1, consume: true, effects: [{ kind: "wish", amount: 2 }] },
  { id: "mixed-potion", title: "Mixed Potion", descriptionLines: ["Mixed at an Alchemist's Shop"], art: mixedPotion, cost: 1, consume: true, effects: [] },
  { id: "wolf-companion", title: "Wolf Companion", descriptionLines: ["Summon a Wolf Companion", "Consume"], art: wolfCompanion, cost: 1, consume: true, effects: [{ kind: "summon-companion", companionId: "wolf" }] },
  { id: "lizard-scout-companion", title: "Lizard Scout Companion", descriptionLines: ["Summon a Lizard Scout Companion", "Consume"], art: lizardScoutCompanion, cost: 1, consume: true, effects: [{ kind: "summon-companion", companionId: "lizard-scout" }] },
  { id: "imp-companion", title: "Imp Companion", descriptionLines: ["Summon an Imp Companion", "Consume"], art: impCompanion, cost: 1, consume: true, effects: [{ kind: "summon-companion", companionId: "imp" }] },
  { id: "shield-bash", title: "Shield Bash", descriptionLines: ["Deal 2 Stun damage", "Gain 2 Block"], art: placeholderCard, cost: 1, effects: [{ kind: "damage", damageType: "stun", amount: 2 }, { kind: "player-status", status: "block", amount: 2 }] },
  { id: "burning-blade", title: "Burning Blade", descriptionLines: ["Deal 2 Physical damage", "Deal 2 Burn damage"], art: placeholderCard, cost: 1, effects: [{ kind: "damage", damageType: "physical", amount: 2 }, { kind: "damage", damageType: "burn", amount: 2 }] },
  // remove-harmful-status must come before self-damage so the burn cost is not instantly cleansed
  { id: "cauterize", title: "Cauterize", descriptionLines: ["Remove 1 harmful status effect", "Receive 1 Burn damage"], art: placeholderCard, cost: 1, effects: [{ kind: "remove-harmful-status", amount: 1 }, { kind: "self-damage", damageType: "burn", amount: 1 }] },
  { id: "blackjack", title: "Blackjack", descriptionLines: ["Deal 2 Stun damage", "Steal 2 Gold"], art: placeholderCard, cost: 1, effects: [{ kind: "damage", damageType: "stun", amount: 2 }, { kind: "gain-gold", amount: 2 }] },
  { id: "sunburst", title: "Sunburst", descriptionLines: ["Restore 2 Health", "Deal 2 Burn damage"], art: placeholderCard, cost: 1, effects: [{ kind: "heal", amount: 2 }, { kind: "damage", damageType: "burn", amount: 2 }] },
  { id: "holy-radiance", title: "Holy Radiance", descriptionLines: ["Restore 2 Health", "Deal 2 Holy damage"], art: placeholderCard, cost: 1, effects: [{ kind: "heal", amount: 2 }, { kind: "damage", damageType: "holy", amount: 2 }] },
  { id: "venom-fangs", title: "Venom Fangs", descriptionLines: ["Deal 2 Poison damage", "Leech"], art: placeholderCard, cost: 1, effects: [{ kind: "damage", damageType: "poison", amount: 2, lifesteal: true }] },
  { id: "bloodthorn", title: "Bloodthorn", descriptionLines: ["Deal 4 Nature damage", "Leech"], art: placeholderCard, cost: 1, effects: [{ kind: "damage", damageType: "nature", amount: 4, lifesteal: true }] },
  { id: "cinderbloom", title: "Cinderbloom", descriptionLines: ["Deal 2 Nature damage", "Deal 2 Burn damage"], art: placeholderCard, cost: 1, effects: [{ kind: "damage", damageType: "nature", amount: 2 }, { kind: "damage", damageType: "burn", amount: 2 }] },
  { id: "grasping-vines", title: "Grasping Vines", descriptionLines: ["Deal 2 Nature damage", "Deal 2 Stun damage"], art: placeholderCard, cost: 1, effects: [{ kind: "damage", damageType: "nature", amount: 2 }, { kind: "damage", damageType: "stun", amount: 2 }] },
  { id: "briar-shield", title: "Briar Shield", descriptionLines: ["Gain 3 Block", "Deal Nature damage equal to your Block"], art: placeholderCard, cost: 1, effects: [{ kind: "player-status", status: "block", amount: 3 }, { kind: "damage", damageType: "nature", amount: 0, equalToBlock: true }] },
  { id: "thorn-mail", title: "Thorn Mail", descriptionLines: ["Gain 2 Armor", "Deal Nature damage equal to your Armor"], art: placeholderCard, cost: 1, effects: [{ kind: "player-status", status: "armor", amount: 2 }, { kind: "damage", damageType: "nature", amount: 0, equalToArmor: true }] },
  { id: "pack-tactics", title: "Pack Tactics", descriptionLines: ["Increase Companion damage by 1", "Deal 2 Nature damage"], art: placeholderCard, cost: 1, effects: [{ kind: "buff-companion", amount: 1 }, { kind: "damage", damageType: "nature", amount: 2 }] },
];

