// Static card definitions. Cards are data and live in a single flat library by design.
// Pool/persistence helpers live in cards/card-pools.ts and cards/hydrate-card.ts.
import type { BattleCard } from "./types";
import {
  acidPotion,
  antivenomPotion,
  anvil,
  apple,
  bash,
  bearCompanion,
  blackjack,
  blessedAegis,
  block,
  bloodOffering,
  bloodthorn,
  bountyShot,
  bread,
  briarShield,
  burningBlade,
  cauterize,
  cinderbloom,
  cleanse,
  coldSnap,
  concussiveShot,
  crystalBulwark,
  darkPact,
  exorcism,
  fangs,
  faustianBargain,
  fireArrow,
  fireball,
  frostbolt,
  frostWhelpCompanion,
  gamblersShot,
  glacialWard,
  goldenPlate,
  goldenRetrieverCompanion,
  graspingVines,
  haste,
  heal,
  healthPotion,
  hemorrhage,
  holyRadiance,
  iceShot,
  impCompanion,
  judgment,
  kindling,
  libraryOwlCompanion,
  lightningArrow,
  lightningBolt,
  lizardScoutCompanion,
  luckPotion,
  manaBerries,
  manaCrystal,
  manaMothCompanion,
  manaPotion,
  manaShield,
  meteor,
  mixedPotion,
  moltenBulwark,
  packTactics,
  panaceaPotion,
  pantherCompanion,
  phoenixCompanion,
  phoenixFeather,
  pixieCompanion,
  plateMail,
  poisonDagger,
  prayer,
  raiseSkeletonCompanion,
  roulette,
  sanctifiedPlate,
  sapArrow,
  serratedArrowhead,
  serratedEdge,
  shieldBash,
  shieldScarabCompanion,
  slash,
  smellingSalts,
  smite,
  spikedShield,
  stab,
  steal,
  stoneskinPotion,
  sunburst,
  sunderArmor,
  thornMail,
  tithe,
  venomArrow,
  venomFangs,
  willOWispCompanion,
  wish,
  wishingPotion,
  wishingWell,
  wolfCompanion,
} from "./assets";
import {
  archeryDamageCard,
  cleansePlayerStatusCard,
  consumableCard,
  damageCard,
  damageThenMultiplyEnemyStatusCard,
  dualDamageCard,
  healThenDamageCard,
  loseHealthBenefitCard,
  playerStatThenScaledDamageCard,
  playerStatusCard,
  singleEffectCard,
  summonCompanionCard,
} from "./cards/card-builders";

export const cardLibrary: BattleCard[] = [
  damageCard({ id: "slash", art: slash, damageType: "physical", amount: 6 }),
  damageCard({ id: "stab", art: stab, damageType: "bleed", amount: 2 }),
  singleEffectCard({
    id: "cleanse",
    art: cleanse,
    effect: { kind: "remove-harmful-status", amount: 1 },
    descriptionLine: "Cleanse 1 harmful status effect",
  }),
  singleEffectCard({ id: "heal", art: heal, effect: { kind: "heal", amount: 4 } }),
  {
    id: "haste",
    title: "Haste",
    descriptionLines: ["Take an extra turn after this one", "Consume"],
    art: haste,
    cost: 1,
    consume: true,
    effects: [{ kind: "player-status", status: "haste", amount: 1 }],
  },
  damageCard({ id: "poison-dagger", art: poisonDagger, damageType: "poison", amount: 2 }),
  damageCard({ id: "fireball", art: fireball, damageType: "burn", amount: 3 }),
  damageCard({ id: "fangs", art: fangs, damageType: "physical", amount: 3, lifesteal: true }),
  damageCard({ id: "frostbolt", art: frostbolt, damageType: "freeze", amount: 3 }),
  consumableCard({
    id: "health-potion",
    art: healthPotion,
    effect: { kind: "heal", amount: 8 },
  }),
  consumableCard({
    id: "mana-berries",
    art: manaBerries,
    effect: { kind: "restore-mana", amount: 2 },
  }),
  consumableCard({
    id: "mana-crystals",
    art: manaCrystal,
    effect: { kind: "gain-max-mana", amount: 1 },
  }),
  consumableCard({
    id: "mana-potion",
    art: manaPotion,
    effect: { kind: "restore-mana", amount: 2 },
  }),
  consumableCard({
    id: "panacea-potion",
    art: panaceaPotion,
    effect: { kind: "remove-harmful-status", amount: 1 },
  }),
  consumableCard({
    id: "stoneskin-potion",
    art: stoneskinPotion,
    effect: { kind: "player-status", status: "armor", amount: 2 },
  }),
  consumableCard({
    id: "acid-potion",
    art: acidPotion,
    effect: { kind: "damage", damageType: "poison", amount: 3 },
  }),
  playerStatusCard({ id: "anvil", art: anvil, status: "forge", amount: 1 }),
  consumableCard({ id: "apple", art: apple, effect: { kind: "heal", amount: 5 } }),
  damageCard({ id: "bash", art: bash, damageType: "stun", amount: 3 }),
  playerStatusCard({ id: "block", art: block, status: "block", amount: 5 }),
  consumableCard({ id: "bread", art: bread, effect: { kind: "heal", amount: 5 } }),
  playerStatThenScaledDamageCard({
    id: "blessed-aegis",
    art: blessedAegis,
    damageType: "holy",
    scaleFrom: "block",
  }),
  consumableCard({
    id: "luck-potion",
    art: luckPotion,
    effect: { kind: "gain-gold", amount: 7 },
  }),
  singleEffectCard({ id: "wish", art: wish, effect: { kind: "wish", amount: 1 } }),
  consumableCard({
    id: "wishing-potion",
    art: wishingPotion,
    effect: { kind: "wish", amount: 1 },
  }),
  {
    id: "meteor",
    title: "Meteor",
    descriptionLines: ["Deal 7 Burn damage", "Lose 1 Mana Crystal", "Consume"],
    art: meteor,
    cost: 1,
    consume: true,
    effects: [
      { kind: "damage", damageType: "burn", amount: 7 },
      { kind: "lose-max-mana", amount: 1 },
    ],
  },
  {
    id: "mixed-potion",
    title: "Mixed Potion",
    descriptionLines: ["Mixed at an Alchemist's Shop", "Consume"],
    art: mixedPotion,
    cost: 1,
    consume: true,
    effects: [],
    excludeFromOfferPool: true,
  },
  summonCompanionCard({ id: "wolf-companion", art: wolfCompanion, companionId: "wolf" }),
  summonCompanionCard({
    id: "lizard-scout-companion",
    art: lizardScoutCompanion,
    companionId: "lizard-scout",
  }),
  summonCompanionCard({ id: "imp-companion", art: impCompanion, companionId: "imp" }),
  archeryDamageCard({
    id: "fire-arrow",
    art: fireArrow,
    damageType: "burn",
    amount: 2,
  }),
  archeryDamageCard({
    id: "ice-shot",
    art: iceShot,
    damageType: "freeze",
    amount: 2,
  }),
  archeryDamageCard({
    id: "venom-arrow",
    art: venomArrow,
    damageType: "poison",
    amount: 2,
  }),
  archeryDamageCard({
    id: "serrated-arrowhead",
    art: serratedArrowhead,
    damageType: "bleed",
    amount: 2,
  }),
  archeryDamageCard({
    id: "concussive-shot",
    art: concussiveShot,
    damageType: "stun",
    amount: 3,
  }),
  archeryDamageCard({
    id: "lightning-arrow",
    art: lightningArrow,
    damageType: "nature",
    amount: 2,
  }),
  {
    id: "tithe",
    title: "Tithe",
    descriptionLines: ["Deal Holy damage equal to 10% of your Gold"],
    art: tithe,
    cost: 1,
    effects: [{ kind: "damage", damageType: "holy", amount: 0, equalToGoldPercent: 10 }],
  },
  {
    id: "exorcism",
    title: "Exorcism",
    descriptionLines: ["Cleanse all Burn on yourself", "Deal Holy damage equal to Burn removed"],
    art: exorcism,
    cost: 1,
    effects: [{ kind: "cleanse-player-status-to-damage", status: "burn", damageType: "holy", removeAll: true }],
  },
  damageThenMultiplyEnemyStatusCard({
    id: "kindling",
    art: kindling,
    damageType: "burn",
    damageAmount: 1,
    status: "burn",
    factor: 2,
    multiplyLine: "Double enemy Burn stacks",
    consume: true,
  }),
  {
    id: "roulette",
    title: "Roulette",
    descriptionLines: ["Deal 3 Random damage or Gain 3 Gold"],
    art: roulette,
    cost: 1,
    effects: [
      {
        kind: "chance",
        probability: 0.5,
        successEffects: [{ kind: "random-damage", minAmount: 3, maxAmount: 3 }],
        failureEffects: [{ kind: "gain-gold", amount: 3 }],
      },
    ],
  },
  damageCard({ id: "lightning-bolt", art: lightningBolt, damageType: "nature", amount: 4 }),
  {
    id: "wishing-well",
    title: "Wishing Well",
    descriptionLines: ["Wish 1", "Gain 1 Gold"],
    art: wishingWell,
    cost: 1,
    effects: [
      { kind: "wish", amount: 1 },
      { kind: "gain-gold", amount: 1 },
    ],
  },
  dualDamageCard({
    id: "hemorrhage",
    art: hemorrhage,
    hits: [
      { damageType: "physical", amount: 2 },
      { damageType: "bleed", amount: 1 },
    ],
  }),
  {
    id: "bounty-shot",
    title: "Bounty Shot",
    descriptionLines: ["Deal 2 Physical damage", "Gain 2 Gold", "Archery"],
    art: bountyShot,
    cost: 1,
    tags: ["archery"],
    effects: [
      { kind: "damage", damageType: "physical", amount: 2 },
      { kind: "gain-gold", amount: 2 },
    ],
  },
  {
    id: "sap-arrow",
    title: "Sap Arrow",
    descriptionLines: ["Deal 2 Nature damage", "Leech", "Archery"],
    art: sapArrow,
    cost: 1,
    tags: ["archery"],
    effects: [{ kind: "damage", damageType: "nature", amount: 2, lifesteal: true }],
  },
  {
    id: "gamblers-shot",
    title: "Gambler's Shot",
    descriptionLines: ["Deal 1–6 Random damage", "Archery"],
    art: gamblersShot,
    cost: 1,
    tags: ["archery"],
    effects: [{ kind: "random-damage", minAmount: 1, maxAmount: 6 }],
  },
  {
    id: "phoenix-feather",
    title: "Phoenix Feather",
    descriptionLines: ["Lose 1 Mana Crystal", "If you would die, instead restore 30% Health"],
    art: phoenixFeather,
    cost: 1,
    effects: [
      { kind: "lose-max-mana", amount: 1 },
      { kind: "player-status", status: "phoenixFeather", amount: 1 },
    ],
  },
  summonCompanionCard({
    id: "frost-whelp-companion",
    art: frostWhelpCompanion,
    companionId: "frost-whelp",
  }),
  summonCompanionCard({ id: "bear-companion", art: bearCompanion, companionId: "bear" }),
  summonCompanionCard({
    id: "panther-companion",
    art: pantherCompanion,
    companionId: "panther",
  }),
  summonCompanionCard({
    id: "phoenix-companion",
    art: phoenixCompanion,
    companionId: "phoenix",
  }),
  playerStatusCard({ id: "plate-mail", art: plateMail, status: "armor", amount: 2 }),
  playerStatThenScaledDamageCard({
    id: "sanctified-plate",
    art: sanctifiedPlate,
    damageType: "holy",
    scaleFrom: "armor",
    playerStat: { status: "armor", amount: 1 },
  }),
  {
    id: "shield-bash",
    title: "Shield Bash",
    descriptionLines: ["Deal 2 Stun damage", "Gain 2 Block"],
    art: shieldBash,
    cost: 1,
    effects: [
      { kind: "damage", damageType: "stun", amount: 2 },
      { kind: "player-status", status: "block", amount: 2 },
    ],
  },
  {
    id: "steal",
    title: "Steal",
    descriptionLines: ["Steal 4 Gold"],
    art: steal,
    cost: 1,
    effects: [{ kind: "gain-gold", amount: 4 }],
  },
  dualDamageCard({
    id: "burning-blade",
    art: burningBlade,
    hits: [
      { damageType: "physical", amount: 2 },
      { damageType: "burn", amount: 2 },
    ],
  }),
  // Effect order invariant: remove-harmful-status before self-damage (see card-effect-ordering.test.ts)
  {
    id: "cauterize",
    title: "Cauterize",
    descriptionLines: ["Remove 2 harmful status effects", "Receive 1 Burn damage"],
    art: cauterize,
    cost: 1,
    effects: [
      { kind: "remove-harmful-status", amount: 2 },
      { kind: "self-damage", damageType: "burn", amount: 1 },
    ],
  },
  {
    id: "blackjack",
    title: "Blackjack",
    descriptionLines: ["Deal 2 Stun damage", "Steal 2 Gold"],
    art: blackjack,
    cost: 1,
    effects: [
      { kind: "damage", damageType: "stun", amount: 2 },
      { kind: "gain-gold", amount: 2 },
    ],
  },
  healThenDamageCard({
    id: "sunburst",
    art: sunburst,
    heal: 2,
    damageType: "burn",
    damage: 2,
  }),
  healThenDamageCard({
    id: "holy-radiance",
    art: holyRadiance,
    heal: 2,
    damageType: "holy",
    damage: 2,
  }),
  damageCard({
    id: "venom-fangs",
    art: venomFangs,
    damageType: "poison",
    amount: 2,
    lifesteal: true,
  }),
  damageCard({
    id: "bloodthorn",
    art: bloodthorn,
    damageType: "nature",
    amount: 4,
    lifesteal: true,
  }),
  dualDamageCard({
    id: "cinderbloom",
    art: cinderbloom,
    hits: [
      { damageType: "nature", amount: 2 },
      { damageType: "burn", amount: 2 },
    ],
  }),
  dualDamageCard({
    id: "grasping-vines",
    art: graspingVines,
    hits: [
      { damageType: "nature", amount: 2 },
      { damageType: "stun", amount: 2 },
    ],
  }),
  playerStatThenScaledDamageCard({
    id: "briar-shield",
    art: briarShield,
    damageType: "nature",
    scaleFrom: "block",
    playerStat: { status: "block", amount: 3 },
  }),
  playerStatThenScaledDamageCard({
    id: "thorn-mail",
    art: thornMail,
    damageType: "nature",
    scaleFrom: "armor",
    playerStat: { status: "armor", amount: 2 },
  }),
  {
    id: "pack-tactics",
    title: "Pack Tactics",
    descriptionLines: ["Increase Companion damage by 1", "Deal 3 Nature damage"],
    art: packTactics,
    cost: 1,
    effects: [
      { kind: "buff-companion", amount: 1 },
      { kind: "damage", damageType: "nature", amount: 3 },
    ],
  },
  dualDamageCard({
    id: "serrated-edge",
    art: serratedEdge,
    hits: [
      { damageType: "bleed", amount: 1 },
      { damageType: "physical", amount: 3 },
    ],
  }),
  dualDamageCard({
    id: "smite",
    art: smite,
    hits: [
      { damageType: "holy", amount: 2 },
      { damageType: "burn", amount: 2 },
    ],
  }),
  cleansePlayerStatusCard({
    id: "antivenom-potion",
    art: antivenomPotion,
    status: "poison",
    cleanseLine: "Cleanse all Poison",
    consume: true,
  }),
  damageThenMultiplyEnemyStatusCard({
    id: "cold-snap",
    art: coldSnap,
    damageType: "freeze",
    damageAmount: 1,
    status: "freeze",
    factor: 2,
    multiplyLine: "Double enemy's Freeze build-up",
  }),
  loseHealthBenefitCard({ id: "blood-offering", art: bloodOffering, healthLoss: 1, draw: 2 }),
  {
    id: "sunder-armor",
    title: "Sunder Armor",
    descriptionLines: ["Deal 4 Physical damage", "Strip 2 enemy Armor"],
    art: sunderArmor,
    cost: 1,
    effects: [
      { kind: "damage", damageType: "physical", amount: 4 },
      { kind: "remove-enemy-armor", amount: 2 },
    ],
  },
  {
    id: "mana-shield",
    title: "Mana Shield",
    descriptionLines: ["Gain 1 Block per Mana Crystal"],
    art: manaShield,
    cost: 1,
    effects: [{ kind: "player-status", status: "block", amount: 0, perManaCrystal: 1 }],
  },
  {
    id: "prayer",
    title: "Prayer",
    descriptionLines: ["Wish 1", "Restore 3 Health"],
    art: prayer,
    cost: 1,
    effects: [
      { kind: "wish", amount: 1 },
      { kind: "heal", amount: 3 },
    ],
  },
  loseHealthBenefitCard({
    id: "faustian-bargain",
    art: faustianBargain,
    healthLoss: 2,
    wish: 2,
    consume: true,
  }),
  dualDamageCard({
    id: "judgment",
    art: judgment,
    hits: [
      { damageType: "holy", amount: 3 },
      { damageType: "stun", amount: 1 },
    ],
  }),
  cleansePlayerStatusCard({
    id: "smelling-salts",
    art: smellingSalts,
    status: "stun",
    cleanseLine: "Cleanse Stun build-up",
  }),
  loseHealthBenefitCard({
    id: "dark-pact",
    art: darkPact,
    healthLoss: 1,
    wish: 1,
    draw: 1,
  }),
  summonCompanionCard({
    id: "skeleton-companion",
    title: "Raise Skeleton",
    art: raiseSkeletonCompanion,
    companionId: "skeleton",
  }),
  summonCompanionCard({ id: "pixie-companion", art: pixieCompanion, companionId: "pixie" }),
  summonCompanionCard({
    id: "mana-moth-companion",
    art: manaMothCompanion,
    companionId: "mana-moth",
  }),
  summonCompanionCard({
    id: "will-o-wisp-companion",
    title: "Will-o'-Wisp",
    art: willOWispCompanion,
    companionId: "will-o-wisp",
  }),
  summonCompanionCard({
    id: "golden-retriever-companion",
    art: goldenRetrieverCompanion,
    companionId: "golden-retriever",
  }),
  summonCompanionCard({
    id: "shield-scarab-companion",
    art: shieldScarabCompanion,
    companionId: "shield-scarab",
  }),
  summonCompanionCard({
    id: "library-owl-companion",
    art: libraryOwlCompanion,
    companionId: "library-owl",
  }),
  {
    id: "molten-bulwark",
    title: "Molten Bulwark",
    descriptionLines: ["Gain 3 Block", "Deal 1 Burn damage"],
    art: moltenBulwark,
    cost: 1,
    effects: [
      { kind: "player-status", status: "block", amount: 3 },
      { kind: "damage", damageType: "burn", amount: 1 },
    ],
  },
  {
    id: "glacial-ward",
    title: "Glacial Ward",
    descriptionLines: ["Gain 3 Block", "Deal 1 Freeze damage"],
    art: glacialWard,
    cost: 1,
    effects: [
      { kind: "player-status", status: "block", amount: 3 },
      { kind: "damage", damageType: "freeze", amount: 1 },
    ],
  },
  {
    id: "spiked-shield",
    title: "Spiked Shield",
    descriptionLines: ["Gain 2 Armor", "Deal 1 Bleed damage"],
    art: spikedShield,
    cost: 1,
    effects: [
      { kind: "player-status", status: "armor", amount: 2 },
      { kind: "damage", damageType: "bleed", amount: 1 },
    ],
  },
  {
    id: "golden-plate",
    title: "Golden Plate",
    descriptionLines: ["Gain 1 Armor", "Gain 2 Gold"],
    art: goldenPlate,
    cost: 1,
    effects: [
      { kind: "player-status", status: "armor", amount: 1 },
      { kind: "gain-gold", amount: 2 },
    ],
  },
  {
    id: "crystal-bulwark",
    title: "Crystal Bulwark",
    descriptionLines: ["Gain 1 Block per Mana Crystal"],
    art: crystalBulwark,
    cost: 1,
    effects: [{ kind: "player-status", status: "block", amount: 0, perManaCrystal: 1 }],
  },
];

export { expectedCompanionTurnLine, formatCompanionTurnLineBase } from "./cards/companion-turn-description";
