import { apple, boneCharm, brassCenser, cleanse, frozenHeart, goblin, imp, ironwoodBuckler, lizardScout, manaCrystal, meteorite, mimic, mixedPotion, mudElemental, necromancer, obsidianHammer, placeholderEnemy, placeholderTrinket, plagueDoctor, poisonDagger, runicQuill, skeleton, slash, stab, steal, tatteredPages, wish } from "./assets";
import type { BestiaryEntry, TrinketEntry } from "./types";

export const enemyBestiary: BestiaryEntry[] = [
  {
    id: "act-i-boss",
    title: "Warden of the Ashen Gate",
    subtitle: "Act I Boss",
    descriptionLines: ["Trait — Ashen Aura: Receives half Burn damage. Attacks apply Burn.", "Attacks with sweeping physical strikes."],
    art: placeholderEnemy,
    enemyType: "boss",
    traits: [{ id: "ashen-aura", title: "Ashen Aura", description: "Receives half Burn damage." }],
    attackEffects: [
      { kind: "damage", damageType: "physical", amount: 3 },
      { kind: "player-status", status: "burn", amount: 2 },
    ],
  },
  {
    id: "act-ii-boss",
    title: "The Hollow Knight",
    subtitle: "Act II Boss",
    descriptionLines: ["Trait — Cursed Armor: Starts with Armor each turn. Immune to Stun.", "Attacks with a powerful bleed-inflicting strike."],
    art: placeholderEnemy,
    enemyType: "boss",
    traits: [{ id: "cursed-armor", title: "Cursed Armor", description: "Starts with Armor each turn. Immune to Stun." }],
    attackEffects: [
      { kind: "damage", damageType: "physical", amount: 4 },
      { kind: "player-status", status: "bleed", amount: 3 },
    ],
  },
  {
    id: "act-iii-boss",
    title: "The Primordial Wyrm",
    subtitle: "Act III Boss",
    descriptionLines: ["Trait — Elemental Scales: Resistant to all elements. Takes double Physical damage.", "Attacks with a devastating multi-element strike."],
    art: placeholderEnemy,
    enemyType: "boss",
    traits: [{ id: "elemental-scales", title: "Elemental Scales", description: "Resistant to all elements. Takes double Physical damage." }],
    attackEffects: [
      { kind: "damage", damageType: "physical", amount: 5 },
      { kind: "player-status", status: "poison", amount: 2 },
      { kind: "player-status", status: "freeze", amount: 2 },
    ],
  },
  {
    id: "skeleton",
    title: "Skeleton",
    subtitle: "Normal",
    descriptionLines: ["Trait — Brittle Bones: Receives double Holy and Stun damage.", "Attacks for physical damage each turn."],
    art: skeleton,
    enemyType: "normal",
    traits: [{ id: "brittle-bones", title: "Brittle Bones", description: "Receives double Holy and Stun damage." }],
    attackEffects: [],
  },
  {
    id: "goblin",
    title: "Goblin",
    subtitle: "Normal",
    descriptionLines: ["Trait — Fear the Light: Receives double Burn and Holy damage.", "Attacks for physical damage each turn."],
    art: goblin,
    enemyType: "normal",
    traits: [{ id: "fear-the-light", title: "Fear the Light", description: "Receives double Burn and Holy damage." }],
    attackEffects: [],
  },
  {
    id: "imp",
    title: "Imp",
    subtitle: "Normal",
    descriptionLines: ["Attack — Fiery Claws: Deal 2 Burn and 1 Physical.", "Trait — Burn Resistance: Receives half Burn damage."],
    art: imp,
    enemyType: "normal",
    traits: [{ id: "burn-resistance", title: "Burn Resistance", description: "Receives half Burn damage." }],
    attackEffects: [
      { kind: "damage", damageType: "physical", amount: 1 },
      { kind: "player-status", status: "burn", amount: 2 },
    ],
  },
  {
    id: "lizard-scout",
    title: "Lizard Scout",
    subtitle: "Normal",
    descriptionLines: ["Attack — Poison Dart: Deal 1 Poison and 1 Physical.", "Trait — Poison Resistance: Receives half Poison damage."],
    art: lizardScout,
    enemyType: "normal",
    traits: [{ id: "poison-resistance", title: "Poison Resistance", description: "Receives half Poison damage." }],
    attackEffects: [
      { kind: "damage", damageType: "physical", amount: 1 },
      { kind: "player-status", status: "poison", amount: 1 },
    ],
  },
  {
    id: "mimic",
    title: "Mimic",
    subtitle: "Elite",
    descriptionLines: ["Trait — Gold Trove: Gain 1 Gold when damaging a Mimic.", "Attacks for physical damage each turn."],
    art: mimic,
    enemyType: "elite",
    traits: [{ id: "gold-trove", title: "Gold Trove", description: "Gain 1 Gold when damaging a Mimic." }],
    attackEffects: [],
  },
  {
    id: "mud-elemental",
    title: "Mud Elemental",
    subtitle: "Elite",
    descriptionLines: ["Attack — Mudslide: Deals 2 Stun and 2 Poison.", "Trait — Regeneration: Gains 2 Health at the end of each of its turns."],
    art: mudElemental,
    enemyType: "elite",
    traits: [{ id: "regeneration", title: "Regeneration", description: "Gains 2 Health at the end of each of its turns." }],
    attackEffects: [
      { kind: "player-status", status: "stun", amount: 2 },
      { kind: "player-status", status: "poison", amount: 2 },
    ],
  },
  {
    id: "necromancer",
    title: "Necromancer",
    subtitle: "Elite",
    descriptionLines: ["Attack — Life Drain: Deal 2 Leech and 2 Bleed.", "Trait — Holy Vulnerability: Receives double Holy damage."],
    art: necromancer,
    enemyType: "elite",
    traits: [{ id: "holy-vulnerability", title: "Holy Vulnerability", description: "Receives double Holy damage." }],
    attackEffects: [
      { kind: "damage", damageType: "physical", amount: 2, lifesteal: true },
      { kind: "player-status", status: "bleed", amount: 2 },
    ],
  },
  {
    id: "plague-doctor",
    title: "Plague Doctor",
    subtitle: "Elite",
    descriptionLines: ["Attack — Poison Attack: Deal 2 Poison.", "Trait — Poison Resistance: Receives half Poison damage."],
    art: plagueDoctor,
    enemyType: "elite",
    traits: [{ id: "poison-resistance", title: "Poison Resistance", description: "Receives half Poison damage." }],
    attackEffects: [
      { kind: "player-status", status: "poison", amount: 2 },
    ],
  },
];

export const trinketLibrary: TrinketEntry[] = [
  {
    id: "brass-censer",
    title: "Brass Censer",
    descriptionLines: ["Your first Holy attack each battle deals 2 extra damage."],
    art: brassCenser,
  },
  {
    id: "tattered-pages",
    title: "Tattered Pages",
    descriptionLines: ["Draw 1 additional card at the start of each battle."],
    art: tatteredPages,
  },
  {
    id: "meteorite",
    title: "Meteorite",
    descriptionLines: ["The first Burn you apply each battle is doubled."],
    art: meteorite,
  },
  {
    id: "bone-charm",
    title: "Bone Charm",
    descriptionLines: ["When an enemy dies, heal 3 HP."],
    art: boneCharm,
  },
  {
    id: "obsidian-hammer",
    title: "Obsidian Hammer",
    descriptionLines: ["When you have 4 or more Forge, your Physical attacks also Stun for 1."],
    art: obsidianHammer,
  },
  {
    id: "frozen-heart",
    title: "Frozen Heart",
    descriptionLines: ["Enemies that miss a turn to Freeze or Stun take 3 damage."],
    art: frozenHeart,
  },
  {
    id: "ironwood-buckler",
    title: "Ironwood Buckler",
    descriptionLines: ["At the end of your turn, if you have 6 or more Block, gain 1 Armor."],
    art: ironwoodBuckler,
  },
  {
    id: "runic-quill",
    title: "Runic Quill",
    descriptionLines: ["When you consume a card, draw 1 card."],
    art: runicQuill,
  },
  {
    id: "sin-eaters-lantern",
    title: "Sin-Eater's Lantern",
    descriptionLines: ["When you remove an ailment from yourself, gain 1 Gold."],
    art: placeholderTrinket,
  },
  {
    id: "vanguards-crest",
    title: "Vanguard's Crest",
    descriptionLines: ["When your Block fully absorbs an attack, gain 1 Forge."],
    art: placeholderTrinket,
  },
  {
    id: "parasitic-bloom",
    title: "Parasitic Bloom",
    descriptionLines: ["When Poison ticks on an enemy, heal 1 HP."],
    art: placeholderTrinket,
  },
  {
    id: "cutpurse-knife",
    title: "Cutpurse Knife",
    descriptionLines: ["When you apply Bleed to an enemy, gain 1 Gold."],
    art: placeholderTrinket,
  },
  {
    id: "wishing-well-coin",
    title: "Wishing Well Coin",
    descriptionLines: ["When you Wish, also gain 3 Gold."],
    art: placeholderTrinket,
  },
  {
    id: "merchants-favor",
    title: "Merchant's Favor",
    descriptionLines: ["Your first purchase at each shop costs 7 less Gold."],
    art: placeholderTrinket,
  },
  {
    id: "plague-doctors-mask",
    title: "Plague Doctor's Mask",
    descriptionLines: ["You are immune to the first ailment you would receive each battle."],
    art: placeholderTrinket,
  },
  {
    id: "mortar-and-pestle",
    title: "Mortar and Pestle",
    descriptionLines: ["The first Potion card you play each combat is free."],
    art: placeholderTrinket,
  },
  {
    id: "sundering-charm",
    title: "Sundering Charm",
    descriptionLines: ["Your Physical attacks ignore 2 enemy Armor."],
    art: placeholderTrinket,
  },
  {
    id: "resonant-chime",
    title: "Resonant Chime",
    descriptionLines: ["When you play 3 or more cards in a single turn, gain 1 Mana."],
    art: placeholderTrinket,
  },
  {
    id: "smugglers-map",
    title: "Smuggler's Map",
    descriptionLines: ["Gold rewards from combat are increased by 2."],
    art: placeholderTrinket,
  },
  {
    id: "groves-favor",
    title: "Grove's Favor",
    descriptionLines: ["Restore 2 Health at the start of each battle."],
    art: placeholderTrinket,
  },
];
