// Compendium data — all enemies (bestiary), trinkets, and their stat/effect definitions.
// Depends on art assets and type contracts. Pure configuration arrays, no game logic.
import { boneCharm, brassCenser, companionsCollar, cutpurseKnife, frozenHeart, goblin, grovesFavor, imp, ironBear, ironwoodBuckler, livingArmor, lizardScout, luckyClover, meteorite, mimic, mortarAndPestle, mudElemental, necromancer, merchantsFavor, obsidianHammer, parasiticBloom, plagueDoctor, plagueDoctorsMask, polarPendant, resonantChime, runicQuill, skeleton, sinEatersLantern, smugglersMap, sunderingCharm, tatteredPages, theBlightTreant, theForgeGolem, theFrostwarden, thunderstone, vanguardsCrest, wishingWellCoin } from "./assets";
import type { BestiaryEntry, TrinketEntry } from "./types";

export const enemyBestiary: BestiaryEntry[] = [
  {
    id: "rusted-colossus",
    title: "The Forge Golem",
    subtitle: "Boss",
    descriptionLines: [],
    art: theForgeGolem,
    enemyType: "boss",
    traits: [{ id: "rusting-carapace", title: "Rusting Carapace", description: "Gains 1 Armor each turn\nGains 1 Forge each turn" }],
    attackEffects: [
      { kind: "damage", damageType: "physical", amount: 5 },
      { kind: "player-status", status: "stun", amount: 2 },
    ],
  },
  {
    id: "frostwarden",
    title: "The Frostwarden",
    subtitle: "Boss",
    descriptionLines: [],
    art: theFrostwarden,
    enemyType: "boss",
    traits: [{ id: "glacial-shell", title: "Glacial Shell", description: "Receives half Freeze damage\nReceives double Burn damage\nGains 1 Freeze damage each turn" }],
    attackEffects: [
      { kind: "damage", damageType: "physical", amount: 8 },
      { kind: "player-status", status: "freeze", amount: 2 },
    ],
  },
  {
    id: "blight-treant",
    title: "The Blight Treant",
    subtitle: "Boss",
    descriptionLines: [],
    art: theBlightTreant,
    enemyType: "boss",
    traits: [{ id: "regeneration", title: "Rotting Regrowth", description: "Gains 4 Health each turn" }],
    attackEffects: [
      { kind: "damage", damageType: "nature", amount: 5 },
      { kind: "player-status", status: "poison", amount: 3 },
    ],
  },
  {
    id: "skeleton",
    title: "Skeleton",
    subtitle: "Normal",
    descriptionLines: [],
    art: skeleton,
    enemyType: "normal",
    traits: [{ id: "brittle-bones", title: "Brittle Bones", description: "Receives double Holy damage\nReceives double Stun damage" }],
    attackEffects: [{ kind: "damage", damageType: "physical", amount: 8 }],
  },
  {
    id: "goblin",
    title: "Goblin",
    subtitle: "Normal",
    descriptionLines: [],
    art: goblin,
    enemyType: "normal",
    traits: [{ id: "trinket-hoarder", title: "Trinket Hoarder", description: "Receives double Burn damage\nMore likely to drop Trinkets" }],
    attackEffects: [{ kind: "damage", damageType: "physical", amount: 8 }],
  },
  {
    id: "imp",
    title: "Imp",
    subtitle: "Normal",
    descriptionLines: [],
    art: imp,
    enemyType: "normal",
    traits: [{ id: "burn-resistance", title: "Burn Resistance", description: "Receives half Burn damage" }],
    attackEffects: [
      { kind: "player-status", status: "burn", amount: 3 },
    ],
  },
  {
    id: "lizard-scout",
    title: "Lizard Scout",
    subtitle: "Normal",
    descriptionLines: [],
    art: lizardScout,
    enemyType: "normal",
    traits: [{ id: "poison-resistance", title: "Poison Resistance", description: "Receives half Poison damage" }],
    attackEffects: [
      { kind: "player-status", status: "poison", amount: 2 },
    ],
  },
  {
    id: "mimic",
    title: "Mimic",
    subtitle: "Elite",
    descriptionLines: [],
    art: mimic,
    enemyType: "elite",
    traits: [{ id: "gold-trove", title: "Gold Trove", description: "Drops 1 Gold when damaged" }],
    attackEffects: [{ kind: "damage", damageType: "physical", amount: 8 }],
  },
  {
    id: "mud-elemental",
    title: "Mud Elemental",
    subtitle: "Elite",
    descriptionLines: [],
    art: mudElemental,
    enemyType: "elite",
    traits: [{ id: "regeneration", title: "Regeneration", description: "Gains 2 Health each turn" }],
    attackEffects: [
      { kind: "player-status", status: "stun", amount: 2 },
      { kind: "player-status", status: "poison", amount: 2 },
    ],
  },
  {
    id: "necromancer",
    title: "Necromancer",
    subtitle: "Elite",
    descriptionLines: [],
    art: necromancer,
    enemyType: "elite",
    traits: [{ id: "holy-vulnerability", title: "Holy Vulnerability", description: "Receives double Holy damage" }],
    attackEffects: [
      { kind: "player-status", status: "bleed", amount: 4 },
    ],
  },
  {
    id: "plague-doctor",
    title: "Plague Doctor",
    subtitle: "Elite",
    descriptionLines: [],
    art: plagueDoctor,
    enemyType: "elite",
    traits: [{ id: "poison-resistance", title: "Poison Resistance", description: "Receives half Poison damage" }],
    attackEffects: [
      { kind: "player-status", status: "poison", amount: 4 },
    ],
  },
  {
    id: "living-armor",
    title: "Living Armor",
    subtitle: "Elite",
    descriptionLines: [],
    art: livingArmor,
    enemyType: "elite",
    traits: [{ id: "living-armor", title: "Living Armor", description: "Starts combat with 8 Armor\nReceives half Bleed damage" }],
    attackEffects: [
      { kind: "damage", damageType: "physical", amount: 5 },
      { kind: "damage", damageType: "nature", amount: 5 },
    ],
  },
  {
    id: "iron-bear",
    title: "The Iron Bear",
    subtitle: "Wildwood Boss",
    descriptionLines: [],
    art: ironBear,
    enemyType: "boss",
    traits: [
      { id: "forge-regeneration", title: "Forge Regeneration", description: "Gains 2 Forge each turn" },
      { id: "iron-hide", title: "Iron Hide", description: "Gains 2 Armor each turn" },
      { id: "thick-hide", title: "Thick Hide", description: "Receives half Physical damage" },
    ],
    attackEffects: [{ kind: "damage", damageType: "physical", amount: 10 }],
  },
];

export const trinketLibrary: TrinketEntry[] = [
  {
    id: "brass-censer",
    title: "Brass Censer",
    descriptionLines: ["Your first Holy damage each combat is doubled."],
    art: brassCenser,
  },
  {
    id: "tattered-pages",
    title: "Tattered Pages",
    descriptionLines: ["Draw 1 additional card at the start of combat."],
    art: tatteredPages,
  },
  {
    id: "meteorite",
    title: "Meteorite",
    descriptionLines: ["Your first Burn damage each combat is doubled."],
    art: meteorite,
  },
  {
    id: "bone-charm",
    title: "Bone Charm",
    descriptionLines: ["Gain 3 Health when you defeat an enemy."],
    art: boneCharm,
  },
  {
    id: "obsidian-hammer",
    title: "Obsidian Hammer",
    descriptionLines: ["When you have 4 or more Forge, your Physical attacks also Stun for 1."],
    art: obsidianHammer,
  },
  {
    id: "frozen-heart",
    title: "Frozen Heart",
    descriptionLines: ["When you Freeze an enemy, deal 6 Physical damage."],
    art: frozenHeart,
  },
  {
    id: "ironwood-buckler",
    title: "Ironwood Buckler",
    descriptionLines: ["At the end of your turn, if you have 6 or more Block, gain 1 Armor."],
    art: ironwoodBuckler,
  },
  {
    id: "runic-quill",
    title: "Runic Quill",
    descriptionLines: ["Draw a card when you Consume a card."],
    art: runicQuill,
  },
  {
    id: "sin-eaters-lantern",
    title: "Sin-Eater's Lantern",
    descriptionLines: ["Gain 6 Health when you remove a harmful status effect from yourself."],
    art: sinEatersLantern,
  },
  {
    id: "vanguards-crest",
    title: "Vanguard's Crest",
    descriptionLines: ["When your Block fully absorbs an attack, gain 1 Forge."],
    art: vanguardsCrest,
  },
  {
    id: "parasitic-bloom",
    title: "Parasitic Bloom",
    descriptionLines: ["Poison has a 10% chance to Leech."],
    art: parasiticBloom,
  },
  {
    id: "cutpurse-knife",
    title: "Cutpurse Knife",
    descriptionLines: ["When you apply Bleed to an enemy, gain 1 Gold."],
    art: cutpurseKnife,
  },
  {
    id: "wishing-well-coin",
    title: "Wishing Well Coin",
    descriptionLines: ["When you Wish, also gain 3 Gold."],
    art: wishingWellCoin,
  },
  {
    id: "merchants-favor",
    title: "Merchant's Favor",
    descriptionLines: ["Your first purchase at each shop costs 7 less Gold."],
    art: merchantsFavor,
  },
  {
    id: "plague-doctors-mask",
    title: "Plague Doctor's Mask",
    descriptionLines: ["You are immune to the first harmful status effect you would receive each battle."],
    art: plagueDoctorsMask,
  },
  {
    id: "mortar-and-pestle",
    title: "Mortar and Pestle",
    descriptionLines: ["The first Potion card you play each combat is free."],
    art: mortarAndPestle,
  },
  {
    id: "sundering-charm",
    title: "Sundering Charm",
    descriptionLines: ["Your Physical attacks ignore 2 enemy Armor."],
    art: sunderingCharm,
  },
  {
    id: "resonant-chime",
    title: "Resonant Chime",
    descriptionLines: ["When you play 3 or more cards in a single turn, gain 1 Mana."],
    art: resonantChime,
  },
  {
    id: "smugglers-map",
    title: "Smuggler's Map",
    descriptionLines: ["Gold rewards from combat are increased by 2."],
    art: smugglersMap,
  },
  {
    id: "groves-favor",
    title: "Grove's Favor",
    descriptionLines: ["Restore 2 Health at the start of each battle."],
    art: grovesFavor,
  },
  {
    id: "companions-collar",
    title: "Companion's Collar",
    descriptionLines: ["Increases Companion damage by 1."],
    art: companionsCollar,
  },
  {
    id: "polar-pendant",
    title: "Polar Pendant",
    descriptionLines: ["Freeze effects last 1 turn longer."],
    art: polarPendant,
  },
  {
    id: "thunderstone",
    title: "Thunderstone",
    descriptionLines: ["When you Stun an enemy, deal 6 Nature damage."],
    art: thunderstone,
  },
  {
    id: "lucky-clover",
    title: "Lucky Clover",
    descriptionLines: ["Nature damage has a 10% chance to grant Gold equal to the damage dealt."],
    art: luckyClover,
  },
];
