// Generated by scripts/sync-gear-art.mjs — do not edit manually.

import gearArtGearCrossbowAstral from "@/assets/optimized/gear-crossbow-astral.webp";
import gearArtGearCrossbowBasic from "@/assets/optimized/gear-crossbow-basic.webp";
import gearArtGearDaggerBasic from "@/assets/optimized/gear-dagger-basic.webp";
import gearArtGearEmeraldAmuletAstral from "@/assets/optimized/gear-emerald-amulet-astral.webp";
import gearArtGearEmeraldAmuletBasic from "@/assets/optimized/gear-emerald-amulet-basic.webp";
import gearArtGearEmeraldRingAstral from "@/assets/optimized/gear-emerald-ring-astral.webp";
import gearArtGearEmeraldRingBasic from "@/assets/optimized/gear-emerald-ring-basic.webp";
import gearArtGearFlailBasic from "@/assets/optimized/gear-flail-basic.webp";
import gearArtGearGreatAxeAstral from "@/assets/optimized/gear-great-axe-astral.webp";
import gearArtGearGreatAxeBasic from "@/assets/optimized/gear-great-axe-basic.webp";
import gearArtGearGreatMaceAstral from "@/assets/optimized/gear-great-mace-astral.webp";
import gearArtGearGreatMaceBasic from "@/assets/optimized/gear-great-mace-basic.webp";
import gearArtGearGreatSwordAstral from "@/assets/optimized/gear-great-sword-astral.webp";
import gearArtGearHandAxeAstral from "@/assets/optimized/gear-hand-axe-astral.webp";
import gearArtGearHandAxeBasic from "@/assets/optimized/gear-hand-axe-basic.webp";
import gearArtGearLeatherArmorAstral from "@/assets/optimized/gear-leather-armor-astral.webp";
import gearArtGearLeatherArmorBasic from "@/assets/optimized/gear-leather-armor-basic.webp";
import gearArtGearLeatherBeltAstral from "@/assets/optimized/gear-leather-belt-astral.webp";
import gearArtGearLeatherBeltBasic from "@/assets/optimized/gear-leather-belt-basic.webp";
import gearArtGearLeatherBootsAstral from "@/assets/optimized/gear-leather-boots-astral.webp";
import gearArtGearLeatherBootsBasic from "@/assets/optimized/gear-leather-boots-basic.webp";
import gearArtGearLeatherGlovesBasic from "@/assets/optimized/gear-leather-gloves-basic.webp";
import gearArtGearLeatherHelmAstral from "@/assets/optimized/gear-leather-helm-astral.webp";
import gearArtGearLeatherHoodBasic from "@/assets/optimized/gear-leather-hood-basic.webp";
import gearArtGearLeatherShieldBasic from "@/assets/optimized/gear-leather-shield-basic.webp";
import gearArtGearLongBowBasic from "@/assets/optimized/gear-long-bow-basic.webp";
import gearArtGearLongSwordAstral from "@/assets/optimized/gear-long-sword-astral.webp";
import gearArtGearLongSwordBasic from "@/assets/optimized/gear-long-sword-basic.webp";
import gearArtGearMaceBasic from "@/assets/optimized/gear-mace-basic.webp";
import gearArtGearPlateArmorAstral from "@/assets/optimized/gear-plate-armor-astral.webp";
import gearArtGearPlateArmorBasic from "@/assets/optimized/gear-plate-armor-basic.webp";
import gearArtGearPlateBootsAstral from "@/assets/optimized/gear-plate-boots-astral.webp";
import gearArtGearPlateBootsBasic from "@/assets/optimized/gear-plate-boots-basic.webp";
import gearArtGearPlateHelmBasic from "@/assets/optimized/gear-plate-helm-basic.webp";
import gearArtGearPlateShieldAstral from "@/assets/optimized/gear-plate-shield-astral.webp";
import gearArtGearPlateShieldBasic from "@/assets/optimized/gear-plate-shield-basic.webp";
import gearArtGearQuiverAstral from "@/assets/optimized/gear-quiver-astral.webp";
import gearArtGearQuiverBasic from "@/assets/optimized/gear-quiver-basic.webp";
import gearArtGearRecurveBowAstral from "@/assets/optimized/gear-recurve-bow-astral.webp";
import gearArtGearRubyAmuletAstral from "@/assets/optimized/gear-ruby-amulet-astral.webp";
import gearArtGearRubyAmuletBasic from "@/assets/optimized/gear-ruby-amulet-basic.webp";
import gearArtGearRubyRingAstral from "@/assets/optimized/gear-ruby-ring-astral.webp";
import gearArtGearRubyRingBasic from "@/assets/optimized/gear-ruby-ring-basic.webp";
import gearArtGearSapphireAmuletAstral from "@/assets/optimized/gear-sapphire-amulet-astral.webp";
import gearArtGearSapphireAmuletBasic from "@/assets/optimized/gear-sapphire-amulet-basic.webp";
import gearArtGearSapphireRingAstral from "@/assets/optimized/gear-sapphire-ring-astral.webp";
import gearArtGearShortBowBasic from "@/assets/optimized/gear-short-bow-basic.webp";
import gearArtGearShortSwordBasic from "@/assets/optimized/gear-short-sword-basic.webp";
import gearArtGearSpellbookAstral from "@/assets/optimized/gear-spellbook-astral.webp";
import gearArtGearSpellbookBasic from "@/assets/optimized/gear-spellbook-basic.webp";
import gearArtGearStaffBasic from "@/assets/optimized/gear-staff-basic.webp";
import gearArtGearTopazAmuletAstral from "@/assets/optimized/gear-topaz-amulet-astral.webp";
import gearArtGearTopazAmuletBasic from "@/assets/optimized/gear-topaz-amulet-basic.webp";
import gearArtGearTopazRingAstral from "@/assets/optimized/gear-topaz-ring-astral.webp";
import gearArtGearTopazRingBasic from "@/assets/optimized/gear-topaz-ring-basic.webp";
import gearArtGearWandAstral from "@/assets/optimized/gear-wand-astral.webp";

export const gearArtByDefinitionId: Record<string, string> = {
  "crossbow-astral": gearArtGearCrossbowAstral,
  "crossbow-basic": gearArtGearCrossbowBasic,
  "dagger-basic": gearArtGearDaggerBasic,
  "emerald-amulet-astral": gearArtGearEmeraldAmuletAstral,
  "emerald-amulet-basic": gearArtGearEmeraldAmuletBasic,
  "emerald-ring-astral": gearArtGearEmeraldRingAstral,
  "emerald-ring-basic": gearArtGearEmeraldRingBasic,
  "flail-basic": gearArtGearFlailBasic,
  "great-axe-astral": gearArtGearGreatAxeAstral,
  "great-axe-basic": gearArtGearGreatAxeBasic,
  "great-mace-astral": gearArtGearGreatMaceAstral,
  "great-mace-basic": gearArtGearGreatMaceBasic,
  "great-sword-astral": gearArtGearGreatSwordAstral,
  "hand-axe-astral": gearArtGearHandAxeAstral,
  "hand-axe-basic": gearArtGearHandAxeBasic,
  "leather-armor-astral": gearArtGearLeatherArmorAstral,
  "leather-armor-basic": gearArtGearLeatherArmorBasic,
  "leather-belt-astral": gearArtGearLeatherBeltAstral,
  "leather-belt-basic": gearArtGearLeatherBeltBasic,
  "leather-boots-astral": gearArtGearLeatherBootsAstral,
  "leather-boots-basic": gearArtGearLeatherBootsBasic,
  "leather-gloves-basic": gearArtGearLeatherGlovesBasic,
  "leather-helm-astral": gearArtGearLeatherHelmAstral,
  "leather-hood-basic": gearArtGearLeatherHoodBasic,
  "leather-shield-basic": gearArtGearLeatherShieldBasic,
  "long-bow-basic": gearArtGearLongBowBasic,
  "long-sword-astral": gearArtGearLongSwordAstral,
  "long-sword-basic": gearArtGearLongSwordBasic,
  "mace-basic": gearArtGearMaceBasic,
  "plate-armor-astral": gearArtGearPlateArmorAstral,
  "plate-armor-basic": gearArtGearPlateArmorBasic,
  "plate-boots-astral": gearArtGearPlateBootsAstral,
  "plate-boots-basic": gearArtGearPlateBootsBasic,
  "plate-helm-basic": gearArtGearPlateHelmBasic,
  "plate-shield-astral": gearArtGearPlateShieldAstral,
  "plate-shield-basic": gearArtGearPlateShieldBasic,
  "quiver-astral": gearArtGearQuiverAstral,
  "quiver-basic": gearArtGearQuiverBasic,
  "recurve-bow-astral": gearArtGearRecurveBowAstral,
  "ruby-amulet-astral": gearArtGearRubyAmuletAstral,
  "ruby-amulet-basic": gearArtGearRubyAmuletBasic,
  "ruby-ring-astral": gearArtGearRubyRingAstral,
  "ruby-ring-basic": gearArtGearRubyRingBasic,
  "sapphire-amulet-astral": gearArtGearSapphireAmuletAstral,
  "sapphire-amulet-basic": gearArtGearSapphireAmuletBasic,
  "sapphire-ring-astral": gearArtGearSapphireRingAstral,
  "short-bow-basic": gearArtGearShortBowBasic,
  "short-sword-basic": gearArtGearShortSwordBasic,
  "spellbook-astral": gearArtGearSpellbookAstral,
  "spellbook-basic": gearArtGearSpellbookBasic,
  "staff-basic": gearArtGearStaffBasic,
  "topaz-amulet-astral": gearArtGearTopazAmuletAstral,
  "topaz-amulet-basic": gearArtGearTopazAmuletBasic,
  "topaz-ring-astral": gearArtGearTopazRingAstral,
  "topaz-ring-basic": gearArtGearTopazRingBasic,
  "wand-astral": gearArtGearWandAstral,
};
