import type { AffixRow } from "./types";

export const affixrows4 = [
  {
    id: "resist-nature",
    aspect: "defensive",
    keywordId: "nature",
    descriptionTemplate: "Reduce Nature damage taken by {value}%",
    effectKey: "resistNature",
    basic: { min: 10, max: 15 },
    astral: { min: 15, max: 20 },
  },
  {
    id: "health-per-turn",
    aspect: "defensive",
    keywordId: "health",
    descriptionTemplate: "Restore {value} Health each turn",
    effectKey: "healthPerTurn",
    basic: { min: 1, max: 2 },
    astral: { min: 3, max: 4 },
  },
  {
    id: "block-gain",
    aspect: "defensive",
    keywordId: "block",
    descriptionTemplate: "Increases Block gained by {value}",
    effectKey: "flatBlockGained",
    basic: { min: 1, max: 2 },
    astral: { min: 3, max: 4 },
  },
  {
    id: "gold-gain",
    aspect: "defensive",
    keywordId: "gold",
    descriptionTemplate: "Increases Gold gained by {value}%",
    effectKey: "goldGainPercent",
    basic: { min: 10, max: 15 },
    astral: { min: 15, max: 20 },
  },
  {
    id: "max-health",
    aspect: "defensive",
    keywordId: "health",
    descriptionTemplate: "Increases Health by {value}",
    effectKey: "maxHealth",
    basic: { min: 7, max: 8 },
    astral: { min: 9, max: 10 },
  },
  {
    id: "burn-on-consume",
    aspect: "offensive",
    keywordId: "consume",
    descriptionTemplate: "Deal {value} Burn damage when you Consume",
    effectKey: "burnOnConsume",
    basic: { min: 2, max: 3 },
    astral: { min: 4, max: 6 },
    secondaryKeywordId: "burn",
  },
  {
    id: "archery-ignore-armor",
    aspect: "offensive",
    keywordId: "archery",
    descriptionTemplate: "Archery attacks ignore {value} Armor",
    effectKey: "archeryArmorPiercing",
    basic: { min: 1, max: 2 },
    astral: { min: 3, max: 4 },
    secondaryKeywordId: "physical",
  },
  {
    id: "absorb-per-mana",
    aspect: "defensive",
    keywordId: "mana",
    descriptionTemplate: "Reduce damage taken by {value} for each full Mana Crystal",
    effectKey: "damageReductionPerMana",
    basic: { min: 2, max: 3 },
    astral: { min: 4, max: 5 },
    secondaryKeywordId: "block",
  },
  {
    id: "heal-on-burn-death",
    aspect: "defensive",
    keywordId: "burn",
    descriptionTemplate: "Restore {value} Health when an enemy with Burn is defeated",
    effectKey: "healOnBurnEnemyDefeated",
    basic: { min: 4, max: 5 },
    astral: { min: 6, max: 7 },
    secondaryKeywordId: "health",
  },
  {
    id: "mana-on-leech-chance",
    aspect: "offensive",
    keywordId: "leech",
    descriptionTemplate: "Leech has a {value}% chance to restore 1 Mana",
    effectKey: "manaOnLeechChance",
    basic: { min: 10, max: 15 },
    astral: { min: 15, max: 20 },
    secondaryKeywordId: "mana",
  },
  {
    id: "poison-reduces-armor",
    aspect: "offensive",
    keywordId: "poison",
    descriptionTemplate: "Poison has a {value}% chance to remove 1 Armor",
    effectKey: "poisonArmorShredChance",
    basic: { min: 10, max: 15 },
    astral: { min: 15, max: 20 },
    secondaryKeywordId: "armor",
  },
  {
    id: "nature-mana-refund-chance",
    aspect: "offensive",
    keywordId: "nature",
    descriptionTemplate: "Nature damage has a {value}% chance to restore 1 Mana",
    effectKey: "manaOnNatureDamageChance",
    basic: { min: 10, max: 15 },
    astral: { min: 15, max: 20 },
    secondaryKeywordId: "mana",
  },
  {
    id: "burn-on-bleed",
    aspect: "offensive",
    keywordId: "bleed",
    descriptionTemplate: "Burn deals {value}% more damage to Bleeding enemies",
    effectKey: "burnDamageBonusToBleedingPercent",
    basic: { min: 10, max: 15 },
    astral: { min: 15, max: 20 },
    secondaryKeywordId: "burn",
  },
  {
    id: "stun-on-block-hit",
    aspect: "defensive",
    keywordId: "block",
    descriptionTemplate: "Deal {value} Stun damage when your Block is depleted",
    effectKey: "stunOnBlockDepleted",
    basic: { min: 2, max: 3 },
    astral: { min: 4, max: 5 },
    secondaryKeywordId: "stun",
  },
  {
    id: "companion-leech",
    aspect: "defensive",
    keywordId: "companion",
    descriptionTemplate: "Restore {value} Health when your Companion attacks",
    effectKey: "healOnCompanionAttack",
    basic: { min: 1, max: 2 },
    astral: { min: 3, max: 4 },
    secondaryKeywordId: "health",
  },
  {
    id: "armor-on-cc",
    aspect: "defensive",
    keywordId: "armor",
    descriptionTemplate: "Gain {value} Armor when you are Stunned or Frozen",
    effectKey: "armorOnStunOrFreeze",
    basic: { min: 1, max: 2 },
    astral: { min: 3, max: 4 },
    secondaryKeywordId: "stun",
  },
] as const satisfies readonly AffixRow[];
