import type { AffixRow } from "./types";

export const affixrows3 = [
  {
    id: "heal-on-block-depleted",
    aspect: "defensive",
    keywordId: "health",
    descriptionTemplate: "Restore {value} Health when Block is depleted",
    effectKey: "blockDepletedHeal",
    basic: { min: 2, max: 3 },
    astral: { min: 4, max: 5 },
    secondaryKeywordId: "block",
  },
  {
    id: "health-on-wish",
    aspect: "defensive",
    keywordId: "health",
    descriptionTemplate: "Restore {value} Health on Wish",
    effectKey: "healthOnWish",
    basic: { min: 2, max: 3 },
    astral: { min: 4, max: 5 },
    secondaryKeywordId: "wish",
  },
  {
    id: "mana-on-wish",
    aspect: "offensive",
    keywordId: "mana",
    descriptionTemplate: "Gain {value} Mana on Wish",
    effectKey: "manaOnWish",
    basic: { min: 1, max: 1 },
    astral: { min: 2, max: 2 },
    secondaryKeywordId: "wish",
  },
  {
    id: "start-freeze",
    aspect: "defensive",
    keywordId: "freeze",
    descriptionTemplate: "Apply {value} Freeze at the start of combat",
    effectKey: "startFreeze",
    basic: { min: 4, max: 5 },
    astral: { min: 6, max: 7 },
  },
  {
    id: "holy-from-block",
    aspect: "offensive",
    keywordId: "holy",
    descriptionTemplate: "Increases Holy damage by {value}% of your Block",
    effectKey: "holyDamageFromBlockPercent",
    basic: { min: 10, max: 15 },
    astral: { min: 15, max: 20 },
    secondaryKeywordId: "block",
  },
  {
    id: "leech-potency",
    aspect: "offensive",
    keywordId: "leech",
    descriptionTemplate: "Leech restores {value}% more Health",
    effectKey: "leechHealBonusPercent",
    basic: { min: 10, max: 15 },
    astral: { min: 15, max: 20 },
  },
  {
    id: "frozen-vulnerable",
    aspect: "offensive",
    keywordId: "freeze",
    descriptionTemplate: "Frozen enemies take {value}% more damage",
    effectKey: "frozenEnemyDamageBonusPercent",
    basic: { min: 10, max: 15 },
    astral: { min: 15, max: 20 },
  },
  {
    id: "companion-forge-power",
    aspect: "offensive",
    keywordId: "companion",
    descriptionTemplate: "Companions benefit from Forge",
    effectKey: "companionBenefitsFromForge",
    basic: { min: 1, max: 1 },
    astral: { min: 1, max: 1 },
    secondaryKeywordId: "forge",
  },
  {
    id: "gold-blessed-holy",
    aspect: "offensive",
    keywordId: "holy",
    descriptionTemplate: "Increases Holy damage by {value}% of your Gold",
    effectKey: "holyDamageFromGoldPercent",
    basic: { min: 2, max: 3 },
    astral: { min: 4, max: 5 },
    secondaryKeywordId: "gold",
  },
  {
    id: "resist-physical",
    aspect: "defensive",
    keywordId: "physical",
    descriptionTemplate: "Reduce Physical damage taken by {value}%",
    effectKey: "resistPhysical",
    basic: { min: 10, max: 15 },
    astral: { min: 15, max: 20 },
  },
  {
    id: "resist-stun",
    aspect: "defensive",
    keywordId: "stun",
    descriptionTemplate: "Reduce Stun damage taken by {value}%",
    effectKey: "resistStun",
    basic: { min: 10, max: 15 },
    astral: { min: 15, max: 20 },
  },
  {
    id: "resist-holy",
    aspect: "defensive",
    keywordId: "holy",
    descriptionTemplate: "Reduce Holy damage taken by {value}%",
    effectKey: "resistHoly",
    basic: { min: 10, max: 15 },
    astral: { min: 15, max: 20 },
  },
  {
    id: "resist-burn",
    aspect: "defensive",
    keywordId: "burn",
    descriptionTemplate: "Reduce Burn damage taken by {value}%",
    effectKey: "resistBurn",
    basic: { min: 10, max: 15 },
    astral: { min: 15, max: 20 },
  },
  {
    id: "resist-poison",
    aspect: "defensive",
    keywordId: "poison",
    descriptionTemplate: "Reduce Poison damage taken by {value}%",
    effectKey: "resistPoison",
    basic: { min: 10, max: 15 },
    astral: { min: 15, max: 20 },
  },
  {
    id: "resist-bleed",
    aspect: "defensive",
    keywordId: "bleed",
    descriptionTemplate: "Reduce Bleed damage taken by {value}%",
    effectKey: "resistBleed",
    basic: { min: 10, max: 15 },
    astral: { min: 15, max: 20 },
  },
  {
    id: "resist-freeze",
    aspect: "defensive",
    keywordId: "freeze",
    descriptionTemplate: "Reduce Freeze damage taken by {value}%",
    effectKey: "resistFreeze",
    basic: { min: 10, max: 15 },
    astral: { min: 15, max: 20 },
  },
] as const satisfies readonly AffixRow[];
