import type { AffixRow } from "./types";

export const affixrows2 = [
  {
    id: "start-forge",
    aspect: "defensive",
    keywordId: "forge",
    descriptionTemplate: "Gain {value} Forge at the start of combat",
    effectKey: "startForge",
    basic: { min: 1, max: 2 },
    astral: { min: 2, max: 4 },
  },
  {
    id: "start-armor",
    aspect: "defensive",
    keywordId: "armor",
    descriptionTemplate: "Gain {value} Armor at the start of combat",
    effectKey: "startArmor",
    basic: { min: 1, max: 2 },
    astral: { min: 2, max: 4 },
  },
  {
    id: "block-on-stun",
    aspect: "defensive",
    keywordId: "block",
    descriptionTemplate: "On Stun: Gain {value} Block",
    effectKey: "blockOnStun",
    basic: { min: 3, max: 4 },
    astral: { min: 5, max: 6 },
  },
  {
    id: "mana-on-stun",
    aspect: "offensive",
    keywordId: "mana",
    descriptionTemplate: "On Stun: Gain {value} Mana",
    effectKey: "manaOnStun",
    basic: { min: 1, max: 1 },
    astral: { min: 2, max: 2 },
  },
  {
    id: "physical-bleed-chance",
    aspect: "offensive",
    keywordId: "bleed",
    descriptionTemplate: "{value}% chance for Physical damage to Bleed",
    effectKey: "physicalBleedChance",
    basic: { min: 7, max: 8 },
    astral: { min: 9, max: 10 },
    secondaryKeywordId: "physical",
  },
  {
    id: "burn-per-mana",
    aspect: "offensive",
    keywordId: "burn",
    descriptionTemplate: "Increases Burn damage by {value}% per Mana Crystal",
    effectKey: "burnDamagePerManaPercent",
    basic: { min: 10, max: 15 },
    astral: { min: 15, max: 20 },
    secondaryKeywordId: "mana",
  },
  {
    id: "gold-on-wish",
    aspect: "offensive",
    keywordId: "gold",
    descriptionTemplate: "Gain {value} Gold on Wish",
    effectKey: "goldOnWish",
    basic: { min: 1, max: 2 },
    astral: { min: 3, max: 4 },
    secondaryKeywordId: "wish",
  },
  {
    id: "burn-on-wish",
    aspect: "offensive",
    keywordId: "burn",
    descriptionTemplate: "Deal {value} Burn damage on Wish",
    effectKey: "burnOnWish",
    basic: { min: 1, max: 2 },
    astral: { min: 3, max: 4 },
    secondaryKeywordId: "wish",
  },
  {
    id: "gold-on-kill",
    aspect: "offensive",
    keywordId: "gold",
    descriptionTemplate: "Gain {value} Gold on kill",
    effectKey: "goldOnKill",
    basic: { min: 4, max: 5 },
    astral: { min: 6, max: 7 },
  },
  {
    id: "physical-stun-chance",
    aspect: "offensive",
    keywordId: "stun",
    descriptionTemplate: "{value}% chance for Physical damage to Stun",
    effectKey: "physicalStunChance",
    basic: { min: 5, max: 10 },
    astral: { min: 10, max: 15 },
    secondaryKeywordId: "physical",
  },
  {
    id: "nature-leech",
    aspect: "offensive",
    keywordId: "leech",
    descriptionTemplate: "Nature damage has a {value}% chance to Leech",
    effectKey: "natureLeechChance",
    basic: { min: 7, max: 8 },
    astral: { min: 9, max: 10 },
    secondaryKeywordId: "nature",
  },
  {
    id: "forge-on-burn",
    aspect: "offensive",
    keywordId: "forge",
    descriptionTemplate: "Gain {value} Forge when you deal Burn damage",
    effectKey: "forgeOnBurnDealt",
    basic: { min: 1, max: 2 },
    astral: { min: 2, max: 4 },
    secondaryKeywordId: "burn",
  },
  {
    id: "draw-on-wish",
    aspect: "offensive",
    keywordId: "wish",
    descriptionTemplate: "Draw {value} Cards on Wish",
    effectKey: "drawOnWish",
    basic: { min: 1, max: 1 },
    astral: { min: 2, max: 2 },
  },
  {
    id: "consume-heal-bonus",
    aspect: "defensive",
    keywordId: "consume",
    descriptionTemplate: "Increases Healing from Consumed cards by {value}%",
    effectKey: "consumeHealBonusPercent",
    basic: { min: 10, max: 15 },
    astral: { min: 15, max: 20 },
    secondaryKeywordId: "health",
  },
  {
    id: "archery-damage",
    aspect: "offensive",
    keywordId: "archery",
    descriptionTemplate: "Increases Archery damage by {value}",
    effectKey: "flatArrowDamage",
    basic: { min: 2, max: 3 },
    astral: { min: 4, max: 5 },
  },
  {
    id: "damage-on-freeze",
    aspect: "offensive",
    keywordId: "physical",
    descriptionTemplate: "On Freeze: Deal {value} Physical damage",
    effectKey: "damageOnFreezePhysical",
    basic: { min: 3, max: 4 },
    astral: { min: 5, max: 6 },
    secondaryKeywordId: "freeze",
  },
] as const satisfies readonly AffixRow[];
