import type { AffixRow } from "./types";

export const affixrows1 = [
  {
    id: "flat-physical",
    aspect: "offensive",
    keywordId: "physical",
    descriptionTemplate: "Increases Physical damage by {value}",
    effectKey: "flatPhysicalDamage",
    basic: { min: 1, max: 2 },
    astral: { min: 3, max: 4 },
  },
  {
    id: "flat-stun",
    aspect: "offensive",
    keywordId: "stun",
    descriptionTemplate: "Increases Stun damage by {value}",
    effectKey: "flatStunDamage",
    basic: { min: 1, max: 2 },
    astral: { min: 3, max: 4 },
  },
  {
    id: "flat-holy",
    aspect: "offensive",
    keywordId: "holy",
    descriptionTemplate: "Increases Holy damage by {value}",
    effectKey: "flatHolyDamage",
    basic: { min: 1, max: 2 },
    astral: { min: 3, max: 4 },
  },
  {
    id: "flat-burn",
    aspect: "offensive",
    keywordId: "burn",
    descriptionTemplate: "Increases Burn damage by {value}",
    effectKey: "flatBurnDamage",
    basic: { min: 1, max: 2 },
    astral: { min: 3, max: 4 },
  },
  {
    id: "flat-poison",
    aspect: "offensive",
    keywordId: "poison",
    descriptionTemplate: "Increases Poison damage by {value}",
    effectKey: "flatPoisonDamage",
    basic: { min: 1, max: 2 },
    astral: { min: 3, max: 4 },
  },
  {
    id: "flat-bleed",
    aspect: "offensive",
    keywordId: "bleed",
    descriptionTemplate: "Increases Bleed damage by {value}",
    effectKey: "flatBleedDamage",
    basic: { min: 1, max: 2 },
    astral: { min: 3, max: 4 },
  },
  {
    id: "flat-freeze",
    aspect: "offensive",
    keywordId: "freeze",
    descriptionTemplate: "Increases Freeze damage by {value}",
    effectKey: "flatFreezeDamage",
    basic: { min: 1, max: 2 },
    astral: { min: 3, max: 4 },
  },
  {
    id: "flat-nature",
    aspect: "offensive",
    keywordId: "nature",
    descriptionTemplate: "Increases Nature damage by {value}",
    effectKey: "flatNatureDamage",
    basic: { min: 1, max: 2 },
    astral: { min: 3, max: 4 },
  },
  {
    id: "start-block",
    aspect: "defensive",
    keywordId: "block",
    descriptionTemplate: "Gain {value} Block at the start of combat",
    effectKey: "startBlock",
    basic: { min: 4, max: 6 },
    astral: { min: 7, max: 9 },
  },
  {
    id: "armor-pierce",
    aspect: "offensive",
    keywordId: "physical",
    descriptionTemplate: "Ignore {value} enemy Armor",
    effectKey: "armorPiercing",
    basic: { min: 1, max: 2 },
    astral: { min: 2, max: 4 },
  },
  {
    id: "damage-on-stun",
    aspect: "offensive",
    keywordId: "physical",
    descriptionTemplate: "On Stun: Deal {value} Physical damage",
    effectKey: "damageOnStunPhysical",
    basic: { min: 3, max: 4 },
    astral: { min: 5, max: 6 },
  },
  {
    id: "forge-on-stun",
    aspect: "offensive",
    keywordId: "forge",
    descriptionTemplate: "On Stun: Gain {value} Forge",
    effectKey: "forgeOnStun",
    basic: { min: 1, max: 2 },
    astral: { min: 2, max: 4 },
  },
  {
    id: "poison-leech",
    aspect: "offensive",
    keywordId: "leech",
    descriptionTemplate: "Poison has a {value}% chance to Leech",
    effectKey: "poisonLeechChance",
    basic: { min: 5, max: 7 },
    astral: { min: 8, max: 10 },
    secondaryKeywordId: "poison",
  },
  {
    id: "companion-damage",
    aspect: "offensive",
    keywordId: "companion",
    descriptionTemplate: "Increases Companion damage by {value}",
    effectKey: "companionDamageBonus",
    basic: { min: 1, max: 2 },
    astral: { min: 2, max: 4 },
  },
  {
    id: "start-heal",
    aspect: "defensive",
    keywordId: "health",
    descriptionTemplate: "Restore {value} Health at the start of combat",
    effectKey: "startHeal",
    basic: { min: 3, max: 4 },
    astral: { min: 5, max: 6 },
  },
  {
    id: "heal-on-kill",
    aspect: "defensive",
    keywordId: "health",
    descriptionTemplate: "Restore {value} Health on kill",
    effectKey: "healOnKill",
    basic: { min: 3, max: 4 },
    astral: { min: 5, max: 6 },
  },
] as const satisfies readonly AffixRow[];
