export const BATTLE_MUSIC_TRACKS = [
  '/assets/audio/music/battle/beach.ogg',
  '/assets/audio/music/battle/cave.ogg',
  '/assets/audio/music/battle/forest-day.ogg',
  '/assets/audio/music/battle/forest-night.ogg',
  '/assets/audio/music/battle/interior-day.ogg',
  '/assets/audio/music/battle/pixel-fantasy-30/Loops/ogg/1. Dawn of Blades.ogg',
  '/assets/audio/music/battle/pixel-fantasy-30/Loops/ogg/10. Crown of Thorns.ogg',
  '/assets/audio/music/battle/pixel-fantasy-30/Loops/ogg/11. Whispers in the Fog.ogg',
  '/assets/audio/music/battle/pixel-fantasy-30/Loops/ogg/12. March of Iron.ogg',
  '/assets/audio/music/battle/pixel-fantasy-30/Loops/ogg/13. The Forgotten Grove.ogg',
  '/assets/audio/music/battle/pixel-fantasy-30/Loops/ogg/14. Sacred Springs.ogg',
  '/assets/audio/music/battle/pixel-fantasy-30/Loops/ogg/15. Legends of the Flame.ogg',
  '/assets/audio/music/battle/pixel-fantasy-30/Loops/ogg/16. Silent Citadel.ogg',
  '/assets/audio/music/battle/pixel-fantasy-30/Loops/ogg/17. Hymn of Valor.ogg',
  '/assets/audio/music/battle/pixel-fantasy-30/Loops/ogg/18. The Dark Moor.ogg',
  '/assets/audio/music/battle/pixel-fantasy-30/Loops/ogg/19. Call of the Raven.ogg',
  '/assets/audio/music/battle/pixel-fantasy-30/Loops/ogg/2. Echoes of the Keep.ogg',
  '/assets/audio/music/battle/pixel-fantasy-30/Loops/ogg/20. Lament of Kings.ogg',
  '/assets/audio/music/battle/pixel-fantasy-30/Loops/ogg/21. The Silent Lake.ogg',
  '/assets/audio/music/battle/pixel-fantasy-30/Loops/ogg/22. Banners in the Wind.ogg',
  '/assets/audio/music/battle/pixel-fantasy-30/Loops/ogg/23. The Last Watch.ogg',
  '/assets/audio/music/battle/pixel-fantasy-30/Loops/ogg/24. Blood and Honor.ogg',
  '/assets/audio/music/battle/pixel-fantasy-30/Loops/ogg/25. Tales by Firelight.ogg',
  '/assets/audio/music/battle/pixel-fantasy-30/Loops/ogg/26. Echoes of Eternity.ogg',
  '/assets/audio/music/battle/pixel-fantasy-30/Loops/ogg/27. The Broken Crown.ogg',
  '/assets/audio/music/battle/pixel-fantasy-30/Loops/ogg/28. Tales of the Hearth.ogg',
  '/assets/audio/music/battle/pixel-fantasy-30/Loops/ogg/29. Arcane Whispers.ogg',
  '/assets/audio/music/battle/pixel-fantasy-30/Loops/ogg/3. Twilight March.ogg',
  '/assets/audio/music/battle/pixel-fantasy-30/Loops/ogg/30. The Hidden Glade.ogg',
  '/assets/audio/music/battle/pixel-fantasy-30/Loops/ogg/4. Ballad of Ashenwood.ogg',
  '/assets/audio/music/battle/pixel-fantasy-30/Loops/ogg/5. Riders of the Storm.ogg',
  '/assets/audio/music/battle/pixel-fantasy-30/Loops/ogg/6. Moonlit Vale.ogg',
  '/assets/audio/music/battle/pixel-fantasy-30/Loops/ogg/7. Chant of the Fallen.ogg',
  '/assets/audio/music/battle/pixel-fantasy-30/Loops/ogg/8. Frostbound Path.ogg',
  '/assets/audio/music/battle/pixel-fantasy-30/Loops/ogg/9. The Old Tavern.ogg',
  '/assets/audio/music/battle/pixel-fantasy-30/Tracks/ogg/1. Dawn of Blades.ogg',
  '/assets/audio/music/battle/pixel-fantasy-30/Tracks/ogg/10. Crown of Thorns.ogg',
  '/assets/audio/music/battle/pixel-fantasy-30/Tracks/ogg/11. Whispers in the Fog.ogg',
  '/assets/audio/music/battle/pixel-fantasy-30/Tracks/ogg/12. March of Iron.ogg',
  '/assets/audio/music/battle/pixel-fantasy-30/Tracks/ogg/13. The Forgotten Grove.ogg',
  '/assets/audio/music/battle/pixel-fantasy-30/Tracks/ogg/14. Sacred Springs.ogg',
  '/assets/audio/music/battle/pixel-fantasy-30/Tracks/ogg/15. Legends of the Flame.ogg',
  '/assets/audio/music/battle/pixel-fantasy-30/Tracks/ogg/16. Silent Citadel.ogg',
  '/assets/audio/music/battle/pixel-fantasy-30/Tracks/ogg/17. Hymn of Valor.ogg',
  '/assets/audio/music/battle/pixel-fantasy-30/Tracks/ogg/18. The Dark Moor.ogg',
  '/assets/audio/music/battle/pixel-fantasy-30/Tracks/ogg/19. Call of the Raven.ogg',
  '/assets/audio/music/battle/pixel-fantasy-30/Tracks/ogg/2. Echoes of the Keep.ogg',
  '/assets/audio/music/battle/pixel-fantasy-30/Tracks/ogg/20. Lament of Kings.ogg',
  '/assets/audio/music/battle/pixel-fantasy-30/Tracks/ogg/21. The Silent Lake.ogg',
  '/assets/audio/music/battle/pixel-fantasy-30/Tracks/ogg/22. Banners in the Wind.ogg',
  '/assets/audio/music/battle/pixel-fantasy-30/Tracks/ogg/23. The Last Watch.ogg',
  '/assets/audio/music/battle/pixel-fantasy-30/Tracks/ogg/24. Blood and Honor.ogg',
  '/assets/audio/music/battle/pixel-fantasy-30/Tracks/ogg/25. Tales by Firelight.ogg',
  '/assets/audio/music/battle/pixel-fantasy-30/Tracks/ogg/26. Echoes of Eternity.ogg',
  '/assets/audio/music/battle/pixel-fantasy-30/Tracks/ogg/27. The Broken Crown.ogg',
  '/assets/audio/music/battle/pixel-fantasy-30/Tracks/ogg/28. Tales of the Hearth.ogg',
  '/assets/audio/music/battle/pixel-fantasy-30/Tracks/ogg/29. Arcane Whispers.ogg',
  '/assets/audio/music/battle/pixel-fantasy-30/Tracks/ogg/3. Twilight March.ogg',
  '/assets/audio/music/battle/pixel-fantasy-30/Tracks/ogg/30. The Hidden Glade.ogg',
  '/assets/audio/music/battle/pixel-fantasy-30/Tracks/ogg/4. Ballad of Ashenwood.ogg',
  '/assets/audio/music/battle/pixel-fantasy-30/Tracks/ogg/5. Riders of the Storm.ogg',
  '/assets/audio/music/battle/pixel-fantasy-30/Tracks/ogg/6. Moonlit Vale.ogg',
  '/assets/audio/music/battle/pixel-fantasy-30/Tracks/ogg/7. Chant of the Fallen.ogg',
  '/assets/audio/music/battle/pixel-fantasy-30/Tracks/ogg/8. Frostbound Path.ogg',
  '/assets/audio/music/battle/pixel-fantasy-30/Tracks/ogg/9. The Old Tavern.ogg',
  '/assets/audio/music/battle/pixel-rpg/Pixel Music Pack/Ogg/Pixel 1.ogg',
  '/assets/audio/music/battle/pixel-rpg/Pixel Music Pack/Ogg/Pixel 10.ogg',
  '/assets/audio/music/battle/pixel-rpg/Pixel Music Pack/Ogg/Pixel 11.ogg',
  '/assets/audio/music/battle/pixel-rpg/Pixel Music Pack/Ogg/Pixel 12.ogg',
  '/assets/audio/music/battle/pixel-rpg/Pixel Music Pack/Ogg/Pixel 2.ogg',
  '/assets/audio/music/battle/pixel-rpg/Pixel Music Pack/Ogg/Pixel 3.ogg',
  '/assets/audio/music/battle/pixel-rpg/Pixel Music Pack/Ogg/Pixel 4.ogg',
  '/assets/audio/music/battle/pixel-rpg/Pixel Music Pack/Ogg/Pixel 5.ogg',
  '/assets/audio/music/battle/pixel-rpg/Pixel Music Pack/Ogg/Pixel 6.ogg',
  '/assets/audio/music/battle/pixel-rpg/Pixel Music Pack/Ogg/Pixel 7.ogg',
  '/assets/audio/music/battle/pixel-rpg/Pixel Music Pack/Ogg/Pixel 8.ogg',
  '/assets/audio/music/battle/pixel-rpg/Pixel Music Pack/Ogg/Pixel 9.ogg',
  '/assets/audio/music/battle/sea.ogg',
] as const
