export const CARD_ART_BY_ID: Record<string, string> = {
  stab:          '/assets/icon-stab.png',
  slash:         '/assets/icon-slash.png',
  defend:        '/assets/icon-defend.png',
  bash:          '/assets/icon-bash.png',
  plate_mail:    '/assets/icon-plate-mail.png',
  anvil:         '/assets/icon-forge.png',
  health_potion: '/assets/icon-health-potion.png',
  apple:         '/assets/icon-apple.png',
  meat:          '/assets/icon-meat.png',
  bread:         '/assets/icon-bread.png',
  bite:          '/assets/icon-bite.png',
  poison_fangs:  '/assets/icon-poison-fangs.png',
  fireball:      '/assets/icon-fireball.png',
  gold:          '/assets/icon-gold.png',
  mana_crystal:  '/assets/icon-mana-crystal.png',
  mana_berries:  '/assets/icon-mana-berries.png',
  poisoned_dagger:'/assets/icon-poisoned-dagger.png',
  lacerate:      '/assets/icon-lacerate.png',
  haste:         '/assets/icon-haste.png',
  heal:          '/assets/icon-heal.png',
  cleanse:       '/assets/icon-cleanse.png',
  fiery_blade:   '/assets/icon-fiery-blade.png',
  bear_trap:     '/assets/icon-bear-trap.png',
  wish:          '/assets/icon-wish.png',
  holy_blade:    '/assets/icon-holy-blade.png',
  immolate:      '/assets/icon-immolate.png',
}
