export const CARD_ART_BY_ID: Record<string, string> = {
  stab:          'assets/cards/icon-stab.png',
  slash:         'assets/cards/icon-slash.png',
  defend:        'assets/cards/icon-defend.png',
  bash:          'assets/cards/icon-bash.png',
  plate_mail:    'assets/cards/icon-plate-mail.png',
  anvil:         'assets/cards/icon-forge.png',
  health_potion: 'assets/cards/icon-health-potion.png',
  panacea_potion:'assets/cards/icon-health-potion.png',
  mana_potion:   'assets/cards/icon-health-potion.png',
  mixed_potion:  'assets/cards/icon-mixed-potion.png',
  apple:         'assets/cards/icon-apple.png',
  meat:          'assets/cards/icon-meat.png',
  bread:         'assets/cards/icon-bread.png',
  bite:          'assets/cards/icon-bite.png',
  poison_fangs:  'assets/cards/icon-poison-fangs.png',
  fireball:      'assets/cards/icon-fireball.png',
  gold:          'assets/cards/icon-gold.png',
  mana_crystal:  'assets/cards/icon-mana-crystal.png',
  mana_berries:  'assets/cards/icon-mana-berries.png',
  poisoned_dagger:'assets/cards/icon-poisoned-dagger.png',
  lacerate:      'assets/cards/icon-lacerate.png',
  haste:         'assets/cards/icon-haste.png',
  heal:          'assets/cards/icon-heal.png',
  cleanse:       'assets/cards/icon-cleanse.png',
  fiery_blade:   'assets/cards/icon-fiery-blade.png',
  bear_trap:     'assets/cards/icon-bear-trap.png',
  wish:          'assets/cards/icon-wish.png',
  holy_blade:    'assets/cards/icon-holy-blade.png',
  immolate:      'assets/cards/icon-immolate.png',
  cauterize:     'assets/cards/icon-cauterize.png',
  blessed_aegis: 'assets/cards/icon-blessed-aegis.png',
  steal:         'assets/cards/icon-steal.png',
  exsanguinate:  'assets/cards/icon-exsanguinate.png',
  conflagrate:   'assets/cards/icon-conflagrate.png',
  frostbolt:     'assets/cards/icon-frostbolt.png',
}
