import { MIXED_POTION_CARD_ID } from "../game-constants";
import { isMixedPotionCard } from "../game-data/cards/card-pools";
import type { Screen } from "../routing/screens";

// Null keeps a semantic event available while explicitly choosing silence.
type SoundCue = string | null;

export const cardSounds: Record<string, string[]> = {
  slash: ["sword-attack-1.ogg"],
  stab: ["sword-attack-3.ogg"],
  bash: ["gut-kick.ogg"],
  block: ["sword-blocked-1.ogg"],
  anvil: ["ilmarinen-blacksmith-forge-hammer-anvil-strik-0f11505a-0-432.ogg"],
  "plate-mail": ["heavy-armor-block-01-a169e2a5-0-2000.ogg"],
  apple: ["bread-curst-bite-mouth-close-chew-crunch-vari-fefd384f-0-1440.ogg"],
  bread: ["bread-curst-bite-mouth-close-chew-crunch-vari-fefd384f-0-1440.ogg"],
  meteor: ["ground-impact-large-falling-rocks-various-04-2f578e6a-0-5305.ogg"],
  steal: ["coins-gather-quick.ogg"],
  "blessed-aegis": ["gut-kick.ogg"],
  wish: ["music-box-mystery.ogg"],
  cleanse: ["buff-pickup-1.ogg"],
  heal: ["buff-pickup-1.ogg"],
  haste: ["texture-whoosh-02-fast-02-1c520254-0-835.ogg"],
  "poison-dagger": ["sword-impact-hit-2.ogg"],
  fireball: ["fireball-1.ogg"],
  fangs: ["monster-bite-3-7193d1d8-0-1339.ogg"],
  "wolf-companion": ["efx-int-mutt-growl-42-b-ef1caab1-0-2443.ogg"],
  "lizard-scout-companion": ["swipe.ogg"],
  frostbolt: ["ice-throw-1.ogg"],
  "health-potion": ["ice-in-water.ogg"],
  "mana-berries": ["bread-curst-bite-mouth-close-chew-crunch-vari-fefd384f-0-1440.ogg"],
  "mana-crystals": ["buff-pickup.ogg"],
  "mana-potion": ["ice-in-water.ogg"],
  "panacea-potion": ["ice-in-water.ogg"],
  "stoneskin-potion": ["ice-in-water.ogg"],
  "acid-potion": ["ice-in-water.ogg"],
  "luck-potion": ["ice-in-water.ogg"],
  "wishing-potion": ["ice-in-water.ogg"],
  "mixed-potion": ["ice-in-water.ogg"],
  "frost-whelp-companion": ["ice-throw-1.ogg"],
  "bear-companion": ["gut-kick.ogg"],
  "panther-companion": ["swipe.ogg"],
  "phoenix-companion": ["fireball-1.ogg"],
  "skeleton-companion": ["swish-hit.ogg"],
  "pixie-companion": ["buff-pickup-1.ogg"],
  "golden-retriever-companion": ["coins-gather-quick.ogg"],
  "shield-scarab-companion": ["sword-blocked-1.ogg"],
  "fox-companion": ["swipe.ogg"],
  "shield-bash": ["gut-kick.ogg"],
  "burning-blade": ["fireball-1.ogg"],
  blackjack: ["coins-gather-quick.ogg"],
  "venom-fangs": ["sword-impact-hit-2.ogg"],
  bloodthorn: ["sword-impact-hit-2.ogg"],
  cinderbloom: ["fireball-1.ogg"],
  "serrated-edge": ["sword-impact-hit-2.ogg"],
  sunder: ["strong-punch.ogg"],
  "briar-shield": ["sword-blocked-1.ogg"],
  "thorn-mail": ["sword-blocked-1.ogg"],
  "mana-shield": ["energy-noise.ogg"],
  "cold-snap": ["ice-throw-1.ogg"],
  cauterize: ["fireball-1.ogg"],
  sunburst: ["fireball-1.ogg"],
  "holy-radiance": ["buff-pickup-1.ogg"],
  "smelling-salts": ["ice-in-water.ogg"],
  "faustian-bargain": ["dark-spell-life-tap-03-dd1d0dd1-0-2754.ogg"],
  "grasping-vines": ["swish-hit.ogg"],
  "pack-tactics": ["monster-bite-3-7193d1d8-0-1339.ogg"],
  smite: ["fireball-1.ogg"],
  "blood-offering": ["dark-spell-life-tap-03-dd1d0dd1-0-2754.ogg"],
  judgment: ["strong-punch.ogg"],
  "ray-of-frost": ["ice-throw-1.ogg"],
  kindling: ["fireball-02-e587c4fa-0-3000.ogg"],
  "roll-the-dice": ["dice-roll-01-b4d30a6d-0-430.ogg"],
  "lightning-bolt": ["lightning-impact-ac84ed8a-0-2000.ogg"],
  hemorrhage: ["monster-bite-3-7193d1d8-0-1339.ogg"],
  "phoenix-feather": ["fireball-1.ogg"],
  pounce: ["gut-kick.ogg"],
  earthquake: ["ground-impact-large-falling-rocks-various-04-2f578e6a-0-5305.ogg"],
  stargaze: ["ice-throw-1.ogg"],
  maul: ["gut-kick.ogg"],
  blizzard: ["ice-throw-1.ogg"],
  combustion: ["fireball-1.ogg"],
  "fire-arrow": ["bow-attack-01-626d2d6d-0-3000.ogg"],
  "ice-shot": ["bow-attack-01-626d2d6d-0-3000.ogg"],
  "venom-arrow": ["bow-attack-02-d2ecb917-0-3000.ogg"],
  "serrated-arrowhead": ["bow-attack-01-626d2d6d-0-3000.ogg"],
  "concussive-shot": ["bow-attack-02-d2ecb917-0-3000.ogg"],
  "lightning-arrow": ["bow-attack-01-626d2d6d-0-3000.ogg"],
  "bounty-shot": ["bow-attack-02-d2ecb917-0-3000.ogg"],
  "sap-arrow": ["bow-attack-01-626d2d6d-0-3000.ogg"],
  "gamblers-shot": ["bow-attack-02-d2ecb917-0-3000.ogg"],
  "astral-arrow": ["bow-attack-01-626d2d6d-0-3000.ogg"],
  "dark-pact": ["dark-spell-life-tap-03-dd1d0dd1-0-2754.ogg"],
  "molten-bulwark": ["fireball-1.ogg"],
  "glacial-ward": ["magic-ice-whoosh-ice-bloc-debris-01-2eb4176c-0-2352.ogg"],
  "spiked-shield": ["wood-breaking-cracking-snapping-breaking-peel-d8b1cf2e-0-1333.ogg"],
  "golden-plate": ["coins-pouch-leather-drop-into-takes-3-bbe032a5-0-2000.ogg"],
  "crystal-bulwark": ["heavy-armor-block-01-a169e2a5-0-2000.ogg"],
  shadowstep: ["texture-whoosh-02-fast-02-1c520254-0-835.ogg"],
};

export const enemyAttackSounds: Record<string, string[]> = {
  skeleton: ["swish-hit.ogg"],
  goblin: ["swish-hit.ogg"],
  mimic: ["creature-monster-attack-09-108cd42b-0-1854.ogg"],
  "mud-elemental": ["strong-punch.ogg"],
  necromancer: ["dark-spell-life-tap-03-dd1d0dd1-0-2754.ogg"],
  "plague-doctor": ["swish-hit.ogg"],
  "forge-golem": ["ilmarinen-blacksmith-forge-hammer-anvil-strik-0f11505a-0-432.ogg"],
  frostwarden: ["ice-throw-1.ogg"],
  "blight-treant": ["wood-breaking-cracking-snapping-breaking-peel-d8b1cf2e-0-1333.ogg"],
  "iron-bear": ["gut-kick.ogg"],
  "living-armor": ["weapon-impact-parry-01-1b12234a-0-922.ogg"],
  "fire-elemental": ["fireball-1.ogg"],
  "frost-elemental": ["ice-throw-1.ogg"],
  slime: ["squelching-4.ogg"],
  bandit: ["sword-attack-1.ogg"],
  ogre: ["gut-kick.ogg"],
  "fire-imp": ["fireball-02-e587c4fa-0-3000.ogg"],
  hellhound: ["fireball-02-e587c4fa-0-3000.ogg"],
  pyromancer: ["fireball-1.ogg"],
  "blood-cultist": ["dark-spell-life-tap-03-dd1d0dd1-0-2754.ogg"],
  "dire-wolf": ["efx-int-mutt-growl-42-b-ef1caab1-0-2443.ogg"],
  vampire: ["dark-spell-life-tap-03-dd1d0dd1-0-2754.ogg"],
  "blood-countess": ["dark-spell-life-tap-03-dd1d0dd1-0-2754.ogg"],
  "ice-wraith": ["ice-throw-1.ogg"],
  brawler: ["gut-kick.ogg"],
  "stone-golem": ["weapon-impact-parry-01-1b12234a-0-922.ogg"],
  "earth-elemental": ["ground-impact-large-falling-rocks-various-04-2f578e6a-0-5305.ogg"],
  "stone-titan": ["ground-impact-large-falling-rocks-various-04-2f578e6a-0-5305.ogg"],
};

export const battleEventSounds = {
  enemyHit: "hand-to-hand-combat-body-hits-deep-punch-02-2265fdc2-0-208.ogg",
  playerHit: "punch-3.ogg",
  blockAbsorb: "weapon-impact-parry-01-1b12234a-0-922.ogg",
  critHit: "sword-clash-02-57d075a4-0-267.ogg",
  stunProc: "gut-kick.ogg",
  freezeProc: "magic-ice-whoosh-ice-bloc-debris-01-2eb4176c-0-2352.ogg",
  burnTick: "fireball-02-e587c4fa-0-3000.ogg",
  poisonTick: "squelching-4.ogg",
  bleedTick: "monster-bite-3-7193d1d8-0-1339.ogg",
  playerHeal: "buff-pickup-1.ogg",
  consumeCard: "card-fan.ogg",
  drawCards: "card-draw-1.ogg",
  drawTransfer: "card-draw-2.ogg",
  endTurn: "toggle-off.ogg",
  wishAppear: "harpsichord-mystery.ogg",
  gainGold: "coins-gather-quick.ogg",
  deathsDoor: "horror-sting.ogg",
  sliceDeath: "sword-slice.ogg",
  dodge: "hkap2-spin-whoosh-2a-261f31e9-0-608.ogg",
  armorChange: "heavy-armor-block-01-a169e2a5-0-2000.ogg",
  forgeGain: "ilmarinen-blacksmith-forge-hammer-anvil-strik-0f11505a-0-432.ogg",
  wildfire: "fireball-1.ogg",
  shatter: "ice-impact-debris-heavy-single-fienup-015-sis-3d39507f-0-1413.ogg",
  haste: "texture-whoosh-02-fast-02-1c520254-0-835.ogg",
} as const satisfies Record<string, SoundCue>;

export const uiSounds = {
  gearMove: "clothing-movement-01-786d2b95-0-1572.ogg",
  cardHover: null,
  cardDrag: "whoosh-1.ogg",
  screenTransition: null,
  toggleOn: "button-assorted-03-fc496fdd-0-359.ogg",
  toggleOff: "switch-03-297909c3-0-640.ogg",
  error: "denied-03.ogg",
  shopBuy: "coins-drop-carpet-06-396f065a-0-650.ogg",
  shopRefresh: "card-fan.ogg",
  shopRemove: null,
  campfireRest: "fire-lighting.ogg",
  alchemistMix: "liquids-gingerbeer-pour-plop-gurgling-fizzy-e-79e9e572-0-4000.ogg",
  talentUnlock: "music-box-chime-positive.ogg",
  collectionPage: null,
  musicBoxMystery: "music-box-mystery.ogg",
  packOpen: "card-fan.ogg",
  salvage: "mine-2.ogg",
  navigate: "button-assorted-03-fc496fdd-0-359.ogg",
  pause: "button-assorted-03-fc496fdd-0-359.ogg",
  selection: "button-assorted-03-fc496fdd-0-359.ogg",
  newRun: "harpsichord-chime-positive-f88163a6-0-1144.ogg",
  draftSelect: "card-draw-1.ogg",
  draftComplete: "harpsichord-chime-positive-f88163a6-0-1144.ogg",
  resumeRun: "button-assorted-03-fc496fdd-0-359.ogg",
  destructiveConfirm: "harpsichord-negative-quick-fd60821c-0-1146.ogg",
  campBrew: "liquids-gingerbeer-pour-plop-gurgling-fizzy-e-79e9e572-0-4000.ogg",
  transmuteSelect: "card-draw-1.ogg",
  corruptSelect: "card-draw-1.ogg",
  shopSelect: "button-assorted-03-fc496fdd-0-359.ogg",
  mapNode: "button-assorted-03-fc496fdd-0-359.ogg",
  bond: "grand-piano-chime-positive-e36bc9a2-0-979.ogg",
  craft: "ilmarinen-blacksmith-forge-hammer-anvil-strik-0f11505a-0-432.ogg",
} as const satisfies Record<string, SoundCue>;

export const stingerSounds = {
  victory: "harpsichord-level-complete.ogg",
  defeat: "harpsichord-defeated.ogg",
  runVictory: "music-box-level-complete-062b379c-0-4197.ogg",
} as const satisfies Record<string, SoundCue>;

export const screenAmbienceSounds = {
  campfire: "burning-house-t4-fire-low-intensity-with-crac-69b70331-0-12000.ogg",
  "labyrinth-map": "atmo-eerie-cave-water-drips-emptyness-howling-f2038732-0-12000.ogg",
  mystery: "atmo-eerie-cave-water-drips-emptyness-howling-f2038732-0-12000.ogg",
} as const satisfies Partial<Record<Screen, string>>;

export type UISound = keyof typeof uiSounds;

export function getCardSounds(cardId: string): readonly string[] {
  return cardSounds[isMixedPotionCard({ id: cardId }) ? MIXED_POTION_CARD_ID : cardId] ?? [];
}

export function allRegisteredSoundFiles(): string[] {
  return [
    ...new Set(
      [
        ...Object.values(cardSounds).flat(),
        ...Object.values(enemyAttackSounds).flat(),
        ...Object.values(battleEventSounds),
        ...Object.values(uiSounds),
        ...Object.values(stingerSounds),
        ...Object.values(screenAmbienceSounds),
      ].filter((name): name is string => typeof name === "string"),
    ),
  ];
}
