import { talent } from "../talent-builder";
import { addEffect, setEffect } from "../types";

export const archeryTalents = [
  talent(
    "archery-damage",
    "archery",
    "Arrow Dance",
    "When you Dodge, your next Archery card is free",
    "Move",
    setEffect("nextArcheryCardFreeOnDodge", true),
  ),
  talent(
    "archery-hail",
    "archery",
    "Follow-through",
    "Archery cards deal 1 additional Physical damage if your previous card this turn was Archery",
    "CloudRain",
    setEffect("consecutiveArcheryPhysicalDamage", 1),
  ),
  talent(
    "archery-eagle-eye",
    "archery",
    "Eagle Eye",
    "When you play an Archery card against a Stunned enemy, draw a card",
    "Eye",
    setEffect("drawOnArcheryVsStunned", 1),
  ),
  talent(
    "archery-hawk-eye",
    "archery",
    "Hawk Eye",
    "Freezing empowers your next Archery hit with 4 additional Holy damage",
    "ScanEye",
    setEffect("archeryHolyDamageVsFrozen", 4),
  ),
  talent(
    "archery-longshot",
    "archery",
    "Longshot",
    "Archery cards deal double damage against enemies at full Health",
    "ArrowRight",
    setEffect("archeryDoubledVsHighHealth", true),
  ),
  talent(
    "archery-piercing-shot",
    "archery",
    "Piercing Shot",
    "Archery cards ignore 1 Armor",
    "Aperture",
    addEffect("archeryArmorPiercing", 1),
  ),
  talent(
    "archery-quickdraw",
    "archery",
    "Quickdraw",
    "Archery cards deal 1 additional Physical damage while you have no Block",
    "Zap",
    setEffect("archeryPhysicalWithoutBlock", 1),
  ),
  talent(
    "archery-kill-shot",
    "archery",
    "Kill Shot",
    "Archery cards deal double damage against enemies below 20% Health",
    "Crosshair",
    setEffect("archeryDoubledVsLowHealth", true),
  ),
  talent(
    "archery-broadhead",
    "archery",
    "Broadhead",
    "Archery hits have a 10% chance to deal a quarter of their damage as Bleed damage",
    "Diamond",
    setEffect("archeryBleedDamageChance", 10),
  ),
  talent(
    "archery-trophy-shot",
    "archery",
    "Trophy Shot",
    "Gain 2 Gold when an Archery card defeats an enemy",
    "Award",
    setEffect("goldOnArcheryKill", 2),
  ),
];
