import { talent } from "../talent-builder";
import { addEffect, setEffect } from "../types";

export const armorTalents = [
  talent(
    "armor-desperate-double",
    "armor",
    "Last Stand",
    "Gain 25% more Armor while below half Health",
    "HeartCrack",
    setEffect("armorLowHealthBonusPercent", 25),
  ),
  talent(
    "armor-block-burst",
    "armor",
    "Armored Surge",
    "Gain 4 Block when your Armor reaches that amount",
    "Shield",
    setEffect("armorBlockThreshold", 4),
    setEffect("armorBlockAmount", 4),
  ),
  talent(
    "armor-burn-mitigate",
    "armor",
    "Fireward",
    "Armor mitigates Burn damage taken",
    "Flame",
    setEffect("armorMitigatesBurn", true),
  ),
  talent(
    "armor-break-block",
    "armor",
    "Reactive Guard",
    "When Armor breaks, gain 3 Block",
    "ShieldPlus",
    setEffect("armorBreakBlock", 3),
  ),
  talent(
    "armor-start-combat",
    "armor",
    "Bulwark",
    "Start each combat with 2 Armor",
    "Square",
    setEffect("startArmor", 2),
  ),
  talent(
    "armor-mitigate-bleed",
    "armor",
    "Thick Hide",
    "Armor mitigates Bleed damage taken",
    "Hexagon",
    setEffect("armorMitigatesBleed", true),
  ),
  talent(
    "armor-first-double",
    "armor",
    "Iron Guard",
    "When you play an Armor card, gain 1 Block",
    "Lock",
    setEffect("blockOnArmorCard", 1),
  ),
  talent(
    "armor-mitigate-stun",
    "armor",
    "Steadfast",
    "When your Health falls below half, gain 3 Armor",
    "Anchor",
    setEffect("healthThresholdArmor", [{ threshold: 50, amount: 3 }]),
  ),
  talent(
    "armor-cleanse-threshold",
    "armor",
    "Purification",
    "When you reach 6 Armor, cleanse all harmful status effects",
    "Sparkles",
    setEffect("armorCleanseThreshold", 6),
  ),
  talent(
    "armor-flat-bonus",
    "armor",
    "Reinforced",
    "Increase Armor gained by 1",
    "Plus",
    addEffect("flatArmorAmount", 1),
  ),
];
