import { talent } from "../talent-builder";
import { addEffect, setEffect } from "../types";

export const blockTalents = [
  talent(
    "block-depleted-heal",
    "block",
    "Second Wind",
    "When Block is depleted, restore 2 Health",
    "Wind",
    setEffect("blockDepletedHeal", 2),
  ),
  talent(
    "block-absorb-physical",
    "block",
    "Reinforce",
    "Block absorbs 10% more Physical damage",
    "ShieldCheck",
    setEffect("blockAbsorbPhysicalBonus", 10),
  ),
  talent(
    "block-to-holy",
    "block",
    "Sacred Shield",
    "Holy damage is increased by 10% of your Block",
    "Sun",
    setEffect("blockHolyDamagePercent", 10),
  ),
  talent(
    "block-to-stun",
    "block",
    "Impact Guard",
    "Stun damage is increased by 10% of your Block",
    "Zap",
    setEffect("blockStunDamagePercent", 10),
  ),
  talent(
    "block-prevent-stun",
    "block",
    "Grounding",
    "While you have Block, prevent Stun buildup",
    "Anchor",
    setEffect("blockPreventsStun", true),
  ),
  talent(
    "block-to-physical",
    "block",
    "Weighted Guard",
    "Physical damage is increased by 10% of your Block",
    "Weight",
    addEffect("blockToPhysicalDamageMultiplier", 0.1),
  ),
  talent(
    "block-reduce-burn",
    "block",
    "Sun-Struck Shield",
    "When attacks deplete your Block, reflect 30% lost as Holy damage",
    "Flame",
    setEffect("holyReflectionBlockLostPercent", 30),
  ),
  talent(
    "block-start",
    "block",
    "Footwork",
    "When you Dodge, gain Block equal to half the dodged attack",
    "ChevronsUp",
    setEffect("dodgeBlockPercent", 50),
  ),
  talent(
    "block-prevent-bleed",
    "block",
    "Coagulate",
    "While you have Block, prevent Bleed buildup",
    "Droplets",
    setEffect("blockPreventsBleed", true),
  ),
  talent(
    "block-prevent-poison",
    "block",
    "Detoxify",
    "While you have Block, prevent Poison buildup",
    "FlaskConical",
    setEffect("blockPreventsPoison", true),
  ),
];
