import { talent } from "../talent-builder";
import { addEffect, setEffect } from "../types";

export const burnTalents = [
  talent(
    "burn-dmg-1",
    "burn",
    "Flashpoint",
    "Increase Burn damage by 1",
    "Thermometer",
    addEffect("flatBurnDamage", 1),
  ),
  talent(
    "burn-dmg-2",
    "burn",
    "Thermal Vent",
    "When you play a Burn card, gain 1 Forge",
    "WavesArrowUp",
    addEffect("forgeOnBurnCard", 1),
  ),
  talent(
    "burn-dmg-5",
    "burn",
    "Smoke Screen",
    "When you Dodge a Burning enemy, deal 2 Burn damage",
    "Shield",
    setEffect("burnOnDodgeBurning", 2),
  ),
  talent(
    "burn-dmg-4",
    "burn",
    "Combustible",
    "When you Consume a card, detonate the enemy’s Burn",
    "Bomb",
    setEffect("consumeDetonatesBurn", true),
  ),
  talent(
    "burn-first-double",
    "burn",
    "Wildfire",
    "When you play a Burn card, remove 1 Poison from yourself; if you do, deal 1 Poison damage",
    "TrendingUp",
    setEffect("cleansePoisonOnBurnCard", 1),
  ),
  talent(
    "burn-remove-armor",
    "burn",
    "Melting Point",
    "Burn hits remove enemy Armor equal to the damage dealt",
    "Droplets",
    setEffect("burnRemovesEnemyArmor", true),
  ),
  talent(
    "burn-dmg-3",
    "burn",
    "Heat Exhaustion",
    "Burn hits have a 10% chance to deal Stun damage equal to their damage",
    "TrendingDown",
    setEffect("burnStunChance", 10),
  ),
  talent(
    "burn-dmg-6",
    "burn",
    "Burning Wish",
    "When you Wish, deal 1 Burn damage to the enemy",
    "Sparkles",
    setEffect("burnOnWish", 1),
  ),
  talent(
    "burn-double-chance",
    "burn",
    "Smoldering",
    "Burn stacks have a 10% chance to not decay",
    "Wind",
    setEffect("burnPreventDecayChance", 10),
  ),
  talent(
    "burn-half-damage",
    "burn",
    "Fire Resistance",
    "Take half Burn damage",
    "ShieldCheck",
    setEffect("receiveHalfBurnDamage", true),
  ),
];
