import { talent } from "../talent-builder";
import { addEffect, setEffect } from "../types";

export const companionTalents = [
  talent(
    "companion-damage",
    "companion",
    "Feral Strength",
    "Increase Companion damage by 1",
    "Bone",
    addEffect("companionDamage", 1),
  ),
  talent(
    "companion-gold-find",
    "companion",
    "Fetch",
    "Win a combat with a Companion to gain 3 additional Gold",
    "Trash",
    setEffect("companionVictoryGold", 3),
  ),
  talent(
    "companion-leech",
    "companion",
    "Leech Companion",
    "Companions have a 10% chance to Leech",
    "HeartPulse",
    setEffect("companionLeechChance", 10),
  ),
  talent(
    "companion-hunters-bond",
    "companion",
    "Hunter's Bond",
    "When you play a Companion card, draw a card",
    "Link2",
    setEffect("drawOnCompanionCard", 1),
  ),
  talent(
    "companion-predator-instinct",
    "companion",
    "Predator's Instinct",
    "Companions deal double damage against enemies below 30% Health",
    "Eye",
    setEffect("companionDoubledVsLowHealth", true),
  ),
  talent(
    "companion-tame",
    "companion",
    "Coordinated Strike",
    "When you play a Physical card, your Companion’s next attack deals 1 additional damage",
    "Hand",
    setEffect("companionNextAttackOnPhysical", 1),
  ),
  talent(
    "companion-loyal",
    "companion",
    "Pack Weave",
    "When you Dodge, your Companion has a 50% chance to attack",
    "PawPrint",
    setEffect("companionAttacksOnDodge", true),
  ),
  talent(
    "companion-watchdog",
    "companion",
    "Watchdog",
    "When your Block is depleted while you're below half Health, your Companion attacks",
    "ShieldAlert",
    setEffect("companionAttackOnBlockDepletedBelowHalf", true),
  ),
  talent(
    "companion-takedown",
    "companion",
    "Takedown",
    "Companion attacks have a 10% chance to deal Stun damage equal to their damage",
    "Ban",
    setEffect("companionStunChance", 10),
  ),
  talent(
    "companion-whistle",
    "companion",
    "Whistle",
    "After you play a Companion card, your active Companion acts immediately",
    "Bell",
    setEffect("companionActsOnCard", true),
  ),
];
