import { talent } from "../talent-builder";
import { addEffect, setEffect } from "../types";

export const consumeTalents = [
  talent(
    "consume-gourmand",
    "consume",
    "Gourmand",
    "Consume cards restore 20% more Health",
    "Apple",
    setEffect("consumeHealMultiplier", 0.2),
  ),
  talent(
    "consume-last-supper",
    "consume",
    "Last Supper",
    "When you Consume your last card in hand, gain 3 Forge",
    "Gift",
    setEffect("forgeOnConsume", 3),
  ),
  talent(
    "consume-volatility",
    "consume",
    "Volatility",
    "Consume cards deal 20% more damage",
    "Flame",
    setEffect("consumeDamageBonusPercent", 20),
  ),
  talent(
    "consume-distillation",
    "consume",
    "Distillation",
    "Consumed Potions are 20% more potent",
    "FlaskConical",
    addEffect("potionPotency", 0.2),
  ),
  talent(
    "consume-brewmaster",
    "consume",
    "Brewmaster",
    "Consumed Mixed Potions have +1 potency",
    "Wine",
    addEffect("potionMixPotency", 1),
  ),
  talent(
    "consume-aftertaste",
    "consume",
    "Aftertaste",
    "When you Consume a card, restore 1 Health",
    "Cookie",
    setEffect("healOnConsume", 1),
  ),
  talent(
    "consume-leftovers",
    "consume",
    "Leftovers",
    "Consuming a card has a 25% chance to grant 4 Gold",
    "Package",
    setEffect("goldOnConsume", 4),
  ),
  talent(
    "consume-second-helping",
    "consume",
    "Second Helping",
    "When you Consume a card, draw a card",
    "CopyPlus",
    setEffect("uncappedDrawOnConsume", 1),
  ),
  talent(
    "consume-rotgut",
    "consume",
    "Rotgut",
    "Your Poison Potions deal 2 additional Poison damage",
    "FlaskRound",
    setEffect("poisonDamageOnConsume", 2),
  ),
  talent(
    "consume-feast",
    "consume",
    "Feast",
    "When a healing Potion brings you to full Health, gain 4 Block",
    "CookingPot",
    setEffect("blockOnConsume", 4),
  ),
];
