import { talent } from "../talent-builder";
import { addEffect, setEffect } from "../types";

export const forgeTalents = [
  talent(
    "forge-to-burn",
    "forge",
    "Ignite",
    "Half your Forge also increases Burn damage",
    "Flame",
    setEffect("forgeBurnDamagePercent", 50),
  ),
  talent(
    "forge-to-holy",
    "forge",
    "Sanctify",
    "Half your Forge also increases Holy damage",
    "Sun",
    setEffect("forgeHolyDamagePercent", 50),
  ),
  talent(
    "forge-to-block",
    "forge",
    "Tempered Guard",
    "Half your Forge also increases Block amount",
    "Shield",
    setEffect("forgeBlockPercent", 50),
  ),
  talent(
    "forge-burn-burst",
    "forge",
    "Overheat",
    "Deal 4 Burn damage when your Forge reaches that amount",
    "Thermometer",
    setEffect("forgeBurnThreshold", 4),
    setEffect("forgeBurnDamage", 4),
  ),
  talent(
    "forge-strength-1",
    "forge",
    "Forge Mastery",
    "Start each combat with 1 Forge",
    "FlameKindling",
    setEffect("startForge", 1),
  ),
  talent(
    "forge-strength-2",
    "forge",
    "Rust",
    "Half your Forge also increases Bleed damage",
    "Eraser",
    setEffect("forgeBleedDamagePercent", 50),
  ),
  talent(
    "forge-strength-3",
    "forge",
    "Sunder",
    "When you reach 6 Forge, remove all enemy Armor",
    "ShieldOff",
    setEffect("forgeStripArmorThreshold", 6),
  ),
  talent(
    "forge-strength-4",
    "forge",
    "Intensify",
    "Increase Forge gained by 1",
    "ChevronsUp",
    addEffect("flatForgeGained", 1),
  ),
  talent(
    "forge-strength-5",
    "forge",
    "Desperate Forge",
    "Gain 25% more Forge while below half Health",
    "HeartCrack",
    setEffect("forgeLowHealthBonusPercent", 25),
  ),
  talent(
    "forge-strength-6",
    "forge",
    "Forged Bulwark",
    "Gain 6 Block when your Forge reaches that amount",
    "Castle",
    setEffect("forgeBlockThreshold", 6),
    setEffect("forgeBlockAmount", 6),
  ),
];
