import { talent } from "../talent-builder";
import { setEffect } from "../types";

export const freezeTalents = [
  talent(
    "freeze-threshold",
    "freeze",
    "Bitter Cold",
    "Freeze threshold reduced by 10%",
    "ThermometerSnowflake",
    setEffect("freezeThresholdReduction", 0.1),
  ),
  talent(
    "freeze-double-damage",
    "freeze",
    "Shatter",
    "Frozen enemies take double damage",
    "Split",
    setEffect("freezeDoubleDamage", true),
  ),
  talent(
    "freeze-start-amount",
    "freeze",
    "Winter's Grasp",
    "Start each combat by dealing 4 Freeze damage",
    "MountainSnow",
    setEffect("startFreeze", 4),
  ),
  talent(
    "freeze-block-grant",
    "freeze",
    "Icebound",
    "When you Freeze an enemy, remove all its Block; Frozen enemies cannot Dodge",
    "Snowflake",
    setEffect("freezeStripBlock", true),
    setEffect("freezePreventsEnemyDodge", true),
  ),
  talent(
    "freeze-companion-bonus",
    "freeze",
    "Snow Pack",
    "Companion hits against Frozen enemies deal 1 additional Freeze damage",
    "CloudSnow",
    setEffect("companionFreezeDamageVsFrozen", 1),
  ),
  talent(
    "freeze-strip-armor",
    "freeze",
    "Brittle Armor",
    "When you Freeze an enemy, remove all its Armor",
    "ShieldOff",
    setEffect("freezeStripArmor", true),
  ),
  talent(
    "freeze-half-damage",
    "freeze",
    "Cold Resistance",
    "Take half Freeze damage",
    "Thermometer",
    setEffect("receiveHalfFreezeDamage", true),
  ),
  talent(
    "freeze-poison-preserve",
    "freeze",
    "Cryo-preservation",
    "Poison stacks on Frozen enemies cannot decay",
    "FlaskConical",
    setEffect("freezePreventsPoisonDecay", true),
  ),
  talent(
    "freeze-prevent-scaling",
    "freeze",
    "Thaw Dividend",
    "When an enemy recovers from Freeze, draw a card",
    "Hexagon",
    setEffect("drawOnThaw", 1),
  ),
  talent(
    "freeze-block-healing",
    "freeze",
    "Glacial Barrier",
    "When you Freeze an enemy, gain 3 Block",
    "Lock",
    setEffect("blockOnFreeze", 3),
  ),
];
