import { talent } from "../talent-builder";
import { setEffect } from "../types";

export const goldTalents = [
  talent(
    "gold-shop-discount",
    "gold",
    "Haggle",
    "Shop purchases cost 5 less Gold",
    "Tag",
    setEffect("shopCardDiscount", 5),
  ),
  talent(
    "gold-shop-refresh",
    "gold",
    "Restock",
    "Shop refreshes have a 10% chance to be free, once per shop",
    "RefreshCw",
    setEffect("shopFreeRefreshChance", 10),
  ),
  talent(
    "gold-start",
    "gold",
    "Seed Money",
    "Dealing Nature damage has a 10% chance to also grant Gold",
    "Sprout",
    setEffect("goldOnNatureDamageChance", 10),
  ),
  talent(
    "gold-per-combat",
    "gold",
    "Lucky Foot",
    "When you Dodge, you have a 25% chance to gain 4 Gold",
    "CircleDollarSign",
    setEffect("goldOnDodge", 4),
  ),
  talent(
    "gold-potion-discount",
    "gold",
    "Apothecary Membership",
    "Potion purchases cost 5 less Gold",
    "Beaker",
    setEffect("potionDiscount", 5),
  ),
  talent(
    "gold-remove-discount",
    "gold",
    "Buyout",
    "Card removal costs 10 less Gold",
    "ShoppingCart",
    setEffect("removeCardDiscount", 10),
  ),
  talent(
    "gold-enemy-drop",
    "gold",
    "Plunder",
    "Enemies drop 10% more Gold",
    "HandCoins",
    setEffect("enemyGoldDropBonus", 0.1),
  ),
  talent(
    "gold-on-wish",
    "gold",
    "Golden Wish",
    "10% chance to gain 7 Gold when you Wish",
    "Sparkles",
    setEffect("goldOnWish", 7),
    setEffect("goldOnWishChance", 10),
  ),
  talent(
    "gold-mix-discount",
    "gold",
    "Alchemy Discount",
    "Mixing Potions costs 10 less Gold",
    "FlaskConical",
    setEffect("mixPotionDiscount", 10),
  ),
  talent(
    "gold-elite-drop",
    "gold",
    "Coinmail",
    "Gaining Armor has a 10% chance to also grant Gold",
    "Trophy",
    setEffect("goldOnArmorGainChance", 10),
  ),
];
