import { talent } from "../talent-builder";
import { setEffect } from "../types";

export const healthTalents = [
  talent(
    "health-threshold-armor",
    "health",
    "Last Resort",
    "When your Health falls below 25%, cleanse all harmful status effects",
    "HeartCrack",
    setEffect("cleanseBelowHealthPercent", 25),
  ),
  talent(
    "health-threshold-block",
    "health",
    "Desperate Guard",
    "When your Health falls below half, gain 4 Block",
    "Shield",
    setEffect("healthThresholdBlock", { threshold: 50, amount: 4 }),
  ),
  talent(
    "health-max-4",
    "health",
    "Will to Live",
    "Death's Door leaves you at 1 Health and lasts 1 turn longer",
    "Activity",
    setEffect("deathsDoorExtension", 1),
  ),
  talent(
    "health-start",
    "health",
    "Combat Surge",
    "Restore 4 Health at the start of combat",
    "ChevronsUp",
    setEffect("startHealth", 4),
  ),
  talent(
    "health-max-per-combat",
    "health",
    "Vitality",
    "Gain 1 maximum Health after every combat",
    "TrendingUp",
    setEffect("maxHealthPerCombat", 1),
  ),
  talent(
    "health-heal-boost",
    "health",
    "Mending",
    "Health restored is increased by 10%",
    "HeartPulse",
    setEffect("healMultiplier", 1.1),
  ),
  talent(
    "health-max-1",
    "health",
    "Overflow",
    "Gain 25% of excess healing from cards as Block",
    "Container",
    setEffect("overhealToBlockRatio", 0.25),
  ),
  talent(
    "health-max-2",
    "health",
    "Cleansing Status",
    "Cleansing a harmful status effect restores 2 Health",
    "Sparkles",
    setEffect("healOnStatusCleanse", 2),
  ),
  talent(
    "health-max-3",
    "health",
    "Last Gasp",
    "While below half Health, gain 10% Dodge chance",
    "ShieldHalf",
    setEffect("dodgeChanceBelowHalfHealth", 10),
  ),
  talent(
    "health-campfire",
    "health",
    "Clean Slate",
    "When a card restores Health beyond your maximum, cleanse a harmful status effect",
    "Flame",
    setEffect("cleanseOnCardOverheal", true),
  ),
];
