import { talent } from "../talent-builder";
import { setEffect } from "../types";

export const holyTalents = [
  talent(
    "holy-block-scaling",
    "holy",
    "Faith Barrier",
    "Holy damage has a 10% chance to also grant Block",
    "Shield",
    setEffect("holyBlockChance", 10),
  ),
  talent(
    "holy-half-damage",
    "holy",
    "Celestial Ward",
    "Take half Holy damage",
    "ShieldCheck",
    setEffect("receiveHalfHolyDamage", true),
  ),
  talent(
    "holy-vs-burn",
    "holy",
    "Purge",
    "Holy damage is increased by 10% against Burning enemies",
    "Eraser",
    setEffect("holyVsBurnMultiplier", 10),
  ),
  talent(
    "holy-first-free",
    "holy",
    "Divine Favor",
    "When you cleanse a harmful status effect, your next Holy card is free",
    "Gift",
    setEffect("nextHolyFreeOnCleanse", true),
  ),
  talent(
    "holy-gold-scaling",
    "holy",
    "Prosperity",
    "Holy damage is increased by 1% of your Gold",
    "TrendingUp",
    setEffect("holyGoldPercent", 1),
  ),
  talent(
    "holy-burn-chance",
    "holy",
    "Scorching Light",
    "Holy damage has a 10% chance to also deal Burn damage",
    "Flame",
    setEffect("holyBurnDamageChance", 10),
  ),
  talent(
    "holy-tithe",
    "holy",
    "Tithe",
    "Holy damage has a 10% chance to also grant Gold",
    "Cross",
    setEffect("holyGoldChance", 10),
  ),
  talent(
    "holy-block-grant",
    "holy",
    "Radiant Guard",
    "Gaining Block has a 10% chance to draw a Holy card",
    "ShieldPlus",
    setEffect("drawHolyOnBlockChance", 10),
  ),
  talent(
    "holy-lifesteal",
    "holy",
    "Blessed Leech",
    "Holy damage gains Leech while you're below half Health",
    "HeartPulse",
    setEffect("holyLifestealPercent", 50),
  ),
  talent(
    "holy-wish-chance",
    "holy",
    "Divine Intervention",
    "Holy damage has a 10% chance to Wish",
    "Sparkles",
    setEffect("holyWishChance", 10),
  ),
];
