import { talent } from "../talent-builder";
import { setEffect } from "../types";

export const holyTalents = [
  talent(
    "holy-block-scaling",
    "holy",
    "Faith Barrier",
    "When you play a Holy card, gain 1 Block",
    "Shield",
    setEffect("blockOnHolyCard", 1),
  ),
  talent(
    "holy-half-damage",
    "holy",
    "Celestial Ward",
    "Take half Holy damage",
    "ShieldCheck",
    setEffect("receiveHalfHolyDamage", true),
  ),
  talent(
    "holy-vs-burn",
    "holy",
    "Purge",
    "Holy damage is increased by 10% against Burning enemies",
    "Eraser",
    setEffect("holyVsBurnMultiplier", 10),
  ),
  talent(
    "holy-first-free",
    "holy",
    "Divine Favor",
    "When you cleanse a harmful status effect, your next Holy card is free",
    "Gift",
    setEffect("nextHolyFreeOnCleanse", true),
  ),
  talent(
    "holy-gold-scaling",
    "holy",
    "Prosperity",
    "Holy damage is increased by 1% of your Gold",
    "TrendingUp",
    setEffect("holyGoldPercent", 1),
  ),
  talent(
    "holy-burn-chance",
    "holy",
    "Scorching Light",
    "Holy hits have a 10% chance to deal half their damage as Burn damage",
    "Flame",
    setEffect("holyBurnDamageChance", 10),
  ),
  talent(
    "holy-tithe",
    "holy",
    "Tithe",
    "10% chance to gain Gold equal to Holy damage",
    "Cross",
    setEffect("holyGoldChance", 10),
  ),
  talent(
    "holy-block-grant",
    "holy",
    "Radiant Guard",
    "At full Health, gain Block equal to 15% of Holy damage",
    "ShieldPlus",
    setEffect("holyBlockPercentFromDamage", 15),
  ),
  talent(
    "holy-lifesteal",
    "holy",
    "Blessed Leech",
    "Below half Health, restore Health equal to 15% of Holy damage",
    "HeartPulse",
    setEffect("holyLifestealPercent", 15),
  ),
  talent(
    "holy-wish-chance",
    "holy",
    "Divine Intervention",
    "After you play a Holy card, your next Wish offers 1 additional card choice",
    "Sparkles",
    setEffect("wishExtraChoiceAfterHolyCard", true),
  ),
];
