import { talent } from "../talent-builder";
import { setEffect } from "../types";

export const leechTalents = [
  talent(
    "leech-first-double",
    "leech",
    "Deep Siphon",
    "Leech from your cards restores 10% more Health",
    "Sword",
    setEffect("cardLeechBonusPercent", 10),
  ),
  talent(
    "leech-blood-debt",
    "leech",
    "Blood Debt",
    "Leech restores an additional Health per 16 missing Health",
    "CircleDollarSign",
    setEffect("leechMissingHealthStep", 16),
  ),
  talent(
    "leech-nature-chance",
    "leech",
    "Affliction Siphon",
    "Leech restores 10% more Health against Poisoned or Bleeding enemies",
    "Utensils",
    setEffect("afflictionLeechBonusPercent", 10),
  ),
  talent(
    "leech-desperate",
    "leech",
    "Desperate Siphon",
    "While below half Health, Leech also grants Block equal to a quarter of the Health restored",
    "HeartCrack",
    setEffect("leechBlockBelowHalfPercent", 25),
  ),
  talent(
    "leech-cull-weak",
    "leech",
    "Cull the Weak",
    "Leech cards deal 25% more damage against enemies below half Health",
    "Skull",
    setEffect("leechCardDamageVsLowHealthPercent", 25),
  ),
  talent(
    "leech-block-enemy",
    "leech",
    "Sanguine Overflow",
    "When Leech fills your Health, your next attack deals 2 additional Physical damage",
    "Hash",
    setEffect("nextAttackPhysicalOnLeechToFull", 2),
  ),
  talent(
    "leech-bleed-chance",
    "leech",
    "Bloodletting",
    "Leech hits have a 10% chance to deal a quarter of their damage as Bleed damage",
    "Droplets",
    setEffect("leechBleedDamageChance", 10),
  ),
  talent(
    "leech-mana-siphon",
    "leech",
    "Mana Siphon",
    "Leech has a 10% chance to gain 1 Mana",
    "Gem",
    setEffect("manaOnLeechChance", 10),
  ),
  talent(
    "leech-trinket-siphon",
    "leech",
    "Armor Siphon",
    "Your Leech cards steal 1 Armor before their effects resolve",
    "Wrench",
    setEffect("armorStealOnLeechCard", 1),
  ),
  talent(
    "leech-poison",
    "leech",
    "Virulent Leech",
    "Leech hits have a 10% chance to deal half their damage as Poison damage",
    "FlaskConical",
    setEffect("leechPoisonDamageChance", 10),
  ),
];
