import { talent } from "../talent-builder";
import { addEffect, setEffect } from "../types";

export const natureTalents = [
  talent(
    "nature-overgrowth",
    "nature",
    "Overgrowth",
    "Nature cards have a 10% chance to play twice",
    "TrendingUp",
    setEffect("natureCardPlayTwiceChance", 10),
  ),
  talent(
    "nature-thornskin",
    "nature",
    "Thornskin",
    "Nature damage has a 10% chance to also grant Armor",
    "Hexagon",
    setEffect("armorOnNatureDamageChance", 10),
  ),
  talent(
    "nature-natural-armor",
    "nature",
    "Bramblegrowth",
    "Nature damage has a 10% chance to also grant Thorns",
    "Shield",
    setEffect("thornsOnNatureDamageChance", 10),
  ),
  talent(
    "nature-photosynthesis",
    "nature",
    "Photosynthesis",
    "Nature damage has a 10% chance to also restore Health",
    "Leaf",
    setEffect("healOnNatureDamageChance", 10),
  ),
  talent(
    "nature-canopy",
    "nature",
    "Windstep",
    "When you Dodge, your next Nature card is free",
    "Feather",
    setEffect("nextNatureCardFreeOnDodge", true),
  ),
  talent(
    "nature-briar-patch",
    "nature",
    "Briar Patch",
    "Nature damage has a 10% chance to also Bleed",
    "Triangle",
    setEffect("natureBleedChance", 10),
  ),
  talent(
    "nature-toxic-pollen",
    "nature",
    "Toxic Pollen",
    "Nature damage has a 10% chance to also Poison",
    "Wind",
    setEffect("naturePoisonChance", 10),
  ),
  talent(
    "nature-verdant-cycle",
    "nature",
    "Verdant Cycle",
    "Nature damage has a 10% chance to Leech",
    "RotateCw",
    addEffect("natureLeechChance", 10),
  ),
  talent(
    "nature-ecosystem",
    "nature",
    "Ecosystem",
    "Draw a Nature card at the start of combat",
    "Network",
    setEffect("drawNatureCardAtCombatStart", true),
  ),
  talent(
    "nature-entangle",
    "nature",
    "Entangle",
    "Nature damage has a 10% chance to also Stun",
    "Link",
    setEffect("natureStunChance", 10),
  ),
];
