import { talent } from "../talent-builder";
import { addEffect, setEffect } from "../types";

export const natureTalents = [
  talent(
    "nature-overgrowth",
    "nature",
    "Overgrowth",
    "Increase Nature damage by 1",
    "TrendingUp",
    addEffect("flatNatureDamage", 1),
  ),
  talent(
    "nature-thornskin",
    "nature",
    "Thornskin",
    "Nature damage is increased by a quarter of your Armor",
    "Hexagon",
    setEffect("armorNatureDamagePercent", 25),
  ),
  talent(
    "nature-natural-armor",
    "nature",
    "Bramblegrowth",
    "When you play a Nature card, gain 1 Thorns",
    "Shield",
    setEffect("thornsOnNatureCard", 1),
  ),
  talent(
    "nature-photosynthesis",
    "nature",
    "Photosynthesis",
    "Restore 1 Health when you play a Nature card",
    "Leaf",
    setEffect("healOnNatureCard", 1),
  ),
  talent(
    "nature-canopy",
    "nature",
    "Windstep",
    "When you Dodge, your next Nature card is free",
    "Feather",
    setEffect("nextNatureCardFreeOnDodge", true),
  ),
  talent(
    "nature-briar-patch",
    "nature",
    "Briar Patch",
    "Physical cards deal 2 additional Bleed damage if your previous card this turn was Nature",
    "Triangle",
    setEffect("physicalAfterNatureBleedDamage", 2),
  ),
  talent(
    "nature-toxic-pollen",
    "nature",
    "Toxic Pollen",
    "Nature hits have a 10% chance to deal half their damage as Poison damage",
    "Wind",
    setEffect("naturePoisonDamageChance", 10),
  ),
  talent(
    "nature-verdant-cycle",
    "nature",
    "Verdant Cycle",
    "Nature damage has a 10% chance to Leech",
    "RotateCw",
    addEffect("natureLeechChance", 10),
  ),
  talent(
    "nature-ecosystem",
    "nature",
    "Ecosystem",
    "When you play a Nature card against a Poisoned enemy, deal 1 Poison damage",
    "Network",
    setEffect("poisonOnNatureCardVsPoisoned", 1),
  ),
  talent(
    "nature-entangle",
    "nature",
    "Entangle",
    "Nature hits have a 10% chance to deal Stun damage equal to their damage",
    "Link",
    setEffect("natureStunChance", 10),
  ),
];
