import { talent } from "../talent-builder";
import { setEffect } from "../types";

export const physicalTalents = [
  talent(
    "physical-expert-blacksmith",
    "physical",
    "Expert Blacksmith",
    "Physical damage bonus from Forge is increased by 25%",
    "Anvil",
    setEffect("forgeToPhysicalDamageMultiplier", 1.25),
  ),
  talent(
    "physical-shield-bash",
    "physical",
    "Shield Slam",
    "Physical damage is increased by half your Block",
    "Shield",
    setEffect("blockToPhysicalDamageMultiplier", 0.5),
  ),
  talent(
    "physical-armored-fists",
    "physical",
    "Armored Fists",
    "Physical damage is increased by half your Armor",
    "HandFist",
    setEffect("armorPhysicalDamagePercent", 50),
  ),
  talent(
    "physical-heavy-blows",
    "physical",
    "Heavy Blows",
    "Physical damage has a 10% chance to also Stun",
    "Hammer",
    setEffect("physicalStunChance", 10),
  ),
  talent(
    "physical-finish-him",
    "physical",
    "Finish Him",
    "Physical damage is doubled against enemies below 25% Health",
    "Skull",
    setEffect("physicalDoubledBelowQuarterHealth", true),
  ),
  talent(
    "physical-shatter",
    "physical",
    "Icebreaker",
    "Physical hits against Frozen enemies grant 1 Forge",
    "Split",
    setEffect("forgeOnPhysicalVsFrozen", 1),
  ),
  talent(
    "physical-lacerate",
    "physical",
    "Lacerate",
    "Physical damage has a 10% chance to Bleed",
    "Scissors",
    setEffect("physicalBleedChance", 10),
  ),
  talent(
    "physical-hemorrhage",
    "physical",
    "Rupture",
    "Physical critical hits detonate Bleed",
    "Droplets",
    setEffect("physicalDetonatesBleed", true),
  ),
  talent(
    "physical-brute-force",
    "physical",
    "Riposte",
    "After you Dodge, your next Physical attack is guaranteed to Critical Hit",
    "Swords",
    setEffect("physicalCritOnDodge", true),
  ),
  talent(
    "physical-unrelenting",
    "physical",
    "Unrelenting",
    "Physical damage is doubled while you're below half Health",
    "ShieldCheck",
    setEffect("physicalDoubledBelowHalfHealth", true),
  ),
];
