import { talent } from "../talent-builder";
import { setEffect } from "../types";

export const physicalTalents = [
  talent(
    "physical-expert-blacksmith",
    "physical",
    "Expert Blacksmith",
    "Physical damage bonus from Forge is increased by 25%",
    "Anvil",
    setEffect("forgeToPhysicalDamageMultiplier", 1.25),
  ),
  talent(
    "physical-shield-bash",
    "physical",
    "Shield Slam",
    "Physical attacks reduce enemy Armor by 2 while you have Block",
    "Shield",
    setEffect("physicalStripArmorWhileBlocked", true),
  ),
  talent(
    "physical-armored-fists",
    "physical",
    "Armored Fists",
    "Physical damage is increased by a quarter of your Armor",
    "HandFist",
    setEffect("armorPhysicalDamagePercent", 25),
  ),
  talent(
    "physical-heavy-blows",
    "physical",
    "Heavy Blows",
    "Physical hits have a 10% chance to deal Stun damage equal to their damage",
    "Hammer",
    setEffect("physicalStunChance", 10),
  ),
  talent(
    "physical-finish-him",
    "physical",
    "Finish Him",
    "Physical hits against Stunned enemies Leech",
    "Skull",
    setEffect("physicalLeechVsStunned", true),
  ),
  talent(
    "physical-shatter",
    "physical",
    "Icebreaker",
    "Physical hits against Frozen enemies grant 1 Forge",
    "Split",
    setEffect("forgeOnPhysicalVsFrozen", 1),
  ),
  talent(
    "physical-lacerate",
    "physical",
    "Lacerate",
    "Physical hits have a 10% chance to deal a quarter of their damage as Bleed damage",
    "Scissors",
    setEffect("physicalBleedDamageChance", 10),
  ),
  talent(
    "physical-hemorrhage",
    "physical",
    "Rupture",
    "Physical hits detonate Bleed",
    "Droplets",
    setEffect("physicalDetonatesBleed", true),
  ),
  talent(
    "physical-brute-force",
    "physical",
    "Riposte",
    "When you Dodge, deal Physical damage equal to a quarter of the dodged attack",
    "Swords",
    setEffect("dodgePhysicalDamagePercent", 25),
  ),
  talent(
    "physical-unrelenting",
    "physical",
    "Unrelenting",
    "Deal 50% more Physical damage while below half Health",
    "ShieldCheck",
    setEffect("physicalLowHealthDamageBonusPercent", 50),
  ),
];
