import { talent } from "../talent-builder";
import { setEffect } from "../types";

export const poisonTalents = [
  talent(
    "poison-leech-chance",
    "poison",
    "Hemotoxin",
    "Poison has a 10% chance to Leech",
    "Biohazard",
    setEffect("poisonLeechChance", 10),
  ),
  talent(
    "poison-physical-bonus",
    "poison",
    "Corrosive",
    "Physical hits deal 1 additional damage against Poisoned enemies",
    "Droplets",
    setEffect("poisonPhysicalBonus", 1),
  ),
  talent(
    "poison-strip-armor",
    "poison",
    "Caustic",
    "Poison hits and ticks remove 1 enemy Armor",
    "FlaskRound",
    setEffect("poisonStripArmor", true),
  ),
  talent(
    "poison-half-damage",
    "poison",
    "Toxin Resistance",
    "Take half Poison damage",
    "Shield",
    setEffect("receiveHalfPoisonDamage", true),
  ),
  talent(
    "poison-gold-first",
    "poison",
    "Toxic Profit",
    "Gain 3 additional Gold when you defeat a Poisoned enemy",
    "Coins",
    setEffect("goldOnPoisonedKill", 3),
  ),
  talent(
    "poison-heal-reduce",
    "poison",
    "Necrosis",
    "Poisoned enemies restore half as much Health",
    "Skull",
    setEffect("poisonHalvesHealing", true),
  ),
  talent(
    "poison-stun-chance",
    "poison",
    "Paralytic Venom",
    "Poison hits and ticks have a 10% chance to deal Stun damage equal to their damage",
    "Lock",
    setEffect("poisonStunChance", 10),
  ),
  talent(
    "poison-gain-chance",
    "poison",
    "Virulent",
    "Poison has a 10% chance to gain instead of lose a stack",
    "TrendingUp",
    setEffect("poisonGainChance", 10),
  ),
  talent(
    "poison-reduce-damage",
    "poison",
    "Torpor",
    "Poisoned enemies cannot Dodge",
    "Moon",
    setEffect("poisonPreventsEnemyDodge", true),
  ),
  talent(
    "poison-first-free",
    "poison",
    "Venom Strike",
    "Poison cards deal 1 additional Physical damage against Poisoned enemies",
    "Syringe",
    setEffect("poisonCardPhysicalVsPoisoned", 1),
  ),
];
