import * as assetRefs from "../assets";
import { defineEnemy, poisonResistance, regeneration, trait } from "../compendium-builders";

export const enemyBestiary = [
  defineEnemy({
    id: "forge-golem",
    title: "The Forge Golem",
    art: assetRefs.theForgeGolem,
    enemyType: "boss",
    traits: [
      trait("rusting-carapace", "Stoke the Forge", "Gains 1 Forge every other turn"),
      trait("starting-block", "Sturdy Plating", "Starts with 4 Block"),
    ],
    abilityIds: ["sunder", "bash", "molten-bulwark"],
  }),
  defineEnemy({
    id: "frostwarden",
    title: "The Frostwarden",
    art: assetRefs.theFrostwarden,
    enemyType: "boss",
    traits: [
      trait(
        "glacial-shell",
        "Glacial Surge",
        "Receives half Freeze damage\nReceives 30% more Burn damage\nFreeze damage increases by 1 every other turn",
      ),
    ],
    abilityIds: ["frostbolt", "cold-snap", "glacial-ward"],
  }),
  defineEnemy({
    id: "blight-treant",
    title: "The Blight Treant",
    art: assetRefs.theBlightTreant,
    enemyType: "boss",
    traits: [
      regeneration("Rotting Regrowth"),
      trait("burn-vulnerability", "Burn Vulnerability", "Receives 30% more Burn damage"),
    ],
    abilityIds: ["grasping-vines", "bloodthorn", "briar-shield"],
  }),
  defineEnemy({
    id: "skeleton",
    title: "Skeleton",
    art: assetRefs.skeleton,
    enemyType: "normal",
    traits: [trait("brittle-bones", "Brittle Bones", "Receives double Holy damage\nReceives double Stun damage")],
    abilityIds: ["slash", "bash", "block"],
  }),
  defineEnemy({
    id: "goblin",
    title: "Goblin",
    art: assetRefs.goblin,
    enemyType: "normal",
    traits: [trait("trinket-hoarder", "Trinket Hoarder", "Receives 30% more Burn damage")],
    abilityIds: ["stab", "slash", "block"],
  }),
  defineEnemy({
    id: "mimic",
    title: "Mimic",
    art: assetRefs.mimic,
    enemyType: "elite",
    traits: [trait("gold-trove", "Gold Trove", "Drops Double Gold on Defeat")],
    abilityIds: ["fangs", "bash", "block"],
  }),
  defineEnemy({
    id: "mud-elemental",
    title: "Mud Elemental",
    art: assetRefs.mudElemental,
    enemyType: "elite",
    traits: [regeneration("Regeneration")],
    abilityIds: ["caustic-jab", "grasping-vines", "block"],
  }),
  defineEnemy({
    id: "necromancer",
    title: "Necromancer",
    art: assetRefs.necromancer,
    enemyType: "elite",
    traits: [trait("holy-vulnerability", "Holy Vulnerability", "Receives double Holy damage")],
    abilityIds: ["fangs", "bloodthorn", "rend"],
  }),
  defineEnemy({
    id: "plague-doctor",
    title: "Plague Doctor",
    art: assetRefs.plagueDoctor,
    enemyType: "elite",
    traits: [poisonResistance],
    abilityIds: ["caustic-jab", "venom-fangs", "rend"],
  }),
  defineEnemy({
    id: "living-armor",
    title: "Living Armor",
    art: assetRefs.livingArmor,
    enemyType: "elite",
    traits: [trait("living-armor", "Living Armor", "Starts combat with Armor\nReceives 25% less Bleed damage")],
    abilityIds: ["slash", "shield-bash", "plate-mail"],
  }),
  defineEnemy({
    id: "iron-bear",
    title: "The Iron Bear",
    art: assetRefs.ironBear,
    enemyType: "boss",
    traits: [trait("iron-hide", "Iron Hide", "Gains 1 Armor every other turn")],
    abilityIds: ["maul", "burning-blade", "plate-mail"],
  }),
  defineEnemy({
    id: "fire-elemental",
    title: "Fire Elemental",
    art: assetRefs.fireElemental,
    enemyType: "elite",
    traits: [
      trait("cinder-skin", "Cinder Skin", "Deals 1 Burn damage when attacked\nOnce per turn"),
      trait("freeze-vulnerability", "Freeze Vulnerability", "Receives double Freeze damage"),
    ],
    abilityIds: ["fireball", "cinderbloom", "molten-bulwark"],
  }),
  defineEnemy({
    id: "frost-elemental",
    title: "Frost Elemental",
    art: assetRefs.frostElemental,
    enemyType: "elite",
    traits: [trait("burn-vulnerability", "Burn Vulnerability", "Receives 30% more Burn damage")],
    abilityIds: ["frostbolt", "cold-snap", "glacial-ward"],
  }),
  defineEnemy({
    id: "slime",
    title: "Slime",
    art: assetRefs.slime,
    enemyType: "normal",
    traits: [trait("amorphous", "Amorphous", "Receives 10% less Physical damage\nReceives 10% less Poison damage")],
    abilityIds: ["venom-fangs", "caustic-jab", "block"],
  }),
  defineEnemy({
    id: "will-o-wisp",
    title: "Will-o-Wisp",
    art: assetRefs.willOWisp,
    enemyType: "elite",
    traits: [trait("will-o-wisp", "Will-o-Wisp", "Receives 30% less Physical damage\nReceives 30% less Freeze damage")],
    abilityIds: ["frostbolt", "lightning-bolt", "glacial-ward"],
  }),
  defineEnemy({
    id: "bandit",
    title: "Bandit",
    art: assetRefs.bandit,
    enemyType: "normal",
    traits: [trait("bandit", "Ambush", "Deals double damage on its first attack\nReceives 30% more Holy damage")],
    abilityIds: ["slash", "serrated-edge", "block"],
  }),
  defineEnemy({
    id: "ogre",
    title: "Ogre",
    art: assetRefs.ogre,
    enemyType: "elite",
    traits: [trait("ogre", "Ogre", "Physical attacks deal double damage to Block\nReceives 30% more Holy damage")],
    abilityIds: ["bash", "sunder", "maul"],
  }),
  defineEnemy({
    id: "fire-imp",
    title: "Fire Imp",
    art: assetRefs.fireImp,
    enemyType: "normal",
    traits: [trait("fire-imp", "Cinder Touch", "Attacks inflict 1 additional Burn\nReceives 30% more Freeze damage")],
    abilityIds: ["fireball", "burning-blade", "molten-bulwark"],
  }),
  defineEnemy({
    id: "hellhound",
    title: "Hellhound",
    art: assetRefs.hellhound,
    enemyType: "elite",
    traits: [
      trait(
        "hellhound",
        "Feed the Flames",
        "Deals 25% more damage against Burning heroes\nReceives 30% more Freeze damage",
      ),
    ],
    abilityIds: ["fangs", "burning-blade", "pounce"],
  }),
  defineEnemy({
    id: "pyromancer",
    title: "Pyromancer",
    art: assetRefs.pyromancer,
    enemyType: "elite",
    traits: [trait("pyromancer", "Pyromancer", "Receives 30% more Freeze damage")],
    abilityIds: ["fireball", "cinderbloom", "sunburst"],
  }),
  defineEnemy({
    id: "giant-spider",
    title: "Giant Spider",
    art: assetRefs.giantSpider,
    enemyType: "normal",
    traits: [
      trait("giant-spider", "Venomous Bite", "Attacks inflict 1 additional Poison\nReceives 30% more Burn damage"),
    ],
    abilityIds: ["venom-fangs", "pounce", "caustic-jab"],
  }),
  defineEnemy({
    id: "giant-snake",
    title: "Giant Snake",
    art: assetRefs.giantSnake,
    enemyType: "elite",
    traits: [
      trait(
        "giant-snake",
        "Giant Snake",
        "Poison removes 1 additional Block before Health\nReceives 30% more Freeze damage",
      ),
    ],
    abilityIds: ["venom-fangs", "caustic-jab", "rend"],
  }),
  defineEnemy({
    id: "blood-cultist",
    title: "Blood Cultist",
    art: assetRefs.bloodCultist,
    enemyType: "elite",
    traits: [trait("blood-cultist", "Blood Offering", "Bleed attacks gain Leech\nReceives 30% more Holy damage")],
    abilityIds: ["rend", "serrated-edge", "bloodthorn"],
  }),
  defineEnemy({
    id: "dire-wolf",
    title: "Dire Wolf",
    art: assetRefs.direWolf,
    enemyType: "normal",
    traits: [
      trait(
        "dire-wolf",
        "Scent of Blood",
        "Deals 1 additional damage against Bleeding heroes\nReceives 10% less Physical damage",
      ),
    ],
    abilityIds: ["fangs", "rend", "pounce"],
  }),
  defineEnemy({
    id: "vampire",
    title: "Vampire",
    art: assetRefs.vampire,
    enemyType: "elite",
    traits: [
      trait(
        "vampire",
        "Blood Scent",
        "Deals 1 additional Bleed damage to heroes below half Health\nReceives 30% more Holy and Burn damage",
      ),
    ],
    abilityIds: ["fangs", "rend", "bloodthorn"],
  }),
  defineEnemy({
    id: "blood-countess",
    title: "The Blood Countess",
    art: assetRefs.theBloodCountess,
    enemyType: "boss",
    traits: [
      trait(
        "blood-countess",
        "Profane Blood",
        "Receives 30% more Holy damage\nTakes 1 Holy damage whenever either combatant restores Health",
      ),
    ],
    abilityIds: ["fangs", "rend", "bloodthorn"],
  }),
  defineEnemy({
    id: "zealot",
    title: "Zealot",
    art: assetRefs.zealot,
    enemyType: "normal",
    traits: [
      trait("zealot-enemy", "Fervor", "Gains 1 Forge after dealing Holy damage\nReceives 30% more Bleed damage"),
    ],
    abilityIds: ["slash", "smite", "judgment"],
  }),
  defineEnemy({
    id: "cleric",
    title: "Cleric",
    art: assetRefs.cleric,
    enemyType: "elite",
    traits: [trait("cleric", "Divine Favor", "Gains 1 Block each turn\nHoly damage restores 1 Health")],
    abilityIds: ["judgment", "holy-radiance", "block"],
  }),
  defineEnemy({
    id: "inquisitor",
    title: "Inquisitor",
    art: assetRefs.inquisitor,
    enemyType: "normal",
    traits: [
      trait(
        "inquisitor",
        "Trial by Fire",
        "Deals double Holy damage against Burning heroes\nReceives 30% more Bleed damage",
      ),
    ],
    abilityIds: ["sunder", "judgment", "smite"],
  }),
  defineEnemy({
    id: "paladin",
    title: "Paladin",
    art: assetRefs.paladin,
    enemyType: "elite",
    traits: [
      trait(
        "paladin",
        "Sacred Bulwark",
        "Gains 1 Block after dealing Stun or Holy damage\nReceives 30% less Holy damage",
      ),
    ],
    abilityIds: ["judgment", "shield-bash", "holy-radiance"],
  }),
  defineEnemy({
    id: "seraph",
    title: "The Seraph",
    art: assetRefs.theSeraph,
    enemyType: "boss",
    traits: [trait("seraph", "Renewing Light", "Receives 30% more Bleed damage\nHoly attacks restore 1 Health")],
    abilityIds: ["smite", "judgment", "holy-radiance"],
  }),
  defineEnemy({
    id: "winter-wolf",
    title: "Winter Wolf",
    art: assetRefs.winterWolf,
    enemyType: "normal",
    traits: [
      trait("winter-wolf", "Winter’s Bite", "Attacks deal 1 additional Freeze damage\nReceives 30% more Burn damage"),
    ],
    abilityIds: ["fangs", "pounce", "frostbolt"],
  }),
  defineEnemy({
    id: "ice-wraith",
    title: "Ice Wraith",
    art: assetRefs.iceWraith,
    enemyType: "elite",
    traits: [
      trait(
        "ice-wraith",
        "Deep Chill",
        "Deals 1 less damage while it has Freeze buildup\nReceives 30% less Physical damage\nReceives 30% more Burn and Holy damage",
      ),
    ],
    abilityIds: ["frostbolt", "cold-snap", "glacial-ward"],
  }),
  defineEnemy({
    id: "yeti",
    title: "Yeti",
    art: assetRefs.yeti,
    enemyType: "elite",
    traits: [
      trait(
        "yeti",
        "Yeti",
        "Gains 1 Block when the hero becomes Frozen\nReceives 30% less Freeze damage\nReceives 30% more Burn damage",
      ),
    ],
    abilityIds: ["maul", "frostbolt", "glacial-ward"],
  }),
  defineEnemy({
    id: "banshee",
    title: "Banshee",
    art: assetRefs.banshee,
    enemyType: "normal",
    traits: [trait("banshee", "Dread Wail", "Attacks Purge one beneficial effect\nReceives double Holy damage")],
    abilityIds: ["bash", "frostbolt", "cold-snap"],
  }),
  defineEnemy({
    id: "brawler",
    title: "Brawler",
    art: assetRefs.brawler,
    enemyType: "elite",
    traits: [
      trait(
        "brawler",
        "Seeing Stars",
        "Deals half damage on its first attack after recovering from Stun\nReceives 30% more Bleed damage",
      ),
    ],
    abilityIds: ["bash", "pounce", "block"],
  }),
  defineEnemy({
    id: "stone-golem",
    title: "Stone Golem",
    art: assetRefs.stoneGolem,
    enemyType: "elite",
    traits: [
      trait("stone-golem", "Stoneguard", "Gains 1 Block each turn\nDeals 1 additional damage while it has Block"),
    ],
    abilityIds: ["bash", "shield-bash", "plate-mail"],
  }),
  defineEnemy({
    id: "earth-elemental",
    title: "Earth Elemental",
    art: assetRefs.earthElemental,
    enemyType: "normal",
    traits: [
      trait(
        "earth-elemental",
        "Earth Elemental",
        "Breaking hero Block deals 1 Physical damage\nReceives 20% less Freeze and Burn damage",
      ),
    ],
    abilityIds: ["bash", "grasping-vines", "block"],
  }),
  defineEnemy({
    id: "stone-titan",
    title: "The Stone Titan",
    art: assetRefs.theStoneTitan,
    enemyType: "boss",
    traits: [trait("stone-titan", "Living Stone", "Stun attacks grant 1 Armor")],
    abilityIds: ["bash", "sunder", "shield-bash"],
  }),
];
