import * as assetRefs from "../assets";
import { defineEnemy, phys, playerStatus, poisonResistance, regeneration, trait } from "../compendium-builders";

export const enemyBestiary = [
  defineEnemy({
    id: "forge-golem",
    title: "The Forge Golem",
    art: assetRefs.theForgeGolem,
    enemyType: "boss",
    traits: [
      trait("rusting-carapace", "Rusting Carapace", "Gains Forge every other turn"),
      trait("starting-block", "Sturdy Plating", "Starts with 4 Block"),
    ],
    attackEffects: [phys(3), { kind: "damage", damageType: "stun", amount: 1 }],
  }),
  defineEnemy({
    id: "frostwarden",
    title: "The Frostwarden",
    art: assetRefs.theFrostwarden,
    enemyType: "boss",
    traits: [
      trait(
        "glacial-shell",
        "Glacial Shell",
        "Receives half Freeze damage\nReceives 50% more Burn damage\nGains Freeze damage every other turn",
      ),
    ],
    attackEffects: [phys(4), { kind: "damage", damageType: "freeze", amount: 1 }],
  }),
  defineEnemy({
    id: "blight-treant",
    title: "The Blight Treant",
    art: assetRefs.theBlightTreant,
    enemyType: "boss",
    traits: [
      regeneration("Rotting Regrowth"),
      trait("burn-vulnerability", "Burn Vulnerability", "Receives 50% more Burn damage"),
    ],
    attackEffects: [{ kind: "damage", damageType: "nature", amount: 3 }, playerStatus("poison", 1)],
  }),
  defineEnemy({
    id: "skeleton",
    title: "Skeleton",
    art: assetRefs.skeleton,
    enemyType: "normal",
    traits: [trait("brittle-bones", "Brittle Bones", "Receives double Holy damage\nReceives double Stun damage")],
    attackEffects: [phys(7)],
  }),
  defineEnemy({
    id: "goblin",
    title: "Goblin",
    art: assetRefs.goblin,
    enemyType: "normal",
    traits: [trait("trinket-hoarder", "Trinket Hoarder", "Receives 50% more Burn damage")],
    attackEffects: [phys(7)],
  }),
  defineEnemy({
    id: "mimic",
    title: "Mimic",
    art: assetRefs.mimic,
    enemyType: "elite",
    traits: [trait("gold-trove", "Gold Trove", "Drops Double Gold on Defeat")],
    attackEffects: [phys(7), playerStatus("bleed", 1)],
  }),
  defineEnemy({
    id: "mud-elemental",
    title: "Mud Elemental",
    art: assetRefs.mudElemental,
    enemyType: "elite",
    traits: [regeneration("Regeneration")],
    attackEffects: [{ kind: "damage", damageType: "nature", amount: 2 }, playerStatus("poison", 1)],
  }),
  defineEnemy({
    id: "necromancer",
    title: "Necromancer",
    art: assetRefs.necromancer,
    enemyType: "elite",
    traits: [trait("holy-vulnerability", "Holy Vulnerability", "Receives double Holy damage")],
    attackEffects: [playerStatus("bleed", 3)],
  }),
  defineEnemy({
    id: "plague-doctor",
    title: "Plague Doctor",
    art: assetRefs.plagueDoctor,
    enemyType: "elite",
    traits: [poisonResistance],
    attackEffects: [playerStatus("bleed", 1), playerStatus("poison", 1)],
  }),
  defineEnemy({
    id: "living-armor",
    title: "Living Armor",
    art: assetRefs.livingArmor,
    enemyType: "elite",
    traits: [trait("living-armor", "Living Armor", "Starts combat with Armor\nReceives 25% less Bleed damage")],
    attackEffects: [phys(3), { kind: "damage", damageType: "nature", amount: 3 }],
  }),
  defineEnemy({
    id: "iron-bear",
    title: "The Iron Bear",
    art: assetRefs.ironBear,
    enemyType: "boss",
    traits: [trait("iron-hide", "Iron Hide", "Gains Armor, Forge, or Burn damage every other turn")],
    attackEffects: [phys(3), { kind: "damage", damageType: "burn", amount: 1 }],
  }),
  defineEnemy({
    id: "fire-elemental",
    title: "Fire Elemental",
    art: assetRefs.fireElemental,
    enemyType: "elite",
    traits: [
      trait("cinder-skin", "Cinder Skin", "Deals 1 Burn damage when attacked"),
      trait("freeze-vulnerability", "Freeze Vulnerability", "Receives double Freeze damage"),
    ],
    attackEffects: [{ kind: "damage", damageType: "burn", amount: 2 }],
  }),
  defineEnemy({
    id: "frost-elemental",
    title: "Frost Elemental",
    art: assetRefs.frostElemental,
    enemyType: "elite",
    traits: [trait("burn-vulnerability", "Burn Vulnerability", "Receives 50% more Burn damage")],
    attackEffects: [{ kind: "damage", damageType: "freeze", amount: 3 }],
  }),
  defineEnemy({
    id: "slime",
    title: "Slime",
    art: assetRefs.slime,
    enemyType: "normal",
    traits: [trait("amorphous", "Amorphous", "Receives 10% less Physical damage\nReceives 10% less Poison damage")],
    attackEffects: [{ kind: "damage", damageType: "poison", amount: 2 }],
  }),
  defineEnemy({
    id: "will-o-wisp",
    title: "Will-o-Wisp",
    art: assetRefs.willOWisp,
    enemyType: "elite",
    traits: [trait("will-o-wisp", "Will-o-Wisp", "Receives 30% less Physical damage\nReceives 30% less Freeze damage")],
    attackEffects: [{ kind: "damage", damageType: "freeze", amount: 3 }],
  }),
  defineEnemy({
    id: "bandit",
    title: "Bandit",
    art: assetRefs.placeholderEnemy,
    enemyType: "normal",
    traits: [trait("bandit", "Bandit", "Deals double damage on the first attack\nReceives 30% more Holy damage")],
    attackEffects: [phys(7)],
  }),
  defineEnemy({
    id: "ogre",
    title: "Ogre",
    art: assetRefs.placeholderEnemy,
    enemyType: "elite",
    traits: [trait("ogre", "Ogre", "Physical attacks deal double damage to Block\nReceives 30% more Holy damage")],
    attackEffects: [phys(7)],
  }),
  defineEnemy({
    id: "fire-imp",
    title: "Fire Imp",
    art: assetRefs.placeholderEnemy,
    enemyType: "normal",
    traits: [trait("fire-imp", "Fire Imp", "Successful attacks apply 1 Burn\nReceives 30% more Freeze damage")],
    attackEffects: [{ kind: "damage", damageType: "burn", amount: 2 }],
  }),
  defineEnemy({
    id: "hellhound",
    title: "Hellhound",
    art: assetRefs.placeholderEnemy,
    enemyType: "elite",
    traits: [
      trait("hellhound", "Hellhound", "Deals 25% more damage against Burning players\nReceives 30% more Freeze damage"),
    ],
    attackEffects: [phys(5), { kind: "damage", damageType: "burn", amount: 1 }],
  }),
  defineEnemy({
    id: "pyromancer",
    title: "Pyromancer",
    art: assetRefs.placeholderEnemy,
    enemyType: "elite",
    traits: [
      trait(
        "pyromancer",
        "Pyromancer",
        "Burn damage ignores Block and damage reduction\nReceives 30% more Freeze damage",
      ),
    ],
    attackEffects: [{ kind: "damage", damageType: "burn", amount: 3 }],
  }),
  defineEnemy({
    id: "giant-spider",
    title: "Giant Spider",
    art: assetRefs.placeholderEnemy,
    enemyType: "normal",
    traits: [trait("giant-spider", "Giant Spider", "Successful attacks apply 1 Poison\nReceives 30% more Burn damage")],
    attackEffects: [{ kind: "damage", damageType: "poison", amount: 2 }],
  }),
  defineEnemy({
    id: "giant-snake",
    title: "Giant Snake",
    art: assetRefs.placeholderEnemy,
    enemyType: "elite",
    traits: [
      trait(
        "giant-snake",
        "Giant Snake",
        "Poison removes 1 additional Block before Health\nReceives 30% more Freeze damage",
      ),
    ],
    attackEffects: [{ kind: "damage", damageType: "poison", amount: 3 }],
  }),
  defineEnemy({
    id: "blood-cultist",
    title: "Blood Cultist",
    art: assetRefs.placeholderEnemy,
    enemyType: "elite",
    traits: [
      trait(
        "blood-cultist",
        "Blood Cultist",
        "When Bleed deals damage, the next attack deals double damage\nReceives 30% more Holy damage",
      ),
    ],
    attackEffects: [{ kind: "damage", damageType: "bleed", amount: 3 }],
  }),
  defineEnemy({
    id: "dire-wolf",
    title: "Dire Wolf",
    art: assetRefs.placeholderEnemy,
    enemyType: "normal",
    traits: [
      trait(
        "dire-wolf",
        "Dire Wolf",
        "Deals 1 additional damage against Bleeding players\nReceives 10% less Physical damage",
      ),
    ],
    attackEffects: [{ kind: "damage", damageType: "bleed", amount: 2, lifesteal: true }],
  }),
  defineEnemy({
    id: "vampire",
    title: "Vampire",
    art: assetRefs.placeholderEnemy,
    enemyType: "elite",
    traits: [
      trait(
        "vampire",
        "Vampire",
        "Has a 10% chance to Leech\nReaching full Health empowers the next attack by 1 damage\nReceives 30% more Holy and Burn damage",
      ),
    ],
    attackEffects: [{ kind: "damage", damageType: "bleed", amount: 2 }],
  }),
  defineEnemy({
    id: "blood-countess",
    title: "The Blood Countess",
    art: assetRefs.placeholderEnemy,
    enemyType: "boss",
    traits: [
      trait(
        "blood-countess",
        "The Blood Countess",
        "Receives 30% more Holy damage\nReceives 1 Holy damage when any combatant restores Health",
      ),
    ],
    attackEffects: [{ kind: "damage", damageType: "bleed", amount: 4 }],
  }),
  defineEnemy({
    id: "zealot",
    title: "Zealot",
    art: assetRefs.placeholderEnemy,
    enemyType: "normal",
    traits: [
      trait(
        "zealot-enemy",
        "Zealot",
        "Holy damage empowers the next attack with 1 Holy damage\nReceives 30% more Bleed damage",
      ),
    ],
    attackEffects: [phys(6), { kind: "damage", damageType: "holy", amount: 1 }],
  }),
  defineEnemy({
    id: "cleric",
    title: "Cleric",
    art: assetRefs.placeholderEnemy,
    enemyType: "elite",
    traits: [trait("cleric", "Cleric", "Gains 1 Block each turn\nHoly damage restores 1 Health")],
    attackEffects: [
      { kind: "damage", damageType: "stun", amount: 1 },
      { kind: "damage", damageType: "holy", amount: 3 },
    ],
  }),
  defineEnemy({
    id: "inquisitor",
    title: "Inquisitor",
    art: assetRefs.placeholderEnemy,
    enemyType: "normal",
    traits: [
      trait(
        "inquisitor",
        "Inquisitor",
        "Holy damage empowers the next attack with 1 Holy damage\nReceives 30% more Bleed damage",
      ),
    ],
    attackEffects: [phys(6), { kind: "damage", damageType: "holy", amount: 1 }],
  }),
  defineEnemy({
    id: "paladin",
    title: "Paladin",
    art: assetRefs.placeholderEnemy,
    enemyType: "elite",
    traits: [
      trait("paladin", "Paladin", "Gains 1 Block after dealing Stun or Holy damage\nReceives 30% less Holy damage"),
    ],
    attackEffects: [
      { kind: "damage", damageType: "stun", amount: 1 },
      { kind: "damage", damageType: "holy", amount: 3 },
    ],
  }),
  defineEnemy({
    id: "seraph",
    title: "The Seraph",
    art: assetRefs.placeholderEnemy,
    enemyType: "boss",
    traits: [trait("seraph", "The Seraph", "Receives 30% more Bleed damage\nDeals 1 Holy damage each turn")],
    attackEffects: [phys(4), { kind: "damage", damageType: "holy", amount: 1 }],
  }),
  defineEnemy({
    id: "winter-wolf",
    title: "Winter Wolf",
    art: assetRefs.placeholderEnemy,
    enemyType: "normal",
    traits: [trait("winter-wolf", "Winter Wolf", "Successful attacks apply 1 Freeze\nReceives 30% more Burn damage")],
    attackEffects: [{ kind: "damage", damageType: "bleed", amount: 2 }],
  }),
  defineEnemy({
    id: "ice-wraith",
    title: "Ice Wraith",
    art: assetRefs.placeholderEnemy,
    enemyType: "elite",
    traits: [
      trait(
        "ice-wraith",
        "Ice Wraith",
        "While Frozen, deals 1 less damage\nReceives 30% less Physical damage\nReceives 30% more Burn and Holy damage",
      ),
    ],
    attackEffects: [{ kind: "damage", damageType: "freeze", amount: 3 }],
  }),
  defineEnemy({
    id: "yeti",
    title: "Yeti",
    art: assetRefs.placeholderEnemy,
    enemyType: "elite",
    traits: [
      trait(
        "yeti",
        "Yeti",
        "Gains 1 Block when the player becomes Frozen\nReceives 30% less Freeze damage\nReceives 30% more Burn damage",
      ),
    ],
    attackEffects: [
      { kind: "damage", damageType: "stun", amount: 2 },
      { kind: "damage", damageType: "freeze", amount: 1 },
    ],
  }),
  defineEnemy({
    id: "banshee",
    title: "Banshee",
    art: assetRefs.placeholderEnemy,
    enemyType: "normal",
    traits: [
      trait("banshee", "Banshee", "Deals 4 Stun damage and Purges a beneficial effect\nReceives double Holy damage"),
    ],
    attackEffects: [{ kind: "damage", damageType: "stun", amount: 4 }],
  }),
  defineEnemy({
    id: "brawler",
    title: "Brawler",
    art: assetRefs.placeholderEnemy,
    enemyType: "elite",
    traits: [
      trait(
        "brawler",
        "Brawler",
        "Deals half damage on the first attack after being Stunned\nReceives 30% more Bleed damage",
      ),
    ],
    attackEffects: [{ kind: "damage", damageType: "stun", amount: 2 }],
  }),
  defineEnemy({
    id: "stone-golem",
    title: "Stone Golem",
    art: assetRefs.placeholderEnemy,
    enemyType: "elite",
    traits: [trait("stone-golem", "Stone Golem", "Gains 1 Block each turn\nDeals 1 additional damage while Blocked")],
    attackEffects: [{ kind: "damage", damageType: "stun", amount: 1 }, phys(3)],
  }),
  defineEnemy({
    id: "earth-elemental",
    title: "Earth Elemental",
    art: assetRefs.placeholderEnemy,
    enemyType: "normal",
    traits: [
      trait(
        "earth-elemental",
        "Earth Elemental",
        "Breaking player Block deals 1 Physical damage\nReceives 20% less Freeze and Burn damage",
      ),
    ],
    attackEffects: [{ kind: "damage", damageType: "stun", amount: 2 }],
  }),
  defineEnemy({
    id: "stone-titan",
    title: "The Stone Titan",
    art: assetRefs.placeholderEnemy,
    enemyType: "boss",
    traits: [trait("stone-titan", "The Stone Titan", "Deals 1 Stun damage each turn")],
    attackEffects: [{ kind: "damage", damageType: "stun", amount: 4 }],
  }),
];
